// app/gui/src/dashboard/components/ContextMenu.vue
<script setup lang="ts">
/**
 * @file The drive's context menu: a non-modal popover of `MenuEntry.vue` buttons at the point that
 * was right-clicked.
 *
 * It has its own DOM and behaviour (#91, ruling 3), not the shared
 * `$/components/Menu/ContextMenu.vue` (a Reka `menu` of `menuitem`s): the `context-menu` test id on
 * the popover, a `dialog` inside it named by `ariaLabel`, buttons operated with Tab, Enter and
 * Space, and no focus taken on opening. It closes on Escape (the dashboard's `closeModal` binding,
 * while it is open), on a press that starts and ends outside it, and when anything outside it
 * scrolls or is right-clicked; and, through the dialog context, when an entry is pressed.
 *
 * A locked entry (`isUnderPaywall`) shows the lock and the "upgrade" tooltip, and opens the paywall
 * dialog for its `feature` instead of running its action.
 */
import type { ContextMenuEntry } from '#/components/contextMenuEntry'
import PaywallModal from '#/layouts/Drive/PaywallModal.vue'
import { POPOVER_STYLES } from '$/components/Dialog/variants'
import { provideDialogContext } from '$/components/Dialog/dialogContext'
import MenuEntry from '$/components/MenuEntry/MenuEntry.vue'
import { portalTarget } from '$/components/portal'
import { useDashboardInputBindings } from '$/providers/dashboardInputBindings'
import { useModals } from '$/providers/modals'
import { useText } from '$/providers/text'
import { twMerge } from '$/utils/style/tailwindMerge'
import { useEventListener } from '@vueuse/core'
import { isOnMacOS } from 'enso-common/src/utilities/detect'
import { ref, watch } from 'vue'

const { ariaLabel, entries, position } = defineProps<{
  ariaLabel: string
  entries: readonly ContextMenuEntry[]
  position: Pick<MouseEvent, 'pageX' | 'pageY'>
}>()

const open = defineModel<boolean>('open', { required: true })

const emit = defineEmits<{
  /** It has closed, however it closed. */
  close: []
}>()

const { getText } = useText()
const modals = useModals()
const inputBindings = useDashboardInputBindings()
const popover = ref<HTMLElement>()

function close() {
  if (!open.value) return
  open.value = false
  emit('close')
}

provideDialogContext({ close })

// Escape closes it while it is open, through the dashboard's `closeModal` binding.
watch(
  open,
  (isOpen, _old, onCleanup) => {
    if (!isOpen) return
    onCleanup(inputBindings.attach(document.body, 'keydown', { closeModal: close }))
  },
  { immediate: true },
)

/** Whether an event's target is outside the menu. */
function isOutside(event: Event) {
  return (
    event.target instanceof Element &&
    popover.value != null &&
    !popover.value.contains(event.target)
  )
}

/**
 * Whether the menu has been open for a couple of frames. Right-clicking a row focuses it, and the
 * focus scrolls the table's layout container a pixel on the next frame; that scroll must not close
 * the menu.
 */
const isSettled = ref(false)
watch(
  open,
  (isOpen) => {
    isSettled.value = false
    if (isOpen) {
      requestAnimationFrame(() =>
        requestAnimationFrame(() => {
          isSettled.value = open.value
        }),
      )
    }
  },
  { immediate: true },
)

// It sits at a fixed point, so scrolling anything else, or right-clicking elsewhere, closes it.
useEventListener(
  document,
  'scroll',
  (event: Event) => {
    if (open.value && isSettled.value && isOutside(event)) close()
  },
  { capture: true, passive: true },
)
useEventListener(
  document,
  'contextmenu',
  (event: MouseEvent) => {
    if (open.value && isOutside(event)) close()
  },
  { capture: true },
)

// A press that starts and ends outside closes it.
let pressStartedOutside = false
useEventListener(
  document,
  'pointerdown',
  (event: PointerEvent) => {
    pressStartedOutside = open.value && isOutside(event)
  },
  { capture: true },
)
useEventListener(
  document,
  'pointerup',
  (event: PointerEvent) => {
    if (pressStartedOutside && open.value && isOutside(event)) close()
    pressStartedOutside = false
  },
  { capture: true },
)

function press(entry: ContextMenuEntry) {
  if (entry.isUnderPaywall === true && entry.feature != null) {
    modals.closeAll()
    modals.open(PaywallModal, { feature: entry.feature })
  } else {
    entry.doAction()
  }
}
</script>

<template>
  <Teleport v-if="open" :to="portalTarget()">
    <div
      ref="popover"
      data-testid="context-menu"
      :class="POPOVER_STYLES().base({ className: 'flex w-min items-start' })"
      data-trigger="DialogTrigger"
      :style="{
        position: 'sticky',
        zIndex: 100000,
        maxHeight: '100vh',
        left: `${position.pageX}px`,
        top: `${position.pageY}px`,
      }"
    >
      <div role="dialog" tabindex="-1" :class="POPOVER_STYLES().dialog()">
        <div
          :aria-label="ariaLabel"
          :class="
            twMerge(
              'relative flex flex-col rounded-default',
              isOnMacOS() ? 'w-context-menu-macos' : 'w-context-menu',
            )
          "
        >
          <MenuEntry
            v-for="entry in entries"
            :key="entry.action"
            variant="context-menu"
            :action="entry.action"
            :label="entry.label"
            :icon="entry.isUnderPaywall === true ? 'lock' : entry.icon"
            :tooltip="entry.isUnderPaywall === true ? getText('upgradeToUseCloud') : entry.tooltip"
            :isDisabled="entry.isDisabled"
            :color="entry.color"
            :onPress="() => press(entry)"
          />
        </div>
      </div>
    </div>
  </Teleport>
</template>

// app/gui/src/dashboard/components/ContextMenu.tsx
/** @file A context menu. */
import { Pressable } from '#/components/aria'
import ContextMenuEntry from '#/components/ContextMenuEntry'
import { Popover } from '#/components/Dialog'
import type { MenuEntryProps } from '#/components/MenuEntry'
import { usePortalContext } from '#/components/Portal'
import { useEventListener } from '#/hooks/eventListenerHooks'
import { useInputBindings } from '#/providers/InputBindingsProvider'
import { twMerge } from '$/utils/style/tailwindMerge'
import { isOnMacOS } from 'enso-common/src/utilities/detect'
import {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  useState,
  type ForwardedRef,
  type MouseEvent,
} from 'react'

/** Props for a {@link ContextMenu}. */
export interface ContextMenuProps {
  // eslint-disable-next-line @typescript-eslint/naming-convention
  readonly 'aria-label': string
  readonly entries: readonly (MenuEntryProps | false | null | undefined)[]
  readonly initialPosition?: Pick<MouseEvent, 'pageX' | 'pageY'> | null | undefined
  readonly onClose?: () => void
}

/** Imperative API for {@link ContextMenu}. */
export interface ContextMenuApi {
  readonly open: (position: Pick<MouseEvent, 'pageX' | 'pageY'>) => void
  readonly close: () => void
}

/** A context menu that opens at the current mouse position. */
export const ContextMenu = forwardRef(function ContextMenuImpl(
  props: ContextMenuProps,
  ref: ForwardedRef<ContextMenuApi>,
) {
  const { entries, initialPosition, onClose } = props

  const inputBindings = useInputBindings()
  const root = usePortalContext()
  const popoverRef = useRef<HTMLElement>(null)
  const [isOpen, setIsOpen] = useState(initialPosition != null)
  const [position, setPosition] = useState<Pick<MouseEvent, 'pageX' | 'pageY'>>(
    initialPosition ?? { pageX: 0, pageY: 0 },
  )

  useImperativeHandle(ref, () => ({
    open: (newPosition) => {
      setPosition(newPosition)
      setIsOpen(true)
    },
    close: () => {
      setIsOpen(false)
    },
  }))

  useEffect(() => {
    if (!isOpen) return
    return inputBindings.attach(document.body, 'keydown', {
      closeModal: () => {
        setIsOpen(false)
      },
    })
  }, [inputBindings, isOpen])

  useEventListener(
    'scroll',
    (event) => {
      if (
        event.target instanceof Element &&
        popoverRef.current &&
        !popoverRef.current.contains(event.target)
      ) {
        setIsOpen(false)
      }
    },
    document,
    { capture: true },
  )

  useEventListener(
    'contextmenu',
    (event) => {
      if (
        event.target instanceof Element &&
        popoverRef.current &&
        !popoverRef.current.contains(event.target)
      ) {
        setIsOpen(false)
      }
    },
    document,
    { capture: true },
  )

  return (
    <Popover.Trigger>
      <Pressable>
        <></>
      </Pressable>
      <Popover
        data-testid="context-menu"
        // Remove the underlay element to allow scrolling.
        isNonModal
        ref={popoverRef}
        // `position: sticky` must be here rather than in tailwind as `react-aria-components`
        // sets `position: absolute` via `style`.
        style={{ position: 'sticky', left: position.pageX, top: position.pageY }}
        shouldCloseOnInteractOutside={() => true}
        className="flex w-min items-start"
        UNSTABLE_portalContainer={root}
        isOpen={isOpen}
        onOpenChange={setIsOpen}
        onClose={() => {
          onClose?.()
          setIsOpen(false)
        }}
      >
        <div
          aria-label={props['aria-label']}
          className={twMerge(
            'relative flex flex-col rounded-default',
            isOnMacOS() ? 'w-context-menu-macos' : 'w-context-menu',
          )}
        >
          {entries.flatMap((entry) => {
            if (entry == null || entry === false) {
              return []
            }
            return [<ContextMenuEntry key={entry.action} {...entry} />]
          })}
        </div>
      </Popover>
    </Popover.Trigger>
  )
})
