// app/gui/src/cloud/datalinks/FilePathInput.vue
<script setup lang="ts">
/**
 * @file A path to a cloud file, with the file browser under it while the field has the focus. The
 * file browser is the project view's `FileBrowserWidget.vue`, mounted directly.
 *
 * Typing changes the path at once. Choosing a file in the browser sets the path; after that, the
 * browser closes when the focus leaves the field (before a choice it stays open).
 */
import Text from '$/components/Text/Text.vue'
import { useText } from '$/providers/text'
import { twMerge } from '$/utils/style/tailwindMerge'
import FileBrowserWidget from '@/components/widgets/FileBrowserWidget.vue'
import { ref } from 'vue'
import { useFocusRing } from './focusRing'
import { ROUNDED_INPUT_BASE_CLASSES } from './variants'

const {
  readOnly = false,
  value,
  validationErrorClass,
  error,
} = defineProps<{
  readOnly?: boolean | undefined
  value: string
  validationErrorClass?: string | undefined
  /** The schema's description, shown while the value is invalid. */
  error?: string | undefined
}>()

const emit = defineEmits<{ change: [value: string] }>()

const { getText } = useText()
const focusRing = useFocusRing()

const fileBrowserPath = ref(value)
const isFileBrowserOpened = ref(false)
let hasPathBeenChanged = false
const root = ref<HTMLElement>()

const roundedInputClass = (roundBottom: boolean) =>
  twMerge(ROUNDED_INPUT_BASE_CLASSES, roundBottom ? 'rounded-input' : 'rounded-t-input')

const FILE_BROWSER_STYLES = {
  '--file-browser-min-width': '280px',
  '--z-index-file-browser': 1,
  '--file-browser-background-color': 'var(--color-dashboard-background)',
  '--file-browser-text-color': 'black',
  '--file-browser-corner-radius': 'var(--input-corner-radius)',
  '--file-browser-top-bar-color': 'var(--color-primary)',
}

function onFocusOut(event: FocusEvent) {
  const next = event.relatedTarget
  if (next == null || !hasPathBeenChanged) return
  // Close the file browser once the focus has left this component.
  if (root.value != null && next instanceof Node && !root.value.contains(next)) {
    isFileBrowserOpened.value = false
    hasPathBeenChanged = false
  }
}

function onInput(event: Event) {
  const newValue = (event.currentTarget as HTMLInputElement).value
  fileBrowserPath.value = newValue
  emit('change', newValue)
}

function onPathAccepted(path: string) {
  fileBrowserPath.value = path
  emit('change', path)
  hasPathBeenChanged = true
}
</script>

<template>
  <div
    ref="root"
    :class="twMerge('flex flex-col', isFileBrowserOpened && 'mb-4')"
    :style="FILE_BROWSER_STYLES"
    tabindex="-1"
    @focusout="onFocusOut"
  >
    <div
      :class="[
        'relative rounded-input focus-within:focus-ring-outset',
        focusRing.isFocusVisible.value && 'focus-ring',
      ]"
      @focusin="((isFileBrowserOpened = true), focusRing.onFocus())"
      @focusout="focusRing.onBlur"
    >
      <input
        type="text"
        :readonly="readOnly"
        :value="fileBrowserPath"
        :size="1"
        :class="twMerge(roundedInputClass(!isFileBrowserOpened), validationErrorClass)"
        :placeholder="getText('enterText')"
        @input="onInput"
      />
      <FileBrowserWidget
        v-if="isFileBrowserOpened"
        type="file"
        :writeMode="true"
        :choosenPath="fileBrowserPath"
        :allowOverride="true"
        @pathAccepted="onPathAccepted"
      />
    </div>
    <Text v-if="error != null" class="px-2 text-danger">{{ error }}</Text>
  </div>
</template>

// app/gui/src/dashboard/components/FilePathInput.tsx
/** @file A file path input component with an integrated file browser. */
import { Input } from '#/components/aria'
import FocusRing from '#/components/styled/FocusRing'
import { vueComponent } from '#/utilities/vue'
import { useText } from '$/providers/react'
import { twMerge } from '$/utils/style/tailwindMerge'
import FileBrowserWidgetVue from '@/components/widgets/FileBrowserWidget.vue'
import { useRef, useState, type CSSProperties } from 'react'
import { ROUNDED_INPUT_BASE_CLASSES } from './JSONSchemaInput'

// eslint-disable-next-line no-restricted-syntax
const FileBrowserWidget = vueComponent(FileBrowserWidgetVue).default

/** Props for {@link FilePathInput}. */
export interface FilePathInputProps {
  readonly readOnly?: boolean
  readonly value: string
  readonly onChange: (value: string) => void
  readonly validationErrorClassName?: string | undefined
  readonly errors?: readonly React.ReactNode[]
}

/** A file path input component with an integrated file browser. */
export default function FilePathInput(props: FilePathInputProps) {
  const { readOnly = false, value, onChange, validationErrorClassName, errors = [] } = props
  const { getText } = useText()
  const [fileBrowserPath, setFileBrowserPath] = useState(() => value)
  const [isFileBrowserOpened, setFileBrowserOpened] = useState(false)
  const hasPathBeenChangedRef = useRef(false)
  const inputRef = useRef<HTMLInputElement>(null)
  const rootRef = useRef<HTMLDivElement>(null)

  const roundedInputClassName = (roundBottom: boolean) =>
    twMerge(ROUNDED_INPUT_BASE_CLASSES, roundBottom ? 'rounded-input' : 'rounded-t-input')

  const fileBrowserZIndex = 1

  /* eslint-disable @typescript-eslint/naming-convention */
  /* eslint-disable-next-line no-restricted-syntax */
  const fileBrowserStyles = {
    '--file-browser-min-width': '280px',
    '--z-index-file-browser': fileBrowserZIndex,
    '--file-browser-background-color': 'var(--color-dashboard-background)',
    '--file-browser-text-color': 'black',
    '--file-browser-corner-radius': 'var(--input-corner-radius)',
    '--file-browser-top-bar-color': 'var(--color-primary)',
  } as CSSProperties
  /* eslint-enable @typescript-eslint/naming-convention */

  return (
    <div
      ref={rootRef}
      className={twMerge('flex flex-col', isFileBrowserOpened && 'mb-4')}
      style={fileBrowserStyles}
      tabIndex={-1}
      onBlur={(event) => {
        if (!event.relatedTarget || !hasPathBeenChangedRef.current) return
        // Check if the focus is still inside the current component, otherwise close the file browser.
        if (rootRef.current && !rootRef.current.contains(event.relatedTarget)) {
          setFileBrowserOpened(false)
          hasPathBeenChangedRef.current = false
        }
      }}
    >
      <FocusRing within={true}>
        <div
          className="relative rounded-input focus-within:focus-ring-outset"
          onFocus={() => {
            setFileBrowserOpened(true)
          }}
        >
          <Input
            ref={inputRef}
            type="text"
            readOnly={readOnly}
            value={fileBrowserPath}
            size={1}
            className={twMerge(
              roundedInputClassName(!isFileBrowserOpened),
              validationErrorClassName,
            )}
            placeholder={getText('enterText')}
            onChange={(event) => {
              const newValue: string = event.currentTarget.value
              setFileBrowserPath(newValue)
              onChange(newValue)
            }}
          />
          {isFileBrowserOpened && (
            <FileBrowserWidget
              type="file"
              writeMode={true}
              choosenPath={fileBrowserPath}
              onPathAccepted={(p: string) => {
                setFileBrowserPath(p)
                onChange(p)
                hasPathBeenChangedRef.current = true
              }}
              allowOverride={true}
            />
          )}
        </div>
      </FocusRing>
      {...errors}
    </div>
  )
}
