// app/gui/src/components/Spinner/Loader.vue
<script setup lang="ts">
/**
 * @file A centred loading spinner that fills its container: the Vue counterpart of the React
 * `#/components/Loader`. Anything in the default slot is shown under the spinner.
 */
import {
  LOADER_SIZES,
  LOADER_STYLES,
  type LoaderSize,
  type SpinnerPhase,
} from '$/components/Spinner/variants'
import type { VariantProps } from '$/utils/style/tailwindVariants'
import { computed } from 'vue'
import StatelessSpinner from './StatelessSpinner.vue'

type LoaderVariants = VariantProps<typeof LOADER_STYLES>

const {
  size = 'medium',
  state = 'loading-fast',
  minHeight = 'full',
  height = 'full',
  color = 'primary',
  class: className,
} = defineProps<{
  size?: LoaderSize | number | undefined
  state?: SpinnerPhase | undefined
  minHeight?: LoaderVariants['minHeight']
  height?: LoaderVariants['height']
  color?: LoaderVariants['color']
  class?: string | undefined
}>()

const pixelSize = computed(() => (typeof size === 'number' ? size : LOADER_SIZES[size]))
</script>

<template>
  <div :class="LOADER_STYLES({ minHeight, height, color, className })">
    <div class="flex flex-col items-center gap-2">
      <StatelessSpinner :size="pixelSize" :phase="state" class="text-current" />
      <slot />
    </div>
  </div>
</template>

// app/gui/src/dashboard/components/Loader.tsx
/** @file A full-screen loading spinner. */
import { StatelessSpinner, type SpinnerState } from '#/components/StatelessSpinner'
import {
  LOADER_SIZES as SIZE_MAP,
  LOADER_STYLES as STYLES,
  type LoaderSize,
} from '$/components/Spinner/variants'
import type { VariantProps } from '$/utils/style/tailwindVariants'
import { memo } from 'react'

/** The possible sizes for a {@link Loader}. */
export type Size = LoaderSize

/** Props for a {@link Loader}. */
export interface LoaderProps extends VariantProps<typeof STYLES> {
  readonly children?: React.ReactNode
  readonly className?: string
  readonly size?: Size | number
  readonly state?: SpinnerState
}

/** A full-screen loading spinner. */

export const Loader = memo(function LoaderImpl(props: LoaderProps) {
  const {
    children,
    className,
    size: sizeRaw = 'medium',
    state = 'loading-fast',
    minHeight = 'full',
    color = 'primary',
    height = 'full',
  } = props

  const size = typeof sizeRaw === 'number' ? sizeRaw : SIZE_MAP[sizeRaw]

  return (
    <div className={STYLES({ minHeight, className, color, height })}>
      <div className="flex flex-col items-center gap-2">
        <StatelessSpinner size={size} phase={state} className="text-current" />
        {children}
      </div>
    </div>
  )
})
