// app/gui/src/components/MenuEntry/MenuEntry.vue
<script setup lang="ts">
/**
 * @file An entry of a menu drawn in a popover (the user and info menus): the Vue counterpart of the
 * React `#/components/MenuEntry`, with the same elements and classes, styled by the same
 * `MENU_ENTRY_VARIANTS`.
 *
 * It is a button, not a `menuitem`: those menus are dialogs of buttons, as in React, and are
 * operated with Tab, Enter and Space. Its icon, colour, label and shortcut come from its action's
 * metadata (`$/configurations/inputBindings`), the shortcut as the user has bound it. Pressing it
 * closes the enclosing popover or dialog (or every modal, outside one), then calls `onPress`.
 *
 * Not ported, as no Vue menu uses them yet: React's `tooltip` and its paywall lock
 * (`isUnderPaywall`, `feature`).
 */
import Icon from '$/components/Icon/Icon.vue'
import { injectDialogContext } from '$/components/Dialog/dialogContext'
import KeyboardShortcut from '$/components/KeyboardShortcut/KeyboardShortcut.vue'
import { MENU_ENTRY_VARIANTS } from '$/components/MenuEntry/variants'
import Text from '$/components/Text/Text.vue'
import type { TEXT_STYLE } from '$/components/Text/variants'
import { actionToTextId, type DashboardBindingKey } from '$/configurations/inputBindings'
import { useDashboardInputBindings } from '$/providers/inputBindings'
import { useModals } from '$/providers/modals'
import { useText } from '$/providers/text'
import { twMerge } from '$/utils/style/tailwindMerge'
import type { VariantProps } from '$/utils/style/tailwindVariants'
import type { Icon as IconName } from '@/util/iconMetadata/iconName'
import type { TextId } from 'enso-common/src/text'
import * as detect from 'enso-common/src/utilities/detect'
import { computed } from 'vue'

const props = withDefaults(
  defineProps<{
    action: DashboardBindingKey
    /** Overrides the action's name. */
    label?: string | undefined
    /** Overrides the action's icon. */
    icon?: IconName | undefined
    truncateLabel?: boolean | undefined
    isDisabled?: boolean | undefined
    title?: string | undefined
    color?: VariantProps<typeof TEXT_STYLE>['color']
    hasHoverBackground?: boolean | undefined
    variant?: 'context-menu' | undefined
    onPress: () => void
  }>(),
  // Explicit `undefined`: an absent boolean would otherwise arrive as `false`, overriding the
  // variants' default.
  { hasHoverBackground: undefined },
)

defineSlots<{
  /** Drawn in place of the icon (a profile picture, in the organization switcher). */
  picture?: () => unknown
}>()

const { getText } = useText()
const inputBindings = useDashboardInputBindings()
const dialog = injectDialogContext(true)
const modals = useModals()

// Read on render: the entry is rendered when its menu opens, so it shows the current binding.
const info = computed(() => inputBindings.metadata[props.action])
const shortcut = computed(() => info.value.bindings[0])

const labelTextId = computed<TextId>(() =>
  props.action === 'openInFileBrowser' ?
    detect.isOnMacOS() ? 'openInFileBrowserShortcutMacOs'
    : detect.isOnWindows() ? 'openInFileBrowserShortcutWindows'
    : 'openInFileBrowserShortcut'
  : actionToTextId(props.action),
)

const contentClass = computed(() =>
  MENU_ENTRY_VARIANTS({ variant: props.variant, hasHoverBackground: props.hasHoverBackground }),
)
const labelClass = computed(() =>
  twMerge(
    'flex min-w-0 items-center gap-menu-entry whitespace-nowrap',
    props.truncateLabel && 'w-0 flex-1',
  ),
)

function press() {
  if (dialog) {
    // Closing a dialog takes precedence over closing the modals.
    dialog.close()
  } else {
    modals.closeAll()
  }
  props.onPress()
}
</script>

<template>
  <button
    type="button"
    class="group flex w-full rounded-menu-entry focus-visible:focus-ring"
    :disabled="isDisabled"
    @click="press"
  >
    <div :class="contentClass">
      <div :title="title" :class="labelClass" :style="{ color: info.color }">
        <slot v-if="$slots.picture" name="picture" />
        <!-- An empty placeholder keeps the labels of entries without an icon aligned. -->
        <Icon
          v-else
          :icon="icon ?? info.icon"
          :class="info.color != null ? undefined : 'text-primary'"
        >
          <span />
        </Icon>
        <Text
          :color="color"
          :class="truncateLabel ? 'min-w-0 flex-1' : undefined"
          :truncate="truncateLabel ? '1' : undefined"
          :disableLineHeightCompensation="truncateLabel"
        >
          {{ label ?? getText(labelTextId) }}
        </Text>
      </div>
      <KeyboardShortcut v-if="shortcut != null" :shortcut="shortcut" />
    </div>
  </button>
</template>

// app/gui/src/dashboard/components/MenuEntry.tsx
/** @file An entry in a menu. */
import * as aria from '#/components/aria'
import { useDialogContext } from '#/components/Dialog'
import { Icon } from '#/components/Icon'
import { PaywallDialog } from '#/components/Paywall'
import FocusRing from '#/components/styled/FocusRing'
import { Text, type TextProps } from '#/components/Text'
import type { SvgUseIcon } from '#/components/types'
import { useVisualTooltip } from '#/components/VisualTooltip'
import KeyboardShortcut from '#/pages/dashboard/components/KeyboardShortcut'
import * as inputBindingsProvider from '#/providers/InputBindingsProvider'
import { setModal, unsetModal } from '#/providers/ModalProvider'
import { MENU_ENTRY_VARIANTS } from '$/components/MenuEntry/variants'
import type { PaywallFeatureName } from '$/composables/paywall'
import { actionToTextId, type DashboardBindingKey } from '$/configurations/inputBindings'
import { useText } from '$/providers/react'
import { twMerge } from '$/utils/style/tailwindMerge'
import type * as tailwindVariants from '$/utils/style/tailwindVariants'
import type * as text from 'enso-common/src/text'
import * as detect from 'enso-common/src/utilities/detect'
import * as React from 'react'

/** Props for a {@link MenuEntry}. */
export interface MenuEntryProps extends tailwindVariants.VariantProps<typeof MENU_ENTRY_VARIANTS> {
  readonly icon?: SvgUseIcon | undefined
  readonly picture?: JSX.Element
  readonly action: DashboardBindingKey
  /** Overrides the text for the menu entry. */
  readonly label?: string | undefined
  readonly truncateLabel?: boolean | undefined
  readonly tooltip?: string | null | undefined
  /** When true, the button is not clickable. */
  readonly isDisabled?: boolean | undefined
  readonly title?: string | undefined
  readonly doAction: () => void
  readonly color?: TextProps['color'] | undefined
  readonly isUnderPaywall?: boolean
  readonly isSelected?: boolean
  readonly feature?: PaywallFeatureName
}

/** An item in a menu. */
export default function MenuEntry(props: MenuEntryProps) {
  const {
    action,
    label,
    isDisabled = false,
    title,
    doAction,
    icon: iconRaw,
    picture,
    truncateLabel = false,
    tooltip: tooltipValueRaw,
    color,
    isUnderPaywall = false,
    feature,
    ...variantProps
  } = props

  const { getText } = useText()
  const icon = isUnderPaywall ? 'lock' : iconRaw
  const tooltipValue = isUnderPaywall ? getText('upgradeToUseCloud') : tooltipValueRaw

  const dialogContext = useDialogContext()
  const inputBindings = inputBindingsProvider.useInputBindings()
  const info = inputBindings.metadata[action]
  const buttonRef = React.useRef<HTMLButtonElement>(null)

  const labelTextId: text.TextId =
    action === 'openInFileBrowser' ?
      detect.isOnMacOS() ? 'openInFileBrowserShortcutMacOs'
      : detect.isOnWindows() ? 'openInFileBrowserShortcutWindows'
      : 'openInFileBrowserShortcut'
    : actionToTextId(action)

  const { tooltip, targetProps } = useVisualTooltip({
    isDisabled: tooltipValue == null,
    targetRef: buttonRef,
    display: 'always',
    children: tooltipValue,
    overlayPositionProps: { placement: 'right' },
  })

  return (
    <>
      <FocusRing>
        <aria.Button
          ref={buttonRef}
          isDisabled={isDisabled}
          className="group flex w-full rounded-menu-entry"
          onPress={() => {
            if (dialogContext) {
              // Closing a dialog takes precedence over unsetting the modal.
              dialogContext.close()
            } else {
              unsetModal()
            }
            if (isUnderPaywall && feature != null) {
              setModal(<PaywallDialog modalProps={{ defaultOpen: true }} feature={feature} />)
            } else {
              doAction()
            }
          }}
        >
          <div className={MENU_ENTRY_VARIANTS(variantProps)} {...targetProps}>
            <div
              title={title}
              className={twMerge(
                'flex min-w-0 items-center gap-menu-entry whitespace-nowrap',
                truncateLabel && 'w-0 flex-1',
              )}
              style={{ color: info.color }}
            >
              {picture === undefined && (
                <Icon
                  // An empty placeholder keeps the labels of entries without an icon aligned.
                  icon={icon ?? info.icon ?? <span />}
                  className={info.color != null ? undefined : 'text-primary'}
                />
              )}
              {picture}
              <Text
                color={color}
                slot="label"
                className={truncateLabel ? 'min-w-0 flex-1' : undefined}
                truncate={truncateLabel ? '1' : undefined}
                disableLineHeightCompensation={truncateLabel}
              >
                {label ?? getText(labelTextId)}
              </Text>
            </div>
            <KeyboardShortcut action={action} />
          </div>
        </aria.Button>
      </FocusRing>
      {tooltip}
    </>
  )
}
