// app/gui/src/components/Inputs/Input.vue
<script setup lang="ts">
/**
 * @file A text input bound to a form field: the Vue counterpart of the React `Input`, a
 * `BasicInput.vue` in a `Field.vue`, styled by the same `INPUT_STYLES` and `FIELD_STYLES`.
 *
 * `name` picks the field of the enclosing `Form.vue` (or of `form`). The value, error, required
 * state and dirty/touched state come from the form. As in React, `type="number"` stores a number
 * and `type="date"` a `Date`, and the input is disabled while the form submits.
 *
 * The `<input>` carries the accessibility state: `aria-invalid`, `aria-describedby` (the
 * description and the error) and `aria-errormessage`. Attributes go on it too, as React spreads its
 * props onto the input; `testId` goes on the field, and the input is `data-testid="input"`.
 */
import Field from '$/components/Form/Field.vue'
import type { AnyFormInstance } from '$/components/Form/types'
import { useField } from '$/components/Form/useField'
import type { FIELD_STYLES } from '$/components/Form/variants'
import type { INPUT_STYLES } from '$/components/Inputs/variants'
import type { ExtractFunction, VariantProps } from '$/utils/style/tailwindVariants'
import type { Icon as IconName } from '@/util/iconMetadata/iconName'
import { computed, ref } from 'vue'
import BasicInput from './BasicInput.vue'

type InputVariants = VariantProps<typeof INPUT_STYLES>

defineOptions({ inheritAttrs: false })

const props = withDefaults(
  defineProps<{
    name: string
    form?: AnyFormInstance | undefined
    type?: string | undefined
    label?: string | undefined
    description?: string | undefined
    contextualHelp?: string | undefined
    placeholder?: string | undefined
    icon?: IconName | undefined
    defaultValue?: unknown
    isRequired?: boolean | undefined
    isDisabled?: boolean | undefined
    isInvalid?: boolean | undefined
    readOnly?: boolean | undefined
    hidden?: boolean | undefined
    autoFocus?: boolean | 'select' | undefined
    size?: InputVariants['size']
    rounded?: InputVariants['rounded']
    variant?: InputVariants['variant']
    variants?: ExtractFunction<typeof INPUT_STYLES> | undefined
    /** React's `fieldVariants`: a `FIELD_STYLES` extension for the field. */
    fieldVariants?: ExtractFunction<typeof FIELD_STYLES> | undefined
    fieldClass?: string | undefined
    testId?: string | undefined
    /** Classes for the `<input>`. */
    class?: string | undefined
  }>(),
  {
    type: 'text',
    // `undefined`, not the `false` Vue casts an absent boolean prop to: "not set, use the form's".
    isRequired: undefined,
    isDisabled: undefined,
    isInvalid: undefined,
    readOnly: undefined,
    hidden: undefined,
    autoFocus: undefined,
  },
)

const basicInput = ref<InstanceType<typeof BasicInput>>()

const field = useField<unknown>({
  name: () => props.name,
  form: () => props.form,
  defaultValue: props.defaultValue,
  isDisabled: () => props.isDisabled,
  isRequired: () => props.isRequired,
  isInvalid: () => props.isInvalid,
  focus: () => basicInput.value?.focus(),
})

const disabled = computed(() => field.isDisabled.value || field.isSubmitting.value)

const inputValue = computed(() => {
  const value = field.value.value
  if (value instanceof Date) return value.toISOString().slice(0, 'yyyy-mm-dd'.length)
  return typeof value === 'number' || typeof value === 'string' ? value : ''
})

function setValue(value: string | number | null | undefined) {
  if (typeof value !== 'string') {
    field.onChange(value)
  } else if (props.type === 'number') {
    field.onChange(Number(value))
  } else if (props.type === 'date') {
    field.onChange(new Date(value))
  } else {
    field.onChange(value)
  }
}

const describedBy = computed(
  () =>
    [
      props.description != null ? field.ids.descriptionId : null,
      field.error.value != null ? field.ids.errorId : null,
    ]
      .filter((id) => id != null)
      .join(' ') || undefined,
)
</script>

<template>
  <Field
    :name="name"
    :form="field.form"
    :label="label"
    :contextualHelp="contextualHelp"
    :isRequired="field.isRequired.value"
    :isInvalid="field.isInvalid.value"
    :isHidden="hidden"
    :fullWidth="true"
    :variants="fieldVariants"
    :ids="field.ids"
    :testId="testId"
    :class="fieldClass"
  >
    <template v-if="$slots.contextualHelp" #contextualHelp><slot name="contextualHelp" /></template>
    <BasicInput
      ref="basicInput"
      v-bind="$attrs"
      :modelValue="inputValue"
      :type="type"
      :name="name"
      :placeholder="placeholder"
      :icon="icon"
      :size="size"
      :rounded="rounded"
      :variant="variant"
      :variants="variants"
      :isInvalid="field.isInvalid.value"
      :isDisabled="disabled"
      :readOnly="readOnly"
      :required="field.isRequired.value"
      :description="description"
      :descriptionId="field.ids.descriptionId"
      :autoFocus="autoFocus"
      :aria-describedby="describedBy"
      :aria-errormessage="field.error.value != null ? field.ids.errorId : undefined"
      :class="props.class"
      @update:modelValue="setValue"
      @blur="field.onBlur"
    >
      <template v-if="$slots.addonStart" #addonStart><slot name="addonStart" /></template>
      <template v-if="$slots.addonEnd" #addonEnd><slot name="addonEnd" /></template>
      <template v-if="$slots.icon" #icon><slot name="icon" /></template>
    </BasicInput>
  </Field>
</template>

// app/gui/src/dashboard/components/Inputs/Input/Input.tsx
/** @file Text input. */
import * as aria from '#/components/aria'
import {
  Form,
  type FieldComponentProps,
  type FieldPath,
  type FieldProps,
  type FieldStateProps,
  type FieldVariantProps,
  type TSchema,
} from '#/components/Form'
import { Icon } from '#/components/Icon'
import { Text } from '#/components/Text'
import type { SvgUseIcon, TestIdProps } from '#/components/types'
import { useAutoFocus } from '#/hooks/autoFocusHooks'
import { mergeRefs } from '#/utilities/mergeRefs'
import { INPUT_STYLES } from '$/components/Inputs/variants'
import type { ExtractFunction, VariantProps } from '$/utils/style/tailwindVariants'
import { omit } from 'enso-common/src/utilities/data/object'
import {
  forwardRef,
  useRef,
  type CSSProperties,
  type ForwardedRef,
  type ReactElement,
  type ReactNode,
  type Ref,
} from 'react'

/** Props for an {@link Input}. */
export interface InputProps<
  Schema extends TSchema,
  TFieldName extends FieldPath<Schema, Constraint>,
  Constraint extends number | string = number | string,
>
  extends
    FieldStateProps<
      Omit<aria.InputProps, 'autoFocus' | 'children' | 'size'>,
      Schema,
      TFieldName,
      Constraint
    >,
    FieldProps,
    FieldVariantProps,
    Omit<VariantProps<typeof INPUT_STYLES>, 'disabled' | 'invalid'>,
    TestIdProps {
  /**
   * If `true`, the input will be focused when the component is mounted.
   * If `select`, the input will be focused and the text will be selected.
   */
  readonly autoFocus?: boolean | 'select' | undefined
  readonly style?: CSSProperties
  readonly inputRef?: Ref<HTMLInputElement>
  readonly addonStart?: ReactNode
  readonly addonEnd?: ReactNode
  readonly placeholder?: string | undefined
  /** The icon to display in the input. */
  readonly icon?: ReactElement | SvgUseIcon | null
  readonly variants?: ExtractFunction<typeof INPUT_STYLES> | undefined
  readonly fieldVariants?: FieldComponentProps<Schema>['variants']
  readonly fieldClassName?: string | undefined
}

/** Basic input component. Input component is a component that is used to get user input in a text field. */
export const Input = forwardRef(function InputImpl<
  Schema extends TSchema,
  TFieldName extends FieldPath<Schema, Constraint>,
  Constraint extends number | string = number | string,
>(props: InputProps<Schema, TFieldName, Constraint>, ref: ForwardedRef<HTMLDivElement>) {
  const {
    name,
    inputRef,
    size,
    rounded,
    type = 'text',
    variant,
    variants = INPUT_STYLES,
    fieldVariants,
    fieldClassName,
    form: formRaw,
    className,
    contextualHelp,
    testId: testIdRaw,
    description,
    ...inputProps
  } = props

  const form = Form.useFormContext(formRaw)
  const testId = testIdRaw ?? props['data-testid']

  const { fieldProps, formInstance } = Form.useFieldRegister<
    Omit<aria.InputProps, 'children' | 'size'>,
    Schema,
    TFieldName,
    Constraint
  >({
    ...props,
    form,
    setValueAs: (value: unknown) => {
      if (typeof value === 'string') {
        if (type === 'number') {
          return Number(value)
        } else if (type === 'date') {
          return new Date(value)
        } else {
          return value
        }
      } else {
        return value
      }
    },
  })

  const invalid = inputProps.isInvalid ?? fieldProps.isInvalid
  const disabled = fieldProps.disabled || formInstance.formState.isSubmitting

  const classes = variants({
    variant,
    size,
    rounded,
    invalid,
    readOnly: inputProps.readOnly,
    disabled,
  })

  const computedClassName = (states: aria.InputRenderProps) => {
    if (typeof className === 'function') {
      return className({
        ...states,
        defaultClassName: classes.textArea(),
      })
    } else {
      return className
    }
  }

  return (
    <Form.Field
      {...aria.mergeProps<FieldComponentProps<Schema>>()(inputProps, fieldProps, {
        isHidden: props.hidden,
        fullWidth: true,
        variants: fieldVariants,
        form: formInstance,
        className: fieldClassName,
      })}
      ref={ref}
      name={name}
      data-testid={testId}
      contextualHelp={contextualHelp}
    >
      <BasicInput
        {...aria.mergeProps<BasicInputProps>()(
          {
            className: (classNameStates) =>
              classes.textArea({ className: computedClassName(classNameStates) }),
            type,
            name,
            isInvalid: invalid,
            isDisabled: disabled,
            variant,
            size,
            rounded,
            variants,
            description,
          },
          omit(inputProps, 'isInvalid', 'isRequired', 'isDisabled'),
          omit(fieldProps, 'isInvalid', 'isRequired', 'isDisabled', 'invalid'),
        )}
        ref={(el) => {
          mergeRefs(inputRef, fieldProps.ref)(el)
        }}
      />
    </Form.Field>
  )
})

/** Props for an {@link BasicInput}. */
export interface BasicInputProps
  extends
    Omit<aria.InputProps, 'autoFocus' | 'children' | 'size'>,
    Omit<VariantProps<typeof INPUT_STYLES>, 'disabled' | 'invalid'>,
    TestIdProps {
  readonly inputRef?: Ref<HTMLInputElement> | undefined
  readonly description?: ReactNode | undefined
  readonly addonStart?: ReactNode | undefined
  readonly addonEnd?: ReactNode | undefined
  readonly placeholder?: string | undefined
  /** The icon to display in the input. */
  readonly icon?: ReactElement | SvgUseIcon | null | undefined
  readonly isInvalid?: boolean | undefined
  readonly isDisabled?: boolean | undefined
  readonly variants?: ExtractFunction<typeof INPUT_STYLES> | undefined
  readonly autoFocus?: boolean | 'select' | undefined
}

/** An input without a {@link Form.Field}. */
export const BasicInput = forwardRef(function BasicInputImpl(
  props: BasicInputProps,
  ref?: Ref<HTMLInputElement>,
) {
  const {
    description,
    addonStart,
    addonEnd,
    icon,
    variant,
    variants = INPUT_STYLES,
    autoFocus = false,
    size,
    rounded,
    isInvalid,
    isDisabled,
    className,
    ...inputProps
  } = props

  const privateInputRef = useRef<HTMLInputElement>(null)

  const classes = variants({
    variant,
    size,
    rounded,
    invalid: isInvalid,
    readOnly: inputProps.readOnly,
    disabled: isDisabled,
  })

  const computedClassName = (states: aria.InputRenderProps) => {
    if (typeof className === 'function') {
      return className({
        ...states,
        defaultClassName: classes.textArea(),
      })
    } else {
      return className
    }
  }

  useAutoFocus({
    ref: privateInputRef,
    disabled: autoFocus === false,
    onFocused: () => {
      if (autoFocus === 'select') {
        privateInputRef.current?.select()
      }
    },
  })

  return (
    <div
      className={classes.base()}
      onClick={() => privateInputRef.current?.focus({ preventScroll: true })}
    >
      <div className={classes.content()}>
        {addonStart != null && (
          <div className={classes.addonStart()} data-testid="addon-start">
            {addonStart}
          </div>
        )}

        {icon != null &&
          (typeof icon === 'string' ? <Icon icon={icon} className={classes.icon()} /> : icon)}

        <div className={classes.inputContainer()}>
          <aria.Input
            {...aria.mergeProps<aria.InputProps>()(
              {
                className: (states) => classes.textArea({ className: computedClassName(states) }),
                // eslint-disable-next-line @typescript-eslint/naming-convention
                'aria-invalid': isInvalid,
              },
              inputProps,
            )}
            ref={(el) => {
              mergeRefs(ref, privateInputRef)(el)
            }}
            data-testid="input"
          />
        </div>

        {addonEnd != null && (
          <div className={classes.addonEnd()} data-testid="addon-end">
            {addonEnd}
          </div>
        )}
      </div>

      {description != null && (
        <Text slot="description" className={classes.description()} data-testid="description">
          {description}
        </Text>
      )}
    </div>
  )
})
