// app/gui/src/cloud/account/ProfilePictureInput.vue
<script setup lang="ts">
/**
 * @file The user's profile picture on the Account settings tab, which uploads a new one when
 * clicked: the Vue port of the React `ProfilePictureInput`.
 */
import Form from '$/components/Form/Form.vue'
import FormError from '$/components/Form/FormError.vue'
import HiddenFile from '$/components/Inputs/HiddenFile.vue'
import ProfilePicture from '$/components/ProfilePicture/ProfilePicture.vue'
import StatelessSpinner from '$/components/Spinner/StatelessSpinner.vue'
import { useBackends } from '$/providers/backends'
import { useText } from '$/providers/text'
import { backendMutationOptions, backendQueryOptions } from '@/composables/backend'
import { useMutation, useQuery } from '@tanstack/vue-query'
import { z } from 'zod'

const { remoteBackend } = useBackends()
const { getText } = useText()

const user = useQuery(backendQueryOptions('usersMe', [], remoteBackend))
const uploadUserPicture = useMutation(backendMutationOptions('uploadUserPicture', remoteBackend))

const schema = z.object({
  picture: z.instanceof(File).refine((file) => file.type.startsWith('image/')),
})

async function upload({ picture }: z.output<typeof schema>) {
  await uploadUserPicture.mutateAsync([{ fileName: picture.name }, picture])
}
</script>

<template>
  <Form :schema="schema" @submit="upload">
    <label
      data-testid="user-profile-picture-input"
      class="relative flex h-profile-picture-large w-profile-picture-large cursor-pointer items-center rounded-full transition-colors has-[:focus-visible]:focus-ring hover:bg-frame"
    >
      <StatelessSpinner
        v-if="uploadUserPicture.isPending.value"
        phase="loading-medium"
        class="absolute -inset-1"
        :thickness="0.5"
      />
      <ProfilePicture
        :picture="user.data.value?.profilePicture"
        :name="user.data.value?.name ?? ''"
        size="large"
        class="pointer-events-none h-full w-full"
      />
      <HiddenFile autoSubmit name="picture" accept="image/*" />
    </label>
    <span class="w-profile-picture-caption py-profile-picture-caption-y">
      {{ getText('profilePictureWarning') }}
    </span>
    <FormError />
  </Form>
</template>

// app/gui/src/dashboard/layouts/Settings/ProfilePictureInput.tsx
/** @file The input for viewing and changing the user's profile picture. */
import * as aria from '#/components/aria'
import { Form } from '#/components/Form'
import { HiddenFile } from '#/components/Inputs/HiddenFile'
import { ProfilePicture } from '#/components/ProfilePicture/ProfilePicture'
import FocusRing from '#/components/styled/FocusRing'
import { backendMutationOptions, backendQueryOptions } from '#/hooks/backendHooks'
import { useText } from '$/providers/react'
import { useMutation, useQuery } from '@tanstack/react-query'
import type { Backend } from 'enso-common/src/services/Backend'
import { StatelessSpinner } from '../../components/StatelessSpinner'

/** Props for a {@link ProfilePictureInput}. */
export interface ProfilePictureInputProps {
  readonly backend: Backend
}

/** The input for viewing and changing the user's profile picture. */
export default function ProfilePictureInput(props: ProfilePictureInputProps) {
  const { backend } = props
  const { data: user } = useQuery(backendQueryOptions(backend, 'usersMe', []))
  const { getText } = useText()

  const uploadUserPicture = useMutation(backendMutationOptions(backend, 'uploadUserPicture'))

  return (
    <Form
      schema={(z) =>
        z.object({ picture: z.instanceof(File).refine((file) => file.type.startsWith('image/')) })
      }
      onSubmit={async ({ picture }) => {
        await uploadUserPicture.mutateAsync([{ fileName: picture.name }, picture])
      }}
    >
      <FocusRing within>
        <aria.Label
          data-testid="user-profile-picture-input"
          className="relative flex h-profile-picture-large w-profile-picture-large cursor-pointer items-center rounded-full transition-colors hover:bg-frame"
        >
          {uploadUserPicture.isPending && (
            <StatelessSpinner
              phase="loading-medium"
              className="absolute -inset-1"
              thickness={0.5}
            />
          )}

          <ProfilePicture
            picture={user?.profilePicture}
            name={user?.name ?? ''}
            size="large"
            className="pointer-events-none h-full w-full"
          />
          <HiddenFile autoSubmit name="picture" accept="image/*" />
        </aria.Label>
      </FocusRing>

      <aria.Text className="w-profile-picture-caption py-profile-picture-caption-y">
        {getText('profilePictureWarning')}
      </aria.Text>

      <Form.FormError />
    </Form>
  )
}
