// app/gui/src/cloud/auth/SetupTwoFaForm.vue
<script setup lang="ts">
/**
 * @file The two-factor authentication section of the Account settings tab. With 2FA on, it offers
 * to turn it off (after a code from the authenticator app); with 2FA off, a switch reveals the
 * setup (`TwoFaSetup.vue`).
 */
import type { MfaType } from '$/authentication/cognito'
import Alert from '$/components/Alert/Alert.vue'
import Button from '$/components/Button/Button.vue'
import ButtonGroup from '$/components/Button/ButtonGroup.vue'
import Dialog from '$/components/Dialog/Dialog.vue'
import DialogClose from '$/components/Dialog/DialogClose.vue'
import ErrorBoundary from '$/components/ErrorBoundary/ErrorBoundary.vue'
import SuspenseLoader from '$/components/ErrorBoundary/SuspenseLoader.vue'
import FieldValue from '$/components/Form/FieldValue.vue'
import Form from '$/components/Form/Form.vue'
import FormError from '$/components/Form/FormError.vue'
import Submit from '$/components/Form/Submit.vue'
import OTPInput from '$/components/Inputs/OTPInput.vue'
import Switch from '$/components/Switch/Switch.vue'
import Text from '$/components/Text/Text.vue'
import TextGroup from '$/components/Text/TextGroup.vue'
import { useSession } from '$/providers/session'
import { useText } from '$/providers/text'
import { useMutation, useQuery } from '@tanstack/vue-query'
import { computed } from 'vue'
import TwoFaSetup from './TwoFaSetup.vue'

/** The length of a one-time code. */
const OTP_LENGTH = 6

const { getText } = useText()
const session = useSession()

const preference = useQuery({
  queryKey: ['twoFaPreference'],
  queryFn: () => session.getMFAPreference(),
})
const isMfaEnabled = computed(() => preference.data.value !== 'NOMFA')

const updateMfaPreference = useMutation({
  mutationFn: (mfaType: MfaType) => session.updateMFAPreference(mfaType),
  meta: { invalidates: [['twoFaPreference']] },
})

/** Check a one-time code, then change the preference. */
async function verifyAndUpdate(otp: string, mfaType: MfaType) {
  const passed = await session.verifyTotpToken(otp)
  if (!passed) throw new Error('Invalid OTP')
  await updateMfaPreference.mutateAsync(mfaType)
}

// Shown once the preference is known.
await preference.suspense()
</script>

<template>
  <div v-if="isMfaEnabled" class="flex w-full flex-col gap-4">
    <Alert variant="neutral" icon="shield_check">
      <TextGroup>
        <Text variant="subtitle" weight="bold">{{ getText('2FAEnabled') }}</Text>
        <Text>{{ getText('2FAEnabledDescription') }}</Text>
      </TextGroup>
    </Alert>
    <div class="flex w-full flex-col">
      <Text variant="subtitle" weight="bold">{{ getText('disable2FA') }}</Text>
      <Text color="disabled" class="mb-4">{{ getText('disable2FADescription') }}</Text>
      <Dialog :title="getText('disable2FA')">
        <template #trigger>
          <Button variant="delete" class="self-start" icon="shield_crossed">
            {{ getText('disable2FA') }}
          </Button>
        </template>
        <Form
          :schema="(z) => z.object({ otp: z.string().min(OTP_LENGTH).max(OTP_LENGTH) })"
          :defaultValues="{ otp: '' }"
          :formOptions="{ mode: 'onSubmit' }"
          method="dialog"
          @submit="({ otp }) => verifyAndUpdate(otp, 'NOMFA')"
        >
          <Text>{{ getText('disable2FAWarning') }}</Text>
          <OTPInput
            autoFocus
            name="otp"
            :maxLength="OTP_LENGTH"
            :label="getText('verificationCode')"
          />
          <ButtonGroup>
            <Submit variant="delete">{{ getText('disable') }}</Submit>
            <DialogClose variant="outline">{{ getText('cancel') }}</DialogClose>
          </ButtonGroup>
          <FormError />
        </Form>
      </Dialog>
    </div>
  </div>
  <Form
    v-else
    :schema="
      (z) =>
        z.object({
          enabled: z.boolean(),
          display: z.string(),
          otp: z.string().min(OTP_LENGTH).max(OTP_LENGTH),
        })
    "
    :defaultValues="{ enabled: false, display: 'QR', otp: '' }"
    @submit="({ enabled, otp }) => (enabled ? verifyAndUpdate(otp, 'TOTP') : undefined)"
  >
    <Switch
      name="enabled"
      :description="getText('enable2FADescription')"
      :label="getText('enable2FA')"
    />
    <ErrorBoundary>
      <SuspenseLoader>
        <FieldValue v-slot="{ value: enabled }" name="enabled">
          <TwoFaSetup v-if="enabled === true" :otpLength="OTP_LENGTH" />
        </FieldValue>
      </SuspenseLoader>
    </ErrorBoundary>
  </Form>
</template>

// app/gui/src/dashboard/layouts/Settings/SetupTwoFaForm.tsx
/**
 * @file
 *
 * 2FA Setup Settings Section. Allows users to setup, disable, and change their 2FA method.
 */
import { Alert } from '#/components/Alert'
import { Button } from '#/components/Button'
import { CopyBlock } from '#/components/CopyBlock'
import { Dialog } from '#/components/Dialog'
import { ErrorBoundary } from '#/components/ErrorBoundary'
import { Form } from '#/components/Form'
import { OTPInput } from '#/components/Inputs/OTPInput'
import { Selector } from '#/components/Inputs/Selector'
import { Suspense } from '#/components/Suspense'
import { Switch } from '#/components/Switch'
import { Text } from '#/components/Text'
import { useMutationCallback } from '#/utilities/tanstackQuery'
import type { MfaType } from '$/authentication/cognito'
import { useSession, useText } from '$/providers/react'
import { useSuspenseQuery } from '@tanstack/react-query'
import { lazy } from 'react'

const LazyQRCode = lazy(() =>
  // eslint-disable-next-line @typescript-eslint/naming-convention
  import('qrcode.react').then(({ QRCodeCanvas }) => ({ default: QRCodeCanvas })),
)

/**
 * 2FA Setup Settings Section.
 *
 * Allows users to setup, disable, and change their 2FA method.
 */
export function SetupTwoFaForm() {
  const { getText } = useText()
  const { getMFAPreference, updateMFAPreference, verifyTotpToken } = useSession()

  const { data } = useSuspenseQuery({
    queryKey: ['twoFaPreference'],
    queryFn: () => getMFAPreference(),
  })

  const MFAEnabled = data !== 'NOMFA'

  const updateMFAPreferenceMutation = useMutationCallback({
    mutationFn: (preference: MfaType) => updateMFAPreference(preference),
    meta: { invalidates: [['twoFaPreference']] },
  })

  if (MFAEnabled) {
    return (
      <div className="flex w-full flex-col gap-4">
        <Alert variant="neutral" icon="shield_check">
          <Text.Group>
            <Text variant="subtitle" weight="bold">
              {getText('2FAEnabled')}
            </Text>
            <Text>{getText('2FAEnabledDescription')}</Text>
          </Text.Group>
        </Alert>

        <div className="flex w-full flex-col">
          <Text variant="subtitle" weight="bold">
            {getText('disable2FA')}
          </Text>

          <Text color="disabled" className="mb-4">
            {getText('disable2FADescription')}
          </Text>

          <Dialog.Trigger>
            <Button variant="delete" className="self-start" icon="shield_crossed">
              {getText('disable2FA')}
            </Button>

            <Dialog title={getText('disable2FA')}>
              <Form
                /* eslint-disable-next-line @typescript-eslint/no-magic-numbers */
                schema={(z) => z.object({ otp: z.string().min(6).max(6) })}
                formOptions={{ mode: 'onSubmit' }}
                method="dialog"
                onSubmit={({ otp }) =>
                  verifyTotpToken(otp).then((passed) => {
                    if (passed) {
                      return updateMFAPreferenceMutation('NOMFA')
                    } else {
                      throw new Error('Invalid OTP')
                    }
                  })
                }
              >
                <Text>{getText('disable2FAWarning')}</Text>

                <OTPInput autoFocus name="otp" maxLength={6} label={getText('verificationCode')} />

                <Button.Group>
                  <Form.Submit variant="delete">{getText('disable')}</Form.Submit>
                  <Dialog.Close variant="outline">{getText('cancel')}</Dialog.Close>
                </Button.Group>

                <Form.FormError />
              </Form>
            </Dialog>
          </Dialog.Trigger>
        </div>
      </div>
    )
  }
  return (
    <Form
      schema={(z) =>
        z.object({
          enabled: z.boolean(),
          display: z.string(),
          /* eslint-disable-next-line @typescript-eslint/no-magic-numbers */
          otp: z.string().min(6).max(6),
        })
      }
      defaultValues={{ enabled: false, display: 'QR' }}
      onSubmit={async ({ enabled, otp }) => {
        if (enabled) {
          return verifyTotpToken(otp).then((passed) => {
            if (passed) {
              return updateMFAPreferenceMutation('TOTP')
            } else {
              throw new Error('Invalid OTP')
            }
          })
        }
      }}
    >
      <>
        <Switch
          name="enabled"
          description={getText('enable2FADescription')}
          label={getText('enable2FA')}
        />

        <ErrorBoundary>
          <Suspense>
            <Form.FieldValue name="enabled">
              {(enabled) => enabled === true && <TwoFa />}
            </Form.FieldValue>
          </Suspense>
        </ErrorBoundary>
      </>
    </Form>
  )
}

/** Two Factor Authentication Setup Form. */
function TwoFa() {
  const { setupTOTP } = useSession()
  const { getText } = useText()

  const { data } = useSuspenseQuery({
    queryKey: ['setupTOTP'],
    queryFn: () => setupTOTP(),
  })

  return (
    <>
      <div className="flex w-full flex-col gap-4">
        <Selector name="display" items={['QR', 'Text']} aria-label={getText('display')} />

        <Form.FieldValue name="display">
          {(display) =>
            display === 'QR' && (
              <>
                <Alert key="alert" variant="neutral" icon="shield_check">
                  <Text.Group>
                    <Text variant="subtitle" weight="bold">
                      {getText('scanQR')}
                    </Text>

                    <Text>{getText('scanQRDescription')}</Text>
                  </Text.Group>
                </Alert>

                <div className="self-center">
                  <LazyQRCode
                    value={data.url}
                    bgColor="transparent"
                    fgColor="rgb(0 0 0 / 60%)"
                    size={192}
                    className="rounded-2xl border-0.5 border-primary p-4"
                  />
                </div>
              </>
            )
          }
        </Form.FieldValue>

        <Form.FieldValue name="display">
          {(display) =>
            display === 'Text' && (
              <>
                <Alert key="alert" variant="neutral" icon="shield_check">
                  <Text.Group>
                    <Text variant="subtitle" weight="bold">
                      {getText('copyLink')}
                    </Text>
                    <Text>{getText('copyLinkDescription')}</Text>
                  </Text.Group>
                </Alert>

                <CopyBlock copyText={data.url} />
              </>
            )
          }
        </Form.FieldValue>

        <OTPInput
          label={getText('verificationCode')}
          name="otp"
          maxLength={6}
          description={getText('verificationCodePlaceholder')}
        />
      </div>

      <Button.Group>
        <Form.Submit>{getText('enable')}</Form.Submit>

        <Form.Reset>{getText('cancel')}</Form.Reset>
      </Button.Group>

      <Form.FormError />
    </>
  )
}
