// app/gui/src/dashboard/components/Inputs/DatePicker/DatePicker.tsx
/** @file A date picker. */
import {
  DatePicker as AriaDatePicker,
  Calendar,
  CalendarCell,
  CalendarGrid,
  CalendarGridBody,
  CalendarGridHeader,
  CalendarHeaderCell,
  DateInput,
  DatePickerStateContext,
  DateSegment,
  Dialog,
  Group,
  Heading,
  I18nProvider,
  Label,
  type DatePickerProps as AriaDatePickerProps,
  type DateValue,
} from '#/components/aria'
import { DATE_PICKER_STYLES } from '$/components/Inputs/dateVariants'
import { useText } from '$/providers/react'
import type { VariantProps } from '$/utils/style/tailwindVariants'
import { forwardRef, useContext, type ForwardedRef } from 'react'
import type { DateSegment as DateSegmentType } from 'react-stately'

import { Button } from '#/components/Button'
import { Popover } from '#/components/Dialog'
import {
  Form,
  type FieldComponentProps,
  type FieldPath,
  type FieldPropsExcept,
  type FieldStateProps,
  type FieldValues,
  type TSchema,
} from '#/components/Form'
import { Text } from '#/components/Text'
import { TEXT_STYLE } from '$/components/Text/variants'
import { twJoin } from '$/utils/style/tailwindMerge'
/** Return the date segment using English placeholders. */
function normalizeDateSegment(segment: DateSegmentType): DateSegmentType {
  if (segment.text !== segment.placeholder) {
    return segment
  }
  switch (segment.type) {
    case 'era': {
      return { ...segment, text: 'AD', placeholder: 'AD' }
    }
    case 'year': {
      return { ...segment, text: 'yyyy', placeholder: 'yyyy' }
    }
    case 'month': {
      return { ...segment, text: 'mm', placeholder: 'mm' }
    }
    case 'day': {
      return { ...segment, text: 'dd', placeholder: 'dd' }
    }
    case 'hour': {
      return { ...segment, text: 'HH', placeholder: 'HH' }
    }
    case 'minute': {
      return { ...segment, text: 'MM', placeholder: 'MM' }
    }
    case 'second': {
      return { ...segment, text: 'SS', placeholder: 'SS' }
    }
    case 'timeZoneName': {
      return { ...segment, text: 'UTC+XX', placeholder: 'UTC+XX' }
    }
    case 'dayPeriod':
    case 'literal': {
      return segment
    }
  }
}

/** Props for a {@link DatePicker}. */
export interface DatePickerProps<
  Schema extends TSchema,
  TFieldName extends FieldPath<Schema, DateValue>,
>
  extends
    Pick<AriaDatePickerProps<DateValue>, 'granularity'>,
    FieldStateProps<
      Omit<
        AriaDatePickerProps<Extract<FieldValues<Schema>[TFieldName], DateValue>>,
        'children' | 'className' | 'style'
      >,
      Schema,
      TFieldName,
      DateValue
    >,
    FieldPropsExcept<AriaDatePickerProps<DateValue>>,
    Pick<FieldComponentProps<Schema>, 'className' | 'style'>,
    VariantProps<typeof DATE_PICKER_STYLES> {
  readonly noResetButton?: boolean
  readonly noCalendarHeader?: boolean
  readonly segments?: Partial<Record<DateSegmentType['type'], boolean>>
}

// This is a function, even though it does not contain function syntax.
// eslint-disable-next-line no-restricted-syntax
const useDateValueField = Form.makeUseField<DateValue>()

/** A date picker. */
export const DatePicker = forwardRef(function DatePickerImpl<
  Schema extends TSchema,
  TFieldName extends FieldPath<Schema, DateValue>,
>(props: DatePickerProps<Schema, TFieldName>, ref: ForwardedRef<HTMLDivElement>) {
  const {
    isRequired = false,
    noResetButton = isRequired,
    noCalendarHeader = false,
    segments = {},
    name,
    isDisabled,
    form,
    defaultValue,
    label,
    className,
    size,
    variants = DATE_PICKER_STYLES,
    granularity,
    isInvalid,
    style,
    rounded,
    contextualHelp,
    ...rest
  } = props

  const { fieldState, formInstance } = useDateValueField({
    name,
    isDisabled,
    form,
    defaultValue,
  })

  const styles = variants({ size, rounded })
  const textStyles = TEXT_STYLE()

  return (
    <Form.Field
      preventLabelFocus
      form={formInstance}
      name={name}
      fullWidth
      label={label}
      aria-label={props['aria-label']}
      aria-labelledby={props['aria-labelledby']}
      aria-describedby={props['aria-describedby']}
      isRequired={isRequired}
      isInvalid={fieldState.invalid}
      aria-details={props['aria-details']}
      ref={ref}
      style={style}
      contextualHelp={contextualHelp}
    >
      <Form.Controller
        control={formInstance.control}
        name={name}
        render={(renderProps) => (
          <AriaDatePicker
            {...rest}
            isInvalid={isInvalid ?? false}
            className={styles.base({ className })}
            {...(granularity != null ? { granularity } : {})}
            {...renderProps.field}
          >
            <Label />
            <Group className={styles.inputContainer()}>
              {/* Use Swedish locale (`sv`) because it uses ISO dates. */}
              <I18nProvider locale="sv">
                <DateInput className={styles.dateInput()}>
                  {(segment) =>
                    segments[segment.type] === false ?
                      <></>
                    : <DateSegment
                        segment={normalizeDateSegment(segment)}
                        className={styles.dateSegment({
                          className: twJoin(
                            segment.type === 'literal' && segment.text === ' ' ? 'w-1.5' : '',
                            textStyles,
                          ),
                        })}
                      />
                  }
                </DateInput>
              </I18nProvider>
              <Button variant="icon" icon="chevron_right" className={styles.calendarButton()} />
              {!noResetButton && <DatePickerResetButton className={styles.resetButton()} />}
            </Group>
            {props.description != null && <Text slot="description" />}
            <Popover size="auto" className={styles.calendarPopover()}>
              <Dialog className={styles.calendarDialog()}>
                <Calendar className={styles.calendarContainer()}>
                  <header className={styles.calendarHeader()}>
                    <Button
                      variant="icon"
                      slot="previous"
                      icon="chevron_right"
                      className="rotate-180"
                    />
                    <Heading className={styles.calendarHeading()} />
                    <Button variant="icon" slot="next" icon="chevron_right" />
                  </header>
                  <CalendarGrid className={styles.calendarGrid()}>
                    {noCalendarHeader ?
                      <></>
                    : <CalendarGridHeader className={styles.calendarGridHeader()}>
                        {() => <CalendarHeaderCell className={styles.calendarGridHeaderCell()} />}
                      </CalendarGridHeader>
                    }
                    <CalendarGridBody className={styles.calendarGridBody()}>
                      {(date) => <CalendarCell date={date} className={styles.calendarGridCell()} />}
                    </CalendarGridBody>
                  </CalendarGrid>
                  <Text slot="errorMessage" />
                </Calendar>
              </Dialog>
            </Popover>
          </AriaDatePicker>
        )}
      />
    </Form.Field>
  )
})

/** Props for a {@link DatePickerResetButton}. */
interface DatePickerResetButtonProps {
  readonly className?: string
}

/** A reset button for a {@link DatePicker}. */
function DatePickerResetButton(props: DatePickerResetButtonProps) {
  const { className } = props
  const state = useContext(DatePickerStateContext)
  const { getText } = useText()

  return (
    <Button
      // Do not inherit default Button behavior from DatePicker.
      slot={null}
      variant="icon"
      aria-label={getText('reset')}
      icon="close"
      className={className ?? ''}
      onPress={() => {
        state?.setValue(null)
      }}
    />
  )
}

// app/gui/src/components/Inputs/DatePicker.vue
<script setup lang="ts">
/**
 * @file A date picker bound to a form field holding an `@internationalized/date` value: the Vue
 * counterpart of the React `DatePicker`, styled by the same `DATE_PICKER_STYLES`.
 *
 * It is a Reka `DatePicker`, which gives what react-aria's did: the date is typed segment by
 * segment (`role="spinbutton"` segments; digits fill them, ArrowUp/ArrowDown change them,
 * ArrowLeft/ArrowRight and Tab move between them, Backspace clears), and the chevron button opens
 * a calendar grid navigated with the arrow keys, Enter selecting a day and Escape closing it. Dates
 * are written in ISO order, 24-hour, with English placeholders, as in React; the calendar speaks
 * the user's locale. The `x`
 * button clears the value (not shown when `isRequired`, unless `noResetButton` says otherwise).
 */
import Button from '$/components/Button/Button.vue'
import { POPOVER_MOTION, POPOVER_STYLES } from '$/components/Dialog/variants'
import Field from '$/components/Form/Field.vue'
import type { AnyFormInstance } from '$/components/Form/types'
import { useField } from '$/components/Form/useField'
import {
  CALENDAR_CELL_VUE_STATES,
  DATE_PICKER_STYLES,
  DATE_SEGMENT_VUE_STATES,
} from '$/components/Inputs/dateVariants'
import { portalTarget } from '$/components/portal'
import { TEXT_STYLE } from '$/components/Text/variants'
import { useText } from '$/providers/text'
import type { VariantProps } from '$/utils/style/tailwindVariants'
import type { DateValue } from '@internationalized/date'
import {
  DatePickerCalendar,
  DatePickerCell,
  DatePickerCellTrigger,
  DatePickerContent,
  DatePickerField,
  DatePickerGrid,
  DatePickerGridBody,
  DatePickerGridHead,
  DatePickerGridRow,
  DatePickerHeadCell,
  DatePickerHeader,
  DatePickerHeading,
  DatePickerInput,
  DatePickerNext,
  DatePickerPrev,
  DatePickerRoot,
  DatePickerTrigger,
} from 'reka-ui'
import { computed } from 'vue'
import { isoSegments, segmentText, type Segment, type SegmentPart } from './dateSegments'

type DatePickerVariants = VariantProps<typeof DATE_PICKER_STYLES>

const props = withDefaults(
  defineProps<{
    name: string
    form?: AnyFormInstance | undefined
    defaultValue?: DateValue | undefined
    label?: string | undefined
    description?: string | undefined
    contextualHelp?: string | undefined
    isDisabled?: boolean | undefined
    isRequired?: boolean | undefined
    isInvalid?: boolean | undefined
    /** Hide the button that clears the value. Default: `isRequired`. */
    noResetButton?: boolean | undefined
    noCalendarHeader?: boolean | undefined
    granularity?: 'day' | 'hour' | 'minute' | 'second' | undefined
    /** Segments to leave out, as `{ day: false }`. */
    segments?: Partial<Record<SegmentPart, boolean>> | undefined
    size?: DatePickerVariants['size']
    rounded?: DatePickerVariants['rounded']
    /** The accessible name, when there is no `label`. */
    ariaLabel?: string | undefined
    testId?: string | undefined
    class?: string | undefined
  }>(),
  { isRequired: false, isInvalid: undefined, noResetButton: undefined, segments: () => ({}) },
)

const { getText } = useText()

const field = useField<DateValue | null | undefined>({
  name: () => props.name,
  form: () => props.form,
  defaultValue: props.defaultValue,
  isDisabled: () => props.isDisabled,
  isRequired: () => props.isRequired,
})

const value = computed({
  get: () => field.value.value ?? null,
  set: (date: DateValue | null | undefined) => field.onChange(date ?? null),
})
const shownSegments = computed(() => props.segments ?? {})
const invalid = computed(() => props.isInvalid ?? field.isInvalid.value)
const showReset = computed(() => !(props.noResetButton ?? props.isRequired))
const styles = computed(() => DATE_PICKER_STYLES({ size: props.size, rounded: props.rounded }))
const popoverStyles = computed(() => POPOVER_STYLES({ size: 'auto' }))
const textStyles = TEXT_STYLE()

function segmentClass(part: SegmentPart, text: string) {
  return styles.value.dateSegment({
    className: `${part === 'literal' && text === ' ' ? 'w-1.5' : ''} ${textStyles} ${DATE_SEGMENT_VUE_STATES}`,
  })
}
</script>

<template>
  <Field
    :name="name"
    :form="field.form"
    :label="label"
    :description="description"
    :contextualHelp="contextualHelp"
    :isRequired="isRequired"
    :isInvalid="invalid"
    :fullWidth="true"
    :preventLabelFocus="true"
    :ids="field.ids"
    :testId="testId"
  >
    <DatePickerRoot
      v-model="value"
      :hourCycle="24"
      v-bind="granularity != null ? { granularity } : {}"
      :disabled="field.isDisabled.value"
      :required="isRequired === true"
      :closeOnSelect="true"
    >
      <div :class="styles.base({ className: props.class })" :data-invalid="invalid || undefined">
        <DatePickerField
          v-slot="{ segments: fieldSegments }"
          :class="styles.inputContainer()"
          :aria-label="ariaLabel ?? label"
          :aria-invalid="invalid || undefined"
          :aria-describedby="field.error.value != null ? field.ids.errorId : undefined"
          @focusout="field.onBlur"
        >
          <div :class="styles.dateInput()">
            <template v-for="(segment, i) in isoSegments(fieldSegments as Segment[])" :key="i">
              <DatePickerInput
                v-if="shownSegments[segment.part as SegmentPart] !== false"
                :part="segment.part"
                :class="segmentClass(segment.part as SegmentPart, segment.value)"
              >
                {{ segmentText(segment.part as SegmentPart, segment.value) }}
              </DatePickerInput>
            </template>
          </div>
          <DatePickerTrigger asChild>
            <Button
              variant="icon"
              icon="chevron_right"
              :class="styles.calendarButton()"
              :tooltip="false"
            />
          </DatePickerTrigger>
          <Button
            v-if="showReset"
            variant="icon"
            icon="close"
            :aria-label="getText('reset')"
            :class="styles.resetButton()"
            @press="value = null"
          />
        </DatePickerField>

        <DatePickerContent
          :portal="{ to: portalTarget() }"
          :sideOffset="8"
          :class="`${popoverStyles.base({ className: styles.calendarPopover() })} ${POPOVER_MOTION}`"
        >
          <div :class="popoverStyles.dialog({ className: styles.calendarDialog() })">
            <DatePickerCalendar v-slot="{ weekDays, grid }" :class="styles.calendarContainer()">
              <DatePickerHeader :class="styles.calendarHeader()">
                <DatePickerPrev asChild>
                  <Button variant="icon" icon="chevron_right" class="rotate-180" :tooltip="false" />
                </DatePickerPrev>
                <DatePickerHeading :class="styles.calendarHeading()" />
                <DatePickerNext asChild>
                  <Button variant="icon" icon="chevron_right" :tooltip="false" />
                </DatePickerNext>
              </DatePickerHeader>
              <DatePickerGrid
                v-for="month in grid"
                :key="month.value.toString()"
                :class="styles.calendarGrid()"
              >
                <DatePickerGridHead v-if="!noCalendarHeader" :class="styles.calendarGridHeader()">
                  <DatePickerGridRow>
                    <DatePickerHeadCell
                      v-for="day in weekDays"
                      :key="day"
                      :class="styles.calendarGridHeaderCell()"
                    >
                      {{ day }}
                    </DatePickerHeadCell>
                  </DatePickerGridRow>
                </DatePickerGridHead>
                <DatePickerGridBody :class="styles.calendarGridBody()">
                  <DatePickerGridRow v-for="(week, w) in month.rows" :key="w">
                    <DatePickerCell v-for="date in week" :key="date.toString()" :date="date">
                      <DatePickerCellTrigger
                        :day="date"
                        :month="month.value"
                        :class="`${styles.calendarGridCell()} ${CALENDAR_CELL_VUE_STATES}`"
                      />
                    </DatePickerCell>
                  </DatePickerGridRow>
                </DatePickerGridBody>
              </DatePickerGrid>
            </DatePickerCalendar>
          </div>
        </DatePickerContent>
      </div>
    </DatePickerRoot>
  </Field>
</template>
