// app/gui/src/dashboard/components/Inputs/OTPInput/OTPInput.tsx
/** @file */
import { mergeProps } from '#/components/aria'
import { useEventCallback } from '#/hooks/eventCallbackHooks'
import { mergeRefs } from '#/utilities/mergeRefs'
import { OTP_INPUT_STYLES, OTP_SLOT_STYLES } from '$/components/Inputs/variants'
import type { VariantProps } from '$/utils/style/tailwindVariants'
import type { OTPInputProps } from 'input-otp'
import { OTPInput as BaseOTPInput, type SlotProps as OTPInputSlotProps } from 'input-otp'
import type { ForwardedRef, Ref } from 'react'
import { forwardRef, useRef } from 'react'
import type {
  FieldComponentProps,
  FieldPath,
  FieldProps,
  FieldStateProps,
  FieldValues,
  FieldVariantProps,
  TSchema,
} from '../../Form'
import { filterNonDOMFormProps, Form } from '../../Form'
import { Separator } from '../../Separator'
import type { TestIdProps } from '../../types'

/** Props for an {@link OTPInput}. */
export interface OtpInputProps<Schema extends TSchema, TFieldName extends FieldPath<Schema, string>>
  extends
    FieldStateProps<Omit<OTPInputProps, 'children' | 'render'>, Schema, TFieldName, string>,
    FieldProps,
    FieldVariantProps,
    Omit<VariantProps<typeof OTP_INPUT_STYLES>, 'disabled' | 'invalid'>,
    TestIdProps {
  readonly inputRef?: Ref<HTMLInputElement>
  readonly maxLength: number
  readonly className?: string
  /**
   * Whether to submit the form when the OTP is filled.
   * @default true
   */
  readonly submitOnComplete?: boolean
  /** Callback when the OTP is filled. */
  readonly onComplete?: () => void
}

/** Accessible one-time password component with copy paste functionality. */
export const OTPInput = forwardRef(function OTPInputImpl<
  Schema extends TSchema,
  TFieldName extends FieldPath<Schema, string>,
>(props: OtpInputProps<Schema, TFieldName>, ref: ForwardedRef<HTMLDivElement>) {
  const {
    maxLength,
    variants = OTP_INPUT_STYLES,
    className,
    name,
    fieldVariants,
    inputRef,
    submitOnComplete = true,
    onComplete,
    contextualHelp,
    // eslint-disable-next-line @typescript-eslint/naming-convention
    form: _,
    ...inputProps
  } = props

  const innerOtpInputRef = useRef<HTMLInputElement>(null)
  const classes = variants({ className })

  const { fieldProps, formInstance } = Form.useFieldRegister(props)

  const onCompleteInternal = useEventCallback(() => {
    if (innerOtpInputRef.current?.value == null) {
      return
    }

    onComplete?.()

    if (submitOnComplete) {
      formInstance.setValue(
        name,
        // eslint-disable-next-line no-restricted-syntax
        innerOtpInputRef.current.value as FieldValues<Schema>[TFieldName],
        { shouldValidate: true },
      )
      void formInstance.submit()
    }
  })

  const onClickInternal = useEventCallback(() => {
    if (innerOtpInputRef.current) {
      // Check if the input is not already focused
      if (document.activeElement !== innerOtpInputRef.current) {
        innerOtpInputRef.current.focus()
      }
    }
  })

  return (
    <Form.Field
      {...mergeProps<FieldComponentProps<Schema>>()(fieldProps, inputProps, {
        fullWidth: true,
        isHidden: props.hidden,
        variants: fieldVariants,
        form: formInstance,
      })}
      ref={ref}
      name={name}
      contextualHelp={contextualHelp}
    >
      <BaseOTPInput
        {...filterNonDOMFormProps(mergeProps<OTPInputProps>()(fieldProps, inputProps))}
        ref={(el) => {
          mergeRefs(fieldProps.ref, inputRef, innerOtpInputRef)(el)
        }}
        name={name}
        maxLength={maxLength}
        noScriptCSSFallback={null}
        containerClassName={classes.base({ className })}
        onClick={onClickInternal}
        onComplete={onCompleteInternal}
        render={({ slots }) => (
          <OTPInputRenderer
            slots={slots}
            isInvalid={fieldProps.isInvalid}
            slotsContainerClassName={classes.slotsContainer()}
          />
        )}
      />
    </Form.Field>
  )
})

/** Props for an {@link OTPInputRenderer}. */
interface OTPInputRendererProps {
  readonly slots: OTPInputSlotProps[]
  readonly isInvalid: boolean
  readonly slotsContainerClassName: string
}
/**
 * OTPInputRenderer is a component that renders the OTP input.
 * @internal
 */
function OTPInputRenderer(props: OTPInputRendererProps) {
  const { slots, isInvalid, slotsContainerClassName } = props

  const sections = (() => {
    const items = []
    const remainingSlots = slots.length % 3

    const sectionsCount = Math.floor(slots.length / 3) + (remainingSlots > 0 ? 1 : 0)

    // eslint-disable-next-line @typescript-eslint/no-magic-numbers
    if (slots.length < 6) {
      items.push(slots)
    } else {
      for (let i = 0; i < sectionsCount; i++) {
        const section = slots.slice(i * 3, (i + 1) * 3)
        items.push(section)
      }
    }

    return items
  })()

  return (
    <div role="presentation" className="flex w-full items-center gap-2">
      {sections.map((section, idx) => (
        <Section
          key={idx}
          slotsContainerClassName={slotsContainerClassName}
          isInvalid={isInvalid}
          section={section}
          isLast={idx === sections.length - 1}
        />
      ))}
    </div>
  )
}

/**
 * Props for a {@link Section}.
 * @internal
 */
interface SectionProps {
  readonly slotsContainerClassName: string
  readonly isInvalid: boolean
  readonly section: OTPInputSlotProps[]
  readonly isLast: boolean
}

/**
 * Section is a component that renders a section of the OTP input.
 * @internal
 */
function Section(props: SectionProps) {
  const { slotsContainerClassName, isInvalid, section, isLast } = props

  return (
    <>
      <div className={slotsContainerClassName}>
        {section.map((slot, key) => (
          <Slot isInvalid={isInvalid} key={key} {...slot} />
        ))}
      </div>

      {!isLast && <Separator orientation="horizontal" className="w-3" size="medium" />}
    </>
  )
}

/** Props for a single {@link Slot}. */
interface SlotProps
  extends Omit<OTPInputSlotProps, 'isActive'>, VariantProps<typeof OTP_SLOT_STYLES> {}

/**
 * Slot is a component that represents a single char in the OTP input.
 * @internal
 */
function Slot(props: SlotProps) {
  const { char, isActive, hasFakeCaret, variants = OTP_SLOT_STYLES, isInvalid } = props
  const classes = variants({ isActive, isInvalid })

  return (
    <div className={classes.base()}>
      {char != null && <div className={classes.char()}>{char}</div>}
      {hasFakeCaret && <div role="presentation" className={classes.fakeCaret()} />}
    </div>
  )
}

// app/gui/src/components/Inputs/OTPInput.vue
<script setup lang="ts">
/**
 * @file A one-time-code input bound to a string form field: the Vue counterpart of the React
 * `OTPInput`, styled by the same `OTP_INPUT_STYLES` and `OTP_SLOT_STYLES`, on Reka's `PinInput`
 * instead of `input-otp`. One `<input>` per character (`autocomplete="one-time-code"`): typing
 * moves to the next, Backspace to the previous, arrow keys between them, and pasting a code fills
 * them all. Six or more characters are grouped in threes with a separator, as in React.
 *
 * When every character is filled it calls `onComplete` and, unless `submitOnComplete` is `false`,
 * submits the form.
 */
import Field from '$/components/Form/Field.vue'
import type { AnyFormInstance } from '$/components/Form/types'
import { useField } from '$/components/Form/useField'
import { OTP_INPUT_STYLES, OTP_SLOT_STYLES } from '$/components/Inputs/variants'
import Separator from '$/components/Separator/Separator.vue'
import { PinInputInput, PinInputRoot } from 'reka-ui'
import { computed, ref } from 'vue'
import { useAutoFocus } from './autoFocus'

const props = withDefaults(
  defineProps<{
    name: string
    form?: AnyFormInstance | undefined
    maxLength: number
    label?: string | undefined
    description?: string | undefined
    contextualHelp?: string | undefined
    isDisabled?: boolean | undefined
    isRequired?: boolean | undefined
    autoFocus?: boolean | undefined
    /** Submit the form once every character is filled. Default `true`. */
    submitOnComplete?: boolean | undefined
    onComplete?: (() => void) | undefined
    testId?: string | undefined
    class?: string | undefined
  }>(),
  { submitOnComplete: true, autoFocus: false },
)

const root = ref<HTMLElement>()
const firstInput = computed(
  () => root.value?.querySelector<HTMLInputElement>('input:not([type="hidden"])') ?? undefined,
)

const field = useField<string | undefined>({
  name: () => props.name,
  form: () => props.form,
  isDisabled: () => props.isDisabled,
  isRequired: () => props.isRequired,
  focus: () => firstInput.value?.focus(),
})

useAutoFocus(firstInput, () => props.autoFocus)

const characters = computed({
  get: () => [...(field.value.value ?? '')],
  set: (chars: string[]) => field.onChange(chars.join('')),
})
const activeIndex = ref<number | null>(null)

/** Slot indices, in sections of three when there are six or more. */
const sections = computed(() => {
  const indices = Array.from({ length: props.maxLength }, (_, i) => i)
  if (indices.length < 6) return [indices]
  const result: number[][] = []
  for (let i = 0; i < indices.length; i += 3) result.push(indices.slice(i, i + 3))
  return result
})

const classes = computed(() => OTP_INPUT_STYLES({ className: props.class }))

function slotClass(index: number) {
  const styles = OTP_SLOT_STYLES({
    isActive: activeIndex.value === index,
    isInvalid: field.isInvalid.value,
  })
  return `${styles.base()} ${styles.char()} text-center bg-transparent`
}

function handleComplete(chars: string[]) {
  props.onComplete?.()
  if (props.submitOnComplete) {
    field.form.setValue(field.name.value as never, chars.join(''), { shouldValidate: true })
    void field.form.submit()
  }
}
</script>

<template>
  <Field
    :name="name"
    :form="field.form"
    :label="label"
    :description="description"
    :contextualHelp="contextualHelp"
    :isRequired="field.isRequired.value"
    :isInvalid="field.isInvalid.value"
    :fullWidth="true"
    :ids="field.ids"
    :testId="testId"
  >
    <div ref="root" :class="classes.base()">
      <PinInputRoot
        v-model="characters"
        otp
        :name="name"
        :disabled="field.isDisabled.value || field.isSubmitting.value"
        :required="field.isRequired.value"
        role="presentation"
        class="flex w-full items-center gap-2"
        @complete="handleComplete"
      >
        <template v-for="(section, s) in sections" :key="s">
          <div :class="classes.slotsContainer()">
            <PinInputInput
              v-for="index in section"
              :key="index"
              :index="index"
              :class="slotClass(index)"
              :aria-invalid="field.isInvalid.value || undefined"
              :aria-describedby="field.error.value != null ? field.ids.errorId : undefined"
              @focus="activeIndex = index"
              @blur="((activeIndex = null), field.onBlur())"
            />
          </div>
          <Separator
            v-if="s < sections.length - 1"
            orientation="horizontal"
            class="w-3"
            size="medium"
          />
        </template>
      </PinInputRoot>
    </div>
  </Field>
</template>
