// app/gui/src/dashboard/components/Inputs/Selector/SelectorOption.tsx
/** @file An option in a selector. */
import { Radio, type RadioProps } from '#/components/aria'
import { SELECTOR_OPTION_STYLES } from '$/components/Inputs/variants'
import type { VariantProps } from '$/utils/style/tailwindVariants'
import { forwardRef, memo, type ForwardedRef } from 'react'

/** Props for a {@link SelectorOption}. */
export interface SelectorOptionProps
  extends RadioProps, VariantProps<typeof SELECTOR_OPTION_STYLES> {
  readonly label: string
  readonly isSelected: boolean
}

export const SelectorOption = memo(
  forwardRef(function SelectorOptionImpl(
    props: SelectorOptionProps,
    ref: ForwardedRef<HTMLLabelElement>,
  ) {
    const {
      label,
      isSelected,
      value,
      size,
      rounded,
      variant,
      className,
      variants = SELECTOR_OPTION_STYLES,
      ...radioProps
    } = props

    const styles = variants({ size, rounded, variant, isSelected })

    return (
      <div className={styles.base()}>
        <Radio
          ref={ref}
          {...radioProps}
          value={value}
          className={(renderProps) => {
            return styles.radio({
              className: typeof className === 'function' ? className(renderProps) : className,
              ...renderProps,
            })
          }}
        >
          {({ isHovered, isPressed }) => (
            <>
              <div className={styles.hover({ isHovered, isSelected, isPressed })} />
              <span className="isolate">{label}</span>
            </>
          )}
        </Radio>
      </div>
    )
  }),
)

// app/gui/src/components/Inputs/SelectorOption.vue
<script setup lang="ts">
/**
 * @file One option of a `Selector.vue`: the Vue counterpart of the React `SelectorOption`, styled
 * by the same `SELECTOR_OPTION_STYLES`. A native radio, visually hidden inside a `<label>`, with the
 * hover, press and focus-visible states react-aria computes tracked here the same way.
 */
import { SELECTOR_OPTION_STYLES } from '$/components/Inputs/variants'
import type { VariantProps } from '$/utils/style/tailwindVariants'
import { computed, ref } from 'vue'

type OptionVariants = VariantProps<typeof SELECTOR_OPTION_STYLES>

const {
  label,
  value,
  name,
  isSelected,
  isDisabled = false,
  size,
  rounded,
  variant,
} = defineProps<{
  label: string
  value: string
  name: string
  isSelected: boolean
  isDisabled?: boolean | undefined
  size?: OptionVariants['size']
  rounded?: OptionVariants['rounded']
  variant?: OptionVariants['variant']
}>()

const emit = defineEmits<{ select: []; blur: [] }>()

const isHovered = ref(false)
const isPressed = ref(false)
const isFocusVisible = ref(false)

const styles = computed(() => SELECTOR_OPTION_STYLES({ size, rounded, variant, isSelected }))

function onFocus(event: FocusEvent) {
  isFocusVisible.value = (event.target as HTMLElement).matches(':focus-visible')
}
</script>

<template>
  <div :class="styles.base()">
    <label
      :class="
        styles.radio({
          isHovered,
          isPressed,
          isFocusVisible,
          isSelected,
        })
      "
      :data-selected="isSelected"
      @pointerenter="isHovered = !isDisabled"
      @pointerleave="((isHovered = false), (isPressed = false))"
      @pointerdown="isPressed = !isDisabled"
      @pointerup="isPressed = false"
    >
      <input
        type="radio"
        class="sr-only"
        :name="name"
        :value="value"
        :checked="isSelected"
        :disabled="isDisabled"
        @change="emit('select')"
        @focus="onFocus"
        @blur="((isFocusVisible = false), emit('blur'))"
      />
      <div :class="styles.hover({ isHovered, isSelected, isPressed })" />
      <span class="isolate">{{ label }}</span>
    </label>
  </div>
</template>
