// app/gui/src/dashboard/components/Inputs/TimeField/TimeField.tsx
/** @file A date picker. */
import {
  TimeField as AriaTimeField,
  DateInput,
  DateSegment,
  Group,
  Label,
  TimeFieldStateContext,
  type TimeFieldProps as AriaTimeFieldProps,
  type TimeValue,
} from '#/components/aria'
import { Button } from '#/components/Button'
import {
  Form,
  type FieldComponentProps,
  type FieldPath,
  type FieldPropsExcept,
  type FieldStateProps,
  type FieldValues,
  type TSchema,
} from '#/components/Form'
import { Text } from '#/components/Text'
import { TIME_FIELD_STYLES } from '$/components/Inputs/dateVariants'
import { useText } from '$/providers/react'
import type { VariantProps } from '$/utils/style/tailwindVariants'
import { forwardRef, useContext, type ForwardedRef } from 'react'
import type { DateSegment as DateSegmentType } from 'react-stately'

/** Props for a {@link TimeField}. */
export interface TimeFieldProps<
  Schema extends TSchema,
  TFieldName extends FieldPath<Schema, TimeValue>,
>
  extends
    Pick<AriaTimeFieldProps<TimeValue>, 'granularity'>,
    FieldStateProps<
      Omit<
        AriaTimeFieldProps<Extract<FieldValues<Schema>[TFieldName], TimeValue>>,
        'children' | 'className' | 'style'
      >,
      Schema,
      TFieldName,
      TimeValue
    >,
    FieldPropsExcept<AriaTimeFieldProps<TimeValue>>,
    Pick<FieldComponentProps<Schema>, 'className' | 'style'>,
    VariantProps<typeof TIME_FIELD_STYLES> {
  readonly noResetButton?: boolean
  readonly segments?: Partial<Record<DateSegmentType['type'], boolean>>
}

// This is a function, even though it does not contain function syntax.
// eslint-disable-next-line no-restricted-syntax
const useTimeValueField = Form.makeUseField<TimeValue>()

/** A date picker. */
export const TimeField = forwardRef(function TimeFieldImpl<
  Schema extends TSchema,
  TFieldName extends FieldPath<Schema, TimeValue>,
>(props: TimeFieldProps<Schema, TFieldName>, ref: ForwardedRef<HTMLDivElement>) {
  const {
    isRequired = false,
    noResetButton = isRequired,
    segments = {},
    name,
    isDisabled,
    form,
    defaultValue,
    label,
    className,
    size,
    variants = TIME_FIELD_STYLES,
    granularity,
    style,
    isInvalid,
    contextualHelp,
    ...rest
  } = props

  const { fieldState, formInstance } = useTimeValueField({
    name,
    isDisabled,
    form,
    defaultValue,
  })

  const styles = variants({ size })

  return (
    <Form.Field
      preventLabelFocus
      form={formInstance}
      name={name}
      fullWidth
      label={label}
      aria-label={props['aria-label']}
      aria-labelledby={props['aria-labelledby']}
      aria-describedby={props['aria-describedby']}
      isRequired={isRequired}
      isInvalid={fieldState.invalid}
      aria-details={props['aria-details']}
      ref={ref}
      style={style}
      contextualHelp={contextualHelp}
    >
      <Form.Controller
        control={formInstance.control}
        name={name}
        render={(renderProps) => (
          <AriaTimeField
            {...rest}
            isInvalid={isInvalid ?? false}
            className={styles.base({ className })}
            {...(granularity != null ? { granularity } : {})}
            {...renderProps.field}
          >
            <Label />
            <Group className={styles.inputGroup()}>
              <DateInput className={styles.dateInput()}>
                {(segment) =>
                  segments[segment.type] === false ?
                    <></>
                  : <DateSegment segment={segment} className={styles.dateSegment()} />
                }
              </DateInput>
              {!noResetButton && <TimeFieldResetButton className={styles.resetButton()} />}
            </Group>
            {props.description != null && <Text slot="description" />}
          </AriaTimeField>
        )}
      />
    </Form.Field>
  )
})

/** Props for a {@link TimeFieldResetButton}. */
interface TimeFieldResetButtonProps {
  readonly className?: string
}

/** A reset button for a {@link TimeField}. */
function TimeFieldResetButton(props: TimeFieldResetButtonProps) {
  const { className } = props
  const state = useContext(TimeFieldStateContext)
  const { getText } = useText()

  return (
    <Button
      // Do not inherit default Button behavior from TimeField.
      slot={null}
      variant="icon"
      aria-label={getText('reset')}
      icon="close"
      className={className ?? ''}
      onPress={() => {
        state?.setValue(null)
      }}
    />
  )
}

// app/gui/src/components/Inputs/TimeField.vue
<script setup lang="ts">
/**
 * @file A time field bound to a form field holding an `@internationalized/date` time, styled by
 * `TIME_FIELD_STYLES`. A Reka `TimeField`: the time is typed segment by segment
 * (`role="spinbutton"`; digits fill a segment, ArrowUp/ArrowDown change it, ArrowLeft/ArrowRight
 * move between them). The `x` button clears it (not shown when `isRequired`, unless
 * `noResetButton` says otherwise).
 */
import Button from '$/components/Button/Button.vue'
import Field from '$/components/Form/Field.vue'
import type { AnyFormInstance } from '$/components/Form/types'
import { useField } from '$/components/Form/useField'
import { DATE_SEGMENT_VUE_STATES, TIME_FIELD_STYLES } from '$/components/Inputs/dateVariants'
import { useText } from '$/providers/text'
import type { VariantProps } from '$/utils/style/tailwindVariants'
import type { Time } from '@internationalized/date'
import { TimeFieldInput, TimeFieldRoot } from 'reka-ui'
import { computed } from 'vue'
import type { SegmentPart } from './dateSegments'

type TimeFieldVariants = VariantProps<typeof TIME_FIELD_STYLES>

const props = withDefaults(
  defineProps<{
    name: string
    form?: AnyFormInstance | undefined
    defaultValue?: Time | undefined
    label?: string | undefined
    description?: string | undefined
    contextualHelp?: string | undefined
    isDisabled?: boolean | undefined
    isRequired?: boolean | undefined
    isInvalid?: boolean | undefined
    /** Hide the button that clears the value. Default: `isRequired`. */
    noResetButton?: boolean | undefined
    granularity?: 'hour' | 'minute' | 'second' | undefined
    /** Segments to leave out, as `{ second: false }`. */
    segments?: Partial<Record<SegmentPart, boolean>> | undefined
    size?: TimeFieldVariants['size']
    /** The accessible name, when there is no `label`. */
    ariaLabel?: string | undefined
    testId?: string | undefined
    class?: string | undefined
  }>(),
  { isRequired: false, isInvalid: undefined, noResetButton: undefined, segments: () => ({}) },
)

const { getText } = useText()

const field = useField<Time | null | undefined>({
  name: () => props.name,
  form: () => props.form,
  defaultValue: props.defaultValue,
  isDisabled: () => props.isDisabled,
  isRequired: () => props.isRequired,
})

const value = computed({
  get: () => field.value.value ?? null,
  set: (time: Time | null | undefined) => field.onChange(time ?? null),
})
const shownSegments = computed(() => props.segments ?? {})
const invalid = computed(() => props.isInvalid ?? field.isInvalid.value)
const showReset = computed(() => !(props.noResetButton ?? props.isRequired))
const styles = computed(() => TIME_FIELD_STYLES({ size: props.size }))
</script>

<template>
  <Field
    :name="name"
    :form="field.form"
    :label="label"
    :description="description"
    :contextualHelp="contextualHelp"
    :isRequired="isRequired"
    :isInvalid="invalid"
    :fullWidth="true"
    :preventLabelFocus="true"
    :ids="field.ids"
    :testId="testId"
  >
    <div :class="styles.base({ className: props.class })" :data-invalid="invalid || undefined">
      <TimeFieldRoot
        v-slot="{ segments: fieldSegments }"
        v-model="value"
        v-bind="granularity != null ? { granularity } : {}"
        :disabled="field.isDisabled.value"
        :required="isRequired === true"
        :class="styles.inputGroup()"
        :aria-label="ariaLabel ?? label"
        :aria-invalid="invalid || undefined"
        :aria-describedby="field.error.value != null ? field.ids.errorId : undefined"
        @focusout="field.onBlur"
      >
        <div :class="styles.dateInput()">
          <template v-for="(segment, i) in fieldSegments" :key="i">
            <TimeFieldInput
              v-if="shownSegments[segment.part as SegmentPart] !== false"
              :part="segment.part"
              :class="`${styles.dateSegment()} ${DATE_SEGMENT_VUE_STATES}`"
            >
              {{ segment.value }}
            </TimeFieldInput>
          </template>
        </div>
        <Button
          v-if="showReset"
          variant="icon"
          icon="close"
          :aria-label="getText('reset')"
          :class="styles.resetButton()"
          @press="value = null"
        />
      </TimeFieldRoot>
    </div>
  </Field>
</template>
