// app/gui/src/components/Stepper/Step.vue
<script setup lang="ts">
/**
 * @file One step's marker in a `Stepper.vue`, styled by `STEP_STYLES`. It shows the step number (or
 * `icon`), a check once completed (or `completeIcon`), a title and a description; the default slot
 * adds content beside them.
 */
import Icon from '$/components/Icon/Icon.vue'
import { STEP_STYLES } from '$/components/Stepper/variants'
import Text from '$/components/Text/Text.vue'
import type { Icon as IconName } from '@/util/iconMetadata/iconName'
import { computed } from 'vue'

const {
  index,
  isCompleted,
  isCurrent,
  isFirst,
  isLast,
  icon,
  completeIcon = 'check',
  title,
  description,
  class: className,
} = defineProps<{
  index: number
  isCompleted: boolean
  isCurrent: boolean
  isFirst: boolean
  isLast: boolean
  icon?: IconName | undefined
  completeIcon?: IconName | undefined
  title?: string | undefined
  description?: string | undefined
  class?: string | undefined
}>()

const styles = computed(() =>
  STEP_STYLES({
    className,
    position:
      isFirst ? 'first'
      : isLast ? 'last'
      : undefined,
    status:
      isCompleted ? 'completed'
      : isCurrent ? 'current'
      : 'next',
  }),
)
</script>

<template>
  <div :class="styles.base()">
    <div :key="isCompleted ? 'done' : 'icon'" :class="styles.icon()">
      <Icon v-if="isCompleted" :icon="completeIcon" />
      <Icon v-else-if="icon != null" :icon="icon" />
      <Text v-else variant="subtitle" color="current" aria-hidden="true">{{ index + 1 }}</Text>
    </div>

    <div :class="styles.titleContainer()">
      <div v-if="title != null || $slots.title">
        <slot name="title">
          <Text nowrap color="current">{{ title }}</Text>
        </slot>
      </div>
      <div v-if="description != null || $slots.description">
        <slot name="description">
          <Text variant="body" color="current" truncate="2">{{ description }}</Text>
        </slot>
      </div>
    </div>
    <div :class="styles.content()"><slot /></div>
  </div>
</template>

// app/gui/src/dashboard/components/Stepper/Step.tsx
/** @file Step component. */
import { Icon } from '#/components/Icon'
import { Text } from '#/components/Text'
import type { SvgUseIcon } from '#/components/types'
import { STEP_STYLES } from '$/components/Stepper/variants'
import * as React from 'react'
import type { RenderStepProps } from './types'

/** A prop with the given type, or a function to produce a value of the given type. */
type StepProp<T> = T | ((props: RenderStepProps) => T)

/** Props for {@link Step} component. */
export interface StepProps extends RenderStepProps {
  readonly className?: StepProp<string | null | undefined>
  readonly icon?: StepProp<React.ReactElement | SvgUseIcon | null | undefined>
  readonly completeIcon?: StepProp<React.ReactElement | SvgUseIcon | null | undefined>
  readonly title?: StepProp<React.ReactElement | string | null | undefined>
  readonly description?: StepProp<React.ReactElement | string | null | undefined>
  readonly children?: StepProp<React.ReactNode>
}

/** A step component is used to represent a single step in a stepper component. */
export function Step(props: StepProps) {
  const {
    index,
    title,
    description,
    isCompleted,
    goToStep,
    nextStep,
    previousStep,
    totalSteps,
    currentStep,
    isCurrent,
    isLast,
    isFirst,
    isDisabled,
    className,
    children,
    icon = (
      <Text variant="subtitle" color="current" aria-hidden>
        {index + 1}
      </Text>
    ),
    completeIcon = 'check',
  } = props

  const renderStepProps = {
    isCompleted,
    goToStep,
    nextStep,
    previousStep,
    totalSteps,
    currentStep,
    isCurrent,
    isLast,
    isFirst,
    isDisabled,
    index,
  } satisfies RenderStepProps

  const classes = typeof className === 'function' ? className(renderStepProps) : className
  const descriptionElement =
    typeof description === 'function' ? description(renderStepProps) : description
  const titleElement = typeof title === 'function' ? title(renderStepProps) : title
  const iconElement = typeof icon === 'function' ? icon(renderStepProps) : icon
  const doneIconElement =
    typeof completeIcon === 'function' ? completeIcon(renderStepProps) : completeIcon

  const styles = STEP_STYLES({
    className: classes,
    position:
      isFirst ? 'first'
      : isLast ? 'last'
      : undefined,
    status:
      isCompleted ? 'completed'
      : isCurrent ? 'current'
      : 'next',
  })

  return (
    <div className={styles.base()}>
      <div key={isCompleted ? 'done' : 'icon'} className={styles.icon()}>
        {(() => {
          const renderIconElement = isCompleted ? doneIconElement : iconElement

          if (renderIconElement == null) {
            return null
          } else if (typeof renderIconElement === 'string') {
            return <Icon icon={renderIconElement} />
          } else {
            return renderIconElement
          }
        })()}
      </div>

      <div className={styles.titleContainer()}>
        {titleElement != null && (
          <div>
            {typeof titleElement === 'string' ?
              <Text nowrap color="current">
                {titleElement}
              </Text>
            : titleElement}
          </div>
        )}

        {descriptionElement != null && (
          <div>
            {typeof descriptionElement === 'string' ?
              <Text variant="body" color="current" truncate="2">
                {descriptionElement}
              </Text>
            : descriptionElement}
          </div>
        )}
      </div>
      <div className={styles.content()}>
        {typeof children === 'function' ? children(renderStepProps) : children}
      </div>
    </div>
  )
}
