// app/gui/src/dashboard/components/Scroller/Scroller.tsx
/** @file A component that adds scroll shadows to a container. */
import type { TestIdProps } from '#/components/types'
import { useEventCallback } from '#/hooks/eventCallbackHooks'
import { useEventListener } from '#/hooks/eventListenerHooks'
import { useMeasureCallback } from '#/hooks/measureHooks'
import { mergeRefs } from '#/utilities/mergeRefs'
import { SCROLLER_STYLES } from '$/components/Scroller/variants'
import type { VariantProps } from '$/utils/style/tailwindVariants'
import {
  forwardRef,
  startTransition,
  useCallback,
  useRef,
  useState,
  type ForwardedRef,
  type HTMLAttributes,
  type PropsWithChildren,
} from 'react'

/** Props for {@link Scroller}. */
export interface ScrollerProps
  extends
    HTMLAttributes<HTMLDivElement>,
    PropsWithChildren,
    TestIdProps,
    Omit<VariantProps<typeof SCROLLER_STYLES>, 'endHidden' | 'startHidden'> {
  readonly shadowStartClassName?: string
}

/** A component that adds scroll shadows to a container. */
export const Scroller = forwardRef(function ScrollerImpl(
  props: ScrollerProps,
  ref: ForwardedRef<HTMLDivElement>,
) {
  const {
    className,
    shadowStartClassName,
    scrollbar = false,
    snap = false,
    variants = SCROLLER_STYLES,
    orientation = 'horizontal',
    showShadows = true,
    testId,
    onScroll,
    background = 'primary',
    fullSize,
    ...rest
  } = props

  const containerRef = useRef<HTMLDivElement>(null)

  const [startHidden, setStartHidden] = useState(true)
  const [endHidden, setEndHidden] = useState(true)

  const setHidden = useEventCallback((start: boolean, end: boolean) => {
    startTransition(() => {
      setStartHidden(start)
      setEndHidden(end)
    })
  })

  const calculateShadows = useEventCallback((element: HTMLDivElement) => {
    const { scrollLeft, clientWidth, scrollTop, clientHeight, scrollWidth, scrollHeight } = element

    const scrollStart = orientation === 'horizontal' ? scrollLeft : scrollTop
    const size = orientation === 'horizontal' ? clientWidth : clientHeight
    const scrollSize = orientation === 'horizontal' ? scrollWidth : scrollHeight

    const isAtStart = scrollStart === 0
    const isAtEnd = Math.ceil(scrollStart + size) >= scrollSize

    return { isAtStart, isAtEnd }
  })

  const updateShadows = useCallback(
    (el: HTMLDivElement | null) => {
      if (!el) return
      const { isAtStart, isAtEnd } = calculateShadows(el)
      setHidden(isAtStart, isAtEnd)
    },
    [calculateShadows, setHidden],
  )

  const [measureRef] = useMeasureCallback({
    isDisabled: !showShadows,
    onResize: () => {
      updateShadows(containerRef.current)
    },
  })

  useEventListener(
    'scroll',
    () => {
      updateShadows(containerRef.current)
    },
    containerRef,
    { passive: true, isDisabled: !showShadows },
  )

  const styles = variants({
    scrollbar,
    snap,
    orientation,
    startHidden,
    endHidden,
    showShadows,
    background,
    fullSize,
  })

  return (
    <div className={styles.base({ className })} data-testid={testId} {...rest}>
      <div
        ref={(el) => {
          mergeRefs(ref, updateShadows, measureRef, containerRef)(el)
        }}
        onScroll={onScroll}
        className={styles.content()}
      >
        {props.children}
      </div>

      <div aria-hidden className={styles.shadowStart({ className: shadowStartClassName })} />
      <div aria-hidden className={styles.shadowEnd()} />
    </div>
  )
})

export { SCROLLER_STYLES } from '$/components/Scroller/variants'

// app/gui/src/components/Scroller/Scroller.vue
<script setup lang="ts">
/**
 * @file A scrolling container that fades its edges while there is more to scroll to, styled
 * by `SCROLLER_STYLES`.
 */
import { SCROLLER_STYLES } from '$/components/Scroller/variants'
import type { VariantProps } from '$/utils/style/tailwindVariants'
import { useEventListener, useResizeObserver } from '@vueuse/core'
import { computed, onMounted, ref } from 'vue'

type ScrollerVariants = VariantProps<typeof SCROLLER_STYLES>

const {
  orientation = 'horizontal',
  scrollbar = false,
  snap = false,
  showShadows = true,
  background = 'primary',
  fullSize = undefined,
  shadowStartClass,
  testId,
  class: className,
} = defineProps<{
  orientation?: ScrollerVariants['orientation']
  scrollbar?: boolean | undefined
  snap?: boolean | undefined
  showShadows?: boolean | undefined
  background?: ScrollerVariants['background']
  fullSize?: boolean | undefined
  shadowStartClass?: string | undefined
  testId?: string | undefined
  class?: string | undefined
}>()

const content = ref<HTMLElement>()
const startHidden = ref(true)
const endHidden = ref(true)

function updateShadows() {
  const element = content.value
  if (element == null || !showShadows) return
  const horizontal = orientation === 'horizontal'
  const scrollStart = horizontal ? element.scrollLeft : element.scrollTop
  const size = horizontal ? element.clientWidth : element.clientHeight
  const scrollSize = horizontal ? element.scrollWidth : element.scrollHeight
  startHidden.value = scrollStart === 0
  endHidden.value = Math.ceil(scrollStart + size) >= scrollSize
}

onMounted(updateShadows)
useEventListener(content, 'scroll', updateShadows, { passive: true })
useResizeObserver(content, updateShadows)

const styles = computed(() =>
  SCROLLER_STYLES({
    scrollbar,
    snap,
    orientation,
    startHidden: startHidden.value,
    endHidden: endHidden.value,
    showShadows,
    background,
    fullSize,
  }),
)

defineExpose({ content })
</script>

<template>
  <div :class="styles.base({ className })" :data-testid="testId">
    <div ref="content" :class="styles.content()"><slot /></div>
    <div aria-hidden="true" :class="styles.shadowStart({ className: shadowStartClass })" />
    <div aria-hidden="true" :class="styles.shadowEnd()" />
  </div>
</template>
