// app/gui/src/dashboard/pages/dashboard/components/column/DatalinkNameColumn.vue
<script setup lang="ts">
/**
 * @file The name cell of a datalink: its icon, and its name, which turns into a form while it is
 * renamed. A double click opens the asset panel's Properties tab. The Vue port of React's
 * `DatalinkNameColumn` (whose name, unlike the other cells', has no `asset-row-name` test id: kept
 * as it was).
 */
import Icon from '$/components/Icon/Icon.vue'
import EditableSpan from '$/components/EditableSpan/EditableSpan.vue'
import { useRightPanelData } from '$/providers/rightPanel'
import { isDoubleClick } from '$/utils/event'
import type { DatalinkAsset } from 'enso-common/src/services/Backend'
import { useNameCell } from './nameColumn'

const { item, isEditable } = defineProps<{
  item: DatalinkAsset
  isEditable: boolean
}>()

const rightPanel = useRightPanelData()
const { isEditingName, setIsEditing, doRename, schema } = useNameCell(
  () => item,
  () => isEditable,
)

function onKeyDown(event: KeyboardEvent) {
  if (isEditingName.value && event.key === 'Enter') event.stopPropagation()
}

function onClick(event: MouseEvent) {
  if (isDoubleClick(event)) {
    event.stopPropagation()
    rightPanel.setTemporaryTab('settings')
  }
}
</script>

<template>
  <div
    class="flex h-table-row w-auto min-w-48 max-w-full items-center gap-name-column-icon whitespace-nowrap rounded-l-full px-name-column-x py-name-column-y rounded-rows-child"
    @keydown="onKeyDown"
    @click="onClick"
  >
    <Icon icon="connector" class="m-name-column-icon" />
    <EditableSpan
      :text="item.title"
      :editable="isEditingName"
      :schema="schema"
      :onSubmit="doRename"
      :onCancel="() => setIsEditing(false)"
      class="grow bg-transparent"
    />
  </div>
</template>

// app/gui/src/dashboard/pages/dashboard/components/column/DatalinkNameColumn.tsx
/** @file The icon and name of a {@link SecretAsset}. */
import EditableSpan from '#/components/EditableSpan'
import { Icon } from '#/components/Icon'
import { useRenameAsset } from '#/hooks/backendHooks'
import { useGetAssetChildren } from '#/layouts/Drive/assetsTableItemsHooks'
import type { AssetNameColumnProps } from '#/pages/dashboard/components/column'
import { useDriveState, useDriveStore } from '#/providers/DriveProvider'
import { useDriveCurrentBackend, useRightPanelData } from '$/providers/react/container'
import { isDoubleClick } from '$/utils/event'
import { titleSchema, type DatalinkAsset } from 'enso-common/src/services/Backend'

/** Props for a {@link DatalinkNameColumn}. */
export interface DatalinkNameColumnProps extends AssetNameColumnProps {
  readonly item: DatalinkAsset
}

/**
 * The icon and name of a {@link DatalinkAsset}.
 * @throws {Error} when the asset is not a {@link DatalinkAsset}.
 * This should never happen.
 */
export default function DatalinkNameColumn(props: DatalinkNameColumnProps) {
  const { item, isEditable } = props

  const backend = useDriveCurrentBackend()
  const getAssetChildren = useGetAssetChildren()
  const renameAsset = useRenameAsset(backend)
  const rightPanel = useRightPanelData()
  const driveStore = useDriveStore()

  const isEditingName = useDriveState(({ assetToRename }) => assetToRename === item.id)
  const setIsEditing = (isEditing: boolean) => {
    if (isEditing) {
      if (isEditable) {
        driveStore.update({ assetToRename: item.id })
      }
    } else {
      driveStore.update({ assetToRename: null })
    }
  }

  const doRename = async (newTitle: string) => {
    await renameAsset(item.id, newTitle)
    setIsEditing(false)
  }

  return (
    <div
      className="flex h-table-row w-auto min-w-48 max-w-full items-center gap-name-column-icon whitespace-nowrap rounded-l-full px-name-column-x py-name-column-y rounded-rows-child"
      onKeyDown={(event) => {
        if (isEditingName && event.key === 'Enter') {
          event.stopPropagation()
        }
      }}
      onClick={(event) => {
        if (isDoubleClick(event)) {
          event.stopPropagation()
          rightPanel.setTemporaryTab('settings')
        }
      }}
    >
      <Icon icon="connector" className="m-name-column-icon" />
      <EditableSpan
        editable={isEditingName}
        onSubmit={doRename}
        onCancel={() => {
          setIsEditing(false)
        }}
        schema={() =>
          titleSchema({
            id: item.id,
            siblings: getAssetChildren(item.parentId),
          })
        }
        className="grow bg-transparent"
      >
        {item.title}
      </EditableSpan>
    </div>
  )
}
