// app/gui/src/dashboard/pages/dashboard/components/column/DirectoryNameColumn.vue
<script setup lang="ts">
/**
 * @file The name cell of a directory: a button opening it, and its name, which turns into a form
 * while it is renamed. The Vue port of React's `DirectoryNameColumn`; the button keeps its test id
 * (`directory-row-navigate-button`) and shows a spinner while the drive opens the directory.
 */
import { useDriveView } from '#/layouts/Drive/driveView'
import { STOP_PRESS_PROPAGATION } from '#/layouts/Drive/pressPropagation'
import Button from '$/components/Button/Button.vue'
import EditableSpan from '$/components/EditableSpan/EditableSpan.vue'
import { useDriveLocation } from '$/providers/drive'
import { useText } from '$/providers/text'
import { twMerge } from '$/utils/style/tailwindMerge'
import type { DirectoryAsset } from 'enso-common/src/services/Backend'
import { directoryNavigationSource, useNameCell } from './nameColumn'

const { item, isEditable } = defineProps<{
  item: DirectoryAsset
  isEditable: boolean
}>()

const { getText } = useText()
const drive = useDriveLocation()
const driveView = useDriveView()
const { isEditingName, setIsEditing, doRename, schema } = useNameCell(
  () => item,
  () => isEditable,
)

/** What opening this directory is, for the drive to show its spinner on this row's button. */
const navigationSource = directoryNavigationSource(item.id)

function onKeyDown(event: KeyboardEvent) {
  if (isEditingName.value && event.key === 'Enter') event.stopPropagation()
}

function openDirectory() {
  driveView.navigate(navigationSource, () => {
    drive.currentDirectory = item.id
  })
}
</script>

<template>
  <div
    class="group flex h-table-row w-auto min-w-48 max-w-full items-center gap-name-column-icon whitespace-nowrap rounded-l-full px-name-column-x py-name-column-y rounded-rows-child"
    @keydown="onKeyDown"
  >
    <Button
      icon="folder"
      variant="icon"
      :isLoading="driveView.isNavigatingFrom(navigationSource)"
      :aria-label="getText('open')"
      tooltipPlacement="left"
      testId="directory-row-navigate-button"
      class="mx-1 transition-transform duration-arrow"
      v-bind="STOP_PRESS_PROPAGATION"
      @press="openDirectory"
    />
    <EditableSpan
      testId="asset-row-name"
      :text="item.title"
      :editable="isEditingName"
      :class="
        twMerge('cursor-pointer bg-transparent', isEditingName ? 'cursor-text' : 'cursor-pointer')
      "
      :schema="schema"
      :onSubmit="doRename"
      :onCancel="() => setIsEditing(false)"
    />
  </div>
</template>

// app/gui/src/dashboard/pages/dashboard/components/column/DirectoryNameColumn.tsx
/** @file The icon and name of a {@link DirectoryAsset}. */
import { Button } from '#/components/Button'
import EditableSpan from '#/components/EditableSpan'
import { useRenameAsset } from '#/hooks/backendHooks'
import { useGetAssetChildren } from '#/layouts/Drive/assetsTableItemsHooks'
import type { AssetNameColumnProps } from '#/pages/dashboard/components/column'
import { useDriveState, useDriveStore } from '#/providers/DriveProvider'
import { useText } from '$/providers/react'
import { useDriveCurrentBackend, useDriveCurrentDirectory } from '$/providers/react/container'
import { twMerge } from '$/utils/style/tailwindMerge'
import { titleSchema, type DirectoryAsset } from 'enso-common/src/services/Backend'
import { useTransition } from 'react'

/** Props for a {@link DirectoryNameColumn}. */
export interface DirectoryNameColumnProps extends AssetNameColumnProps {
  readonly item: DirectoryAsset
}

/**
 * The icon and name of a {@link DirectoryAsset}.
 * @throws {Error} when the asset is not a {@link DirectoryAsset}.
 * This should never happen.
 */
export default function DirectoryNameColumn(props: DirectoryNameColumnProps) {
  const { item, isEditable, isNavigating } = props

  const backend = useDriveCurrentBackend()
  const [, setDirectory] = useDriveCurrentDirectory()
  const [isLoading, startNavigation] = useTransition()
  const { getText } = useText()
  const driveStore = useDriveStore()
  const getAssetChildren = useGetAssetChildren()
  const renameAsset = useRenameAsset(backend)

  const isEditingName = useDriveState(({ assetToRename }) => assetToRename === item.id)
  const setIsEditing = (isEditing: boolean) => {
    if (isEditable && isEditing) {
      driveStore.update({ assetToRename: item.id })
    }
    if (!isEditing) {
      driveStore.update({ assetToRename: null })
    }
  }

  const doRename = async (newTitle: string) => {
    await renameAsset(item.id, newTitle)
    setIsEditing(false)
  }

  return (
    <div
      className="group flex h-table-row w-auto min-w-48 max-w-full items-center gap-name-column-icon whitespace-nowrap rounded-l-full px-name-column-x py-name-column-y rounded-rows-child"
      onKeyDown={(event) => {
        if (isEditingName && event.key === 'Enter') {
          event.stopPropagation()
        }
      }}
    >
      <Button
        icon="folder"
        variant="icon"
        isLoading={isLoading || isNavigating}
        aria-label={getText('open')}
        tooltipPlacement="left"
        testId="directory-row-navigate-button"
        className="mx-1 transition-transform duration-arrow"
        onPress={() => {
          startNavigation(() => {
            setDirectory(item.id)
          })
        }}
      />

      <EditableSpan
        data-testid="asset-row-name"
        editable={isEditingName}
        className={twMerge(
          'cursor-pointer bg-transparent',
          isEditingName ? 'cursor-text' : 'cursor-pointer',
        )}
        schema={() =>
          titleSchema({
            id: item.id,
            siblings: getAssetChildren(item.parentId),
          })
        }
        onSubmit={doRename}
        onCancel={() => {
          setIsEditing(false)
        }}
      >
        {item.title}
      </EditableSpan>
    </div>
  )
}
