// app/gui/src/dashboard/pages/dashboard/components/column/FileNameColumn.tsx
/** @file The icon and name of a {@link FileAsset}. */
import EditableSpan from '#/components/EditableSpan'
import { Icon } from '#/components/Icon'
import { useRenameAsset } from '#/hooks/backendHooks'
import { useGetAssetChildren } from '#/layouts/Drive/assetsTableItemsHooks'
import type { AssetNameColumnProps } from '#/pages/dashboard/components/column'
import { useDriveState, useDriveStore } from '#/providers/DriveProvider'
import { useDriveCurrentBackend } from '$/providers/react/container'
import { fileIcon } from '$/utils/fileIcon'
import { titleSchema, type FileAsset } from 'enso-common/src/services/Backend'

/** Props for a {@link FileNameColumn}. */
export interface FileNameColumnProps extends AssetNameColumnProps {
  readonly item: FileAsset
}

/**
 * The icon and name of a {@link FileAsset}.
 * @throws {Error} when the asset is not a {@link FileAsset}.
 * This should never happen.
 */
export default function FileNameColumn(props: FileNameColumnProps) {
  const { item, isEditable } = props

  const backend = useDriveCurrentBackend()
  const getAssetChildren = useGetAssetChildren()
  const driveStore = useDriveStore()
  const renameAsset = useRenameAsset(backend)

  const isEditingName = useDriveState(({ assetToRename }) => assetToRename === item.id)
  const setIsEditing = (isEditing: boolean) => {
    if (isEditing) {
      if (isEditable) {
        driveStore.update({ assetToRename: item.id })
      }
    } else {
      driveStore.update({ assetToRename: null })
    }
  }

  const doRename = async (newTitle: string) => {
    await renameAsset(item.id, newTitle)
    setIsEditing(false)
  }

  return (
    <div
      className="flex h-table-row w-auto min-w-48 max-w-full items-center gap-name-column-icon whitespace-nowrap rounded-l-full px-name-column-x py-name-column-y rounded-rows-child"
      onKeyDown={(event) => {
        if (isEditingName && event.key === 'Enter') {
          event.stopPropagation()
        }
      }}
    >
      <Icon icon={fileIcon(item.title)} className="m-name-column-icon" />
      <EditableSpan
        data-testid="asset-row-name"
        editable={isEditingName}
        className="grow bg-transparent"
        onSubmit={doRename}
        onCancel={() => {
          setIsEditing(false)
        }}
        schema={() =>
          titleSchema({
            id: item.id,
            siblings: getAssetChildren(item.parentId),
          })
        }
      >
        {item.title}
      </EditableSpan>
    </div>
  )
}

// app/gui/src/dashboard/pages/dashboard/components/column/FileNameColumn.vue
<script setup lang="ts">
/**
 * @file The name cell of a file: its type's icon, and its name, which turns into a form while it is
 * renamed. The Vue port of React's `FileNameColumn`.
 */
import Icon from '$/components/Icon/Icon.vue'
import EditableSpan from '$/components/EditableSpan/EditableSpan.vue'
import { fileIcon } from '$/utils/fileIcon'
import type { FileAsset } from 'enso-common/src/services/Backend'
import { useNameCell } from './nameColumn'

const { item, isEditable } = defineProps<{
  item: FileAsset
  isEditable: boolean
}>()

const { isEditingName, setIsEditing, doRename, schema } = useNameCell(
  () => item,
  () => isEditable,
)

function onKeyDown(event: KeyboardEvent) {
  if (isEditingName.value && event.key === 'Enter') event.stopPropagation()
}
</script>

<template>
  <div
    class="flex h-table-row w-auto min-w-48 max-w-full items-center gap-name-column-icon whitespace-nowrap rounded-l-full px-name-column-x py-name-column-y rounded-rows-child"
    @keydown="onKeyDown"
  >
    <Icon :icon="fileIcon(item.title)" class="m-name-column-icon" />
    <EditableSpan
      testId="asset-row-name"
      :text="item.title"
      :editable="isEditingName"
      class="grow bg-transparent"
      :schema="schema"
      :onSubmit="doRename"
      :onCancel="() => setIsEditing(false)"
    />
  </div>
</template>
