// app/gui/src/dashboard/pages/dashboard/components/column/PathColumn.vue
<script setup lang="ts">
/**
 * @file The path column of the drive's table (shown in Recent, the trash and search results): the
 * asset's parent directory, or a button opening a popover with the whole path. Pressing a directory
 * there goes to its category, as React's `PathColumn` did (it set the directory and then the
 * category, which resets the directory: kept as it was). Test ids are React's
 * (`path-column-cell-…`, `path-column-item-…`).
 */
import { useDriveView } from '#/layouts/Drive/driveView'
import { STOP_PRESS_PROPAGATION } from '#/layouts/Drive/pressPropagation'
import Button from '$/components/Button/Button.vue'
import Popover from '$/components/Dialog/Popover.vue'
import Icon from '$/components/Icon/Icon.vue'
import Text from '$/components/Text/Text.vue'
import { useAuth } from '$/providers/auth'
import { useCategories } from '$/providers/category'
import { useDriveLocation } from '$/providers/drive'
import { parseDirectoriesPath, type PathItem } from '$/utils/parseDirectoriesPath'
import type { AnyAsset, DirectoryId } from 'enso-common/src/services/Backend'
import invariant from 'tiny-invariant'
import { computed } from 'vue'

const { item } = defineProps<{ item: AnyAsset }>()

const auth = useAuth()
const categories = useCategories()
const drive = useDriveLocation()
const driveView = useDriveView()

const finalPath = computed(() => {
  const user = auth.session?.user
  if (user == null) return []
  return parseDirectoriesPath({
    parentsPath: item.parentsPath,
    virtualParentsPath: item.virtualParentsPath,
    rootDirectoryId: user.rootDirectoryId,
    getCategoryByDirectoryId: categories.getCategoryByDirectoryId,
    categoryLabel: categories.categoryLabel,
  }).finalPath
})

const firstItemInPath = computed(() => finalPath.value.at(0))
const lastItemInPath = computed(() => finalPath.value.at(-1))
const cellTestId = computed(
  () => `path-column-cell-${item.title.toLowerCase().replace(/\s+/g, '-')}`,
)

/** What navigating from a path item is, for its spinner. */
function navigationSource(id: DirectoryId) {
  return `path:${item.id}:${id}`
}

function navigateToDirectory(targetDirectory: DirectoryId) {
  const targetDirectoryIndex = finalPath.value.findIndex(({ id }) => id === targetDirectory)
  const targetDirectoryInfo = finalPath.value[targetDirectoryIndex]
  if (targetDirectoryIndex === -1 || !targetDirectoryInfo) return
  const pathToDirectory = finalPath.value.slice(0, targetDirectoryIndex + 1)
  const rootDirectoryInThePath = pathToDirectory[0]
  // This should never happen, as we always have the root directory in the path.
  invariant(rootDirectoryInThePath, 'Root directory id is null')
  driveView.navigate(navigationSource(targetDirectory), () => {
    drive.currentDirectory = targetDirectory
    drive.currentCategory = rootDirectoryInThePath.category
  })
}

function pathItemTestId(entry: PathItem) {
  return `path-column-item-${entry.label.toLowerCase().replace(/\s+/g, '-')}`
}
</script>

<template>
  <template v-if="lastItemInPath != null && firstItemInPath != null">
    <div v-if="firstItemInPath === lastItemInPath" class="contents" :data-testid="cellTestId">
      <Button
        variant="ghost-fading"
        size="small"
        :isLoading="driveView.isNavigatingFrom(navigationSource(lastItemInPath.id))"
        :icon="lastItemInPath.icon"
        loaderPosition="icon"
        :testId="pathItemTestId(lastItemInPath)"
        v-bind="STOP_PRESS_PROPAGATION"
        @press="navigateToDirectory(lastItemInPath.id)"
      >
        <Text color="custom" truncate="1" class="max-w-48">{{ lastItemInPath.label }}</Text>
      </Button>
    </div>
    <div v-else :data-testid="cellTestId">
      <Popover
        size="auto"
        placement="bottom-end"
        :crossOffset="14"
        class="max-w-lg"
        rounded="xxxlarge"
      >
        <template #trigger>
          <Button variant="ghost-fading" size="xsmall" v-bind="STOP_PRESS_PROPAGATION">
            <div class="flex items-center gap-2">
              <Icon class="h-3 w-3" :icon="firstItemInPath.icon" />
              <Icon class="h-3 w-3" icon="chevron_right" />
              <Icon class="h-3 w-3" :icon="lastItemInPath.icon" />
              <Text color="custom" truncate="1" class="max-w-48">{{ lastItemInPath.label }}</Text>
            </div>
          </Button>
        </template>
        <div class="flex items-center gap-1">
          <template v-for="(entry, index) in finalPath" :key="entry.id">
            <Button
              variant="ghost-fading"
              size="small"
              :isLoading="driveView.isNavigatingFrom(navigationSource(entry.id))"
              :icon="entry.icon"
              loaderPosition="icon"
              :testId="pathItemTestId(entry)"
              v-bind="STOP_PRESS_PROPAGATION"
              @press="navigateToDirectory(entry.id)"
            >
              <Text color="custom" truncate="1" class="max-w-48">{{ entry.label }}</Text>
            </Button>
            <Icon
              v-if="index < finalPath.length - 1"
              icon="chevron_right"
              class="h-4 w-4 text-primary"
            />
          </template>
        </div>
      </Popover>
    </div>
  </template>
</template>

// app/gui/src/dashboard/pages/dashboard/components/column/PathColumn.tsx
/** @file A column displaying the path of the asset. */
import { Button } from '#/components/Button'
import { Popover } from '#/components/Dialog'
import { Icon } from '#/components/Icon'
import { Text } from '#/components/Text'
import { useEventCallback } from '#/hooks/eventCallbackHooks'
import { parseDirectoriesPath } from '#/layouts/Drive/Categories/parseDirectoriesPath'
import type { AssetColumnProps } from '#/pages/dashboard/components/column'
import { useCategories, useUser } from '$/providers/react'
import { useDriveCurrentCategory, useDriveCurrentDirectory } from '$/providers/react/container'
import type { Icon as IconName } from '@/util/iconMetadata/iconName'
import type { DirectoryId } from 'enso-common/src/services/Backend'
import { Fragment, useTransition } from 'react'
import invariant from 'tiny-invariant'

/** A column displaying the path of the asset. */
export function PathColumn(props: AssetColumnProps) {
  const { item } = props
  const { virtualParentsPath, parentsPath } = item

  const { rootDirectoryId } = useUser()
  const { getCategoryByDirectoryId, categoryLabel } = useCategories()
  const [, setDrive] = useDriveCurrentDirectory()
  const [, setCategory] = useDriveCurrentCategory()

  const { finalPath } = parseDirectoriesPath({
    parentsPath,
    virtualParentsPath,
    rootDirectoryId,
    getCategoryByDirectoryId,
    categoryLabel,
  })

  const navigateToDirectory = useEventCallback((targetDirectory: DirectoryId) => {
    const targetDirectoryIndex = finalPath.findIndex(({ id }) => id === targetDirectory)
    const targetDirectoryInfo = finalPath[targetDirectoryIndex]
    if (targetDirectoryIndex === -1 || !targetDirectoryInfo) {
      return
    }
    const pathToDirectory = finalPath.slice(0, targetDirectoryIndex + 1)
    const rootDirectoryInThePath = pathToDirectory[0]
    // This should never happen, as we always have the root directory in the path.
    invariant(rootDirectoryInThePath, 'Root directory id is null')
    setDrive(targetDirectory)
    setCategory(rootDirectoryInThePath.category)
  })

  const firstItemInPath = finalPath.at(0)
  const lastItemInPath = finalPath.at(-1)
  // This will be true if `finalPath` is empty.
  if (lastItemInPath == null || firstItemInPath == null) {
    return <></>
  }

  // If the first and last item are the same, then there is only one entry.
  if (firstItemInPath === lastItemInPath) {
    return (
      <div
        className="contents"
        data-testid={`path-column-cell-${item.title.toLowerCase().replace(/\s+/g, '-')}`}
      >
        <PathItem
          id={lastItemInPath.id}
          label={lastItemInPath.label}
          icon={lastItemInPath.icon}
          onNavigate={navigateToDirectory}
        />
      </div>
    )
  }

  return (
    <div data-testid={`path-column-cell-${item.title.toLowerCase().replace(/\s+/g, '-')}`}>
      <Popover.Trigger>
        <Button variant="ghost-fading" size="xsmall">
          <div className="flex items-center gap-2">
            <Icon className="h-3 w-3" icon={firstItemInPath.icon} />
            <Icon className="h-3 w-3" icon="chevron_right" />
            <Icon className="h-3 w-3" icon={lastItemInPath.icon} />

            <Text color="custom" truncate="1" className="max-w-48">
              {lastItemInPath.label}
            </Text>
          </div>
        </Button>

        <Popover
          size="auto"
          placement="bottom end"
          crossOffset={14}
          className="max-w-lg"
          rounded="xxxlarge"
        >
          <div className="flex items-center gap-1">
            {finalPath.map((entry, index) => (
              <Fragment key={entry.id}>
                <PathItem
                  id={entry.id}
                  label={entry.label}
                  icon={entry.icon}
                  onNavigate={navigateToDirectory}
                />

                {index < finalPath.length - 1 && (
                  <Icon icon="chevron_right" className="h-4 w-4 text-primary" />
                )}
              </Fragment>
            ))}
          </div>
        </Popover>
      </Popover.Trigger>
    </div>
  )
}

/** Props for the {@link PathItem} component. */
interface PathItemProps {
  readonly id: DirectoryId
  readonly label: string
  readonly icon: IconName
  readonly onNavigate: (targetDirectory: DirectoryId) => void
}

/** Individual item in the path. */
function PathItem(props: PathItemProps) {
  const { id, label, icon, onNavigate } = props
  const [transition, startTransition] = useTransition()

  const onPress = useEventCallback(() => {
    startTransition(() => {
      onNavigate(id)
    })
  })

  return (
    <Button
      key={id}
      variant="ghost-fading"
      size="small"
      isLoading={transition}
      icon={icon}
      onPress={onPress}
      loaderPosition="icon"
      testId={`path-column-item-${label.toLowerCase().replace(/\s+/g, '-')}`}
    >
      <Text color="custom" truncate="1" className="max-w-48">
        {label}
      </Text>
    </Button>
  )
}
