// app/gui/src/dashboard/pages/dashboard/components/column/ProjectNameColumn.tsx
/** @file The icon and name of a {@link ProjectAsset}. */
import EditableSpan from '#/components/EditableSpan'
import { useRenameAsset } from '#/hooks/backendHooks'
import { useGetAssetChildren } from '#/layouts/Drive/assetsTableItemsHooks'
import type { AssetNameColumnProps } from '#/pages/dashboard/components/column'
import ProjectIcon, { CLOSED_PROJECT_STATE } from '#/pages/dashboard/components/ProjectIcon'
import { useDriveState, useDriveStore } from '#/providers/DriveProvider'
import { useFullUserSession } from '$/providers/react'
import { useContainerData, useDriveCurrentBackend } from '$/providers/react/container'
import { isDoubleClick } from '$/utils/event'
import { twMerge } from '$/utils/style/tailwindMerge'
import { BackendType, titleSchema, type ProjectAsset } from 'enso-common/src/services/Backend'
import { isOnMacOS } from 'enso-common/src/utilities/detect'
import {
  PERMISSION_ACTION_CAN_EXECUTE,
  tryFindSelfPermission,
} from 'enso-common/src/utilities/permissions'

/** Props for a {@link ProjectNameColumn}. */
export interface ProjectNameColumnProps extends AssetNameColumnProps {
  readonly item: ProjectAsset
}

/** The icon and name of a {@link ProjectAsset}. */
export default function ProjectNameColumn(props: ProjectNameColumnProps) {
  const { item, isEditable, isPlaceholder } = props

  const backend = useDriveCurrentBackend()
  const { user } = useFullUserSession()
  const getAssetChildren = useGetAssetChildren()
  const renameAsset = useRenameAsset(backend)
  const driveStore = useDriveStore()
  const { openProjectLocally } = useContainerData()

  const isEditingName = useDriveState(({ assetToRename }) => assetToRename === item.id)
  const setIsEditing = (isEditing: boolean) => {
    if (isEditing) {
      if (isEditable) {
        driveStore.update({ assetToRename: item.id })
      }
    } else {
      driveStore.update({ assetToRename: null })
    }
  }

  const ownPermission = tryFindSelfPermission(user, item.permissions)
  // This is a workaround for a temporary bad state in the backend causing the `projectState` key
  // to be absent.
  // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
  const projectState = item.projectState ?? CLOSED_PROJECT_STATE
  const canExecute =
    isEditable &&
    (backend.type === BackendType.local ||
      (ownPermission != null && PERMISSION_ACTION_CAN_EXECUTE[ownPermission.permission]))
  const isCloud = backend.type === BackendType.remote
  const isOtherUserUsingProject =
    isCloud && projectState.openedBy != null && projectState.openedBy !== user.email

  const doRename = async (newTitle: string) => {
    await renameAsset(item.id, newTitle)
    setIsEditing(false)
  }

  return (
    <div
      className="flex h-table-row w-auto min-w-48 max-w-full items-center gap-name-column-icon whitespace-nowrap rounded-l-full px-name-column-x py-name-column-y rounded-rows-child"
      onKeyDown={(event) => {
        if (isEditingName && isOnMacOS() && event.key === 'Enter') {
          event.stopPropagation()
        }
      }}
      onClick={(event) => {
        if (isEditingName || isOtherUserUsingProject) {
          // The project should neither be edited nor opened in these cases.
        } else if (isDoubleClick(event) && canExecute) {
          openProjectLocally(item, backend.type)
        }
      }}
    >
      <ProjectIcon
        isDisabled={!canExecute}
        backend={backend}
        item={item}
        isPlaceholder={isPlaceholder}
      />

      <EditableSpan
        data-testid="asset-row-name"
        editable={isEditingName}
        className={twMerge(
          'grow bg-transparent',
          canExecute && !isOtherUserUsingProject && 'cursor-pointer',
          isEditingName && 'cursor-text',
        )}
        onSubmit={doRename}
        onCancel={() => {
          setIsEditing(false)
        }}
        schema={() =>
          titleSchema({
            id: item.id,
            siblings: getAssetChildren(item.parentId),
          })
        }
      >
        {item.title}
      </EditableSpan>
    </div>
  )
}

// app/gui/src/dashboard/pages/dashboard/components/column/ProjectNameColumn.vue
<script setup lang="ts">
/**
 * @file The name cell of a project: its state button (`ProjectIcon.vue`) and its name, which turns
 * into a form while it is renamed. A double click opens the project, when the user may run it and
 * nobody else is using it. The Vue port of React's `ProjectNameColumn`.
 */
import { useDriveView } from '#/layouts/Drive/driveView'
import ProjectIcon, { CLOSED_PROJECT_STATE } from '#/pages/dashboard/components/ProjectIcon.vue'
import EditableSpan from '$/components/EditableSpan/EditableSpan.vue'
import { useAuth } from '$/providers/auth'
import { useContainerData } from '$/providers/container'
import { isDoubleClick } from '$/utils/event'
import { twMerge } from '$/utils/style/tailwindMerge'
import { BackendType, type ProjectAsset } from 'enso-common/src/services/Backend'
import { isOnMacOS } from 'enso-common/src/utilities/detect'
import {
  PERMISSION_ACTION_CAN_EXECUTE,
  tryFindSelfPermission,
} from 'enso-common/src/utilities/permissions'
import { computed } from 'vue'
import { useNameCell } from './nameColumn'

const { item, isEditable } = defineProps<{
  item: ProjectAsset
  isEditable: boolean
}>()

const auth = useAuth()
const container = useContainerData()
const driveView = useDriveView()
const backend = computed(() => driveView.location.backend)
const { isEditingName, setIsEditing, doRename, schema } = useNameCell(
  () => item,
  () => isEditable,
)

const user = computed(() => auth.session?.user)
const ownPermission = computed(() =>
  user.value != null ? tryFindSelfPermission(user.value, item.permissions) : null,
)
// A workaround for a temporary bad state in the backend, in which `projectState` is absent.
const projectState = computed(() => item.projectState ?? CLOSED_PROJECT_STATE)
const canExecute = computed(
  () =>
    isEditable &&
    (backend.value.type === BackendType.local ||
      (ownPermission.value != null &&
        PERMISSION_ACTION_CAN_EXECUTE[ownPermission.value.permission])),
)
const isOtherUserUsingProject = computed(
  () =>
    backend.value.type === BackendType.remote &&
    projectState.value.openedBy != null &&
    projectState.value.openedBy !== user.value?.email,
)

function onKeyDown(event: KeyboardEvent) {
  if (isEditingName.value && isOnMacOS() && event.key === 'Enter') event.stopPropagation()
}

function onClick(event: MouseEvent) {
  if (isEditingName.value || isOtherUserUsingProject.value) {
    // The project should neither be edited nor opened in these cases.
  } else if (isDoubleClick(event) && canExecute.value) {
    container.openProjectLocally(item, backend.value.type)
  }
}
</script>

<template>
  <div
    class="flex h-table-row w-auto min-w-48 max-w-full items-center gap-name-column-icon whitespace-nowrap rounded-l-full px-name-column-x py-name-column-y rounded-rows-child"
    @keydown="onKeyDown"
    @click="onClick"
  >
    <ProjectIcon :isDisabled="!canExecute" :backend="backend" :item="item" />
    <EditableSpan
      testId="asset-row-name"
      :text="item.title"
      :editable="isEditingName"
      :class="
        twMerge(
          'grow bg-transparent',
          canExecute && !isOtherUserUsingProject && 'cursor-pointer',
          isEditingName && 'cursor-text',
        )
      "
      :schema="schema"
      :onSubmit="doRename"
      :onCancel="() => setIsEditing(false)"
    />
  </div>
</template>
