// app/gui/src/dashboard/components/Form/components/Field.tsx
/** @file Field component */
import * as aria from '#/components/aria'
import { FIELD_ERROR_STYLES, FIELD_STYLES } from '$/components/Form/variants'
import type { Path } from '$/utils/objectPath'
import type { VariantProps } from '$/utils/style/tailwindVariants'
import * as React from 'react'
import { ContextualHelp } from '../../ContextualHelp'
import { Form } from '../Form'
import type * as types from './types'

export { FIELD_ERROR_STYLES, FIELD_STYLES }

/** Props for Field component */
export interface FieldComponentProps<Schema extends types.TSchema>
  extends VariantProps<typeof FIELD_STYLES>, types.FieldProps {
  readonly 'data-testid'?: string | undefined
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  readonly name: Path<types.FieldValues<Schema>, any>
  readonly form?: types.FormInstance<Schema> | undefined
  readonly isInvalid?: boolean | undefined
  readonly className?: string | undefined
  readonly children?: React.ReactNode | ((props: FieldChildrenRenderProps) => React.ReactNode)
  readonly style?: React.CSSProperties | undefined
}

/** Props for Field variants */
export interface FieldVariantProps {
  readonly fieldVariants?: VariantProps<typeof FIELD_STYLES>['variants'] | undefined
}

/** Props for Field children */
export interface FieldChildrenRenderProps {
  readonly isInvalid: boolean
  readonly isDirty: boolean
  readonly isTouched: boolean
  readonly isValidating: boolean
  readonly hasError: boolean
  readonly error?: string | null | undefined
}

/** Field component */
export const Field = React.forwardRef(function FieldImpl<Schema extends types.TSchema>(
  props: FieldComponentProps<Schema>,
  ref: React.ForwardedRef<HTMLDivElement>,
) {
  const {
    children,
    className,
    label,
    description,
    fullWidth,
    error,
    isHidden,
    isInvalid = false,
    isRequired = false,
    preventLabelFocus = false,
    contextualHelp,
    variants = FIELD_STYLES,
  } = props

  const labelId = React.useId()
  const descriptionId = React.useId()
  const errorId = React.useId()

  // This is SAFE, we are just using a type with added constraint.
  // eslint-disable-next-line no-restricted-syntax
  const fieldState = Form.useFieldState(props as never)

  const invalid = isInvalid || fieldState.hasError

  const classes = variants({ fullWidth, isInvalid: invalid, isHidden })

  const hasError = (error !== undefined ? error : fieldState.error) != null

  return (
    <div
      ref={ref}
      className={classes.base({ className })}
      data-testid={props['data-testid']}
      aria-invalid={invalid}
      aria-label={props['aria-label']}
      aria-labelledby={labelId}
      aria-describedby={descriptionId}
      aria-details={props['aria-details']}
      aria-errormessage={hasError ? errorId : ''}
      aria-required={isRequired}
    >
      <aria.Label
        id={labelId}
        className={classes.fieldContent()}
        onClickCapture={(event) => {
          if (preventLabelFocus) {
            event.preventDefault()
          }
        }}
      >
        <div className={classes.labelContainer()}>
          {label != null && (
            <span id={labelId} className={classes.label()}>
              {label}

              {isRequired && (
                <span aria-hidden="true" className="text-primary" data-testid="required-mark">
                  {' *'}
                </span>
              )}
            </span>
          )}

          <div className={classes.contextualHelp()}>
            {contextualHelp != null && (
              <ContextualHelp placement="top" variant="help">
                {contextualHelp}
              </ContextualHelp>
            )}
          </div>
        </div>

        <div className={classes.content()}>
          {typeof children === 'function' ?
            children({
              isInvalid: invalid,
              isDirty: fieldState.isDirty,
              isTouched: fieldState.isTouched,
              isValidating: fieldState.isValidating,
              hasError: fieldState.hasError,
              error: fieldState.error,
            })
          : children}
        </div>
      </aria.Label>

      {description != null && (
        <span id={descriptionId} className={classes.description()} data-testid="description">
          {description}
        </span>
      )}

      <FieldError
        error={error}
        id={errorId}
        /* This is SAFE, we are just using a type with added constraint. */
        /* eslint-disable-next-line no-restricted-syntax */
        name={props.name as types.FieldPath<Schema, string>}
        form={props.form}
      />
    </div>
  )
})

/**
 * Props for the {@link FieldError} component.
 */
export interface FieldErrorProps<
  Schema extends types.TSchema,
  TFieldName extends types.FieldPath<Schema, string>,
>
  extends React.HTMLAttributes<HTMLSpanElement>, VariantProps<typeof FIELD_ERROR_STYLES> {
  readonly error?: React.ReactNode | string | null | undefined
  readonly id?: string | undefined
  readonly form?: types.FormInstance<Schema> | undefined
  readonly name: TFieldName
}

/**
 * Component for displaying an error message for a field.
 */
export function FieldError<
  Schema extends types.TSchema,
  TFieldName extends types.FieldPath<Schema, string>,
>(props: FieldErrorProps<Schema, TFieldName>) {
  const { error, className, id, variants = FIELD_ERROR_STYLES, fullWidth, ...rest } = props

  // This is SAFE, we are just using a type with added constraint.
  // eslint-disable-next-line no-restricted-syntax
  const fieldState = Form.useFieldState(props as never)

  const hasError = (error !== undefined ? error : fieldState.error) != null

  if (!hasError) {
    return null
  }

  return (
    <span data-testid="error" id={id} className={variants({ className, fullWidth })} {...rest}>
      {error ?? fieldState.error}
    </span>
  )
}

// app/gui/src/components/Form/Field.vue
<script setup lang="ts">
/**
 * @file A labelled form field: the Vue counterpart of the React `Form.Field`, styled by the same
 * `FIELD_STYLES`. The inputs render their control inside one; a custom control can too.
 *
 * It shows the label (with a `*` when required, and an optional contextual-help button), the
 * control in a `<label>` so that clicking the text focuses it (unless `preventLabelFocus`), a
 * description, and the field's error from the form. The default slot receives the field's state
 * (`isInvalid`, `isDirty`, `isTouched`, `isValidating`, `hasError`, `error`).
 *
 * The `ids` tie the control to the label, description and error: an input passes the ids from
 * its `useField` and sets `aria-describedby`/`aria-errormessage` on its control with them.
 * Attributes (`aria-label`, `aria-details`, …) go on the root, as in React.
 * @example
 * ```vue
 * <Field name="age" label="Age" :ids="field.ids">
 *   <input v-model="field.value.value" :aria-describedby="field.ids.errorId" />
 * </Field>
 * ```
 */
import ContextualHelp from '$/components/ContextualHelp/ContextualHelp.vue'
import { FIELD_STYLES } from '$/components/Form/variants'
import type { ExtractFunction } from '$/utils/style/tailwindVariants'
import { computed, useId } from 'vue'
import FieldError from './FieldError.vue'
import { useOptionalFormContext } from './formContext'
import type { AnyFormInstance } from './types'
import type { FieldIds } from './useField'

const {
  name,
  form,
  label,
  description,
  contextualHelp,
  error = undefined,
  isRequired = false,
  isInvalid = false,
  // `undefined`, not the `false` Vue casts an absent boolean prop to, so the variant default applies.
  fullWidth = undefined,
  isHidden = undefined,
  preventLabelFocus = false,
  variants = FIELD_STYLES,
  ids,
  testId,
  class: className,
} = defineProps<{
  name: string
  form?: AnyFormInstance | undefined
  label?: string | undefined
  description?: string | undefined
  contextualHelp?: string | undefined
  /** Overrides the field's error. `null` shows none. */
  error?: string | null | undefined
  isRequired?: boolean | undefined
  isInvalid?: boolean | undefined
  fullWidth?: boolean | undefined
  isHidden?: boolean | undefined
  preventLabelFocus?: boolean | undefined
  /** React's `variants`/`fieldVariants`: a `FIELD_STYLES` extension. */
  variants?: ExtractFunction<typeof FIELD_STYLES> | undefined
  ids?: FieldIds | undefined
  testId?: string | undefined
  class?: string | undefined
}>()

const formInstance = useOptionalFormContext(form)
const state = computed(() => formInstance?.getFieldState(name))
const invalid = computed(() => isInvalid || state.value?.hasError === true)
const hasError = computed(() => (error !== undefined ? error : state.value?.error) != null)

const ownId = useId()
const fieldIds = computed<FieldIds>(
  () =>
    ids ?? {
      labelId: `${ownId}-label`,
      descriptionId: `${ownId}-description`,
      errorId: `${ownId}-error`,
    },
)

const classes = computed(() => variants({ fullWidth, isInvalid: invalid.value, isHidden }))

function onLabelClick(event: MouseEvent) {
  if (preventLabelFocus) event.preventDefault()
}
</script>

<template>
  <div
    :class="classes.base({ className })"
    :data-testid="testId"
    :aria-invalid="invalid"
    :aria-labelledby="label != null || $slots.label ? fieldIds.labelId : undefined"
    :aria-describedby="
      description != null || $slots.description ? fieldIds.descriptionId : undefined
    "
    :aria-errormessage="hasError ? fieldIds.errorId : undefined"
    :aria-required="isRequired"
  >
    <label :class="classes.fieldContent()" @click.capture="onLabelClick">
      <div :class="classes.labelContainer()">
        <span v-if="label != null || $slots.label" :id="fieldIds.labelId" :class="classes.label()">
          <slot name="label">{{ label }}</slot>
          <span
            v-if="isRequired"
            aria-hidden="true"
            class="text-primary"
            data-testid="required-mark"
          >
            {{ ' *' }}
          </span>
        </span>

        <div :class="classes.contextualHelp()">
          <ContextualHelp v-if="contextualHelp != null || $slots.contextualHelp" placement="top">
            <slot name="contextualHelp">{{ contextualHelp }}</slot>
          </ContextualHelp>
        </div>
      </div>

      <div :class="classes.content()">
        <slot
          :isInvalid="invalid"
          :isDirty="state?.isDirty ?? false"
          :isTouched="state?.isTouched ?? false"
          :isValidating="state?.isValidating ?? false"
          :hasError="state?.hasError ?? false"
          :error="state?.error"
        />
      </div>
    </label>

    <span
      v-if="description != null || $slots.description"
      :id="fieldIds.descriptionId"
      :class="classes.description()"
      data-testid="description"
    >
      <slot name="description">{{ description }}</slot>
    </span>

    <FieldError :id="fieldIds.errorId" :error="error" :name="name" :form="formInstance" />
  </div>
</template>
