// app/gui/src/dashboard/components/Text/Text.tsx
/** @file Text component */
import * as aria from '#/components/aria'
import type { TooltipElementType } from '#/components/VisualTooltip'
import * as visualTooltip from '#/components/VisualTooltip'
import { useEventCallback } from '#/hooks/eventCallbackHooks'
import { mergeRefs } from '#/utilities/mergeRefs'
import type { VariantProps } from '#/utilities/tailwindVariants'
import * as React from 'react'
import { memo } from 'react'
import type { TestIdProps } from '../types'
import * as textProvider from './TextProvider'
import { TEXT_STYLE } from './variants'

/** Props for the Text component */
export interface TextProps
  extends Omit<aria.TextProps, 'color'>, VariantProps<typeof TEXT_STYLE>, TestIdProps {
  readonly elementType?: keyof HTMLElementTagNameMap
  readonly lineClamp?: number
  readonly tooltip?: TooltipElementType
  readonly tooltipTriggerRef?: React.RefObject<HTMLElement>
  readonly tooltipDisplay?: visualTooltip.VisualTooltipOptions['display'] | 'never'
  readonly tooltipPlacement?: aria.Placement
  readonly tooltipOffset?: number
  readonly tooltipCrossOffset?: number
}

/** Heading props */
export interface HeadingProps extends Omit<TextProps, 'elementType'> {
  // eslint-disable-next-line @typescript-eslint/no-magic-numbers
  readonly level?: '1' | '2' | '3' | '4' | '5' | '6' | 1 | 2 | 3 | 4 | 5 | 6
}

/** Heading component */
const Heading = memo(
  React.forwardRef(function Heading(props: HeadingProps, ref: React.Ref<HTMLHeadingElement>) {
    const { level = 1, ...textProps } = props
    return <Text ref={ref} elementType={`h${level}`} variant="h1" balance {...textProps} />
  }),
)

/** Body props */
export interface BodyProps extends Omit<TextProps, 'elementType'> {}

/** Body component */
const Body = memo(
  React.forwardRef(function Body(props: BodyProps, ref: React.Ref<HTMLParagraphElement>) {
    return <Text ref={ref} variant="body" balance {...props} />
  }),
)

/** Text group component. It's used to visually group text elements together */
function TextGroup(props: React.PropsWithChildren) {
  return (
    <textProvider.TextProvider value={{ isInsideTextComponent: true }}>
      {props.children}
    </textProvider.TextProvider>
  )
}

/** Text component that supports truncation and show a tooltip on hover when text is truncated */
export const Text = Object.assign(
  memo(
    React.forwardRef(function Text(props: TextProps, ref: React.Ref<HTMLSpanElement>) {
      const {
        className,
        variant,
        font,
        italic,
        weight,
        nowrap,
        monospace,
        transform,
        truncate,
        lineClamp = 1,
        children,
        color,
        balance,
        testId,
        elementType: ElementType = 'span',
        tooltip: tooltipElement = children,
        tooltipDisplay = 'whenOverflowing',
        tooltipPlacement,
        tooltipOffset,
        tooltipCrossOffset,
        textSelection,
        disableLineHeightCompensation = false,
        align,
        ...ariaProps
      } = props

      const textElementRef = React.useRef<HTMLElement>(null)
      const textContext = textProvider.useTextContext()

      const textClasses = TEXT_STYLE({
        variant,
        font,
        weight,
        transform,
        monospace,
        italic,
        nowrap,
        truncate,
        color,
        balance,
        textSelection,
        disableLineHeightCompensation:
          disableLineHeightCompensation === false ?
            textContext.isInsideTextComponent
          : disableLineHeightCompensation,
        className,
        align,
      })

      const isTooltipDisabled = useEventCallback(() => {
        if (tooltipDisplay === 'whenOverflowing') {
          return truncate == null
        }
        if (tooltipDisplay === 'always') {
          return tooltipElement === false || tooltipElement == null
        }

        return tooltipDisplay === 'never'
      })

      const { tooltip, targetProps } = visualTooltip.useVisualTooltip({
        isDisabled: isTooltipDisabled(),
        targetRef: textElementRef,
        display: tooltipDisplay === 'never' ? () => false : tooltipDisplay,
        children: tooltipElement,
        ...(tooltipPlacement || tooltipOffset != null || tooltipCrossOffset != null ?
          {
            overlayPositionProps: {
              ...(tooltipPlacement && { placement: tooltipPlacement }),
              ...(tooltipOffset != null && { offset: tooltipOffset }),
              ...(tooltipCrossOffset != null && { crossOffset: tooltipCrossOffset }),
            },
          }
        : {}),
      })

      return (
        <textProvider.TextProvider value={{ isInsideTextComponent: true }}>
          <ElementType
            // @ts-expect-error This is caused by the type-safe `elementType` type.
            ref={(el) => {
              // eslint-disable-next-line @typescript-eslint/no-unsafe-argument
              mergeRefs(ref, textElementRef)(el)
            }}
            data-testid={testId}
            className={textClasses}
            {...aria.mergeProps<React.HTMLAttributes<HTMLElement>>()(
              ariaProps,
              targetProps,
              truncate === 'custom' ?
                // eslint-disable-next-line @typescript-eslint/naming-convention,no-restricted-syntax
                ({ style: { '--line-clamp': `${lineClamp}` } } as React.HTMLAttributes<HTMLElement>)
              : {},
            )}
          >
            {children}
          </ElementType>

          {tooltip}
        </textProvider.TextProvider>
      )
    }),
  ),
  /* eslint-disable @typescript-eslint/naming-convention */
  {
    Heading,
    Body,
    Group: TextGroup,
  },
  /* eslint-enable @typescript-eslint/naming-convention */
)

// app/gui/src/components/Text/Text.vue
<script setup lang="ts">
/**
 * @file Text in one of the design system's type styles.
 *
 * A truncated text (`truncate`) shows its full content in a visual tooltip when it overflows. The
 * tooltip is the default slot again, unless the `tooltip` prop or slot gives something else;
 * `tooltipDisplay` changes when it shows (`always`, or `never`).
 *
 * Nested texts drop their line-height compensation; `TextGroup.vue` does the same for a group of
 * sibling texts.
 */
import type { Placement } from '$/components/placement'
import { TEXT_STYLE } from '$/components/Text/variants'
import { useVisualTooltip } from '$/components/Tooltip/useVisualTooltip'
import VisualTooltipPopup from '$/components/Tooltip/VisualTooltipPopup.vue'
import type { VariantProps } from '$/utils/style/tailwindVariants'
import { computed, ref, useSlots } from 'vue'
import { injectInsideText, provideInsideText } from './textContext'

type TextVariants = VariantProps<typeof TEXT_STYLE>

// The root is a fragment (the text and its tooltip), so attributes go to the text explicitly.
defineOptions({ inheritAttrs: false })

const {
  elementType = 'span',
  variant,
  weight,
  color,
  transform,
  // `undefined`, not the `false` Vue casts an absent boolean prop to: "not truncated".
  truncate = undefined,
  lineClamp = 1,
  italic,
  nowrap,
  monospace,
  balance,
  textSelection,
  disableLineHeightCompensation = false,
  align,
  // `undefined`, not the `false` Vue casts an absent `string | false` prop to.
  tooltip = undefined,
  tooltipDisplay = 'whenOverflowing',
  tooltipPlacement,
  tooltipOffset,
  tooltipCrossOffset,
  testId,
  class: className,
} = defineProps<{
  elementType?: keyof HTMLElementTagNameMap | undefined
  variant?: TextVariants['variant']
  weight?: TextVariants['weight']
  color?: TextVariants['color']
  transform?: TextVariants['transform']
  truncate?: true | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | 'custom' | undefined
  /** The number of lines for `truncate: 'custom'`. */
  lineClamp?: number | undefined
  italic?: boolean | undefined
  nowrap?: boolean | 'normal' | undefined
  monospace?: boolean | undefined
  balance?: boolean | undefined
  textSelection?: TextVariants['textSelection']
  disableLineHeightCompensation?: boolean | 'bottom' | 'top' | undefined
  align?: TextVariants['align']
  /** The tooltip's text; `false` disables it. Defaults to the text itself. */
  tooltip?: string | false | undefined
  tooltipDisplay?: 'always' | 'never' | 'whenOverflowing' | undefined
  tooltipPlacement?: Placement | undefined
  tooltipOffset?: number | undefined
  tooltipCrossOffset?: number | undefined
  testId?: string | undefined
  class?: string | undefined
}>()

const isInsideText = injectInsideText(true) != null
provideInsideText()

const classes = computed(() =>
  TEXT_STYLE({
    variant,
    weight,
    transform,
    monospace,
    italic,
    nowrap,
    truncate,
    color,
    balance,
    textSelection,
    disableLineHeightCompensation:
      disableLineHeightCompensation === false ? isInsideText : disableLineHeightCompensation,
    className,
    align,
  }),
)

const slots = useSlots()
const isTooltipDisabled = computed(() => {
  if (tooltip === false) return true
  switch (tooltipDisplay) {
    case 'whenOverflowing':
      return truncate == null
    case 'always':
      return tooltip == null && slots.tooltip == null && slots.default == null
    case 'never':
      return true
  }
})

const element = ref<HTMLElement>()
const { isOpen, onTooltipEnter, onTooltipLeave } = useVisualTooltip(element, {
  display: () => (tooltipDisplay === 'always' ? 'always' : 'whenOverflowing'),
  isDisabled: isTooltipDisabled,
})

/** The text's element, for a caller that measures it. */
defineExpose({ element })
</script>

<template>
  <component
    :is="elementType"
    v-bind="$attrs"
    ref="element"
    :class="classes"
    :data-testid="testId"
    :style="truncate === 'custom' ? { '--line-clamp': `${lineClamp}` } : undefined"
  >
    <slot />
  </component>
  <VisualTooltipPopup
    v-if="!isTooltipDisabled"
    :target="element"
    :open="isOpen"
    :placement="tooltipPlacement"
    :offset="tooltipOffset"
    :crossOffset="tooltipCrossOffset"
    @pointerenter="onTooltipEnter"
    @pointerleave="onTooltipLeave"
  >
    <slot name="tooltip">{{ tooltip }}<slot v-if="tooltip == null" /></slot>
  </VisualTooltipPopup>
</template>
