// app/gui/src/dashboard/pages/dashboard/components/AssetRow.tsx
/** @file A table row for an arbitrary asset. */
import type { ContextMenuApi } from '#/components/ContextMenu'
import {
  useDeleteAssetsMutationState,
  useMoveAssetsMutationState,
  useRestoreAssetsMutationState,
} from '#/hooks/backendBatchedHooks'
import { useBackendMutationState } from '#/hooks/backendHooks'
import * as dragAndDropHooks from '#/hooks/dragAndDropHooks'
import { useDragDelayAction } from '#/hooks/dragDelayHooks'
import { useEventCallback } from '#/hooks/eventCallbackHooks'
import { useSyncRef } from '#/hooks/syncRefHooks'
import type * as assetsTable from '#/layouts/AssetsTable'
import { useGetAsset } from '#/layouts/Drive/assetsTableItemsHooks'
import * as columnModule from '#/pages/dashboard/components/column'
import * as columnUtils from '#/pages/dashboard/components/column/columnUtils'
import {
  useDriveState,
  useDriveStore,
  useSetDragTargetAssetId,
  useSetSelectedAssets,
} from '#/providers/DriveProvider'
import { unsetModal } from '#/providers/ModalProvider'
import * as drag from '#/utilities/drag'
import { isLocalCategory } from '$/providers/category'
import { useFullUserSession } from '$/providers/react'
import {
  useDriveCurrentBackend,
  useDriveCurrentCategory,
  useDriveCurrentDirectory,
} from '$/providers/react/container'
import { useIsProjectClosing } from '$/providers/react/openedProjects'
import * as eventModule from '$/utils/event'
import * as tailwindMerge from '$/utils/style/tailwindMerge'
import Visibility from '$/utils/Visibility'
import type { Label } from 'enso-common/src/services/Backend'
import * as backendModule from 'enso-common/src/services/Backend'
import {
  canPermissionModifyDirectoryContents,
  isTeamPath,
  tryFindSelfPermission,
} from 'enso-common/src/utilities/permissions'
import * as React from 'react'
import { useTransition } from 'react'
import invariant from 'tiny-invariant'

/** Common properties for state and setters passed to event handlers on an {@link AssetRow}. */
export interface AssetRowInnerProps {
  readonly asset: backendModule.AnyAsset
  readonly state: assetsTable.AssetsTableState
}

/** Props for an {@link AssetRow}. */
export interface AssetRowProps {
  readonly item: backendModule.AnyAsset
  readonly isPlaceholder: boolean
  readonly id: backendModule.AssetId
  readonly parentId: backendModule.DirectoryId
  readonly contextMenuRef: React.RefObject<ContextMenuApi>
  readonly type: backendModule.AssetType
  readonly state: assetsTable.AssetsTableState
  readonly columns: readonly columnUtils.Column[]
  readonly isKeyboardSelected: boolean
  readonly labels: readonly Label[]
  readonly grabKeyboardFocus: (item: backendModule.AnyAsset) => void
  readonly onClick: (props: AssetRowInnerProps, event: React.MouseEvent) => void
  readonly select: (item: backendModule.AnyAsset) => void
  readonly onDragStart: (
    event: React.DragEvent<HTMLTableRowElement>,
    item: backendModule.AnyAsset,
  ) => void
  readonly onDragEnd: (
    event: React.DragEvent<HTMLTableRowElement>,
    item: backendModule.AnyAsset,
  ) => void
  readonly onDrop: (
    event: React.DragEvent<HTMLTableRowElement>,
    item: backendModule.AnyAsset,
  ) => void
}

/** Render a real asset row. */
export const AssetRow = React.memo(function AssetRowImpl(props: AssetRowProps) {
  const {
    id,
    parentId,
    contextMenuRef,
    isKeyboardSelected,
    select,
    state,
    columns,
    onClick,
    isPlaceholder,
    type,
    item,
    labels,
    grabKeyboardFocus,
  } = props

  const [category] = useDriveCurrentCategory()
  const backend = useDriveCurrentBackend()
  const [, setDirectory] = useDriveCurrentDirectory()
  const [isNavigating, startNavigation] = useTransition()

  const driveStore = useDriveStore()
  const { user } = useFullUserSession()
  const setSelectedAssets = useSetSelectedAssets()
  const getAsset = useGetAsset()
  const { isSelected, isMultiSelected } = useDriveState(
    ({ visuallySelectedKeys, selectedIds }) => {
      const selection = visuallySelectedKeys ?? selectedIds

      return {
        isSelected: selection.has(id),
        isMultiSelected: selection.size > 1,
      }
    },
    { areEqual: 'shallow', unsafeEnableTransition: true },
  )

  const draggableProps = dragAndDropHooks.useDraggable({ isDisabled: !isSelected })
  const [isDraggedOver, setIsDraggedOver] = React.useState(false)
  const setDragTargetAssetId = useSetDragTargetAssetId()
  const rootRef = React.useRef<HTMLElement | null>(null)
  const grabKeyboardFocusRef = useSyncRef(grabKeyboardFocus)

  const isEditingName = useDriveState(({ assetToRename }) => assetToRename === item.id)

  const isDeletingSingleAsset =
    useBackendMutationState(backend, 'deleteAsset', {
      predicate: ({ state: { variables } }) => variables?.[0] === item.id,
      select: () => null,
    }).length !== 0
  const isDeletingMultipleAssets =
    useDeleteAssetsMutationState(backend, {
      predicate: ({ state: { variables: [assetIds = []] = [] } }) => assetIds.includes(item.id),
      select: () => null,
    }).length !== 0
  const isDeleting = isDeletingSingleAsset || isDeletingMultipleAssets
  const isRestoringSingleAsset =
    useBackendMutationState(backend, 'undoDeleteAsset', {
      predicate: ({ state: { variables } }) => variables?.[0] === item.id,
      select: () => null,
    }).length !== 0
  const isRestoringMultipleAssets =
    useRestoreAssetsMutationState(backend, {
      predicate: ({ state: { variables = { ids: [], parentId: null } } }) =>
        variables.ids.includes(item.id),
      select: () => null,
    }).length !== 0
  const isRestoring = isRestoringSingleAsset || isRestoringMultipleAssets
  const isUpdatingSingleAsset =
    useBackendMutationState(backend, 'updateAsset', {
      predicate: ({ state: { variables } }) => variables?.[0] === item.id,
      select: () => null,
    }).length !== 0
  const isMovingMultipleAssets =
    useMoveAssetsMutationState(backend, {
      predicate: ({ state: { variables: [assetIds = []] = [] } }) => assetIds.includes(item.id),
      select: () => null,
    }).length !== 0

  const isUpdating = isUpdatingSingleAsset || isMovingMultipleAssets
  const isClosing = useIsProjectClosing(
    item.type === backendModule.AssetType.project ? item.id : null,
  )

  const insertionVisibility = useDriveState((driveState) => {
    return (
        driveState.pasteData?.type === 'move' &&
          driveState.pasteData.data.assets.some((asset) => asset.id === item.id)
      ) ?
        'opacity-50'
      : Visibility.visible
  })
  const visibility = isDeleting || isRestoring || isUpdating ? 'opacity-50' : insertionVisibility

  const setSelected = useEventCallback((newSelected: boolean) => {
    const { selectedAssets } = driveStore.state
    setSelectedAssets(
      newSelected ?
        [...selectedAssets, item]
      : selectedAssets.filter((otherAsset) => otherAsset.id !== item.id),
    )
  })

  React.useEffect(() => {
    if (isSelected && (isDeleting || isRestoring)) {
      setSelected(false)
    }
  }, [isSelected, setSelected, isDeleting, isRestoring])

  React.useEffect(() => {
    if (isKeyboardSelected) {
      rootRef.current?.focus()
      grabKeyboardFocusRef.current(item)
    }
  }, [grabKeyboardFocusRef, isKeyboardSelected, item])

  const dragDelayProps = useDragDelayAction(
    item.type === backendModule.AssetType.directory ?
      () => {
        startNavigation(() => {
          setDirectory(item.id)
        })
      }
    : undefined,
  )

  const onDragOver = (event: React.DragEvent<Element>) => {
    const directoryId = item.type === backendModule.AssetType.directory ? id : parentId
    const payload = drag.ASSET_ROWS.lookup(event)
    const isPayloadMatch =
      payload != null && payload.items.every((innerItem) => innerItem.key !== directoryId)
    const canPaste = (() => {
      if (!isPayloadMatch) {
        return false
      }
      if (isLocalCategory(category)) {
        return true
      }
      return payload.items.every(({ asset }) => {
        const payloadParentId = getAsset(asset.id)?.parentId
        const parent = payloadParentId == null ? null : getAsset(payloadParentId)
        if (!parent) {
          // Assume the parent is the root directory.
          return true
        }
        if (isTeamPath(parent.ensoPath)) {
          return true
        }
        // Assume user path; check permissions
        const permission = tryFindSelfPermission(user, item.permissions)
        return permission != null && canPermissionModifyDirectoryContents(permission.permission)
      })
    })()

    if ((isPayloadMatch && canPaste) || event.dataTransfer.types.includes('Files')) {
      event.preventDefault()
      if (item.type === backendModule.AssetType.directory && state.category.type !== 'trash') {
        setIsDraggedOver(true)
      }
    }
  }

  switch (type) {
    case backendModule.AssetType.directory:
    case backendModule.AssetType.project:
    case backendModule.AssetType.file:
    case backendModule.AssetType.datalink:
    case backendModule.AssetType.secret: {
      const innerProps: AssetRowInnerProps = { asset: item, state }

      return (
        <>
          <tr
            data-testid="asset-row"
            tabIndex={0}
            data-selected={isSelected}
            aria-selected={isSelected}
            data-id={item.id}
            onDoubleClick={() => {
              if (item.type === backendModule.AssetType.directory) {
                startNavigation(() => {
                  setDirectory(item.id)
                })
              }
            }}
            ref={(element) => {
              rootRef.current = element

              if (isKeyboardSelected && element?.contains(document.activeElement) === false) {
                element.scrollIntoView({ block: 'nearest' })
                element.focus()
              }
            }}
            className={tailwindMerge.twMerge(
              'h-table-row rounded-full transition-all ease-in-out rounded-rows-child',
              visibility,
              (isDraggedOver || isSelected) && 'selected',
            )}
            {...draggableProps}
            onClick={(event) => {
              unsetModal()
              onClick(innerProps, event)
              if (
                item.type === backendModule.AssetType.directory &&
                eventModule.isDoubleClick(event) &&
                !isEditingName
              ) {
                // This must be processed on the next tick, otherwise it will be overridden
                // by the default click handler.
                window.setTimeout(() => {
                  setSelected(false)
                })
              }
            }}
            onContextMenu={(event) => {
              // We show the asset row context menu if the asset is included in the selection.
              // Or we click on a asset row outside of the selection. In that case we reset the
              // selection to the clicked asset.
              if (isSelected && isMultiSelected) {
                return
              }

              event.preventDefault()
              event.stopPropagation()

              if (!isSelected) {
                select(item)
              }

              driveStore.update({
                contextMenuData: {
                  triggerRef: rootRef,
                  initialContextMenuPosition: event,
                },
              })
              contextMenuRef.current?.open(event)
            }}
            onDragStart={(event) => {
              if (isEditingName) {
                event.preventDefault()
              }

              if (
                item.type === backendModule.AssetType.project &&
                (backendModule.IS_OPENING_OR_OPENED[item.projectState.type] || isClosing)
              ) {
                event.preventDefault()
              }

              props.onDragStart(event, item)
            }}
            onDragEnter={(event) => {
              // Required because `dragover` does not fire on `mouseenter`.
              onDragOver(event)
              dragDelayProps.onDragEnter(event)
            }}
            onDragOver={(event) => {
              if (state.category.type === 'trash') {
                event.dataTransfer.dropEffect = 'none'
              }
              onDragOver(event)
            }}
            onDragEnd={(event) => {
              setIsDraggedOver(false)
              props.onDragEnd(event, item)
            }}
            onDragLeave={(event) => {
              if (
                event.relatedTarget instanceof Node &&
                !event.currentTarget.contains(event.relatedTarget)
              ) {
                setIsDraggedOver(false)
                setDragTargetAssetId(null)
              }
              dragDelayProps.onDragLeave(event)
            }}
            onDrop={(event) => {
              event.preventDefault()
              event.stopPropagation()

              setIsDraggedOver(false)
              dragDelayProps.onDrop(event)
              props.onDrop(event, item)
            }}
          >
            {columns.map((column) => {
              const Render = columnModule.COLUMN_RENDERER[column]
              return (
                <td key={column} className={columnUtils.COLUMN_CSS_CLASS[column]}>
                  <Render
                    isNavigating={isNavigating}
                    labels={labels}
                    isPlaceholder={isPlaceholder}
                    backendType={backend.type}
                    item={item}
                    setSelected={setSelected}
                    state={state}
                    isEditable={state.category.type !== 'trash'}
                  />
                </td>
              )
            })}
          </tr>
        </>
      )
    }
    default: {
      invariant(false, `Unsupported asset type '${String(type)}'`)
    }
  }
})

// app/gui/src/dashboard/pages/dashboard/components/AssetRow.vue
<script setup lang="ts">
/**
 * @file A row of the drive's table: the Vue port of React's `AssetRow`, with its `asset-row` test
 * id, `aria-selected` and `data-selected`.
 *
 * The row is the drag source of the selection and a drop target: dropped rows move into it (or its
 * parent, for a file), dropped files upload there, and assets held over a directory for two seconds
 * open it. A right click opens the asset's context menu, selecting the row first, unless the row is
 * part of a multiple selection, whose menu the table opens. A row the arrow keys moved to takes the
 * focus and is scrolled into view. A row being deleted, restored, renamed or moved (or cut) is
 * faded.
 */
import { ASSET_ROWS } from '#/layouts/Drive/drag'
import { useAssetItems } from '#/layouts/Drive/assetItems'
import { useDriveView } from '#/layouts/Drive/driveView'
import AssetColumnCell from '#/pages/dashboard/components/column/AssetColumnCell.vue'
import { COLUMN_CSS_CLASS, type Column } from '#/pages/dashboard/components/column/columnUtils'
import { directoryNavigationSource } from '#/pages/dashboard/components/column/nameColumn'
import { useDragDelayAction } from '$/composables/dragDelay'
import { isLocalCategory } from '$/providers/category'
import { useAuth } from '$/providers/auth'
import { useDriveLocation } from '$/providers/drive'
import { useDriveStore } from '$/providers/driveStore'
import { useModals } from '$/providers/modals'
import { useOpenedProjects } from '$/providers/openedProjects'
import { isDoubleClick, isElementTextInput } from '$/utils/event'
import { twMerge } from '$/utils/style/tailwindMerge'
import Visibility from '$/utils/Visibility'
import {
  AssetType,
  IS_OPENING_OR_OPENED,
  type AnyAsset,
  type Label,
} from 'enso-common/src/services/Backend'
import {
  canPermissionModifyDirectoryContents,
  isTeamPath,
  tryFindSelfPermission,
} from 'enso-common/src/utilities/permissions'
import { computed, onMounted, onUpdated, ref, watch } from 'vue'

const props = defineProps<{
  item: AnyAsset
  columns: readonly Column[]
  labels: readonly Label[]
  isKeyboardSelected: boolean
  /** Whether a deletion of this asset is in flight. */
  isDeleting: boolean
  /** Whether a restoration of this asset from the trash is in flight. */
  isRestoring: boolean
  /** Whether a rename or move of this asset is in flight. */
  isUpdating: boolean
  grabKeyboardFocus: (item: AnyAsset) => void
  onRowClick: (item: AnyAsset, event: MouseEvent) => void
  select: (item: AnyAsset) => void
  onRowDragStart: (event: DragEvent, item: AnyAsset) => void
  onRowDragEnd: () => void
  onRowDrop: (event: DragEvent, item: AnyAsset) => void
  openContextMenu: (position: Pick<MouseEvent, 'pageX' | 'pageY'>) => void
}>()

const driveStore = useDriveStore()
const driveView = useDriveView()
const drive = useDriveLocation()
const assetItems = useAssetItems()
const auth = useAuth()
const modals = useModals()
const openedProjects = useOpenedProjects()

const category = computed(() => driveView.location.category)

const selection = computed(() => driveStore.visuallySelectedKeys ?? driveStore.selectedIds)
const isSelected = computed(() => selection.value.has(props.item.id))
const isMultiSelected = computed(() => selection.value.size > 1)
const isEditingName = computed(() => driveStore.assetToRename === props.item.id)
const isClosing = computed(
  () => props.item.type === AssetType.project && openedProjects.isProjectClosing(props.item.id),
)

const insertionVisibility = computed(() =>
  (
    driveStore.pasteData?.type === 'move' &&
    driveStore.pasteData.data.assets.some((asset) => asset.id === props.item.id)
  ) ?
    'opacity-50'
  : Visibility.visible,
)
const visibility = computed(() =>
  props.isDeleting || props.isRestoring || props.isUpdating ?
    'opacity-50'
  : insertionVisibility.value,
)

const root = ref<HTMLTableRowElement>()
const isDraggedOver = ref(false)

/**
 * Whether the row may be dragged: only while selected, and not while a text field in it has the
 * focus (a Firefox bug otherwise breaks selecting text there), as React's `useDraggable`.
 */
const isDraggable = ref(true)
function onFocusIn(event: FocusEvent) {
  if (isElementTextInput(event.target)) isDraggable.value = false
}
function onFocusOut() {
  isDraggable.value = true
}

function setSelected(newSelected: boolean) {
  const { selectedAssets } = driveStore.state
  driveStore.setSelectedAssets(
    newSelected ?
      [...selectedAssets, props.item]
    : selectedAssets.filter((otherAsset) => otherAsset.id !== props.item.id),
  )
}

// An asset being deleted or restored leaves the selection.
watch(
  () => isSelected.value && (props.isDeleting || props.isRestoring),
  (shouldDeselect) => {
    if (shouldDeselect) setSelected(false)
  },
  { immediate: true },
)

// A row the arrow keys moved to takes the keyboard focus.
watch(
  () => [props.isKeyboardSelected, props.item] as const,
  ([isKeyboardSelected]) => {
    if (isKeyboardSelected) {
      root.value?.focus()
      props.grabKeyboardFocus(props.item)
    }
  },
  { flush: 'post' },
)

/** As React's ref callback did on every render: keep the keyboard-selected row focused and shown. */
function focusIfKeyboardSelected() {
  const element = root.value
  if (props.isKeyboardSelected && element != null && !element.contains(document.activeElement)) {
    element.scrollIntoView({ block: 'nearest' })
    element.focus()
  }
}
onMounted(focusIfKeyboardSelected)
onUpdated(focusIfKeyboardSelected)

function openDirectory() {
  driveView.navigate(directoryNavigationSource(props.item.id), () => {
    drive.currentDirectory = props.item.id as never
  })
}

const dragDelay = useDragDelayAction(
  props.item.type === AssetType.directory ? openDirectory : undefined,
)

function onDragOverRow(event: DragEvent) {
  const item = props.item
  const directoryId = item.type === AssetType.directory ? item.id : item.parentId
  const payload = ASSET_ROWS.lookup(event)
  const isPayloadMatch =
    payload != null && payload.items.every((innerItem) => innerItem.key !== directoryId)
  const canPaste = (() => {
    if (!isPayloadMatch) return false
    if (isLocalCategory(category.value)) return true
    return payload.items.every(({ asset }) => {
      const payloadParentId = assetItems.getAsset(asset.id)?.parentId
      const parent = payloadParentId == null ? null : assetItems.getAsset(payloadParentId)
      // Assume the parent is the root directory.
      if (!parent) return true
      if (isTeamPath(parent.ensoPath)) return true
      // Assume a user path; check the permissions.
      const user = auth.session?.user
      const permission = user != null ? tryFindSelfPermission(user, item.permissions) : null
      return permission != null && canPermissionModifyDirectoryContents(permission.permission)
    })
  })()

  if ((isPayloadMatch && canPaste) || event.dataTransfer?.types.includes('Files') === true) {
    event.preventDefault()
    if (item.type === AssetType.directory && category.value.type !== 'trash') {
      isDraggedOver.value = true
    }
  }
}

function onDoubleClick() {
  if (props.item.type === AssetType.directory) openDirectory()
}

function onClick(event: MouseEvent) {
  modals.closeAll()
  props.onRowClick(props.item, event)
  if (props.item.type === AssetType.directory && isDoubleClick(event) && !isEditingName.value) {
    // On the next tick, or the default click handler overrides it.
    window.setTimeout(() => setSelected(false))
  }
}

function onContextMenu(event: MouseEvent) {
  // The table opens the menu of a multiple selection this row is part of.
  if (isSelected.value && isMultiSelected.value) return
  event.preventDefault()
  event.stopPropagation()
  if (!isSelected.value) props.select(props.item)
  driveStore.update({
    contextMenuData: {
      triggerRef: { current: root.value ?? null },
      initialContextMenuPosition: { pageX: event.pageX, pageY: event.pageY },
    },
  })
  props.openContextMenu(event)
}

function onDragStart(event: DragEvent) {
  const item = props.item
  if (isEditingName.value) event.preventDefault()
  if (
    item.type === AssetType.project &&
    (IS_OPENING_OR_OPENED[item.projectState.type] || isClosing.value)
  ) {
    event.preventDefault()
  }
  props.onRowDragStart(event, item)
}

function onDragEnter(event: DragEvent) {
  // Needed because `dragover` does not fire on entering.
  onDragOverRow(event)
  dragDelay.onDragEnter(event)
}

function onDragOver(event: DragEvent) {
  if (category.value.type === 'trash' && event.dataTransfer != null) {
    event.dataTransfer.dropEffect = 'none'
  }
  onDragOverRow(event)
}

function onDragEnd() {
  isDraggedOver.value = false
  props.onRowDragEnd()
}

function onDragLeave(event: DragEvent) {
  if (
    event.relatedTarget instanceof Node &&
    event.currentTarget instanceof Node &&
    !event.currentTarget.contains(event.relatedTarget)
  ) {
    isDraggedOver.value = false
    driveStore.setDragTargetAssetId(null)
  }
  dragDelay.onDragLeave(event)
}

function onDrop(event: DragEvent) {
  event.preventDefault()
  event.stopPropagation()
  isDraggedOver.value = false
  dragDelay.onDrop(event)
  props.onRowDrop(event, props.item)
}
</script>

<template>
  <tr
    ref="root"
    data-testid="asset-row"
    tabindex="0"
    :data-selected="isSelected"
    :aria-selected="isSelected"
    :data-id="item.id"
    :class="
      twMerge(
        'h-table-row rounded-full transition-all ease-in-out rounded-rows-child',
        visibility,
        (isDraggedOver || isSelected) && 'selected',
      )
    "
    :draggable="isSelected ? isDraggable : false"
    @focusin="onFocusIn"
    @focusout="onFocusOut"
    @dblclick="onDoubleClick"
    @click="onClick"
    @contextmenu="onContextMenu"
    @dragstart="onDragStart"
    @dragenter="onDragEnter"
    @dragover="onDragOver"
    @dragend="onDragEnd"
    @dragleave="onDragLeave"
    @drop="onDrop"
  >
    <td v-for="column in columns" :key="column" :class="COLUMN_CSS_CLASS[column]">
      <AssetColumnCell
        :column="column"
        :item="item"
        :labels="labels"
        :isEditable="category.type !== 'trash'"
      />
    </td>
  </tr>
</template>
