// app/gui/src/components/Drive/AssetSummary.vue
<script setup lang="ts">
/**
 * @file A few details of an asset (icon, title, "New" or "Existing", last modified).
 */
import Badge from '$/components/Badge/Badge.vue'
import Icon from '$/components/Icon/Icon.vue'
import Text from '$/components/Text/Text.vue'
import { useText } from '$/providers/text'
import { twMerge } from '$/utils/style/tailwindMerge'
import type { AnyAsset } from 'enso-common/src/services/Backend'
import { toReadableIsoString } from 'enso-common/src/utilities/data/dateTime'
import AssetIcon from './AssetIcon.vue'

const {
  asset,
  new: isNew = false,
  class: className,
} = defineProps<{
  asset: AnyAsset
  /** Whether it is the asset being added, rather than the one already there. */
  new?: boolean | undefined
  class?: string | undefined
}>()

const { getText } = useText()
</script>

<template>
  <div :class="twMerge('flex items-center gap-3 rounded-4xl bg-frame px-4 py-1.5', className)">
    <div class="grid size-4 place-items-center">
      <AssetIcon :asset="asset" />
    </div>

    <div class="flex min-w-0 flex-col">
      <div class="flex items-center gap-1">
        <Text variant="subtitle" nowrap truncate>{{ asset.title }}</Text>

        <Badge variant="outline" color="primary" class="flex-none">
          {{ isNew ? getText('new') : getText('existing') }}
        </Badge>
      </div>

      <span class="flex items-center gap-1">
        <Icon icon="calendar" size="small" />

        <Text variant="body-sm" truncate>
          {{ getText('lastModifiedOn', toReadableIsoString(new Date(asset.modifiedAt))) }}
        </Text>
      </span>
    </div>
  </div>
</template>

// app/gui/src/dashboard/pages/dashboard/components/AssetSummary.tsx
/** @file Displays a few details of an asset. */
import { Text } from '#/components/Text'
import AssetIcon from '#/pages/dashboard/components/AssetIcon'
import * as tailwindMerge from '#/utilities/tailwindMerge'
import { useText } from '$/providers/react'
import type * as backend from 'enso-common/src/services/Backend'
import * as dateTime from 'enso-common/src/utilities/data/dateTime'
import { Badge } from '../../../components/Badge'
import { Icon } from '../../../components/Icon'

/** Props for an {@link AssetSummary}. */
export interface AssetSummaryProps {
  readonly asset: backend.AnyAsset
  readonly new?: boolean
  readonly newName?: string
  readonly className?: string
}

/** Displays a few details of an asset. */
export default function AssetSummary(props: AssetSummaryProps) {
  const { asset, new: isNew = false, newName, className } = props

  const { getText } = useText()

  return (
    <div
      className={tailwindMerge.twMerge(
        'flex items-center gap-3 rounded-4xl bg-frame px-4 py-1.5',
        className,
      )}
    >
      <div className="grid size-4 place-items-center">
        <AssetIcon asset={asset} />
      </div>

      <div className="flex min-w-0 flex-col">
        <div className="flex items-center gap-1">
          <Text variant="subtitle" nowrap truncate>
            {asset.title}

            {newName != null && (
              <>
                <Icon
                  icon="arrow_right_head_only"
                  color="muted"
                  className="inline-block align-middle"
                />
                {newName}
              </>
            )}
          </Text>

          {isNew && (
            <Badge variant="outline" color="primary" className="flex-none">
              {getText('new')}
            </Badge>
          )}

          {!isNew && (
            <Badge variant="outline" color="primary" className="flex-none">
              {getText('existing')}
            </Badge>
          )}
        </div>

        <span className="flex items-center gap-1">
          <Icon icon="calendar" size="small" />

          <Text variant="body-sm" truncate>
            {getText('lastModifiedOn', dateTime.toReadableIsoString(new Date(asset.modifiedAt)))}
          </Text>
        </span>
      </div>
    </div>
  )
}
