// app/gui/src/dashboard/layouts/AssetPanel/components/ProjectSessions.tsx
/** @file A list of previous versions of an asset. */
import { ErrorBoundary } from '#/components/ErrorBoundary'
import { Result } from '#/components/Result'
import { Scroller } from '#/components/Scroller'
import { AssetPanelPlaceholder } from '#/layouts/AssetPanel/components/AssetPanelPlaceholder'
import { useBackends, useText } from '$/providers/react'
import { useVueValue } from '$/providers/react/common'
import { useRightPanelData, useRightPanelFocusedAsset } from '$/providers/react/container'
import type { SessionsProject } from '$/providers/rightPanel'
import { useSuspenseQuery } from '@tanstack/react-query'
import type { Backend } from 'enso-common/src/services/Backend'
import { AssetType } from 'enso-common/src/services/Backend'
import { useCallback } from 'react'
import { ProjectSession } from './ProjectSession'

/** A list of previous versions of an asset. */
export function ProjectSessions() {
  const { getText } = useText()
  const rightPanel = useRightPanelData()
  const focusedAsset = useRightPanelFocusedAsset()
  const project = useVueValue(useCallback(() => rightPanel.sessionsProject, [rightPanel]))
  const { backendForType } = useBackends()

  if (project == null) {
    const isOtherAsset = focusedAsset != null && focusedAsset.type !== AssetType.project
    const title =
      isOtherAsset ?
        getText('assetProjectSessions.notProjectAsset')
      : getText('assetProjectSessions.notSelected')
    return <AssetPanelPlaceholder title={title} />
  }

  return (
    <ErrorBoundary>
      <AssetProjectSessionsInternal backend={backendForType(project.backendType)} item={project} />
    </ErrorBoundary>
  )
}

/** Props for a {@link AssetProjectSessionsInternal}. */
interface AssetProjectSessionsInternalProps {
  readonly backend: Backend
  readonly item: SessionsProject
}

/** A list of previous versions of an asset. */
function AssetProjectSessionsInternal(props: AssetProjectSessionsInternalProps) {
  const { backend, item } = props
  const { getText } = useText()

  const projectSessionsQuery = useSuspenseQuery({
    queryKey: ['getProjectSessions', item.id, item.title],
    queryFn: async () => {
      const sessions = await backend.listProjectSessions(item.id, item.title)
      return [...sessions].reverse()
    },
  })

  return projectSessionsQuery.data.length === 0 ?
      <Result status="info" centered title={getText('assetProjectSessions.noSessions')} />
    : <div className="flex min-h-0 w-full flex-col justify-start">
        <Scroller scrollbar orientation="vertical" background="white" className="h-full">
          {projectSessionsQuery.data.map((session, i) => (
            <ProjectSession
              key={session.projectSessionId}
              backend={backend}
              project={item}
              projectSession={session}
              index={projectSessionsQuery.data.length - i}
            />
          ))}
        </Scroller>
      </div>
}

// app/gui/src/components/AssetPanel/ProjectSessions.vue
<script setup lang="ts">
/**
 * @file The right panel's Activity tab: the sessions of the project the panel is focused on, the
 * project selected in the drive or the one opened in a project tab (#176). The Vue port of the
 * React `AssetPanel/components/ProjectSessions`.
 *
 * Without such a project it asks for one. The list itself (`ProjectSessionList.vue`) loads in a
 * `SuspenseLoader`, as React's suspended, and is remounted for each project.
 */
import ErrorBoundary from '$/components/ErrorBoundary/ErrorBoundary.vue'
import SuspenseLoader from '$/components/ErrorBoundary/SuspenseLoader.vue'
import Result from '$/components/Result/Result.vue'
import { useBackends } from '$/providers/backends'
import { useRightPanelData } from '$/providers/rightPanel'
import { useText } from '$/providers/text'
import { AssetType } from 'enso-common/src/services/Backend'
import { computed } from 'vue'
import ProjectSessionList from './ProjectSessionList.vue'

defineProps<{
  /** The panel's toolbar slot, given to every tab. This one puts nothing there. */
  toolbar?: HTMLElement | string | undefined
}>()

const rightPanel = useRightPanelData()
const { backendForType } = useBackends()
const { getText } = useText()

const project = computed(() => rightPanel.sessionsProject)
const placeholder = computed(() => {
  const asset = rightPanel.focusedAsset
  return asset != null && asset.type !== AssetType.project ?
      getText('assetProjectSessions.notProjectAsset')
    : getText('assetProjectSessions.notSelected')
})
const projectKey = computed(() =>
  project.value ? `${project.value.backendType}:${project.value.id}:${project.value.title}` : '',
)
</script>

<template>
  <Result v-if="project == null" status="info" :centered="true" :title="placeholder" />
  <ErrorBoundary v-else :key="projectKey">
    <SuspenseLoader>
      <ProjectSessionList :backend="backendForType(project.backendType)" :project="project" />
    </SuspenseLoader>
  </ErrorBoundary>
</template>
