// app/gui/src/dashboard/data/serviceCredentials/GoogleCredentialsForm.tsx
/**
 * @file
 * Dialog for a Google credential.
 * Remember to ensure this component is added to `CREDENTIAL_INFOS` in `constants.ts`.
 */
import { Checkbox } from '#/components/Checkbox'
import { Form } from '#/components/Form'
import { Input } from '#/components/Inputs/Input'
import * as google from '$/cloud/serviceCredentials/google'
import type { CredentialFormProps } from '$/cloud/serviceCredentials/types'
import { useRemoteConfig, useText } from '$/providers/react'
import { CredentialsFormFooter } from './CredentialsFormFooter'

/** Dialog for a Google credential. */
export function GoogleCredentialsForm(props: CredentialFormProps) {
  const { createCredentials } = props
  const { getText } = useText()
  const apiUrl = useRemoteConfig('ENSO_IDE_API_URL')
  const oauthId = useRemoteConfig('ENSO_IDE_GOOGLE_OAUTH_CLIENT_ID')

  return (
    <Form
      method="dialog"
      schema={google.FORM_SCHEMA}
      defaultValues={{ scopes: ['sheets'] }}
      className="w-full"
      onSubmit={async (values) => {
        await google.submitForm(apiUrl, oauthId, createCredentials, values)
      }}
    >
      <Input name="name" label={getText('name')} />

      <Checkbox.Group name="scopes" label={getText('googleCredentialScopes')}>
        <Checkbox value="sheets">{getText('googleCredentialSheetsScope')}</Checkbox>
        <Checkbox value="analytics">{getText('googleCredentialAnalyticsScope')}</Checkbox>
      </Checkbox.Group>

      <CredentialsFormFooter isCreating={true} canCancel={false} canReset={false} />
    </Form>
  )
}

// app/gui/src/cloud/credentials/GoogleCredentialsForm.vue
<script setup lang="ts">
/**
 * @file The form creating a Google credential: the Vue port of the React `GoogleCredentialsForm`.
 * The recipe is `$/cloud/serviceCredentials/google`. As in React, a failure shows under the form,
 * not as a toast. Remember to list a new form in `credentialInfos.ts`.
 */
import * as google from '$/cloud/serviceCredentials/google'
import type { CredentialRecipe } from '$/cloud/serviceCredentials/types'
import Checkbox from '$/components/Checkbox/Checkbox.vue'
import CheckboxGroup from '$/components/Checkbox/CheckboxGroup.vue'
import Form from '$/components/Form/Form.vue'
import Input from '$/components/Inputs/Input.vue'
import { useConfig } from '$/providers/config'
import { useText } from '$/providers/text'
import CredentialsFormFooter from './CredentialsFormFooter.vue'

const { createCredentials } = defineProps<{
  createCredentials: (recipe: CredentialRecipe) => Promise<void>
}>()

const { getText } = useText()
const config = useConfig()

function submit(values: Parameters<typeof google.submitForm>[3]) {
  return google.submitForm(
    config.remoteConfig?.ENSO_IDE_API_URL,
    config.remoteConfig?.ENSO_IDE_GOOGLE_OAUTH_CLIENT_ID,
    createCredentials,
    values,
  )
}
</script>

<template>
  <Form
    method="dialog"
    :schema="google.FORM_SCHEMA"
    :defaultValues="{ name: '', scopes: ['sheets'] }"
    class="w-full"
    @submit="submit"
  >
    <Input name="name" :label="getText('name')" />

    <CheckboxGroup name="scopes" :label="getText('googleCredentialScopes')">
      <Checkbox value="sheets">{{ getText('googleCredentialSheetsScope') }}</Checkbox>
      <Checkbox value="analytics">{{ getText('googleCredentialAnalyticsScope') }}</Checkbox>
    </CheckboxGroup>

    <CredentialsFormFooter :isCreating="true" :canCancel="false" :canReset="false" />
  </Form>
</template>
