// app/gui/src/dashboard/data/serviceCredentials/MS365CredentialsForm.tsx
/**
 * @file
 * Dialog for an MS365 credential.
 * Remember to ensure this component is added to `CREDENTIAL_INFOS` in `constants.ts`.
 */

import { Checkbox } from '#/components/Checkbox'
import { Form } from '#/components/Form'
import { Input } from '#/components/Inputs/Input'
import { Selector } from '#/components/Inputs/Selector/Selector'
import { Text } from '#/components/Text'
import { useToastAndLog } from '#/hooks/toastAndLogHooks'
import * as ms365 from '$/cloud/serviceCredentials/ms365'
import type { CredentialFormProps } from '$/cloud/serviceCredentials/types'
import { useRemoteConfig, useText } from '$/providers/react'
import type { TextId } from 'enso-common/src/text'
import { CredentialsFormFooter } from './CredentialsFormFooter'

/** Dialog for a MS365 credential. */
export function MS365CredentialsForm(props: CredentialFormProps) {
  const { createCredentials } = props
  const { getText } = useText()
  const toastAndLog = useToastAndLog()
  const apiUrl = useRemoteConfig('ENSO_IDE_API_URL')
  const oauthId = useRemoteConfig('ENSO_IDE_MS365_OAUTH_CLIENT_ID')

  return (
    <Form
      method="dialog"
      schema={ms365.FORM_SCHEMA}
      defaultValues={{
        scopes: ['User.Read'],
        filesPermission: 'Files.ReadWrite.All',
        sitesPermission: 'NoAccess',
      }}
      className="w-full"
      onSubmit={async (values) => {
        try {
          await ms365.submitForm(apiUrl, oauthId, createCredentials, values)
        } catch (error) {
          toastAndLog(null, error)
        }
      }}
    >
      {(form) => {
        const filesPermission = form.watch('filesPermission')
        const sitesPermission = form.watch('sitesPermission')

        return (
          <>
            <Input form={form} name="name" label={getText('name')} defaultValue="Microsoft365" />
            <Checkbox.Group form={form} name="scopes" label={getText('ms365CredentialScopes')}>
              <Checkbox value="User.Read">{getText('ms365CredentialUserReadScope')}</Checkbox>
            </Checkbox.Group>
            <Selector
              form={form}
              name="filesPermission"
              label={getText('ms365CredentialFilesPermission')}
              items={
                [
                  'Files.ReadWrite.All',
                  'Files.Read.All',
                  'Files.ReadWrite',
                  'Files.Read',
                  'NoAccess',
                ] as const
              }
            >
              {(item) => {
                // eslint-disable-next-line no-restricted-syntax
                const key = `ms365CredentialFilesPermission${item.replace(/\./g, '')}` as TextId
                return getText(key)
              }}
            </Selector>
            <Text variant="body" color="primary">
              {(() => {
                const key =
                  // eslint-disable-next-line no-restricted-syntax
                  `ms365CredentialFilesPermission${filesPermission.replace(/\./g, '')}Description` as TextId
                return getText(key)
              })()}
            </Text>
            <Selector
              form={form}
              name="sitesPermission"
              label={getText('ms365CredentialSitesPermission')}
              items={
                ['Sites.Manage.All', 'Sites.ReadWrite.All', 'Sites.Read.All', 'NoAccess'] as const
              }
            >
              {(item) => {
                // eslint-disable-next-line no-restricted-syntax
                const key = `ms365CredentialSitesPermission${item.replace(/\./g, '')}` as TextId
                return getText(key)
              }}
            </Selector>
            <Text variant="body" color="primary">
              {(() => {
                const key =
                  // eslint-disable-next-line no-restricted-syntax
                  `ms365CredentialSitesPermission${sitesPermission.replace(/\./g, '')}Description` as TextId
                return getText(key)
              })()}
            </Text>
            <CredentialsFormFooter isCreating={true} canCancel={false} canReset={false} />
          </>
        )
      }}
    </Form>
  )
}

// app/gui/src/cloud/credentials/MS365CredentialsForm.vue
<script setup lang="ts">
/**
 * @file The form creating a Microsoft 365 credential: the Vue port of the React
 * `MS365CredentialsForm`. The recipe is `$/cloud/serviceCredentials/ms365`. Each permission's
 * description follows the chosen one. Remember to list a new form in `credentialInfos.ts`.
 */
import * as ms365 from '$/cloud/serviceCredentials/ms365'
import type { CredentialRecipe } from '$/cloud/serviceCredentials/types'
import Checkbox from '$/components/Checkbox/Checkbox.vue'
import CheckboxGroup from '$/components/Checkbox/CheckboxGroup.vue'
import Form from '$/components/Form/Form.vue'
import Input from '$/components/Inputs/Input.vue'
import Selector from '$/components/Inputs/Selector.vue'
import Text from '$/components/Text/Text.vue'
import { useConfig } from '$/providers/config'
import { useText } from '$/providers/text'
import type { TextId } from 'enso-common/src/text'
import CredentialsFormFooter from './CredentialsFormFooter.vue'
import { toastAndLogError } from './toastAndLog'

const { createCredentials } = defineProps<{
  createCredentials: (recipe: CredentialRecipe) => Promise<void>
}>()

const FILES_PERMISSIONS = [
  'Files.ReadWrite.All',
  'Files.Read.All',
  'Files.ReadWrite',
  'Files.Read',
  'NoAccess',
] as const
const SITES_PERMISSIONS = [
  'Sites.Manage.All',
  'Sites.ReadWrite.All',
  'Sites.Read.All',
  'NoAccess',
] as const

const { getText } = useText()
const config = useConfig()

/** A permission's text, or its description's: `ms365Credential<kind><permission><suffix>`. */
function permissionText(kind: 'FilesPermission' | 'SitesPermission', item: string, suffix = '') {
  return getText(`ms365Credential${kind}${item.replace(/\./g, '')}${suffix}` as TextId)
}

async function submit(values: Parameters<typeof ms365.submitForm>[3]) {
  try {
    await ms365.submitForm(
      config.remoteConfig?.ENSO_IDE_API_URL,
      config.remoteConfig?.ENSO_IDE_MS365_OAUTH_CLIENT_ID,
      createCredentials,
      values,
    )
  } catch (error) {
    toastAndLogError(error)
  }
}
</script>

<template>
  <Form
    v-slot="{ form }"
    method="dialog"
    :schema="ms365.FORM_SCHEMA"
    :defaultValues="{
      name: 'Microsoft365',
      scopes: ['User.Read'],
      filesPermission: 'Files.ReadWrite.All',
      sitesPermission: 'NoAccess',
    }"
    class="w-full"
    @submit="submit"
  >
    <Input name="name" :label="getText('name')" />
    <CheckboxGroup name="scopes" :label="getText('ms365CredentialScopes')">
      <Checkbox value="User.Read">{{ getText('ms365CredentialUserReadScope') }}</Checkbox>
    </CheckboxGroup>
    <Selector
      name="filesPermission"
      :label="getText('ms365CredentialFilesPermission')"
      :items="FILES_PERMISSIONS"
      :toLabel="(item) => permissionText('FilesPermission', item)"
    />
    <Text variant="body" color="primary">
      {{ permissionText('FilesPermission', String(form.watch('filesPermission')), 'Description') }}
    </Text>
    <Selector
      name="sitesPermission"
      :label="getText('ms365CredentialSitesPermission')"
      :items="SITES_PERMISSIONS"
      :toLabel="(item) => permissionText('SitesPermission', item)"
    />
    <Text variant="body" color="primary">
      {{ permissionText('SitesPermission', String(form.watch('sitesPermission')), 'Description') }}
    </Text>
    <CredentialsFormFooter :isCreating="true" :canCancel="false" :canReset="false" />
  </Form>
</template>
