// app/gui/src/dashboard/components/Paywall/components/PaywallBulletPoints.tsx
/** @file A list of bullet points for a paywall. */
import { Icon } from '#/components/Icon'
import { Text } from '#/components/Text'
import { useText } from '$/providers/react'
import { twMerge } from '$/utils/style/tailwindMerge'
import type { TextId } from 'enso-common/src/text'

/** Props for a {@link PaywallBulletPoints}. */
export interface PaywallBulletPointsProps {
  readonly bulletPointsTextId: TextId
  readonly className?: string
}

/** A component that renders a list of bullet points for a paywall. */
export function PaywallBulletPoints(props: PaywallBulletPointsProps) {
  const { bulletPointsTextId, className } = props

  const { getText } = useText()
  const bulletPoints = getText(bulletPointsTextId)
    .split(';')
    .map((bulletPoint) => bulletPoint.trim())

  if (bulletPoints.length === 0) {
    return null
  } else {
    return (
      <ul className={twMerge('m-0 flex w-full list-inside list-none flex-col gap-1', className)}>
        {bulletPoints.map((bulletPoint) => (
          <li key={bulletPoint} className="flex items-start gap-1.5">
            <div className="m-0 flex">
              <div className="m-0 flex">
                <span className="mt-1 flex aspect-square h-4 flex-none place-items-center justify-center rounded-full bg-green/30">
                  <Icon icon="check" className="text-green" />
                </span>
              </div>
            </div>

            <Text className="flex-grow" variant="body">
              {bulletPoint}
            </Text>
          </li>
        ))}
      </ul>
    )
  }
}

// app/gui/src/cloud/billing/paywall/PaywallBulletPoints.vue
<script setup lang="ts">
/**
 * @file The list of what a plan brings, from a `;`-separated text: the Vue port of the React
 * `PaywallBulletPoints`.
 */
import Icon from '$/components/Icon/Icon.vue'
import Text from '$/components/Text/Text.vue'
import { useText } from '$/providers/text'
import { twMerge } from '$/utils/style/tailwindMerge'
import type { TextId } from 'enso-common/src/text'
import { computed } from 'vue'

const { bulletPointsTextId, class: className } = defineProps<{
  bulletPointsTextId: TextId
  class?: string | undefined
}>()

const { getText } = useText()
const bulletPoints = computed(() =>
  getText(bulletPointsTextId)
    .split(';')
    .map((bulletPoint) => bulletPoint.trim()),
)
</script>

<template>
  <ul :class="twMerge('m-0 flex w-full list-inside list-none flex-col gap-1', className)">
    <li v-for="bulletPoint in bulletPoints" :key="bulletPoint" class="flex items-start gap-1.5">
      <div class="m-0 flex">
        <div class="m-0 flex">
          <span
            class="mt-1 flex aspect-square h-4 flex-none place-items-center justify-center rounded-full bg-green/30"
          >
            <Icon icon="check" class="text-green" />
          </span>
        </div>
      </div>
      <Text class="flex-grow" variant="body">{{ bulletPoint }}</Text>
    </li>
  </ul>
</template>
