// app/gui/src/dashboard/components/Paywall/PaywallAlert.tsx
/** @file A paywall alert. */
import { Alert, type AlertProps } from '#/components/Alert'
import { Icon } from '#/components/Icon'
import * as paywall from '#/components/Paywall'
import { Text } from '#/components/Text'
import type { PaywallFeatureName } from '$/composables/paywall'
import * as React from 'react'
import { twJoin } from 'tailwind-merge'

/** Props for {@link PaywallAlert}. */
export interface PaywallAlertProps<IconType extends string> extends Omit<AlertProps, 'children'> {
  readonly feature: PaywallFeatureName
  readonly label: string
  readonly showUpgradeButton?: boolean
  readonly upgradeButtonProps?: Omit<paywall.UpgradeButtonProps<IconType>, 'feature'>
}

/** A paywall alert. */
export function PaywallAlert<IconType extends string>(
  props: PaywallAlertProps<IconType>,
): React.JSX.Element {
  const {
    label,
    showUpgradeButton = true,
    feature,
    upgradeButtonProps,
    className,
    ...alertProps
  } = props

  return (
    <Alert
      variant="outline"
      size="small"
      rounded="xlarge"
      className={twJoin('border border-primary/20', className)}
      {...alertProps}
    >
      <div className="flex items-center gap-2">
        <Icon icon="lock" className="h-5 w-5 flex-none text-primary" />

        <Text>
          {label}{' '}
          {showUpgradeButton && (
            <paywall.UpgradeButton
              feature={feature}
              variant="link"
              size="small"
              {...upgradeButtonProps}
            />
          )}
        </Text>
      </div>
    </Alert>
  )
}

// app/gui/src/cloud/billing/paywall/PaywallAlert.vue
<script setup lang="ts">
/**
 * @file An alert that a feature is limited on the user's plan, with a link-style upgrade button:
 * the Vue port of the React `PaywallAlert`.
 */
import Alert from '$/components/Alert/Alert.vue'
import Icon from '$/components/Icon/Icon.vue'
import Text from '$/components/Text/Text.vue'
import type { PaywallFeatureName } from '$/composables/paywall'
import { twJoin } from '$/utils/style/tailwindMerge'
import PaywallUpgradeButton from './PaywallUpgradeButton.vue'

const {
  feature,
  label,
  showUpgradeButton = true,
  class: className,
} = defineProps<{
  feature: PaywallFeatureName
  label: string
  showUpgradeButton?: boolean | undefined
  class?: string | undefined
}>()
</script>

<template>
  <Alert
    variant="outline"
    size="small"
    rounded="xlarge"
    :class="twJoin('border border-primary/20', className)"
  >
    <div class="flex items-center gap-2">
      <Icon icon="lock" class="h-5 w-5 flex-none text-primary" />
      <Text>
        {{ label }}
        <PaywallUpgradeButton
          v-if="showUpgradeButton"
          :feature="feature"
          variant="link"
          size="small"
        />
      </Text>
    </div>
  </Alert>
</template>
