// app/gui/src/dashboard/modals/InviteUsersModal/InviteUsersButton.tsx
/**
 * @file The user bar's "Invite" button and the invitation dialog it opens. It stays React with the
 * dialog, which the organization port (#87) moves to `src/cloud/organization/`; the Vue user bar
 * (#83) mounts it through `reactComponent`.
 */
import { Button } from '#/components/Button'
import { Dialog } from '#/components/Dialog'
import { useText } from '$/providers/react'
import InviteUsersModal from './InviteUsersModal'

/** The "Invite" button, opening the invitation dialog. */
export function InviteUsersButton() {
  const { getText } = useText()
  return (
    <Dialog.Trigger>
      <Button size="medium" variant="outline">
        {getText('invite')}
      </Button>

      <InviteUsersModal />
    </Dialog.Trigger>
  )
}

// app/gui/src/cloud/organization/InviteUsersButton.vue
<script setup lang="ts">
/**
 * @file The user bar's "Invite" button, opening the invitation dialog.
 */
import Button from '$/components/Button/Button.vue'
import { useText } from '$/providers/text'
import InviteUsersModal from './InviteUsersModal.vue'

const { getText } = useText()
</script>

<template>
  <InviteUsersModal>
    <template #trigger>
      <Button size="medium" variant="outline">{{ getText('invite') }}</Button>
    </template>
  </InviteUsersModal>
</template>
