// app/gui/src/dashboard/layouts/AssetSearchBar.tsx
/** @file A search bar containing a text input, and a list of suggestions. */
import * as aria from '#/components/aria'
import { Button } from '#/components/Button'
import { Icon } from '#/components/Icon'
import FocusRing from '#/components/styled/FocusRing'
import { Text } from '#/components/Text'
import { useEventCallback } from '#/hooks/eventCallbackHooks'
import { useSyncRef } from '#/hooks/syncRefHooks'
import Label from '#/pages/dashboard/components/Label'
import * as modalProvider from '#/providers/ModalProvider'
import { createStore, useStore } from '#/utilities/zustand'
import { DIALOG_BACKGROUND } from '$/components/Dialog/variants'
import { useText } from '$/providers/react'
import { useContainerData } from '$/providers/react/container'
import AssetQuery from '$/utils/AssetQuery'
import { backendQueryOptions } from '$/utils/backendQuery'
import * as string from '$/utils/data/string'
import * as eventModule from '$/utils/event'
import * as tailwindMerge from '$/utils/style/tailwindMerge'
import { unsafeWriteValue } from '$/utils/write'
import { useQuery } from '@tanstack/react-query'
import type { Backend, Label as BackendLabel } from 'enso-common/src/services/Backend'
import * as detect from 'enso-common/src/utilities/detect'
import * as React from 'react'

/** The reason behind a new query. */
enum QuerySource {
  /**
   * A query change initiated by tabbing. While *technically* internal, it is semantically
   * different in that tabbing does not update the base query.
   */
  tabbing = 'tabbing',
  /** A query change initiated from code in this component. */
  internal = 'internal',
  /** A query change initiated by typing in the search bar. */
  typing = 'typing',
  /** A query change initiated from code in another component. */
  external = 'external',
}

/** A suggested query. */
export interface Suggestion {
  readonly key: string
  readonly render: () => React.ReactNode
  readonly addToQuery: (query: AssetQuery) => AssetQuery
  readonly deleteFromQuery: (query: AssetQuery) => AssetQuery
}

/** Props for a {@link Tags}. */
interface InternalTagsProps {
  readonly isCloud: boolean
  readonly querySource: React.MutableRefObject<QuerySource>
  readonly query: AssetQuery
  readonly setQuery: React.Dispatch<React.SetStateAction<AssetQuery>>
}

// eslint-disable-next-line react-refresh/only-export-components
export const searchbarSuggestionsStore = createStore<{
  readonly suggestions: readonly Suggestion[]
  readonly setSuggestions: (suggestions: readonly Suggestion[]) => void
}>((set) => ({
  suggestions: [],
  setSuggestions: (suggestions) => {
    set({ suggestions })
  },
}))

/** Sets the suggestions. */
// eslint-disable-next-line react-refresh/only-export-components
export function useSetSuggestions() {
  return useStore(searchbarSuggestionsStore, (state) => state.setSuggestions, {
    unsafeEnableTransition: true,
  })
}

/** Tags (`name:`, `modified:`, etc.) */
function Tags(props: InternalTagsProps) {
  const { isCloud, querySource, query, setQuery } = props

  return (
    <div
      data-testid="asset-search-tag-names"
      className="pointer-events-auto flex flex-wrap gap-2 whitespace-nowrap px-1.5"
    >
      {(isCloud ? AssetQuery.tagNames : AssetQuery.localTagNames).flatMap((entry) => {
        const [key, tag] = entry
        return tag == null ?
            []
          : [
              <FocusRing key={key}>
                <Button
                  variant="outline"
                  size="xsmall"
                  className="min-w-12"
                  onPress={() => {
                    unsafeWriteValue(querySource, 'current', QuerySource.internal)
                    setQuery(query.add(key, ['']))
                  }}
                >
                  {tag + ':'}
                </Button>
              </FocusRing>,
            ]
      })}
    </div>
  )
}

/** Props for a {@link AssetSearchBar}. */
export interface AssetSearchBarProps {
  readonly backend: Backend | null
  readonly isCloud: boolean
  readonly query: AssetQuery
  readonly setQuery: React.Dispatch<React.SetStateAction<AssetQuery>>
}

/** A search bar containing a text input, and a list of suggestions. */
export const AssetSearchBar = React.memo(function AssetSearchBarImpl(props: AssetSearchBarProps) {
  const { backend, isCloud, query, setQuery } = props
  const { modalRef } = modalProvider.useModalRef()
  /** A cached query as of the start of tabbing. */
  const baseQuery = React.useRef(query)
  const container = useContainerData()

  const rawSuggestions = useStore(searchbarSuggestionsStore, (state) => state.suggestions, {
    unsafeEnableTransition: true,
  })

  const [suggestions, setSuggestions] = React.useState(rawSuggestions)

  const suggestionsRef = useSyncRef(suggestions)

  const [selectedIndex, setSelectedIndex] = React.useState<number | null>(null)
  const [areSuggestionsVisible, privateSetAreSuggestionsVisible] = React.useState(false)
  const areSuggestionsVisibleRef = React.useRef(areSuggestionsVisible)
  const querySource = React.useRef(QuerySource.external)
  const rootRef = React.useRef<HTMLLabelElement | null>(null)
  const searchRef = React.useRef<HTMLInputElement | null>(null)

  const setAreSuggestionsVisible = useEventCallback((value: boolean) => {
    React.startTransition(() => {
      privateSetAreSuggestionsVisible(value)
      areSuggestionsVisibleRef.current = value
    })
  })

  React.useEffect(() => {
    if (querySource.current !== QuerySource.tabbing) {
      setSuggestions(rawSuggestions)
      unsafeWriteValue(suggestionsRef, 'current', rawSuggestions)
    }
  }, [rawSuggestions, suggestionsRef])

  React.useEffect(() => {
    if (querySource.current !== QuerySource.tabbing) {
      baseQuery.current = query
    }
    // This effect MUST only run when `query` changes.
  }, [query])

  React.useEffect(() => {
    if (querySource.current !== QuerySource.tabbing) {
      setSelectedIndex(null)
    }
    if (
      querySource.current !== QuerySource.internal &&
      querySource.current !== QuerySource.tabbing
    ) {
      if (searchRef.current != null) {
        searchRef.current.value = query.query
      }
    }
  }, [query])

  const selectedIndexDeps = useSyncRef({ query, setQuery, suggestions })

  React.useEffect(() => {
    const deps = selectedIndexDeps.current
    if (
      querySource.current === QuerySource.internal ||
      querySource.current === QuerySource.tabbing
    ) {
      let newQuery = deps.query
      const suggestion = selectedIndex == null ? null : deps.suggestions[selectedIndex]
      if (suggestion != null) {
        newQuery = suggestion.addToQuery(baseQuery.current)
        deps.setQuery(newQuery)
      }
      searchRef.current?.focus()
      const end = searchRef.current?.value.length ?? 0
      searchRef.current?.setSelectionRange(end, end)
      if (searchRef.current != null) {
        searchRef.current.value = newQuery.toString()
      }
    }
  }, [selectedIndex, selectedIndexDeps])

  React.useEffect(() => {
    const onSearchKeyDown = (event: KeyboardEvent) => {
      if (areSuggestionsVisibleRef.current) {
        if (event.key === 'ArrowUp' || event.key === 'ArrowDown') {
          event.preventDefault()
          event.stopImmediatePropagation()
          querySource.current = QuerySource.tabbing
          const reverse = event.key === 'ArrowUp'
          setSelectedIndex((oldIndex) => {
            const length = Math.max(1, suggestionsRef.current.length)
            if (reverse) {
              return oldIndex == null ? length - 1 : (oldIndex + length - 1) % length
            } else {
              return oldIndex == null ? 0 : (oldIndex + 1) % length
            }
          })
        }
        if (
          event.key === 'Enter' ||
          (event.key === ' ' && document.activeElement !== searchRef.current)
        ) {
          querySource.current = QuerySource.external
          if (searchRef.current != null) {
            searchRef.current.focus()
            const end = searchRef.current.value.length
            searchRef.current.setSelectionRange(end, end)
          }
        }
        if (event.key === 'Enter') {
          setAreSuggestionsVisible(false)
        }
        if (event.key === 'Escape') {
          if (querySource.current === QuerySource.tabbing) {
            querySource.current = QuerySource.external
            setQuery(baseQuery.current)
            setAreSuggestionsVisible(false)
          } else {
            searchRef.current?.blur()
          }
        }
      }
    }
    const onKeyDown = (event: KeyboardEvent) => {
      // Allow `alt` key to be pressed in case it is being used to enter special characters.
      if (
        !eventModule.isElementTextInput(event.target) &&
        (!(event.target instanceof Node) || rootRef.current?.contains(event.target) !== true) &&
        eventModule.isTextInputEvent(event) &&
        event.key !== ' ' &&
        event.key !== 'Delete' &&
        modalRef.current == null &&
        // We intentionally do not attach reactivity to `focusedPanel`, as we don't want to
        // reattach event handler on every change; it's enough to read it when event happens.
        container.focusedPanel.type === 'drive'
      ) {
        searchRef.current?.focus()
      }
      if (
        event.target instanceof Node &&
        rootRef.current?.contains(event.target) === true &&
        eventModule.isPotentiallyShortcut(event)
      ) {
        searchRef.current?.focus()
      }
    }
    const root = rootRef.current
    root?.addEventListener('keydown', onSearchKeyDown)
    document.addEventListener('keydown', onKeyDown)
    return () => {
      root?.removeEventListener('keydown', onSearchKeyDown)
      document.removeEventListener('keydown', onKeyDown)
    }
  }, [setQuery, modalRef, setAreSuggestionsVisible, suggestionsRef, container])

  // Reset `querySource` after all other effects have run.
  React.useEffect(() => {
    if (querySource.current !== QuerySource.typing && searchRef.current != null) {
      searchRef.current.value = query.toString()
    }
    if (querySource.current !== QuerySource.tabbing) {
      baseQuery.current = query
      querySource.current = QuerySource.external
    }
  }, [query, setQuery])

  const onSearchFieldKeyDown = useEventCallback((event: aria.KeyboardEvent) => {
    event.continuePropagation()
  })

  const searchFieldOnChange = useEventCallback((event: React.ChangeEvent<HTMLInputElement>) => {
    if (querySource.current !== QuerySource.internal) {
      querySource.current = QuerySource.typing
      setQuery(AssetQuery.fromString(event.target.value))
    }
  })

  const searchInputOnKeyDown = useEventCallback((event: React.KeyboardEvent<HTMLInputElement>) => {
    if (
      event.key === 'Enter' &&
      !event.shiftKey &&
      !event.altKey &&
      !event.metaKey &&
      !event.ctrlKey
    ) {
      // Clone the query to refresh results.
      setQuery(query.clone())
    }
  })

  const deferredSuggestions = React.useDeferredValue(suggestions)

  return (
    <div className="relative w-full max-w-[60em]">
      <aria.Label
        data-testid="asset-search-bar"
        ref={rootRef}
        className="group z-1 flex grow items-center gap-asset-search-bar rounded-full border-0.5 border-primary/50 py-[3.5px] pl-2 pr-1.5 text-primary"
        onFocus={() => {
          setAreSuggestionsVisible(true)
        }}
        onBlur={(event) => {
          if (!event.currentTarget.contains(event.relatedTarget)) {
            if (querySource.current === QuerySource.tabbing) {
              querySource.current = QuerySource.external
            }
            setAreSuggestionsVisible(false)
          }
        }}
      >
        <div className="relative size-4 placeholder" />

        <AssetSearchBarPopover
          areSuggestionsVisible={areSuggestionsVisible}
          isCloud={isCloud}
          querySource={querySource}
          query={query}
          setQuery={setQuery}
          suggestions={deferredSuggestions}
          selectedIndex={selectedIndex}
          setAreSuggestionsVisible={setAreSuggestionsVisible}
          baseQuery={baseQuery}
          backend={backend}
        />

        <Icon
          icon="find"
          className="absolute left-2.5 top-[50%] z-1 -mt-[1px] -translate-y-1/2 text-primary"
        />

        <AssetSearchBarInput
          query={query}
          isCloud={isCloud}
          onSearchFieldKeyDown={onSearchFieldKeyDown}
          searchRef={searchRef}
          searchFieldOnChange={searchFieldOnChange}
          searchInputOnKeyDown={searchInputOnKeyDown}
        />
      </aria.Label>
    </div>
  )
})

/** Props for a {@link AssetSearchBarInput}. */
interface AssetSearchBarInputProps {
  readonly query: AssetQuery
  readonly isCloud: boolean
  readonly onSearchFieldKeyDown: (event: aria.KeyboardEvent) => void
  readonly searchRef: React.RefObject<HTMLInputElement>
  readonly searchFieldOnChange: (event: React.ChangeEvent<HTMLInputElement>) => void
  readonly searchInputOnKeyDown: (event: React.KeyboardEvent<HTMLInputElement>) => void
}

/** Search field. */
const AssetSearchBarInput = React.memo(function AssetSearchBarInputImpl(
  props: AssetSearchBarInputProps,
) {
  const {
    query,
    isCloud,
    onSearchFieldKeyDown,
    searchRef,
    searchFieldOnChange,
    searchInputOnKeyDown,
  } = props
  const { getText } = useText()
  return (
    <>
      <FocusRing placement="before">
        <aria.SearchField
          aria-label={getText('assetSearchFieldLabel')}
          className="relative grow before:text before:absolute before:-inset-x-1 before:my-auto before:rounded-full before:transition-all"
          value={query.query}
          onKeyDown={onSearchFieldKeyDown}
        >
          <aria.Input
            type="search"
            ref={searchRef}
            size={1}
            placeholder={
              isCloud ?
                detect.isOnMacOS() ?
                  getText('remoteBackendSearchPlaceholderMacOs')
                : getText('remoteBackendSearchPlaceholder')
              : getText('localBackendSearchPlaceholder')
            }
            className="peer text relative z-1 w-full bg-transparent placeholder-primary/40"
            onChange={searchFieldOnChange}
            onKeyDown={searchInputOnKeyDown}
          />
        </aria.SearchField>
      </FocusRing>
    </>
  )
})

/** Props for a {@link AssetSearchBarPopover}. */
interface AssetSearchBarPopoverProps {
  readonly areSuggestionsVisible: boolean
  readonly isCloud: boolean
  readonly querySource: React.MutableRefObject<QuerySource>
  readonly query: AssetQuery
  readonly setQuery: React.Dispatch<React.SetStateAction<AssetQuery>>
  readonly suggestions: readonly Suggestion[]
  readonly selectedIndex: number | null
  readonly setAreSuggestionsVisible: (value: boolean) => void
  readonly baseQuery: React.MutableRefObject<AssetQuery>
  readonly backend: Backend | null
}

/** Renders the popover containing suggestions. */
const AssetSearchBarPopover = React.memo(function AssetSearchBarPopoverImpl(
  props: AssetSearchBarPopoverProps,
) {
  const {
    areSuggestionsVisible,
    isCloud,
    querySource,
    query,
    setQuery,
    suggestions,
    selectedIndex,
    setAreSuggestionsVisible,
    baseQuery,
    backend,
  } = props

  const [selectedIndices, setSelectedIndices] = React.useState<ReadonlySet<number>>(
    new Set<number>(),
  )

  return (
    areSuggestionsVisible && (
      <div
        className={DIALOG_BACKGROUND({
          className:
            'absolute left-0 right-0 top-0 z-1 grid w-full overflow-hidden rounded-default border-0.5 border-primary/20 -outline-offset-1 outline-primary',
        })}
      >
        <div className="overflow-hidden">
          <div className="relative mt-3 flex flex-col gap-3 pt-8">
            {/* Tags (`name:`, `modified:`, etc.) */}
            <Tags isCloud={isCloud} querySource={querySource} query={query} setQuery={setQuery} />
            {/* Asset labels */}
            <Labels
              isCloud={isCloud}
              query={query}
              setQuery={setQuery}
              querySource={querySource}
              backend={backend}
            />
            {/* Suggestions */}
            <div className="flex max-h-search-suggestions-list flex-col overflow-y-auto overflow-x-hidden pb-0.5 pl-0.5">
              {suggestions.map((suggestion, index) => (
                <SuggestionRenderer
                  key={suggestion.key}
                  index={index}
                  selectedIndex={selectedIndex}
                  selectedIndices={selectedIndices}
                  querySource={querySource}
                  setQuery={setQuery}
                  suggestion={suggestion}
                  setSelectedIndices={setSelectedIndices}
                  setAreSuggestionsVisible={setAreSuggestionsVisible}
                  query={query}
                  baseQuery={baseQuery}
                />
              ))}
            </div>
          </div>
        </div>
      </div>
    )
  )
})

/** Props for a {@link SuggestionRenderer}. */
interface SuggestionRendererProps {
  readonly index: number
  readonly suggestion: Suggestion
  readonly query: AssetQuery
  readonly baseQuery: React.MutableRefObject<AssetQuery>
  readonly selectedIndex: number | null
  readonly selectedIndices: ReadonlySet<number>
  readonly setSelectedIndices: React.Dispatch<React.SetStateAction<ReadonlySet<number>>>
  readonly querySource: React.MutableRefObject<QuerySource>
  readonly setQuery: React.Dispatch<React.SetStateAction<AssetQuery>>
  readonly setAreSuggestionsVisible: (value: boolean) => void
}

/** Renders a suggestion. */
const SuggestionRenderer = React.memo(function SuggestionRendererImpl(
  props: SuggestionRendererProps,
) {
  const {
    index,
    selectedIndex,
    selectedIndices,
    querySource,
    setQuery,
    suggestion,
    setSelectedIndices,
    setAreSuggestionsVisible,
    query,
    baseQuery,
  } = props

  return (
    <aria.Button
      data-testid="asset-search-suggestion"
      key={index}
      ref={(el) => {
        if (index === selectedIndex) {
          el?.focus()
        }
      }}
      className={tailwindMerge.twMerge(
        'flex w-full cursor-pointer rounded-l-default rounded-r-sm px-[7px] py-0.5 text-left transition-[background-color] hover:bg-primary/5',
        selectedIndices.has(index) && 'bg-primary/10',
        index === selectedIndex && 'bg-selected-frame',
      )}
      onPress={(event) => {
        unsafeWriteValue(querySource, 'current', QuerySource.internal)
        setQuery(
          selectedIndices.has(index) ?
            suggestion.deleteFromQuery(event.shiftKey ? query : baseQuery.current)
          : suggestion.addToQuery(event.shiftKey ? query : baseQuery.current),
        )
        if (event.shiftKey) {
          setSelectedIndices(
            new Set(
              selectedIndices.has(index) ?
                [...selectedIndices].filter((otherIndex) => otherIndex !== index)
              : [...selectedIndices, index],
            ),
          )
        } else {
          setAreSuggestionsVisible(false)
        }
      }}
    >
      <Text variant="body" truncate="1" className="w-full">
        {suggestion.render()}
      </Text>
    </aria.Button>
  )
})

/** Props for a {@link Labels}. */
interface LabelsProps {
  readonly isCloud: boolean
  readonly query: AssetQuery
  readonly setQuery: React.Dispatch<React.SetStateAction<AssetQuery>>
  readonly backend: Backend | null
  readonly querySource: React.MutableRefObject<QuerySource>
}

/** Renders labels. */
const Labels = React.memo(function LabelsImpl(props: LabelsProps) {
  const { isCloud, query, setQuery, backend, querySource } = props

  const { data: labels = [] } = useQuery(backendQueryOptions(backend, 'listTags', []))
  const sortedLabels = React.useMemo(
    () => [...labels].sort((a, b) => string.compareCaseInsensitive(a.value, b.value)),
    [labels],
  )

  const toggleLabel = useEventCallback((label?: BackendLabel) => {
    if (label == null) {
      return
    }
    unsafeWriteValue(querySource, 'current', QuerySource.internal)
    setQuery(query.withToggled('labels', label.value))
  })

  if (!isCloud || labels.length === 0) return null

  return (
    <div data-testid="asset-search-labels" className="pointer-events-auto flex gap-2 px-1.5">
      {sortedLabels.map((label) => {
        return (
          <Label
            key={label.id}
            color={label.color}
            label={label}
            active={query.labels.some((term) => term === label.value)}
            onPress={toggleLabel}
          >
            {label.value}
          </Label>
        )
      })}
    </div>
  )
})

// app/gui/src/dashboard/layouts/AssetSearchBar.vue
<script setup lang="ts">
/**
 * @file The drive's search bar: a search field over a popover of the query's tags (`name:`,
 * `type:`, …), the labels (in the cloud) and suggestions for the term being typed. Its keyboard
 * behaviour:
 *
 * - typing anywhere on the drive (outside a text field and a modal) focuses the field;
 * - the arrow keys move through the suggestions, previewing each in the field, and Escape returns
 *   to what was typed; Enter, or a press on a suggestion, takes it;
 * - Shift with a press adds a suggestion and keeps the popover open (Shift again removes it);
 * - Escape otherwise leaves the field, keeping its text.
 *
 * The suggestions come from the table (`useSuggestions`), which knows the listed assets, the labels
 * and the users. The suggestion the arrow keys highlight takes the focus (it is focused whenever
 * the popover re-renders, which outlasts the field's own refocus): typing then goes nowhere until
 * the field is clicked, and Escape drops the focus.
 */
import { useSuggestions, type Suggestion } from '#/layouts/Drive/suggestions'
import DriveLabel from '#/pages/dashboard/components/DriveLabel.vue'
import Button from '$/components/Button/Button.vue'
import { DIALOG_BACKGROUND } from '$/components/Dialog/variants'
import Icon from '$/components/Icon/Icon.vue'
import Text from '$/components/Text/Text.vue'
import { useContainerData } from '$/providers/container'
import { useModals } from '$/providers/modals'
import { useText } from '$/providers/text'
import AssetQuery, { type AssetQueryKey } from '$/utils/AssetQuery'
import { backendQueryOptions } from '$/utils/backendQuery'
import { compareCaseInsensitive } from '$/utils/data/string'
import { isElementTextInput, isPotentiallyShortcut, isTextInputEvent } from '$/utils/event'
import { twMerge } from '$/utils/style/tailwindMerge'
import { useQuery } from '@tanstack/vue-query'
import { useEventListener } from '@vueuse/core'
import type { Backend, Label as BackendLabel } from 'enso-common/src/services/Backend'
import { isOnMacOS } from 'enso-common/src/utilities/detect'
import { computed, nextTick, onMounted, onUpdated, ref, shallowRef, watch } from 'vue'

const { backend, isCloud, query, setQuery } = defineProps<{
  backend: Backend | null
  isCloud: boolean
  query: AssetQuery
  setQuery: (query: AssetQuery) => void
}>()

const { getText } = useText()
const container = useContainerData()
const modals = useModals()
const { suggestions: rawSuggestions } = useSuggestions()

/** The query as of the start of moving through the suggestions. */
let baseQuery = query
let querySource: QuerySource = QuerySource.external

const suggestions = shallowRef<readonly Suggestion[]>(rawSuggestions.value)
const selectedIndex = ref<number | null>(null)
/** Whether the suggestions show, as rendered; see {@link setAreSuggestionsVisible}. */
const areSuggestionsVisible = ref(false)
/** Whether the suggestions are to show, at once. */
let suggestionsVisibleNow = false
/**
 * Show or hide the suggestions after anything else the event changed has rendered: so the table
 * re-renders for a new query while a suggestion still has the focus, and does not take the focus
 * from it (it takes the focus only from the body).
 */
function setAreSuggestionsVisible(value: boolean) {
  suggestionsVisibleNow = value
  void nextTick(() => {
    areSuggestionsVisible.value = suggestionsVisibleNow
  })
}
const selectedIndices = shallowRef<ReadonlySet<number>>(new Set())
const root = ref<HTMLLabelElement>()
const searchInput = ref<HTMLInputElement>()

const placeholder = computed(() =>
  isCloud ?
    isOnMacOS() ? getText('remoteBackendSearchPlaceholderMacOs')
    : getText('remoteBackendSearchPlaceholder')
  : getText('localBackendSearchPlaceholder'),
)

watch(rawSuggestions, (newSuggestions) => {
  if (querySource !== QuerySource.tabbing) suggestions.value = newSuggestions
})

/** Put the caret at the end of the field. */
function moveCaretToEnd() {
  const input = searchInput.value
  if (input == null) return
  const end = input.value.length
  input.setSelectionRange(end, end)
}

// The effects of a new query, in order, run after rendering.
watch(
  () => query,
  (newQuery) => {
    if (querySource !== QuerySource.tabbing) baseQuery = newQuery
    if (querySource !== QuerySource.tabbing) selectedIndex.value = null
    if (querySource !== QuerySource.internal && querySource !== QuerySource.tabbing) {
      if (searchInput.value != null) searchInput.value.value = newQuery.query
    }
    if (querySource !== QuerySource.typing && searchInput.value != null) {
      searchInput.value.value = newQuery.toString()
    }
    if (querySource !== QuerySource.tabbing) {
      baseQuery = newQuery
      querySource = QuerySource.external
    }
  },
  { flush: 'post' },
)

// Moving through the suggestions previews each one in the field.
watch(
  selectedIndex,
  (index) => {
    if (querySource === QuerySource.internal || querySource === QuerySource.tabbing) {
      let newQuery = query
      const suggestion = index == null ? null : suggestions.value[index]
      if (suggestion != null) {
        newQuery = suggestion.addToQuery(baseQuery)
        setQuery(newQuery)
      }
      searchInput.value?.focus()
      moveCaretToEnd()
      if (searchInput.value != null) searchInput.value.value = newQuery.toString()
      void nextTick(focusSelectedSuggestion)
    }
  },
  { flush: 'post' },
)

/** The suggestions' buttons, by index. */
const suggestionButtons = new Map<number, HTMLElement>()
function setSuggestionButton(element: unknown, index: number) {
  if (element instanceof HTMLElement) suggestionButtons.set(index, element)
  else suggestionButtons.delete(index)
}

/** Focus the highlighted suggestion, on every render of the popover. */
function focusSelectedSuggestion() {
  if (selectedIndex.value != null) suggestionButtons.get(selectedIndex.value)?.focus()
}
onUpdated(focusSelectedSuggestion)

onMounted(() => {
  if (searchInput.value != null) searchInput.value.value = query.query
})

useEventListener(root, 'keydown', (event: KeyboardEvent) => {
  if (!suggestionsVisibleNow) return
  if (event.key === 'ArrowUp' || event.key === 'ArrowDown') {
    event.preventDefault()
    event.stopImmediatePropagation()
    querySource = QuerySource.tabbing
    const reverse = event.key === 'ArrowUp'
    const oldIndex = selectedIndex.value
    const length = Math.max(1, suggestions.value.length)
    selectedIndex.value =
      reverse ?
        oldIndex == null ?
          length - 1
        : (oldIndex + length - 1) % length
      : oldIndex == null ? 0
      : (oldIndex + 1) % length
  }
  if (
    event.key === 'Enter' ||
    (event.key === ' ' && document.activeElement !== searchInput.value)
  ) {
    querySource = QuerySource.external
    if (searchInput.value != null) {
      searchInput.value.focus()
      moveCaretToEnd()
    }
  }
  if (event.key === 'Enter') setAreSuggestionsVisible(false)
  if (event.key === 'Escape') {
    if (querySource === QuerySource.tabbing) {
      querySource = QuerySource.external
      setQuery(baseQuery)
      setAreSuggestionsVisible(false)
    } else {
      searchInput.value?.blur()
    }
  }
})

useEventListener(document, 'keydown', (event: KeyboardEvent) => {
  // Allow `alt` to be held, in case it is being used to enter special characters.
  if (
    !isElementTextInput(event.target) &&
    (!(event.target instanceof Node) || root.value?.contains(event.target) !== true) &&
    isTextInputEvent(event) &&
    event.key !== ' ' &&
    event.key !== 'Delete' &&
    modals.stack.value.length === 0 &&
    container.focusedPanel.type === 'drive'
  ) {
    searchInput.value?.focus()
  }
  if (
    event.target instanceof Node &&
    root.value?.contains(event.target) === true &&
    isPotentiallyShortcut(event)
  ) {
    searchInput.value?.focus()
  }
})

/**
 * The field keeps to the query's `query`, not what the effects above wrote there: after moving
 * through the suggestions and pressing Escape, the field shows nothing, and on focus it shows the
 * query again, so typing goes on from it.
 */
function onInputFocus(event: FocusEvent) {
  const input = event.target as HTMLInputElement
  if (input.value !== query.query) input.value = query.query
}

function onInput(event: Event) {
  if (querySource !== QuerySource.internal) {
    querySource = QuerySource.typing
    setQuery(AssetQuery.fromString((event.target as HTMLInputElement).value))
  }
}

function onInputKeyDown(event: KeyboardEvent) {
  // Escape keeps a non-empty field, rather than letting the browser clear it.
  if (event.key === 'Escape' && (event.target as HTMLInputElement).value !== '') {
    event.preventDefault()
  }
  if (
    event.key === 'Enter' &&
    !event.shiftKey &&
    !event.altKey &&
    !event.metaKey &&
    !event.ctrlKey
  ) {
    // Clone the query to refresh the results.
    setQuery(query.clone())
  }
}

function onRootFocusIn() {
  setAreSuggestionsVisible(true)
}

function onRootFocusOut(event: FocusEvent) {
  const next = event.relatedTarget
  if (!(next instanceof Node) || root.value?.contains(next) !== true) {
    if (querySource === QuerySource.tabbing) querySource = QuerySource.external
    setAreSuggestionsVisible(false)
  }
}

const tagNames = computed(() =>
  (isCloud ? AssetQuery.tagNames : AssetQuery.localTagNames).flatMap(([key, tag]) =>
    tag == null ? [] : [{ key, tag }],
  ),
)

function addTag(key: AssetQueryKey) {
  querySource = QuerySource.internal
  setQuery(query.add(key, ['']))
}

function pressSuggestion(index: number, suggestion: Suggestion, event: MouseEvent) {
  querySource = QuerySource.internal
  setQuery(
    selectedIndices.value.has(index) ?
      suggestion.deleteFromQuery(event.shiftKey ? query : baseQuery)
    : suggestion.addToQuery(event.shiftKey ? query : baseQuery),
  )
  if (event.shiftKey) {
    selectedIndices.value = new Set(
      selectedIndices.value.has(index) ?
        [...selectedIndices.value].filter((otherIndex) => otherIndex !== index)
      : [...selectedIndices.value, index],
    )
  } else {
    setAreSuggestionsVisible(false)
  }
}

const labelsQuery = useQuery(computed(() => backendQueryOptions(backend, 'listTags', [])))
const sortedLabels = computed(() =>
  [...(labelsQuery.data.value ?? [])].sort((a, b) => compareCaseInsensitive(a.value, b.value)),
)

function toggleLabel(label?: BackendLabel) {
  if (label == null) return
  querySource = QuerySource.internal
  setQuery(query.withToggled('labels', label.value))
}

const popoverClass = DIALOG_BACKGROUND({
  className:
    'absolute left-0 right-0 top-0 z-1 grid w-full overflow-hidden rounded-default border-0.5 border-primary/20 -outline-offset-1 outline-primary',
})
</script>

<script lang="ts">
/** The reason behind a new query. */
enum QuerySource {
  /**
   * A change from moving through the suggestions. While technically internal, it does not change
   * the base query.
   */
  tabbing = 'tabbing',
  /** A change made by this component. */
  internal = 'internal',
  /** A change from typing in the field. */
  typing = 'typing',
  /** A change made by another component. */
  external = 'external',
}
</script>

<template>
  <div class="relative w-full max-w-[60em]">
    <label
      ref="root"
      data-testid="asset-search-bar"
      class="group z-1 flex grow items-center gap-asset-search-bar rounded-full border-0.5 border-primary/50 py-[3.5px] pl-2 pr-1.5 text-primary"
      @focusin="onRootFocusIn"
      @focusout="onRootFocusOut"
    >
      <div class="relative size-4 placeholder" />
      <div v-if="areSuggestionsVisible" :class="popoverClass">
        <div class="overflow-hidden">
          <div class="relative mt-3 flex flex-col gap-3 pt-8">
            <!-- Tags (`name:`, `modified:`, …) -->
            <div
              data-testid="asset-search-tag-names"
              class="pointer-events-auto flex flex-wrap gap-2 whitespace-nowrap px-1.5"
            >
              <Button
                v-for="{ key, tag } in tagNames"
                :key="key"
                variant="outline"
                size="xsmall"
                class="min-w-12"
                @press="addTag(key)"
              >
                {{ tag + ':' }}
              </Button>
            </div>
            <!-- The labels -->
            <div
              v-if="isCloud && sortedLabels.length !== 0"
              data-testid="asset-search-labels"
              class="pointer-events-auto flex gap-2 px-1.5"
            >
              <DriveLabel
                v-for="label in sortedLabels"
                :key="label.id"
                :color="label.color"
                :label="label"
                :active="query.labels.some((term) => term === label.value)"
                :onPress="toggleLabel"
              >
                {{ label.value }}
              </DriveLabel>
            </div>
            <!-- Suggestions -->
            <div
              class="flex max-h-search-suggestions-list flex-col overflow-y-auto overflow-x-hidden pb-0.5 pl-0.5"
            >
              <button
                v-for="(suggestion, index) in suggestions"
                :key="suggestion.key"
                :ref="(element) => setSuggestionButton(element, index)"
                data-testid="asset-search-suggestion"
                type="button"
                :class="
                  twMerge(
                    'flex w-full cursor-pointer rounded-l-default rounded-r-sm px-[7px] py-0.5 text-left transition-[background-color] hover:bg-primary/5',
                    selectedIndices.has(index) && 'bg-primary/10',
                    index === selectedIndex && 'bg-selected-frame',
                  )
                "
                @click="pressSuggestion(index, suggestion, $event)"
              >
                <Text variant="body" truncate="1" class="w-full">
                  <component :is="() => suggestion.render()" />
                </Text>
              </button>
            </div>
          </div>
        </div>
      </div>
      <Icon
        icon="find"
        class="absolute left-2.5 top-[50%] z-1 -mt-[1px] -translate-y-1/2 text-primary"
      />
      <div
        class="relative grow before:text before:absolute before:-inset-x-1 before:my-auto before:rounded-full before:transition-all"
        :data-empty="query.query === '' ? 'true' : undefined"
      >
        <input
          ref="searchInput"
          :aria-label="getText('assetSearchFieldLabel')"
          type="search"
          size="1"
          :placeholder="placeholder"
          class="peer text relative z-1 w-full bg-transparent placeholder-primary/40"
          @focus="onInputFocus"
          @input="onInput"
          @keydown="onInputKeyDown"
        />
      </div>
    </label>
  </div>
</template>
