// app/gui/src/dashboard/layouts/AssetsTableCombinedContextMenu.vue
<script setup lang="ts">
/**
 * @file The asset table's context menu: one asset's (`AssetContextMenu.vue`) while exactly one is
 * selected, else the table's (`AssetsTableContextMenu.vue`). The Vue port of React's
 * `AssetsTableCombinedContextMenu`.
 *
 * It keeps where the menu is and whether it is open, which React kept in each menu: when the kind
 * of menu changes (a right click on a row that was not selected selects it), the new one opens
 * only where the row's right click asked for it (`contextMenuData`), as React's freshly mounted
 * menu did. `open` and `close` are React's imperative `ContextMenuApi`.
 */
import AssetContextMenu from '#/layouts/AssetContextMenu.vue'
import AssetsTableContextMenu from '#/layouts/AssetsTableContextMenu.vue'
import { useAssetItems } from '#/layouts/Drive/assetItems'
import { useDriveStore } from '$/providers/driveStore'
import type { DirectoryId } from 'enso-common/src/services/Backend'
import { computed, ref, shallowRef, watch } from 'vue'

const { currentDirectoryId, bindingTarget, doCopy, doCut, doPaste } = defineProps<{
  currentDirectoryId: DirectoryId
  bindingTarget: HTMLElement | null | undefined
  doCopy: () => void
  doCut: () => void
  doPaste: (newParentId: DirectoryId) => void
}>()

const driveStore = useDriveStore()
const assetItems = useAssetItems()

/** The one selected asset, when exactly one is selected and listed. */
const asset = computed(() => {
  const { selectedIds } = driveStore
  if (selectedIds.size !== 1) return undefined
  const [soleId] = selectedIds
  return soleId != null ? assetItems.getAsset(soleId) : undefined
})
const kind = computed(() => (asset.value != null ? 'asset' : 'table'))

const isOpen = ref(false)
const position = shallowRef<Pick<MouseEvent, 'pageX' | 'pageY'>>({ pageX: 0, pageY: 0 })

watch(kind, (newKind) => {
  const initialPosition =
    newKind === 'asset' ? driveStore.contextMenuData?.initialContextMenuPosition : null
  if (initialPosition != null) {
    position.value = initialPosition
    isOpen.value = true
  } else {
    isOpen.value = false
  }
})

defineExpose({
  /** Open the menu at a point in page coordinates. */
  open(newPosition: Pick<MouseEvent, 'pageX' | 'pageY'>) {
    position.value = { pageX: newPosition.pageX, pageY: newPosition.pageY }
    isOpen.value = true
  },
  close() {
    isOpen.value = false
  },
})
</script>

<template>
  <AssetContextMenu
    v-if="asset != null"
    v-model:open="isOpen"
    :asset="asset"
    :position="position"
    :currentDirectoryId="currentDirectoryId"
    :bindingTarget="bindingTarget"
    :doCopy="doCopy"
    :doCut="doCut"
    :doPaste="doPaste"
    @close="driveStore.update({ contextMenuData: null })"
  />
  <AssetsTableContextMenu
    v-else
    v-model:open="isOpen"
    :position="position"
    :currentDirectoryId="currentDirectoryId"
    :bindingTarget="bindingTarget"
    :doCopy="doCopy"
    :doCut="doCut"
    :doPaste="doPaste"
  />
</template>

// app/gui/src/dashboard/layouts/AssetsTableCombinedContextMenu.tsx
/**
 * @file Switches between {@link AssetContextMenu}
 * and {@link AssetsTableContextMenu} as necessary.
 */
import type { ContextMenuApi } from '#/components/ContextMenu'
import { useStore } from '#/hooks/storeHooks'
import { useSyncRef } from '#/hooks/syncRefHooks'
import { AssetContextMenu } from '#/layouts/AssetContextMenu'
import { AssetsTableContextMenu } from '#/layouts/AssetsTableContextMenu'
import { useGetAsset } from '#/layouts/Drive/assetsTableItemsHooks'
import { useDriveStore } from '#/providers/DriveProvider'
import type { DirectoryId } from 'enso-common/src/services/Backend'
import { forwardRef, type ForwardedRef } from 'react'

/** Props for an {@link AssetsTableCombinedContextMenu}. */
export interface AssetsTableCombinedContextMenuProps {
  readonly currentDirectoryId: DirectoryId
  readonly doCopy: () => void
  readonly doCut: () => void
  readonly doPaste: (newParentId: DirectoryId) => void
}

export const AssetsTableCombinedContextMenu = forwardRef(
  function AssetsTableCombinedContextMenuImpl(
    props: AssetsTableCombinedContextMenuProps,
    ref: ForwardedRef<ContextMenuApi>,
  ) {
    const { currentDirectoryId, doCopy, doCut, doPaste } = props

    const driveStore = useDriveStore()

    const singleSelectedItemId = useStore(
      driveStore,
      (state) =>
        state.selectedIds.size === 1 ?
          state.selectedIds[Symbol.iterator]().next().value
        : undefined,
      { unsafeEnableTransition: true },
    )
    const contextMenuData = useStore(driveStore, (state) => state.contextMenuData)
    const getAsset = useGetAsset()
    const asset = singleSelectedItemId ? getAsset(singleSelectedItemId) : undefined
    const contextMenuDataRef = useSyncRef(contextMenuData?.triggerRef.current ?? null)

    return asset ?
        <AssetContextMenu
          ref={ref}
          asset={asset}
          currentDirectoryId={currentDirectoryId}
          doCopy={doCopy}
          doCut={doCut}
          doPaste={doPaste}
          triggerRef={contextMenuDataRef}
          initialPosition={contextMenuData?.initialContextMenuPosition}
        />
      : <AssetsTableContextMenu
          ref={ref}
          currentDirectoryId={currentDirectoryId}
          doCopy={doCopy}
          doCut={doCut}
          doPaste={doPaste}
        />
  },
)
