// app/gui/src/components/AboutModal/AboutModal.vue
<script setup lang="ts">
/**
 * @file The "About Enso" dialog: the app's edition and versions, with a button to copy them. The Vue
 * port of the React `AboutModal`, with the same dialog, text and layout.
 *
 * `App.vue` mounts it once, and the app menu's About item, the user menu and the info menu open it
 * through {@link openAboutModal} (`./aboutModal.ts`).
 */
import CopyButton from '$/components/Button/CopyButton.vue'
import Dialog from '$/components/Dialog/Dialog.vue'
import Icon from '$/components/Icon/Icon.vue'
import Heading from '$/components/Text/Heading.vue'
import Text from '$/components/Text/Text.vue'
import { useBackends } from '$/providers/backends'
import { useText } from '$/providers/text'
import type { TextId } from 'enso-common/src/text'
import { computed } from 'vue'

const open = defineModel<boolean>('open', { default: false })

const { localBackend } = useBackends()
const { getText } = useText()

const versionsEntries = computed((): readonly (readonly [TextId, string])[] => [
  ...(window.api != null ?
    ([
      ['version', window.api.versionInfo.version],
      ['build', window.api.versionInfo.build],
      ['electronVersion', window.api.versionInfo.electron],
      ['chromeVersion', window.api.versionInfo.chrome],
    ] as const)
  : [
      ...($config.VERSION == null ? [] : ([['version', $config.VERSION]] as const)),
      ...($config.COMMIT_HASH == null ? [] : ([['build', $config.COMMIT_HASH]] as const)),
    ]),
  ['userAgent', navigator.userAgent],
])

const copyText = computed(() =>
  versionsEntries.value.map(([textId, version]) => `${getText(textId)} ${version}`).join('\n'),
)
</script>

<template>
  <Dialog v-model:open="open" :title="getText('aboutThisAppShortcut')" size="large">
    <div class="relative flex flex-col items-center gap-4">
      <Icon icon="enso_logo" class="size-16 shrink-0" />

      <div class="flex flex-col items-center gap-2">
        <Heading>
          {{
            localBackend != null ? getText('appNameDesktopEdition') : getText('appNameCloudEdition')
          }}
        </Heading>

        <table class="self-stretch">
          <tbody>
            <tr v-for="[textId, version] in versionsEntries" :key="textId">
              <td class="pr-cell-x align-text-top">
                <Text nowrap>{{ getText(textId) }}</Text>
              </td>
              <td>
                <Text class="break-words [word-break:break-word]">{{ version }}</Text>
              </td>
            </tr>
          </tbody>
        </table>

        <CopyButton :copyText="copyText" size="medium" variant="submit">
          {{ getText('copy') }}
        </CopyButton>
      </div>
    </div>
  </Dialog>
</template>

// app/gui/src/dashboard/modals/AboutModal.tsx
/* eslint-disable react-refresh/only-export-components --
 * These files export a compound component built with `Object.assign(Component, { Sub })`.
 * eslint-plugin-react-refresh 0.5 cannot see through `Object.assign`, so it treats the file as
 * exporting a non-component and flags every local component in it. There is no `extraHOCs`
 * equivalent for this pattern. */
/** @file Modal for confirming delete of any type of asset. */
import { CopyButton } from '#/components/Button'
import { Dialog } from '#/components/Dialog'
import { Icon } from '#/components/Icon'
import { Text } from '#/components/Text'
import { mergeRefs } from '#/utilities/mergeRefs'
import { useModalState, type ModalApi } from '#/utilities/modal'
import { useBackends, useText } from '$/providers/react'
import type { TextId } from 'enso-common/src/text'
import { forwardRef, useMemo, type ForwardedRef } from 'react'

/** A modal for confirming the deletion of an asset. */
export const AboutModal = Object.assign(
  forwardRef(function AboutModalImpl(_props: object, ref: ForwardedRef<ModalApi>) {
    const { localBackend } = useBackends()
    const { getText } = useText()
    const { isOpen, setIsOpen } = useModalState(
      mergeRefs(ref, (api) => {
        if (api) {
          ABOUT_MODAL_OUTER.open = api.open
          ABOUT_MODAL_OUTER.close = api.close
        }
      }),
    )

    const versionsEntries = [
      ...(window.api != null ?
        ([
          ['version', window.api.versionInfo.version],
          ['build', window.api.versionInfo.build],
          ['electronVersion', window.api.versionInfo.electron],
          ['chromeVersion', window.api.versionInfo.chrome],
        ] as const)
      : ([
          ...($config.VERSION == null ? [] : ([['version', $config.VERSION]] as const)),
          ...($config.COMMIT_HASH == null ? [] : ([['build', $config.COMMIT_HASH]] as const)),
        ] as const)),
      ['userAgent', navigator.userAgent],
    ] satisfies readonly (readonly [TextId, string])[]

    const copyText = useMemo(
      () => versionsEntries.map(([textId, version]) => `${getText(textId)} ${version}`).join('\n'),
      [getText, versionsEntries],
    )

    return (
      <Dialog
        title={getText('aboutThisAppShortcut')}
        size="large"
        modalProps={{ isOpen }}
        onOpenChange={setIsOpen}
      >
        <div className="relative flex flex-col items-center gap-4">
          <Icon icon="enso_logo" className="size-16 shrink-0" />

          <div className="flex flex-col items-center gap-2">
            <Text.Heading>
              {localBackend != null ?
                getText('appNameDesktopEdition')
              : getText('appNameCloudEdition')}
            </Text.Heading>

            <table className="self-stretch">
              <tbody>
                {versionsEntries.map((entry) => {
                  const [textId, version] = entry

                  return (
                    <tr key={textId}>
                      <td className="pr-cell-x align-text-top">
                        <Text nowrap>{getText(textId)}</Text>
                      </td>
                      <td>
                        <Text className="break-words [word-break:break-word]">{version}</Text>
                      </td>
                    </tr>
                  )
                })}
              </tbody>
            </table>

            <CopyButton copyText={copyText} size="medium" variant="submit">
              {getText('copy')}
            </CopyButton>
          </div>
        </div>
      </Dialog>
    )
  }),
  { open: () => {}, close: () => {} },
)
const ABOUT_MODAL_OUTER = AboutModal
