// app/gui/src/dashboard/layouts/AssetPanel/components/ProjectExecution.tsx
/** @file Displays information describing a specific version of an asset. */
import { Button } from '#/components/Button'
import { IconDisplay } from '#/components/IconDisplay'
import { Menu } from '#/components/Menu'
import { Text } from '#/components/Text'
import { VisualTooltip } from '#/components/VisualTooltip'
import { backendMutationOptions } from '#/hooks/backendHooks'
import { useLocalStorageState } from '#/hooks/localStoreState'
import { useGetOrdinal } from '#/hooks/ordinalHooks'
import ConfirmDeleteModal from '#/modals/ConfirmDeleteModal'
import { setModal } from '#/providers/ModalProvider'
import { useText } from '$/providers/react'
import { useContainerData } from '$/providers/react/container'
import { useFeatureFlag } from '$/providers/react/featureFlags'
import { tv } from '$/utils/style/tailwindVariants'
import {
  getLocalTimeZone,
  now,
  parseAbsolute,
  toZoned,
  type ZonedDateTime,
} from '@internationalized/date'
import { useMutation } from '@tanstack/react-query'
import type { Backend } from 'enso-common/src/services/Backend'
import * as backendModule from 'enso-common/src/services/Backend'
import {
  DAY_3_LETTER_TEXT_IDS,
  DAY_TEXT_IDS,
  getDescriptionForTimeZone,
  getTimeZoneOffsetStringWithGMT,
  MONTH_3_LETTER_TEXT_IDS,
  zonedDateTimeToReadableIsoString,
} from 'enso-common/src/utilities/data/dateTime'

const MONTHS_IN_YEAR = 12

const PROJECT_EXECUTION_STYLES = tv({
  base: 'group flex flex-row gap-1 w-full rounded-default items-center odd:bg-primary/5 p-2',
  variants: {
    isEnabled: { false: { time: 'opacity-50', infoContainer: 'opacity-50' } },
    compact: { true: { base: 'px-2' } },
  },
  slots: {
    timeContainer: 'flex flex-row items-center gap-2 grow px-2 py-0.5',
    times: 'flex flex-col max-h-[10lh] overflow-auto grow',
    time: '',
    timeButtons: 'opacity-0 group-hover:opacity-100 transition-[opacity]',
    infoContainer: 'flex flex-col grow-0 gap-1',
    info: 'cursor-default max-w-48 hover:bg-transparent',
  },
})

/** Props for a {@link ProjectExecution}. */
export interface ProjectExecutionProps {
  /** Defaults to `false`. */
  readonly compact?: boolean
  readonly backend: Backend
  readonly item: backendModule.ProjectAsset
  readonly projectExecution: backendModule.ProjectExecution
  /** Defaults to the first date of `projectExecution` if not given. */
  readonly date?: ZonedDateTime
  readonly session: backendModule.ProjectSession | undefined
}

/** Displays information describing a specific version of an asset. */
export function ProjectExecution(props: ProjectExecutionProps) {
  const { compact = false, backend, item, projectExecution, session } = props
  const { getText } = useText()
  const getOrdinal = useGetOrdinal()
  const container = useContainerData()
  const [timeZone = getLocalTimeZone()] = useLocalStorageState('preferredTimeZone')
  const date = props.date == null ? null : toZoned(props.date, timeZone)
  const enableAdvancedProjectExecutionOptions = useFeatureFlag(
    'enableAdvancedProjectExecutionOptions',
  )
  const { repeat } = projectExecution
  const repeatString = (() => {
    if (date) {
      const minuteString = String(date.minute).padStart(2, '0')
      // eslint-disable-next-line @typescript-eslint/no-magic-numbers
      return getText(date.hour > 11 ? 'xPm' : 'xAm', `${date.hour % 12 || 12}:${minuteString}`)
    } else {
      const zonedStartDate = parseAbsolute(projectExecution.startDate, timeZone)
      const minuteString = String(zonedStartDate.minute).padStart(2, '0')
      const startDateDailyRepeat = getText(
        // eslint-disable-next-line @typescript-eslint/no-magic-numbers
        zonedStartDate.hour > 11 ? 'xPm' : 'xAm',
        // eslint-disable-next-line @typescript-eslint/no-magic-numbers
        `${zonedStartDate.hour % 12 || 12}:${minuteString}`,
      )
      switch (repeat.type) {
        case 'none': {
          return zonedDateTimeToReadableIsoString(zonedStartDate)
        }
        case 'daily': {
          return `${startDateDailyRepeat} ${getText('everyDaySuffix')}`
        }
        case 'weekly': {
          const dayNames = repeat.daysOfWeek
            .map((day) => getText(DAY_3_LETTER_TEXT_IDS[day] ?? 'monday3'))
            .join(', ')
          return `${startDateDailyRepeat} ${dayNames}`
        }
        case 'monthlyDate':
        case 'monthlyWeekday':
        case 'monthlyLastWeekday': {
          const monthNames =
            repeat.months.length === MONTHS_IN_YEAR ?
              getText('everyMonth')
            : repeat.months
                .map((month) => getText(MONTH_3_LETTER_TEXT_IDS[month] ?? 'january3'))
                .join(', ')
          switch (repeat.type) {
            case 'monthlyDate': {
              return getText(
                'repeatsTimeXMonthsXDateX',
                startDateDailyRepeat,
                monthNames,
                getOrdinal(repeat.date),
              )
            }
            case 'monthlyWeekday': {
              return getText(
                'repeatsTimeXMonthsXDayXWeekX',
                startDateDailyRepeat,
                monthNames,
                getText(DAY_TEXT_IDS[repeat.dayOfWeek] ?? 'monday'),
                getText('xthWeek', getOrdinal(repeat.weekNumber)),
              )
            }
            case 'monthlyLastWeekday': {
              return getText(
                'repeatsTimeXMonthsXDayXLastWeek',
                startDateDailyRepeat,
                monthNames,
                getText(DAY_TEXT_IDS[repeat.dayOfWeek] ?? 'monday'),
              )
            }
          }
        }
      }
    }
  })()

  const styles = PROJECT_EXECUTION_STYLES({
    compact,
    isEnabled: true,
  })

  const deleteProjectExecution = useMutation(
    backendMutationOptions(backend, 'deleteProjectExecution'),
  )

  const repeatEl = <div>{repeatString}</div>

  const maxDurationLabel = getText('maxDurationLabel')
  const maxDurationDescription = getText('xMinutes', projectExecution.maxDurationMinutes)
  const repeatIntervalLabel = getText('repeatIntervalLabel')
  const repeatIntervalDescription = getText(
    backendModule.PROJECT_EXECUTION_REPEAT_TYPE_TO_TEXT_ID[projectExecution.repeat.type],
  )
  const timeZoneLabel = getText('timeZoneLabel')
  const timeZoneDescription = `${getTimeZoneOffsetStringWithGMT(now(projectExecution.timeZone))} ${getDescriptionForTimeZone(projectExecution.timeZone)}`

  return (
    <div className={styles.base()}>
      <div className={styles.timeContainer()}>
        {!compact ?
          repeatEl
        : <VisualTooltip
            tooltip={
              <div>
                {enableAdvancedProjectExecutionOptions && (
                  <Text color="inherit">{`${maxDurationLabel}: ${maxDurationDescription}`}</Text>
                )}
                <Text color="inherit">{`${repeatIntervalLabel}: ${repeatIntervalDescription}`}</Text>
                <Text color="inherit">{`${timeZoneLabel}: ${timeZoneDescription}`}</Text>
              </div>
            }
            tooltipPlacement="left"
            className={styles.times()}
          >
            {repeatEl}
          </VisualTooltip>
        }
        <Button.GroupJoin
          className="shrink-0 grow-0"
          buttonVariants={{ size: 'small', variant: 'outline' }}
        >
          {session && (
            <Button
              icon="log"
              onPress={() => {
                container.openProjectLogTab(session.projectSessionId, item.title)
              }}
            >
              {getText('showLogs')}
            </Button>
          )}
          <Menu.Trigger>
            <Button icon="chevron_down" iconPosition="end" variant="outline">
              {!session && getText('actions')}
            </Button>

            <Menu>
              <Menu.Item
                icon="trash"
                onAction={() => {
                  setModal(
                    <ConfirmDeleteModal
                      defaultOpen
                      actionText={getText('deleteThisProjectExecution')}
                      onConfirm={async () => {
                        await deleteProjectExecution.mutateAsync([
                          projectExecution.executionId,
                          item.title,
                        ])
                      }}
                    />,
                  )
                }}
              >
                {getText('delete')}
              </Menu.Item>
            </Menu>
          </Menu.Trigger>
        </Button.GroupJoin>
      </div>
      {!compact && (
        <Button.Group className={styles.infoContainer()}>
          {enableAdvancedProjectExecutionOptions && (
            <IconDisplay
              variant="outline"
              icon="time"
              tooltip={maxDurationLabel}
              tooltipPlacement="left"
              className={styles.info()}
            >
              {maxDurationDescription}
            </IconDisplay>
          )}
          <IconDisplay
            variant="outline"
            icon="repeat"
            tooltip={repeatIntervalLabel}
            tooltipPlacement="left"
            className={styles.info()}
          >
            {repeatIntervalDescription}
          </IconDisplay>
          <IconDisplay
            variant="outline"
            icon="time"
            tooltip={timeZoneLabel}
            tooltipPlacement="left"
            className={styles.info()}
          >
            {timeZoneDescription}
          </IconDisplay>
        </Button.Group>
      )}
    </div>
  )
}

// app/gui/src/cloud/versions/ProjectExecution.vue
<script setup lang="ts">
/**
 * @file One scheduled execution of a project on the Schedule tab's selected day: when it runs (and,
 * on hover, its repeat interval, time zone and, with the advanced options, its maximum duration),
 * the logs of the session it started, if any, and an actions menu to delete it. It is always
 * compact, as the calendar shows it.
 */
import ConfirmDeleteModal from '$/components/AlertDialog/ConfirmDeleteModal.vue'
import Button from '$/components/Button/Button.vue'
import ButtonGroup from '$/components/Button/ButtonGroup.vue'
import DropdownMenu from '$/components/Menu/DropdownMenu.vue'
import MenuItem from '$/components/Menu/MenuItem.vue'
import Text from '$/components/Text/Text.vue'
import VisualTooltip from '$/components/Tooltip/VisualTooltip.vue'
import { useContainerData } from '$/providers/container'
import { useFeatureFlag } from '$/providers/featureFlags'
import { useModals } from '$/providers/modals'
import { useText } from '$/providers/text'
import { tv } from '$/utils/style/tailwindVariants'
import { backendMutationOptions } from '@/composables/backend'
import { now, parseAbsolute, toZoned, type ZonedDateTime } from '@internationalized/date'
import { useMutation } from '@tanstack/vue-query'
import {
  PROJECT_EXECUTION_REPEAT_TYPE_TO_TEXT_ID,
  type Backend,
  type ProjectAsset,
  type ProjectExecution,
  type ProjectSession,
} from 'enso-common/src/services/Backend'
import {
  DAY_3_LETTER_TEXT_IDS,
  DAY_TEXT_IDS,
  getDescriptionForTimeZone,
  getTimeZoneOffsetStringWithGMT,
  MONTH_3_LETTER_TEXT_IDS,
  zonedDateTimeToReadableIsoString,
} from 'enso-common/src/utilities/data/dateTime'
import { computed } from 'vue'
import { useGetOrdinal, usePreferredTimeZone } from './schedule'

const { backend, item, projectExecution, session, ...props } = defineProps<{
  backend: Backend
  item: ProjectAsset
  projectExecution: ProjectExecution
  /** Defaults to the first date of `projectExecution` if not given. */
  date?: ZonedDateTime | undefined
  session: ProjectSession | undefined
}>()

const MONTHS_IN_YEAR = 12
/** The execution's styles, compact as the calendar shows it (and always enabled). */
const PROJECT_EXECUTION_STYLES = tv({
  base: 'group flex flex-row gap-1 w-full rounded-default items-center odd:bg-primary/5 p-2',
  variants: {
    compact: { true: { base: 'px-2' } },
  },
  slots: {
    timeContainer: 'flex flex-row items-center gap-2 grow px-2 py-0.5',
    times: 'flex flex-col max-h-[10lh] overflow-auto grow',
  },
})
const styles = PROJECT_EXECUTION_STYLES({ compact: true })

const { getText } = useText()
const getOrdinal = useGetOrdinal()
const container = useContainerData()
const modals = useModals()
const timeZone = usePreferredTimeZone()
const enableAdvancedProjectExecutionOptions = useFeatureFlag(
  'enableAdvancedProjectExecutionOptions',
)

/** `hh:mm` with "am" or "pm", in the user's language. */
function timeOfDay(dateTime: ZonedDateTime) {
  const minuteString = String(dateTime.minute).padStart(2, '0')
  return getText(dateTime.hour > 11 ? 'xPm' : 'xAm', `${dateTime.hour % 12 || 12}:${minuteString}`)
}

const repeatString = computed(() => {
  if (props.date != null) return timeOfDay(toZoned(props.date, timeZone.value))
  const { repeat } = projectExecution
  const zonedStartDate = parseAbsolute(projectExecution.startDate, timeZone.value)
  const startDateDailyRepeat = timeOfDay(zonedStartDate)
  switch (repeat.type) {
    case 'none': {
      return zonedDateTimeToReadableIsoString(zonedStartDate)
    }
    case 'daily': {
      return `${startDateDailyRepeat} ${getText('everyDaySuffix')}`
    }
    case 'weekly': {
      const dayNames = repeat.daysOfWeek
        .map((day) => getText(DAY_3_LETTER_TEXT_IDS[day] ?? 'monday3'))
        .join(', ')
      return `${startDateDailyRepeat} ${dayNames}`
    }
    case 'monthlyDate':
    case 'monthlyWeekday':
    case 'monthlyLastWeekday': {
      const monthNames =
        repeat.months.length === MONTHS_IN_YEAR ?
          getText('everyMonth')
        : repeat.months
            .map((month) => getText(MONTH_3_LETTER_TEXT_IDS[month] ?? 'january3'))
            .join(', ')
      switch (repeat.type) {
        case 'monthlyDate': {
          return getText(
            'repeatsTimeXMonthsXDateX',
            startDateDailyRepeat,
            monthNames,
            getOrdinal(repeat.date),
          )
        }
        case 'monthlyWeekday': {
          return getText(
            'repeatsTimeXMonthsXDayXWeekX',
            startDateDailyRepeat,
            monthNames,
            getText(DAY_TEXT_IDS[repeat.dayOfWeek] ?? 'monday'),
            getText('xthWeek', getOrdinal(repeat.weekNumber)),
          )
        }
        case 'monthlyLastWeekday': {
          return getText(
            'repeatsTimeXMonthsXDayXLastWeek',
            startDateDailyRepeat,
            monthNames,
            getText(DAY_TEXT_IDS[repeat.dayOfWeek] ?? 'monday'),
          )
        }
      }
    }
  }
  return ''
})

const deleteProjectExecution = useMutation(
  backendMutationOptions('deleteProjectExecution', backend),
)

const maxDuration = computed(
  () =>
    `${getText('maxDurationLabel')}: ${getText('xMinutes', projectExecution.maxDurationMinutes)}`,
)
const repeatInterval = computed(
  () =>
    `${getText('repeatIntervalLabel')}: ${getText(
      PROJECT_EXECUTION_REPEAT_TYPE_TO_TEXT_ID[projectExecution.repeat.type],
    )}`,
)
const timeZoneDescription = computed(
  () =>
    `${getText('timeZoneLabel')}: ${getTimeZoneOffsetStringWithGMT(now(projectExecution.timeZone))} ${getDescriptionForTimeZone(projectExecution.timeZone)}`,
)

function askToDelete() {
  void modals.ask(ConfirmDeleteModal, {
    actionText: getText('deleteThisProjectExecution'),
    onConfirm: () => deleteProjectExecution.mutateAsync([projectExecution.executionId, item.title]),
  })
}
</script>

<template>
  <div :class="styles.base()">
    <div :class="styles.timeContainer()">
      <VisualTooltip tooltipPlacement="left" :class="styles.times()">
        <div>{{ repeatString }}</div>
        <template #tooltip>
          <div>
            <Text v-if="enableAdvancedProjectExecutionOptions" color="inherit">
              {{ maxDuration }}
            </Text>
            <Text color="inherit">{{ repeatInterval }}</Text>
            <Text color="inherit">{{ timeZoneDescription }}</Text>
          </div>
        </template>
      </VisualTooltip>
      <ButtonGroup
        direction="row"
        gap="joined"
        class="shrink-0 grow-0"
        :buttonVariants="{ size: 'small', variant: 'outline' }"
      >
        <Button
          v-if="session"
          icon="log"
          @press="container.openProjectLogTab(session.projectSessionId, item.title)"
        >
          {{ getText('showLogs') }}
        </Button>
        <DropdownMenu placement="bottom" :offset="8">
          <template #trigger>
            <Button icon="chevron_down" iconPosition="end" variant="outline">
              <template v-if="!session" #default>{{ getText('actions') }}</template>
            </Button>
          </template>
          <MenuItem icon="trash" @select="askToDelete">{{ getText('delete') }}</MenuItem>
        </DropdownMenu>
      </ButtonGroup>
    </div>
  </div>
</template>
