// app/gui/src/dashboard/components/Result.tsx
/** @file Display the result of an operation. */
import type { SvgUseIcon, TestIdProps } from '#/components/types'
import {
  RESULT_STATUS_STYLES,
  RESULT_STYLES,
  type ResultStatus,
  type ResultStatusStyle,
} from '$/components/Result/variants'
import type { VariantProps } from '$/utils/style/tailwindVariants'
import * as objects from 'enso-common/src/utilities/data/object'
import type { JSX, PropsWithChildren, ReactElement } from 'react'
import { Icon } from './Icon'
import { Loader } from './Loader'
import { Text } from './Text'

const INFO_ICON = (
  // eslint-disable-next-line no-restricted-syntax
  <Text variant="custom" className="pb-0.5 text-xl leading-[0]" aria-hidden>
    i
  </Text>
)

const STATUS_ICONS = {
  loader: <Loader minHeight="h8" />,
  info: INFO_ICON,
  check: 'check',
  close: 'close',
} as const satisfies Record<ResultStatusStyle['icon'], ReactElement | SvgUseIcon>

const STATUS_ICON_MAP: Readonly<Record<Status, StatusIcon>> = objects.mapEntries(
  RESULT_STATUS_STYLES,
  (_status, { icon, ...colors }) => ({ icon: STATUS_ICONS[icon], ...colors }),
)

/** Possible statuses for a result. */
export type Status = ResultStatus

/** The corresponding icon and color for each status. */
interface StatusIcon {
  readonly icon: ReactElement | SvgUseIcon
  readonly colorClassName: string
  readonly bgClassName: string
}

/** Props for a {@link Result}. */
export interface ResultProps
  extends PropsWithChildren, VariantProps<typeof RESULT_STYLES>, TestIdProps {
  readonly className?: string
  readonly title?: JSX.Element | string
  readonly subtitle?: JSX.Element | string
  /**
   * The status of the result.
   * @default 'success'
   */
  readonly status?: ReactElement | Status
  readonly icon?: SvgUseIcon | false
}

/** Display the result of an operation. */
export function Result(props: ResultProps) {
  const { title, children, status = 'success', subtitle, className, icon, testId, centered } = props

  const statusIcon = typeof status === 'string' ? STATUS_ICON_MAP[status] : null
  const showIcon = icon !== false

  const classes = RESULT_STYLES({ centered })

  return (
    <section className={classes.base({ className })} data-testid={testId}>
      {showIcon ?
        <>
          {statusIcon != null ?
            <div className={classes.statusIcon({ className: statusIcon.bgClassName })}>
              {typeof statusIcon.icon === 'string' ?
                <Icon
                  icon={icon ?? statusIcon.icon}
                  className={classes.icon({ className: statusIcon.colorClassName })}
                />
              : statusIcon.icon}
            </div>
          : status}
        </>
      : null}

      {typeof title === 'string' ?
        <Text.Heading level={2} className={classes.title()} variant="subtitle">
          {title}
        </Text.Heading>
      : title}

      {typeof subtitle === 'string' ?
        <Text elementType="p" className={classes.subtitle()} balance variant="body">
          {subtitle}
        </Text>
      : subtitle}

      {children != null && <div className={classes.content()}>{children}</div>}
    </section>
  )
}

// app/gui/src/components/Result/Result.vue
<script setup lang="ts">
/**
 * @file The result of an operation (success, error, info, loading), with a title, a subtitle and
 * any content: the Vue counterpart of the React `#/components/Result`.
 *
 * `status` may also be `'custom'`, with the `status` slot supplying the icon; the React one takes
 * an element there. `icon` replaces the status's `icons.svg` icon; `false` hides the icon.
 */
import Icon from '$/components/Icon/Icon.vue'
import {
  RESULT_STATUS_STYLES,
  RESULT_STYLES,
  type ResultStatus,
} from '$/components/Result/variants'
import Loader from '$/components/Spinner/Loader.vue'
import Heading from '$/components/Text/Heading.vue'
import Text from '$/components/Text/Text.vue'
import type { VariantProps } from '$/utils/style/tailwindVariants'
import type { Icon as IconName } from '@/util/iconMetadata/iconName'
import { computed } from 'vue'

type ResultVariants = VariantProps<typeof RESULT_STYLES>

const {
  status = 'success',
  title,
  subtitle,
  // `undefined`, not the `false` Vue casts an absent boolean prop to: `false` hides the icon.
  icon = undefined,
  // `undefined`, not the `false` Vue casts an absent boolean prop to, so the default applies.
  centered = undefined,
  testId,
  class: className,
} = defineProps<{
  status?: ResultStatus | 'custom' | undefined
  title?: string | undefined
  subtitle?: string | undefined
  icon?: IconName | false | undefined
  centered?: ResultVariants['centered']
  testId?: string | undefined
  class?: string | undefined
}>()

const styles = computed(() => RESULT_STYLES({ centered }))
const statusStyle = computed(() => (status === 'custom' ? null : RESULT_STATUS_STYLES[status]))
</script>

<template>
  <section :class="styles.base({ className })" :data-testid="testId">
    <template v-if="icon !== false">
      <div
        v-if="statusStyle != null"
        :class="styles.statusIcon({ className: statusStyle.bgClassName })"
      >
        <Loader v-if="statusStyle.icon === 'loader'" minHeight="h8" />
        <!-- No whitespace around the "i": it would be rendered, and shift the glyph. -->
        <!-- eslint-disable-next-line vue/multiline-html-element-content-newline -->
        <Text
          v-else-if="statusStyle.icon === 'info'"
          variant="custom"
          class="pb-0.5 text-xl leading-[0]"
          aria-hidden="true"
        >
          i
        </Text>
        <Icon
          v-else
          :icon="icon ?? statusStyle.icon"
          :class="styles.icon({ className: statusStyle.colorClassName })"
        />
      </div>
      <slot v-else name="status" />
    </template>

    <slot name="title">
      <Heading v-if="title != null" :level="2" :class="styles.title()" variant="subtitle">
        {{ title }}
      </Heading>
    </slot>

    <slot name="subtitle">
      <Text
        v-if="subtitle != null"
        elementType="p"
        :class="styles.subtitle()"
        balance
        variant="body"
      >
        {{ subtitle }}
      </Text>
    </slot>

    <div v-if="$slots.default" :class="styles.content()"><slot /></div>
  </section>
</template>
