// app/gui/src/cloud/credentials/SalesforceCredentialsForm.vue
<script setup lang="ts">
/**
 * @file The form creating a Salesforce credential: the Vue port of the React
 * `SalesforceCredentialsForm`. The recipe is `$/cloud/serviceCredentials/salesforce`; its scopes are
 * fixed, so the form asks only for a name. Remember to list a new form in `credentialInfos.ts`.
 */
import * as salesforce from '$/cloud/serviceCredentials/salesforce'
import type { CredentialRecipe } from '$/cloud/serviceCredentials/types'
import Form from '$/components/Form/Form.vue'
import Input from '$/components/Inputs/Input.vue'
import Text from '$/components/Text/Text.vue'
import { useConfig } from '$/providers/config'
import { useText } from '$/providers/text'
import CredentialsFormFooter from './CredentialsFormFooter.vue'
import { toastAndLogError } from './toastAndLog'

const { createCredentials } = defineProps<{
  createCredentials: (recipe: CredentialRecipe) => Promise<void>
}>()

const { getText } = useText()
const config = useConfig()

async function submit(values: Parameters<typeof salesforce.submitForm>[3]) {
  try {
    await salesforce.submitForm(
      config.remoteConfig?.ENSO_IDE_API_URL,
      config.remoteConfig?.ENSO_IDE_SALESFORCE_OAUTH_CLIENT_ID,
      createCredentials,
      values,
    )
  } catch (error) {
    toastAndLogError(error)
  }
}
</script>

<template>
  <Form
    method="dialog"
    :schema="salesforce.FORM_SCHEMA"
    :defaultValues="{
      ...salesforce.DEFAULT_FORM_VALUES,
      scopes: [...salesforce.DEFAULT_FORM_VALUES.scopes],
    }"
    class="w-full"
    @submit="submit"
  >
    <Input name="name" :label="getText('name')" />
    <Text variant="body" color="primary">{{ getText('salesforceCredentialScopesSummary') }}</Text>
    <CredentialsFormFooter :isCreating="true" :canCancel="false" :canReset="false" />
  </Form>
</template>

// app/gui/src/dashboard/data/serviceCredentials/SalesforceCredentialsForm.tsx
/**
 * @file
 * Dialog for a Salesforce credential.
 * Remember to ensure this component is added to `CREDENTIAL_INFOS` in `constants.ts`.
 */

import { Form } from '#/components/Form'
import { Input } from '#/components/Inputs/Input'
import { Text } from '#/components/Text'
import { useToastAndLog } from '#/hooks/toastAndLogHooks'
import * as salesforce from '$/cloud/serviceCredentials/salesforce'
import type { CredentialFormProps } from '$/cloud/serviceCredentials/types'
import { useRemoteConfig, useText } from '$/providers/react'
import { CredentialsFormFooter } from './CredentialsFormFooter'

/** Dialog for a Salesforce credential. */
export function SalesforceCredentialsForm(props: CredentialFormProps) {
  const { createCredentials } = props
  const { getText } = useText()
  const toastAndLog = useToastAndLog()
  const apiUrl = useRemoteConfig('ENSO_IDE_API_URL')
  const oauthId = useRemoteConfig('ENSO_IDE_SALESFORCE_OAUTH_CLIENT_ID')

  return (
    <Form
      method="dialog"
      schema={salesforce.FORM_SCHEMA}
      defaultValues={{
        ...salesforce.DEFAULT_FORM_VALUES,
        scopes: [...salesforce.DEFAULT_FORM_VALUES.scopes],
      }}
      className="w-full"
      onSubmit={async (values) => {
        try {
          await salesforce.submitForm(apiUrl, oauthId, createCredentials, values)
        } catch (error) {
          toastAndLog(null, error)
        }
      }}
    >
      {(form) => (
        <>
          <Input
            form={form}
            name="name"
            label={getText('name')}
            defaultValue={salesforce.DEFAULT_FORM_VALUES.name}
          />
          <Text variant="body" color="primary">
            {getText('salesforceCredentialScopesSummary')}
          </Text>
          <CredentialsFormFooter isCreating={true} canCancel={false} canReset={false} />
        </>
      )}
    </Form>
  )
}
