// app/gui/src/cloud/credentials/StravaCredentialsForm.vue
<script setup lang="ts">
/**
 * @file The form creating a Strava credential: the Vue port of the React `StravaCredentialsForm`.
 * The recipe is `$/cloud/serviceCredentials/strava`. Remember to list a new form in
 * `credentialInfos.ts`.
 */
import * as strava from '$/cloud/serviceCredentials/strava'
import type { CredentialRecipe } from '$/cloud/serviceCredentials/types'
import Checkbox from '$/components/Checkbox/Checkbox.vue'
import CheckboxGroup from '$/components/Checkbox/CheckboxGroup.vue'
import Form from '$/components/Form/Form.vue'
import Input from '$/components/Inputs/Input.vue'
import { useConfig } from '$/providers/config'
import { useText } from '$/providers/text'
import CredentialsFormFooter from './CredentialsFormFooter.vue'
import { toastAndLogError } from './toastAndLog'

const { createCredentials } = defineProps<{
  createCredentials: (recipe: CredentialRecipe) => Promise<void>
}>()

const { getText } = useText()
const config = useConfig()

async function submit(values: Parameters<typeof strava.submitForm>[3]) {
  try {
    await strava.submitForm(
      config.remoteConfig?.ENSO_IDE_API_URL,
      config.remoteConfig?.ENSO_IDE_STRAVA_OAUTH_CLIENT_ID,
      createCredentials,
      values,
    )
  } catch (error) {
    toastAndLogError(error)
  }
}
</script>

<template>
  <Form
    method="dialog"
    :schema="strava.FORM_SCHEMA"
    :defaultValues="{ name: '', scopes: ['read', 'activity:read'] }"
    class="w-full"
    @submit="submit"
  >
    <Input name="name" :label="getText('name')" />
    <CheckboxGroup name="scopes" :label="getText('stravaCredentialScopes')">
      <Checkbox value="read">{{ getText('stravaCredentialReadScope') }}</Checkbox>
      <Checkbox value="activity:read">{{ getText('stravaCredentialActivityReadScope') }}</Checkbox>
    </CheckboxGroup>
    <CredentialsFormFooter :isCreating="true" :canCancel="false" :canReset="false" />
  </Form>
</template>

// app/gui/src/dashboard/data/serviceCredentials/StravaCredentialsForm.tsx
/**
 * @file
 * Dialog for a Strava credential.
 * Remember to ensure this component is added to `CREDENTIAL_INFOS` in `constants.ts`.
 */

import { Checkbox } from '#/components/Checkbox'
import { Form } from '#/components/Form'
import { Input } from '#/components/Inputs/Input'
import { useToastAndLog } from '#/hooks/toastAndLogHooks'
import * as strava from '$/cloud/serviceCredentials/strava'
import type { CredentialFormProps } from '$/cloud/serviceCredentials/types'
import { useRemoteConfig, useText } from '$/providers/react'
import { CredentialsFormFooter } from './CredentialsFormFooter'

/** Dialog for a Strava credential. */
export function StravaCredentialsForm(props: CredentialFormProps) {
  const { createCredentials } = props
  const { getText } = useText()
  const toastAndLog = useToastAndLog()
  const apiUrl = useRemoteConfig('ENSO_IDE_API_URL')
  const oauthId = useRemoteConfig('ENSO_IDE_STRAVA_OAUTH_CLIENT_ID')

  return (
    <Form
      method="dialog"
      schema={strava.FORM_SCHEMA}
      defaultValues={{
        scopes: ['read', 'activity:read'],
      }}
      className="w-full"
      onSubmit={async (values) => {
        try {
          await strava.submitForm(apiUrl, oauthId, createCredentials, values)
        } catch (error) {
          toastAndLog(null, error)
        }
      }}
    >
      {(form) => (
        <>
          <Input form={form} name="name" label={getText('name')} />
          <Checkbox.Group form={form} name="scopes" label={getText('stravaCredentialScopes')}>
            <Checkbox value="read">{getText('stravaCredentialReadScope')}</Checkbox>
            <Checkbox value="activity:read">
              {getText('stravaCredentialActivityReadScope')}
            </Checkbox>
          </Checkbox.Group>
          <CredentialsFormFooter isCreating={true} canCancel={false} canReset={false} />
        </>
      )}
    </Form>
  )
}
