// app/gui/src/dashboard/components/ColorPicker.tsx
/** @file A color picker to select from a predetermined list of colors. */
import * as React from 'react'

import * as aria from '#/components/aria'
import FocusRing from '#/components/styled/FocusRing'
import RadioGroup from '#/components/styled/RadioGroup'

import * as backend from 'enso-common/src/services/Backend'

import * as tailwindMerge from '$/utils/style/tailwindMerge'

/** Props for a {@link ColorPickerItem}. */
export interface InternalColorPickerItemProps {
  readonly color: backend.LChColor
}

/** An input in a {@link ColorPicker}. */
function ColorPickerItem(props: InternalColorPickerItemProps) {
  const { color } = props
  const cssColor = backend.lChColorToCssColor(color)

  return (
    <FocusRing within>
      <aria.Radio
        value={cssColor}
        className="group flex h-6 w-6 cursor-pointer items-center justify-center rounded-full"
        style={{ backgroundColor: cssColor }}
      >
        <div className="hidden aspect-square h-3 w-3 rounded-full bg-selected-frame group-selected:block" />
      </aria.Radio>
    </FocusRing>
  )
}

/** Props for a {@link ColorPicker}. */
export interface ColorPickerProps extends Readonly<Omit<aria.RadioGroupProps, 'className'>> {
  readonly children?: React.ReactNode
  readonly className?: string
  readonly pickerClassName?: string
  readonly setColor: (color: backend.LChColor) => void
}

/** A color picker to select from a predetermined list of colors. */
export default React.forwardRef(ColorPicker)

/** A color picker to select from a predetermined list of colors. */
function ColorPicker(props: ColorPickerProps, ref: React.ForwardedRef<HTMLDivElement>) {
  const { className, pickerClassName = '', children, setColor, ...radioGroupProps } = props
  return (
    <RadioGroup
      ref={ref}
      {...radioGroupProps}
      orientation="horizontal"
      className={tailwindMerge.twMerge('flex flex-col', className)}
      onChange={(value) => {
        const color = backend.COLOR_STRING_TO_COLOR.get(value)
        if (color != null) {
          setColor(color)
        }
      }}
    >
      {children}
      <div
        className={tailwindMerge.twMerge(
          'flex items-center justify-between gap-colors',
          pickerClassName,
        )}
      >
        {backend.COLORS.map((currentColor, i) => (
          <ColorPickerItem key={i} color={currentColor} />
        ))}
      </div>
    </RadioGroup>
  )
}

// app/gui/src/cloud/labels/ColorPicker.vue
<script setup lang="ts">
/**
 * @file A choice of one of the label colours (`COLORS`). It is a `role="radiogroup"` of native
 * radios hidden in round swatches, so arrow keys move the choice as the browser does. The chosen
 * swatch shows a dot; a swatch focused from the keyboard shows the focus ring. `v-model` holds the
 * colour.
 */
import { twMerge } from '$/utils/style/tailwindMerge'
import {
  COLOR_STRING_TO_COLOR,
  COLORS,
  lChColorToCssColor,
  type LChColor,
} from 'enso-common/src/services/Backend'
import { computed, ref, useId } from 'vue'

const { class: className, pickerClass } = defineProps<{
  class?: string | undefined
  pickerClass?: string | undefined
}>()

const color = defineModel<LChColor | undefined>()

const name = useId()
const selected = computed(() => (color.value == null ? null : lChColorToCssColor(color.value)))
const focusVisible = ref<string | null>(null)

function onChange(event: Event) {
  const value = (event.target as HTMLInputElement).value
  const newColor = COLOR_STRING_TO_COLOR.get(value)
  if (newColor != null) color.value = newColor
}

function onFocus(event: FocusEvent, cssColor: string) {
  focusVisible.value = (event.target as HTMLElement).matches(':focus-visible') ? cssColor : null
}
</script>

<template>
  <div role="radiogroup" aria-orientation="horizontal" :class="twMerge('flex flex-col', className)">
    <slot />
    <div :class="twMerge('flex items-center justify-between gap-colors', pickerClass)">
      <label
        v-for="(currentColor, i) in COLORS"
        :key="i"
        :class="[
          'group flex h-6 w-6 cursor-pointer items-center justify-center rounded-full',
          focusVisible === lChColorToCssColor(currentColor) && 'focus-ring',
        ]"
        :style="{ backgroundColor: lChColorToCssColor(currentColor) }"
        :data-selected="selected === lChColorToCssColor(currentColor) || undefined"
      >
        <input
          type="radio"
          class="sr-only"
          :name="name"
          :value="lChColorToCssColor(currentColor)"
          :checked="selected === lChColorToCssColor(currentColor)"
          @change="onChange"
          @focus="onFocus($event, lChColorToCssColor(currentColor))"
          @blur="focusVisible = null"
        />
        <div
          class="hidden aspect-square h-3 w-3 rounded-full bg-selected-frame group-data-[selected]:block"
        />
      </label>
    </div>
  </div>
</template>
