// app/gui/src/components/Inputs/Selector.vue
<script setup lang="ts" generic="T">
/**
 * @file A horizontal selector of one item, bound to a form field: the Vue counterpart of the React
 * `Selector`, styled by the same `SELECTOR_STYLES` and `SELECTOR_OPTION_STYLES`. The options are
 * native radios in a `role="radiogroup"`, so arrow keys move the selection. The field holds the
 * item itself; `toLabel` names each (React's `children`, default `String`).
 */
import Field from '$/components/Form/Field.vue'
import type { AnyFormInstance } from '$/components/Form/types'
import { useField } from '$/components/Form/useField'
import { valuesEqual } from '$/components/Form/values'
import type { FIELD_STYLES } from '$/components/Form/variants'
import { SELECTOR_STYLES } from '$/components/Inputs/variants'
import type { ExtractFunction, VariantProps } from '$/utils/style/tailwindVariants'
import { computed, useAttrs } from 'vue'
import SelectorOption from './SelectorOption.vue'

type SelectorVariants = VariantProps<typeof SELECTOR_STYLES>

const props = withDefaults(
  defineProps<{
    name: string
    form?: AnyFormInstance | undefined
    items: readonly T[]
    /** The text of each item. React's `children`. */
    toLabel?: ((item: T) => string) | undefined
    columns?: number | undefined
    defaultValue?: T | undefined
    label?: string | undefined
    contextualHelp?: string | undefined
    isDisabled?: boolean | undefined
    isRequired?: boolean | undefined
    isInvalid?: boolean | undefined
    readOnly?: boolean | undefined
    size?: SelectorVariants['size']
    rounded?: SelectorVariants['rounded']
    variant?: SelectorVariants['variant']
    fieldVariants?: ExtractFunction<typeof FIELD_STYLES> | undefined
    testId?: string | undefined
    class?: string | undefined
  }>(),
  { toLabel: String, readOnly: undefined },
)

const labelOf = (item: T) => (props.toLabel ?? String)(item)

const field = useField<T | undefined>({
  name: () => props.name,
  form: () => props.form,
  defaultValue: props.defaultValue,
  isDisabled: () => props.isDisabled,
  isRequired: () => props.isRequired,
})

const disabled = computed(() => field.isDisabled.value || field.isSubmitting.value)
const classes = computed(() =>
  SELECTOR_STYLES({
    size: props.size,
    rounded: props.rounded,
    readOnly: props.readOnly,
    disabled: disabled.value,
    variant: props.variant,
  }),
)

const attrs = useAttrs()
const ariaLabel = computed(() => (attrs['aria-label'] as string | undefined) ?? props.label ?? '')

function select(item: T) {
  if (props.readOnly === true) return
  field.onChange(item)
}
</script>

<template>
  <Field
    :name="name"
    :form="field.form"
    :label="label"
    :contextualHelp="contextualHelp"
    :isRequired="field.isRequired.value"
    :fullWidth="true"
    :variants="fieldVariants"
    :ids="field.ids"
    :testId="testId"
    :class="props.class"
  >
    <div :class="classes.base()">
      <div
        role="radiogroup"
        :class="classes.radioGroup()"
        :style="{ gridTemplateColumns: `repeat(${columns ?? items.length}, 1fr)` }"
        :aria-label="ariaLabel"
        :aria-invalid="isInvalid || field.isInvalid.value || undefined"
        :aria-required="field.isRequired.value || undefined"
        :aria-disabled="disabled || undefined"
        :aria-describedby="field.error.value != null ? field.ids.errorId : undefined"
      >
        <SelectorOption
          v-for="(item, i) in items"
          :key="i"
          :name="name"
          :value="String(i)"
          :label="labelOf(item)"
          :isSelected="valuesEqual(item, field.value.value)"
          :isDisabled="disabled"
          :size="size"
          :rounded="rounded"
          :variant="variant"
          @select="select(item)"
          @blur="field.onBlur"
        />
      </div>
    </div>
  </Field>
</template>

// app/gui/src/dashboard/components/Inputs/Selector/Selector.tsx
/** @file A horizontal selector. */
import { mergeProps, type RadioGroupProps } from '#/components/aria'
import {
  Form,
  type FieldComponentProps,
  type FieldPath,
  type FieldProps,
  type FieldStateProps,
  type FieldVariantProps,
  type TSchema,
} from '#/components/Form'
import RadioGroup from '#/components/styled/RadioGroup'
import { mergeRefs } from '#/utilities/mergeRefs'
import { SELECTOR_STYLES } from '$/components/Inputs/selectorVariants'
import type { VariantProps } from '$/utils/style/tailwindVariants'
import * as React from 'react'
import { SelectorOption } from './SelectorOption'

/** * Props for the Selector component. */
export interface SelectorProps<Schema extends TSchema, TFieldName extends FieldPath<Schema, T>, T>
  extends
    FieldStateProps<
      Omit<RadioGroupProps, 'children' | 'value'> & { value: T },
      Schema,
      TFieldName,
      T
    >,
    FieldProps,
    Omit<VariantProps<typeof SELECTOR_STYLES>, 'disabled' | 'invalid' | 'variants'>,
    FieldVariantProps {
  readonly items: readonly T[]
  readonly children?: (item: T) => string
  readonly columns?: number
  readonly className?: string
  readonly style?: React.CSSProperties
  readonly inputRef?: React.Ref<HTMLDivElement>
  readonly placeholder?: string
}

/** A horizontal selector. */
export const Selector = React.forwardRef(function SelectorImpl<
  Schema extends TSchema,
  TFieldName extends FieldPath<Schema, T>,
  T,
>(props: SelectorProps<Schema, TFieldName, T>, ref: React.ForwardedRef<HTMLDivElement>) {
  const {
    name,
    items,
    children = String,
    isDisabled = false,
    columns,
    form,
    inputRef,
    label,
    size,
    rounded,
    variant,
    isRequired = false,
    isInvalid = false,
    fieldVariants,
    defaultValue,
    contextualHelp,
    ...inputProps
  } = props

  const privateInputRef = React.useRef<HTMLDivElement>(null)

  const formInstance = Form.useFormContext(form)

  const classes = SELECTOR_STYLES({
    size,
    rounded,
    readOnly: inputProps.readOnly,
    disabled: isDisabled || formInstance.formState.isSubmitting,
    variant,
  })

  return (
    <Form.Controller
      control={formInstance.control}
      name={name}
      render={(renderProps) => {
        const { value } = renderProps.field
        return (
          <Form.Field
            {...mergeProps<FieldComponentProps<Schema>>()(inputProps, renderProps.field, {
              fullWidth: true,
              variants: fieldVariants,
              form: formInstance,
              label,
              isRequired,
              contextualHelp,
            })}
            name={props.name}
            ref={ref}
          >
            <div
              className={classes.base()}
              onClick={() => privateInputRef.current?.focus({ preventScroll: true })}
            >
              <RadioGroup
                {...mergeProps<RadioGroupProps>()(
                  {
                    className: classes.radioGroup(),
                    name,
                    isRequired,
                    isDisabled,
                    isInvalid,
                    style: { gridTemplateColumns: `repeat(${columns ?? items.length}, 1fr)` },
                    ...(defaultValue != null ? { defaultValue } : {}),
                  },
                  inputProps,
                  renderProps.field,
                )}
                ref={mergeRefs(inputRef, privateInputRef, renderProps.field.ref)}
                // eslint-disable-next-line no-restricted-syntax
                aria-label={props['aria-label'] ?? (typeof label === 'string' ? label : '')}
                value={String(items.indexOf(value))}
                onChange={(newValue) => {
                  renderProps.field.onChange(items[Number(newValue)])
                }}
              >
                {items.map((item, i) => (
                  <SelectorOption
                    key={i}
                    value={String(i)}
                    label={children(item)}
                    rounded={rounded}
                    size={size}
                    variant={variant}
                    isSelected={item === value}
                  />
                ))}
              </RadioGroup>
            </div>
          </Form.Field>
        )
      }}
    />
  )
})
