// app/gui/src/dashboard/pages/dashboard/Drive/DriveBar/DriveBarToolbar.vue
<script setup lang="ts">
/**
 * @file The drive's toolbar: the buttons creating assets (a project, a folder, a secret, a
 * credential, a datalink), uploading and downloading, the count of cut or copied assets, and the
 * search bar. In the trash, a button emptying it; in Recent, only the count and the search bar. The
 * Vue port of React's `DriveBarToolbar`.
 *
 * The secret dialog is Vue's; the credential and datalink dialogs are still React's (#198), opened
 * over the page as their `Dialog.Trigger` did. Each of those buttons keeps the `aria-expanded`
 * react-aria gave it.
 */
import AssetSearchBar from '#/layouts/AssetSearchBar.vue'
import {
  useExportArchive,
  useMutationCallback,
  useNewFolder,
  useNewProject,
  useUploadFiles,
} from '#/layouts/Drive/driveActions'
import { useDriveView } from '#/layouts/Drive/driveView'
import CreateCredentialModal from '$/cloud/credentials/CreateCredentialModal.vue'
import UpsertSecretModal from '$/cloud/credentials/UpsertSecretModal.vue'
import UpsertDatalinkModal from '$/cloud/datalinks/UpsertDatalinkModal.vue'
import ConfirmDeleteModal from '$/components/AlertDialog/ConfirmDeleteModal.vue'
import Button from '$/components/Button/Button.vue'
import ButtonGroup from '$/components/Button/ButtonGroup.vue'
import ErrorBoundary from '$/components/ErrorBoundary/ErrorBoundary.vue'
import { useVisualTooltip } from '$/components/Tooltip/useVisualTooltip'
import VisualTooltipPopup from '$/components/Tooltip/VisualTooltipPopup.vue'
import { canTransferBetweenCategories, useCategories } from '$/providers/category'
import { useDriveStore } from '$/providers/driveStore'
import { useModals } from '$/providers/modals'
import { useIsOnline } from '$/providers/online'
import { useText } from '$/providers/text'
import type AssetQuery from '$/utils/AssetQuery'
import { backendMutationOptions } from '$/utils/backendQuery'
import { deleteAssetsMutationOptions, downloadAssetsMutationOptions } from '$/utils/driveMutations'
import { getAllTrashedItems, listDirectoryQueryOptions } from '$/utils/driveQueries'
import { useQuery, useQueryClient } from '@tanstack/vue-query'
import {
  BackendType,
  isDirectoryId,
  isProjectId,
  type CredentialConfig,
} from 'enso-common/src/services/Backend'
import { readUserSelectedFile } from 'enso-common/src/utilities/file'
import { computed, ref, shallowRef } from 'vue'
import PasteStatus from './PasteStatus.vue'

const { query, setQuery } = defineProps<{
  query: AssetQuery
  setQuery: (query: AssetQuery) => void
}>()

const { getText } = useText()
const categories = useCategories()
const driveStore = useDriveStore()
const driveView = useDriveView()
const modals = useModals()
const isOnline = useIsOnline()
const queryClient = useQueryClient()

const category = computed(() => driveView.location.category)
const backend = computed(() => driveView.location.backend)
const currentDirectoryId = computed(() => driveView.location.currentDirectoryId)
const isCloud = computed(() => backend.value.type === BackendType.remote)
const shouldBeDisabled = computed(() => isCloud.value && !isOnline.value)
const error = computed(() => (shouldBeDisabled.value ? getText('cannotCreateAssetsHere') : null))

const createAssetButtons = ref<InstanceType<typeof ButtonGroup>>()
const createAssetButtonsElement = computed(
  () => (createAssetButtons.value?.$el as HTMLElement | undefined) ?? null,
)
const {
  isOpen: isCreateAssetsTooltipOpen,
  onTooltipEnter,
  onTooltipLeave,
} = useVisualTooltip(createAssetButtonsElement, { isDisabled: () => error.value == null })

const effectivePasteData = computed(() => {
  const pasteData = driveStore.pasteData
  return (
      pasteData?.data.backendType === backend.value.type &&
        canTransferBetweenCategories(pasteData.data.category, category.value)
    ) ?
      pasteData
    : null
})

const downloadAssets = useMutationCallback(() => downloadAssetsMutationOptions(backend.value))
const newFolder = useNewFolder(backend, () => category.value.type, driveStore)
const uploadFiles = useUploadFiles(backend, () => category.value.type, driveStore)
const newSecret = useMutationCallback(() => backendMutationOptions(backend.value, 'createSecret'))
const newCredential = useMutationCallback(() =>
  backendMutationOptions(backend.value, 'createCredential'),
)
const newDatalink = useMutationCallback(() =>
  backendMutationOptions(backend.value, 'createDatalink'),
)
const newProjectRaw = useNewProject(backend, () => category.value.type)
const exportArchive = useExportArchive(backend, driveStore)
const newProject = useMutationCallback({
  mutationKey: ['newProject'],
  mutationFn: async () => await newProjectRaw({}, currentDirectoryId.value),
})

/** Keys of the dialogs these buttons opened on the modal stack, for their `aria-expanded`. */
const openedModals = shallowRef<Partial<Record<'secret' | 'credential' | 'datalink', number>>>({})
function isOpened(which: 'secret' | 'credential' | 'datalink') {
  const key = openedModals.value[which]
  return key != null && modals.stack.value.some((entry) => entry.key === key)
}

function openNewSecret() {
  const { key } = modals.open(UpsertSecretModal, {
    onCreate: async (name: string, value: string) => {
      await newSecret([{ name, value, parentDirectoryId: currentDirectoryId.value }])
    },
  })
  openedModals.value = { ...openedModals.value, secret: key }
}

function openNewCredential() {
  const { key } = modals.open(CreateCredentialModal, {
    doCreate: (name: string, value: CredentialConfig) =>
      newCredential([{ name, value, parentDirectoryId: currentDirectoryId.value }]),
  })
  openedModals.value = { ...openedModals.value, credential: key }
}

function openNewDatalink() {
  const { key } = modals.open(UpsertDatalinkModal, {
    doCreate: async (name: string, value: unknown) => {
      await newDatalink([
        { name, value, parentDirectoryId: currentDirectoryId.value, datalinkId: null },
      ])
    },
  })
  openedModals.value = { ...openedModals.value, datalink: key }
}

async function uploadFilesFromDialog() {
  const files = await readUserSelectedFile({ multiple: true })
  await uploadFiles(Array.from(files), currentDirectoryId.value)
}

function downloadFiles() {
  modals.closeAll()
  const { selectedAssets } = driveStore.state
  const sole = selectedAssets[0]
  if (
    selectedAssets.length === 1 &&
    sole != null &&
    (isCloud.value ? !isDirectoryId(sole.id) : isProjectId(sole.id))
  ) {
    void downloadAssets({ ids: selectedAssets, targetDirectoryId: null })
  } else {
    void exportArchive()
  }
}

// === The trash ===

const trashCategory = { type: 'trash' } as const
const trashListing = useQuery(
  computed(() => ({
    ...listDirectoryQueryOptions({
      backend: backend.value,
      category: trashCategory,
      parentId: categories.categoryDirectoryId(trashCategory),
      refetchInterval: null,
      labels: null,
      sortDirection: null,
      sortExpression: null,
    }),
    enabled: category.value.type === 'trash',
  })),
)
const isTrashEmpty = computed(() => (trashListing.data.value?.assets.length ?? 0) === 0)
const deleteAssets = useMutationCallback(() => deleteAssetsMutationOptions(backend.value))
const clearTrashKey = ref<number | null>(null)
const isClearTrashOpen = computed(
  () =>
    clearTrashKey.value != null &&
    modals.stack.value.some((entry) => entry.key === clearTrashKey.value),
)

function openClearTrash() {
  const { key } = modals.open(ConfirmDeleteModal, {
    actionText: getText('allTrashedItemsForever'),
    onConfirm: async () => {
      const allTrashedItems = await getAllTrashedItems(
        queryClient,
        backend.value,
        categories.categoryDirectoryId(trashCategory),
      )
      await deleteAssets([allTrashedItems.map((item) => item.id), true])
    },
  })
  clearTrashKey.value = key
}
</script>

<template>
  <ButtonGroup v-if="category.type === 'recent'" class="grow-0">
    <PasteStatus v-if="effectivePasteData" :pasteData="effectivePasteData" />
    <AssetSearchBar :backend="backend" :isCloud="isCloud" :query="query" :setQuery="setQuery" />
  </ButtonGroup>
  <ErrorBoundary v-else-if="category.type === 'trash'">
    <ButtonGroup class="grow-0" :buttonVariants="{ isDisabled: shouldBeDisabled }">
      <Button
        size="medium"
        variant="outline"
        :isDisabled="isTrashEmpty"
        :aria-expanded="isClearTrashOpen"
        @press="openClearTrash"
      >
        {{ getText('clearTrash') }}
      </Button>
      <PasteStatus v-if="effectivePasteData" :pasteData="effectivePasteData" />
      <AssetSearchBar :backend="backend" :isCloud="isCloud" :query="query" :setQuery="setQuery" />
    </ButtonGroup>
  </ErrorBoundary>
  <div v-else class="flex w-full flex-1 shrink-0 gap-2">
    <ButtonGroup
      ref="createAssetButtons"
      class="grow-0"
      :buttonVariants="{ isDisabled: shouldBeDisabled }"
    >
      <Button
        variant="accent"
        icon="add"
        loaderPosition="icon"
        @press="() => newProject(undefined)"
      >
        {{ getText('newEmptyProject') }}
      </Button>
      <div
        class="flex h-row items-center gap-4 rounded-full border-0.5 border-primary/20 px-[11px]"
      >
        <Button
          variant="icon"
          size="medium"
          icon="folder_add"
          :aria-label="getText('newFolder')"
          @press="() => newFolder(currentDirectoryId)"
        />
        <Button
          :isDisabled="!isCloud"
          variant="icon"
          size="medium"
          icon="key_add"
          :aria-label="isCloud ? getText('newSecret') : getText('newSecret.cloudOnly')"
          :aria-expanded="isOpened('secret')"
          @press="openNewSecret"
        />
        <Button
          :isDisabled="!isCloud"
          variant="icon"
          size="medium"
          icon="credential_add"
          :aria-expanded="isOpened('credential')"
          :aria-label="isCloud ? getText('newCredential') : getText('newCredential.cloudOnly')"
          @press="openNewCredential"
        />
        <Button
          :isDisabled="!isCloud"
          variant="icon"
          size="medium"
          icon="connector_add"
          :aria-expanded="isOpened('datalink')"
          :aria-label="isCloud ? getText('newDatalink') : getText('newDatalink.cloudOnly')"
          @press="openNewDatalink"
        />
      </div>
      <div
        class="flex h-row items-center gap-4 rounded-full border-0.5 border-primary/20 px-[11px]"
      >
        <Button
          variant="icon"
          size="medium"
          icon="data_upload"
          :aria-label="getText('uploadFiles')"
          @press="uploadFilesFromDialog"
        />
        <Button
          :isDisabled="!driveStore.canDownload"
          variant="icon"
          size="medium"
          icon="data_download"
          :aria-label="getText('downloadFiles')"
          @press="downloadFiles"
        />
      </div>
      <VisualTooltipPopup
        v-if="error != null"
        :target="createAssetButtonsElement"
        :open="isCreateAssetsTooltipOpen"
        placement="top"
        @pointerenter="onTooltipEnter"
        @pointerleave="onTooltipLeave"
      >
        {{ error }}
      </VisualTooltipPopup>
    </ButtonGroup>
    <PasteStatus v-if="effectivePasteData" :pasteData="effectivePasteData" />
    <AssetSearchBar :backend="backend" :isCloud="isCloud" :query="query" :setQuery="setQuery" />
  </div>
</template>

// app/gui/src/dashboard/pages/dashboard/Drive/DriveBar/DriveBarToolbar.tsx
/**
 * @file Header menubar for the directory listing, containing information about
 * the current directory and some configuration options.
 */
import { Button } from '#/components/Button'
import { Dialog } from '#/components/Dialog'
import { ErrorBoundary, InlineErrorDisplay } from '#/components/ErrorBoundary'
import { IconDisplay } from '#/components/IconDisplay'
import { useVisualTooltip, VisualTooltip } from '#/components/VisualTooltip'
import { useNewFolder, useNewProject } from '#/hooks/backendHooks'
import { useUploadFiles } from '#/hooks/backendUploadFilesHooks'
import { useEventCallback } from '#/hooks/eventCallbackHooks'
import { useOffline } from '#/hooks/offlineHooks'
import { useVueModalTrigger } from '#/hooks/vueModalHooks'
import { AssetSearchBar } from '#/layouts/AssetSearchBar'
import { useDirectoryIds } from '#/layouts/Drive/directoryIdsHooks'
import { CreateCredentialModal } from '#/modals/CreateCredentialModal'
import UpsertDatalinkModal from '#/modals/UpsertDatalinkModal'
import { useExportArchive } from '#/pages/useExportArchive'
import { useCanDownload, useDriveStore, usePasteData } from '#/providers/DriveProvider'
import { unsetModal } from '#/providers/ModalProvider'
import { useMutationCallback } from '#/utilities/tanstackQuery'
import UpsertSecretModal from '$/cloud/credentials/UpsertSecretModal.vue'
import ConfirmDeleteModal from '$/components/AlertDialog/ConfirmDeleteModal.vue'
import { canTransferBetweenCategories } from '$/providers/category'
import { useCategories, useText } from '$/providers/react'
import { useDriveCurrentBackend, useDriveCurrentCategory } from '$/providers/react/container'
import type AssetQuery from '$/utils/AssetQuery'
import { backendMutationOptions } from '$/utils/backendQuery'
import { deleteAssetsMutationOptions, downloadAssetsMutationOptions } from '$/utils/driveMutations'
import { getAllTrashedItems, listDirectoryQueryOptions } from '$/utils/driveQueries'
import { useQueryClient, useSuspenseQuery } from '@tanstack/react-query'
import type { Backend } from 'enso-common/src/services/Backend'
import {
  BackendType,
  isDirectoryId,
  isProjectId,
  type CredentialConfig,
} from 'enso-common/src/services/Backend'
import { readUserSelectedFile } from 'enso-common/src/utilities/file'
import type { PropsWithChildren } from 'react'
import * as React from 'react'

/** Props for a {@link DriveBar}. */
export interface DriveBarToolbarProps {
  readonly query: AssetQuery
  readonly setQuery: React.Dispatch<React.SetStateAction<AssetQuery>>
}

/**
 * Displays the current directory path and permissions, upload and download buttons,
 * and a column display mode switcher.
 */
export function DriveBarToolbar(props: DriveBarToolbarProps) {
  const { query, setQuery } = props

  const [category] = useDriveCurrentCategory()
  const backend = useDriveCurrentBackend()
  const { getText } = useText()
  const driveStore = useDriveStore()
  const createAssetButtonsRef = React.useRef<HTMLDivElement>(null)
  const isCloud = backend.type === BackendType.remote
  const { isOffline } = useOffline()
  const canDownload = useCanDownload()

  const { currentDirectoryId } = useDirectoryIds({ category })

  const shouldBeDisabled = isCloud && isOffline

  const error = shouldBeDisabled ? getText('cannotCreateAssetsHere') : null

  const createAssetsVisualTooltip = useVisualTooltip({
    isDisabled: error == null,
    children: error,
    targetRef: createAssetButtonsRef,
    overlayPositionProps: { placement: 'top' },
  })

  const pasteData = usePasteData()
  const effectivePasteData =
    (
      pasteData?.data.backendType === backend.type &&
      canTransferBetweenCategories(pasteData.data.category, category)
    ) ?
      pasteData
    : null

  const downloadAssetsMutation = useMutationCallback(downloadAssetsMutationOptions(backend))
  const newFolder = useNewFolder(backend, category.type)
  const uploadFilesRaw = useUploadFiles(backend, category.type)
  const uploadFiles = useEventCallback(async (files: readonly File[]) => {
    await uploadFilesRaw(files, currentDirectoryId)
  })
  const newSecret = useMutationCallback(backendMutationOptions(backend, 'createSecret'))
  const newCredential = useMutationCallback(backendMutationOptions(backend, 'createCredential'))
  const newDatalink = useMutationCallback(backendMutationOptions(backend, 'createDatalink'))
  const newProjectRaw = useNewProject(backend, category.type)
  const exportArchive = useExportArchive({ backend })

  const newProjectMutation = useMutationCallback({
    mutationKey: ['newProject'],
    mutationFn: async () => await newProjectRaw({}, currentDirectoryId),
  })

  const newProject = useEventCallback(async () => {
    await newProjectMutation()
  })

  const newFolderCallback = useEventCallback(async () => {
    await newFolder(currentDirectoryId)
  })

  const newCredentialCallback = useEventCallback(async (name: string, value: CredentialConfig) => {
    return await newCredential([{ name, value, parentDirectoryId: currentDirectoryId }])
  })

  const newSecretTrigger = useVueModalTrigger()
  const newSecretCallback = useEventCallback(async (name: string, value: string) => {
    await newSecret([{ name, value, parentDirectoryId: currentDirectoryId }])
  })

  const newDatalinkCallback = useEventCallback(async (name: string, value: unknown) => {
    await newDatalink([
      {
        name,
        value,
        parentDirectoryId: currentDirectoryId,
        datalinkId: null,
      },
    ])
  })

  const uploadFilesCallback = useEventCallback(async () => {
    const files = await readUserSelectedFile({ multiple: true })
    await uploadFiles(Array.from(files))
  })

  const downloadFilesCallback = useEventCallback(() => {
    unsetModal()
    const { selectedAssets } = driveStore.state
    if (
      selectedAssets.length === 1 &&
      selectedAssets[0] != null &&
      (isCloud ? !isDirectoryId(selectedAssets[0].id) : isProjectId(selectedAssets[0].id))
    ) {
      void downloadAssetsMutation({
        ids: selectedAssets,
        targetDirectoryId: null,
      })
    } else {
      void exportArchive()
    }
  })

  const searchBar = (
    <AssetSearchBar backend={backend} isCloud={isCloud} query={query} setQuery={setQuery} />
  )

  const pasteDataStatus = effectivePasteData && (
    <div className="flex items-center">
      <VisualTooltip
        tooltip={
          effectivePasteData.type === 'copy' ?
            getText('xItemsCopied', effectivePasteData.data.assets.length)
          : getText('xItemsCut', effectivePasteData.data.assets.length)
        }
        tooltipPlacement="top"
      >
        <IconDisplay icon={effectivePasteData.type === 'copy' ? 'copy' : 'scissors'}>
          {String(effectivePasteData.data.assets.length)}
        </IconDisplay>
      </VisualTooltip>
    </div>
  )

  switch (category.type) {
    case 'recent': {
      return (
        <Button.Group className="grow-0">
          {pasteDataStatus}
          {searchBar}
        </Button.Group>
      )
    }
    case 'trash': {
      return (
        <ErrorBoundary FallbackComponent={InlineErrorDisplay}>
          <TrashFolderToolbar shouldBeDisabled={shouldBeDisabled} backend={backend}>
            {pasteDataStatus}
            {searchBar}
          </TrashFolderToolbar>
        </ErrorBoundary>
      )
    }
    case 'cloud':
    case 'local':
    case 'team':
    case 'localDirectory': {
      return (
        <div className="flex w-full flex-1 shrink-0 gap-2">
          <Button.Group
            ref={createAssetButtonsRef}
            className="grow-0"
            buttonVariants={{ isDisabled: shouldBeDisabled }}
            {...createAssetsVisualTooltip.targetProps}
          >
            <Button variant="accent" icon="add" loaderPosition="icon" onPress={newProject}>
              {getText('newEmptyProject')}
            </Button>

            <div className="flex h-row items-center gap-4 rounded-full border-0.5 border-primary/20 px-[11px]">
              <Button
                variant="icon"
                size="medium"
                icon="folder_add"
                aria-label={getText('newFolder')}
                onPress={newFolderCallback}
              />
              <Button
                isDisabled={!isCloud}
                variant="icon"
                size="medium"
                icon="key_add"
                aria-label={isCloud ? getText('newSecret') : getText('newSecret.cloudOnly')}
                {...newSecretTrigger.triggerProps}
                onPress={() => {
                  newSecretTrigger.open(UpsertSecretModal, { onCreate: newSecretCallback })
                }}
              />
              <Dialog.Trigger>
                <Button
                  isDisabled={!isCloud}
                  variant="icon"
                  size="medium"
                  icon="credential_add"
                  aria-label={
                    isCloud ? getText('newCredential') : getText('newCredential.cloudOnly')
                  }
                />
                <CreateCredentialModal doCreate={newCredentialCallback} />
              </Dialog.Trigger>
              <Dialog.Trigger>
                <Button
                  isDisabled={!isCloud}
                  variant="icon"
                  size="medium"
                  icon="connector_add"
                  aria-label={isCloud ? getText('newDatalink') : getText('newDatalink.cloudOnly')}
                />
                <UpsertDatalinkModal doCreate={newDatalinkCallback} />
              </Dialog.Trigger>
            </div>

            <div className="flex h-row items-center gap-4 rounded-full border-0.5 border-primary/20 px-[11px]">
              <Button
                variant="icon"
                size="medium"
                icon="data_upload"
                aria-label={getText('uploadFiles')}
                onPress={uploadFilesCallback}
              />
              <Button
                isDisabled={!canDownload}
                variant="icon"
                size="medium"
                icon="data_download"
                aria-label={getText('downloadFiles')}
                onPress={downloadFilesCallback}
              />
            </div>
            {createAssetsVisualTooltip.tooltip}
          </Button.Group>
          {pasteDataStatus}
          {searchBar}
        </div>
      )
    }
  }
}

/**
 * Props for a {@link TrashFolderToolbar}.
 */
interface TrashFolderToolbarProps extends PropsWithChildren {
  readonly shouldBeDisabled: boolean
  readonly backend: Backend
}

/**
 * A toolbar for the trash folder.
 */
function TrashFolderToolbar(props: TrashFolderToolbarProps) {
  const { shouldBeDisabled, backend, children } = props
  const { getText } = useText()
  const { categoryDirectoryId } = useCategories()
  const category = { type: 'trash' as const }

  const rootDirectoryQueryOptions = listDirectoryQueryOptions({
    backend,
    category,
    parentId: categoryDirectoryId(category),
    refetchInterval: null,
    labels: null,
    sortDirection: null,
    sortExpression: null,
  })

  const { data: isEmpty } = useSuspenseQuery({
    ...rootDirectoryQueryOptions,
    select: (data) => data.assets.length === 0,
  })

  const queryClient = useQueryClient()
  const clearTrashTrigger = useVueModalTrigger()
  const deleteAssetsMutation = useMutationCallback(deleteAssetsMutationOptions(backend))

  const clearTrash = useEventCallback(async () => {
    const allTrashedItems = await getAllTrashedItems(
      queryClient,
      backend,
      categoryDirectoryId(category),
    )
    await deleteAssetsMutation([allTrashedItems.map((item) => item.id), true])
  })

  return (
    <Button.Group className="grow-0" buttonVariants={{ isDisabled: shouldBeDisabled }}>
      <Button
        size="medium"
        variant="outline"
        isDisabled={isEmpty}
        {...clearTrashTrigger.triggerProps}
        onPress={() => {
          clearTrashTrigger.open(ConfirmDeleteModal, {
            actionText: getText('allTrashedItemsForever'),
            onConfirm: async () => {
              await clearTrash()
            },
          })
        }}
      >
        {getText('clearTrash')}
      </Button>

      {children}
    </Button.Group>
  )
}
