// app/gui/src/components/Inputs/Dropdown.vue
<script setup lang="ts" generic="T">
/**
 * @file A styled dropdown that expands in place: the Vue counterpart of the React `Dropdown`,
 * styled by the same `DROPDOWN_STYLES`. The options are a Reka `Listbox` (`role="listbox"`), so
 * the keyboard works as react-aria's did: Tab focuses the list and expands it, arrow keys and
 * typeahead move between options, Enter or Space selects. A mouse press on the dropdown toggles it;
 * a press elsewhere closes it.
 *
 * Each item is rendered by the default slot (`{ item }`), in the list and as the current value.
 * Single selection is `v-model:selectedIndex`; with `multiple` it is `v-model:selectedIndices`, and
 * the `multiple` slot (`{ items }`) shows the selection (React's `renderMultiple`).
 * `FormDropdown.vue` binds one to a form field.
 */
import Icon from '$/components/Icon/Icon.vue'
import { DROPDOWN_OPTION_VUE_STATES, DROPDOWN_STYLES } from '$/components/Inputs/variants'
import type { VariantProps } from '$/utils/style/tailwindVariants'
import { useEventListener } from '@vueuse/core'
import { ListboxContent, ListboxItem, ListboxRoot } from 'reka-ui'
import { computed, ref, watch } from 'vue'

type DropdownVariants = VariantProps<typeof DROPDOWN_STYLES>

const {
  items,
  multiple = false,
  readOnly = false,
  rounded,
  size,
  ariaLabel = 'Dropdown',
  class: className,
} = defineProps<{
  items: readonly T[]
  multiple?: boolean | undefined
  readOnly?: boolean | undefined
  rounded?: DropdownVariants['rounded']
  size?: DropdownVariants['size']
  /** The list's accessible name. */
  ariaLabel?: string | undefined
  class?: string | undefined
}>()

const selectedIndex = defineModel<number | null>('selectedIndex', { default: null })
const selectedIndices = defineModel<readonly number[]>('selectedIndices', { default: () => [] })

defineSlots<{
  default: (props: { item: T }) => unknown
  multiple?: (props: { items: readonly T[] }) => unknown
}>()

const root = ref<HTMLElement>()
const isFocusWithin = ref(false)
const isMouseFocused = ref(false)
/** Whether the last interaction was the keyboard: react-aria's `useFocusVisible`. */
const isKeyboardModality = ref(false)

useEventListener(document, 'keydown', () => (isKeyboardModality.value = true), { capture: true })
useEventListener(
  document,
  'mousedown',
  (event) => {
    isKeyboardModality.value = false
    if (!(event.target instanceof Node) || !root.value?.contains(event.target)) {
      isMouseFocused.value = false
    }
  },
  { capture: true },
)

const isFocused = computed(() =>
  isKeyboardModality.value ? isFocusWithin.value : isMouseFocused.value,
)

const currentIndices = computed(() =>
  multiple ? selectedIndices.value
  : selectedIndex.value != null ? [selectedIndex.value]
  : [],
)
const selectedItems = computed(() =>
  currentIndices.value.flatMap((i) => (items[i] !== undefined ? [items[i] as T] : [])),
)
const displayedItem = computed(() =>
  selectedIndex.value == null ? undefined : items[selectedIndex.value],
)

const styles = computed(() =>
  DROPDOWN_STYLES({
    isFocused: isFocused.value,
    isReadOnly: readOnly,
    multiple,
    rounded,
    size,
  }),
)

const listModel = computed<number | number[] | null>({
  get: () => (multiple ? [...selectedIndices.value] : selectedIndex.value),
  set: (value) => {
    if (readOnly) return
    if (multiple) {
      selectedIndices.value = Array.isArray(value) ? value : []
    } else if (typeof value === 'number') {
      selectedIndex.value = value
      close()
    }
  },
})

function close() {
  isMouseFocused.value = false
  isKeyboardModality.value = false
  const active = document.activeElement
  if (active instanceof HTMLElement && root.value?.contains(active)) active.blur()
}

let wasFocused = false
watch(isFocused, (focused) => requestAnimationFrame(() => (wasFocused = focused)))

function onMouseDown(event: MouseEvent) {
  // A press on an option selects it (Reka selects on click), which closes a single dropdown.
  if (event.target instanceof Element && event.target.closest('[role="option"]') != null) return
  // Anywhere else it toggles: open when closed, closed when open.
  isMouseFocused.value = !wasFocused
}

function onFocusOut(event: FocusEvent) {
  if (!(event.relatedTarget instanceof Node) || !root.value?.contains(event.relatedTarget)) {
    isFocusWithin.value = false
    isMouseFocused.value = false
  }
}
</script>

<template>
  <div
    ref="root"
    tabindex="-1"
    :class="styles.base({ className })"
    :data-focused="isFocused || undefined"
    @mousedown="onMouseDown"
    @focusin="isFocusWithin = true"
    @focusout="onFocusOut"
  >
    <div :class="styles.container()">
      <div :class="styles.options()">
        <!-- Spacing. -->
        <div :class="styles.input()">&nbsp;</div>
        <div :class="styles.optionsContainer()">
          <ListboxRoot
            v-model="listModel"
            :multiple="multiple"
            :selectionBehavior="multiple ? 'toggle' : 'replace'"
            :disabled="readOnly"
          >
            <ListboxContent :class="styles.optionsList()" :aria-label="ariaLabel">
              <ListboxItem
                v-for="(item, i) in items"
                :key="i"
                :value="i"
                :class="`${styles.optionsItem()} ${DROPDOWN_OPTION_VUE_STATES}`"
              >
                <Icon
                  icon="check"
                  :class="styles.icon({ className: currentIndices.includes(i) ? '' : 'invisible' })"
                />
                <slot :item="item" />
              </ListboxItem>
            </ListboxContent>
          </ListboxRoot>
        </div>
      </div>
    </div>
    <div :class="styles.input()">
      <Icon icon="chevron_right" :class="styles.dropdownArrow()" />
      <div :class="styles.inputDisplay()">
        <template v-if="isMouseFocused && !multiple">&nbsp;</template>
        <slot v-else-if="displayedItem !== undefined" :item="displayedItem" />
        <slot v-else-if="multiple" name="multiple" :items="selectedItems" />
      </div>
    </div>
    <!-- Hidden, but required for the width of the parent element to be correct. -->
    <div :class="styles.hiddenOptions()" aria-hidden="true">
      <div v-for="(item, i) in items" :key="i" :class="styles.hiddenOption()">
        <Icon icon="check" />
        <slot :item="item" />
      </div>
    </div>
  </div>
</template>

// app/gui/src/dashboard/components/Inputs/Dropdown/Dropdown.tsx
/** @file A styled dropdown. */
import { forwardRef, useEffect, useRef, useState, type ForwardedRef, type ReactNode } from 'react'

import {
  FieldError,
  ListBox,
  ListBoxItem,
  mergeProps,
  useFocusVisible,
  useFocusWithin,
  type InputProps,
} from '#/components/aria'
import { Icon } from '#/components/Icon'
import FocusRing from '#/components/styled/FocusRing'
import { useSyncRef } from '#/hooks/syncRefHooks'
import { mergeRefs } from '#/utilities/mergeRefs'
import { DROPDOWN_STYLES } from '$/components/Inputs/dropdownVariants'
import type { VariantProps } from '$/utils/style/tailwindVariants'
import {
  Form,
  type FieldComponentProps,
  type FieldPath,
  type FieldProps,
  type FieldStateProps,
  type FieldValues,
  type FieldVariantProps,
  type FormInstance,
  type TSchema,
} from '../../Form'

/** Props for a list item child. */
interface InternalChildProps<T> {
  readonly item: T
}

/** Props for the display of the currently selected item, when the dropdown supports multiple children. */
interface InternalChildrenProps<T> {
  readonly items: readonly T[]
  /** This is the value passed as {@link DropdownProps.children}. */
  readonly children: (props: InternalChildProps<T>) => ReactNode
}

/** Props for a {@link Dropdown} shared between all variants. */
interface InternalBaseDropdownProps<T>
  extends
    InternalChildrenProps<T>,
    Omit<VariantProps<typeof DROPDOWN_STYLES>, 'isFocused' | 'isReadOnly' | 'multiple'> {
  readonly readOnly?: boolean
  readonly className?: string
  // eslint-disable-next-line @typescript-eslint/naming-convention
  readonly 'aria-label'?: string | undefined
}

/** Props for a {@link Dropdown}, when `multiple` is `false` or absent. */
interface InternalSingleDropdownProps<T> extends InternalBaseDropdownProps<T> {
  readonly multiple?: false
  readonly selectedIndex: number | null
  readonly onChange: (item: T, index: number) => void
}

/** Props for a {@link Dropdown}, when `multiple` is `true`. */
interface InternalMultipleDropdownProps<T> extends InternalBaseDropdownProps<T> {
  readonly multiple: true
  readonly selectedIndices: readonly number[]
  readonly renderMultiple: (props: InternalChildrenProps<T>) => ReactNode
  readonly onChange: (items: readonly T[], indices: readonly number[]) => void
}

/** Props for a {@link Dropdown}. */
export type DropdownProps<T> = InternalMultipleDropdownProps<T> | InternalSingleDropdownProps<T>

/** A styled dropdown. */
export const Dropdown = forwardRef(function DropdownImpl<T>(
  props: DropdownProps<T>,
  ref: ForwardedRef<HTMLDivElement>,
) {
  const {
    readOnly = false,
    className,
    items,
    rounded,
    size,
    variants = DROPDOWN_STYLES,
    children: Child,
  } = props
  const listBoxItems = items.map((item, i) => ({ item, i }))
  const [tempSelectedIndex, setTempSelectedIndex] = useState<number | null>(null)
  const rootRef = useRef<HTMLDivElement | null>(null)
  const [isFocusWithin, setIsFocusWithin] = useState(false)
  const [isMouseFocused, setIsMouseFocused] = useState(false)
  const { isFocusVisible } = useFocusVisible()
  const isFocusedRef = useSyncRef(isFocusWithin)
  const isSelfMouseDownRef = useRef(false)
  const delayedIsFocused = useRef(false)
  const { focusWithinProps } = useFocusWithin({
    onFocusWithinChange: setIsFocusWithin,
  })
  const multiple = props.multiple === true
  const selectedIndex = 'selectedIndex' in props ? props.selectedIndex : null
  const selectedIndices =
    'selectedIndices' in props ? props.selectedIndices
    : selectedIndex != null ? [selectedIndex]
    : []
  const selectedItems = selectedIndices.flatMap((index) => {
    const item = items[index]
    return item != null ? [item] : []
  })
  const visuallySelectedIndex = tempSelectedIndex ?? selectedIndex
  const visuallySelectedItem = visuallySelectedIndex == null ? null : items[visuallySelectedIndex]

  const isFocused = isFocusVisible ? isFocusWithin : isMouseFocused

  const styles = variants({
    isFocused,
    isReadOnly: readOnly,
    multiple,
    rounded,
    size,
  })

  useEffect(() => {
    setTempSelectedIndex(selectedIndex)
  }, [selectedIndex])

  useEffect(() => {
    const onDocumentMouseDown = () => {
      if (!isSelfMouseDownRef.current) {
        setIsMouseFocused(false)
        if (document.activeElement === rootRef.current) {
          rootRef.current?.blur()
        }
        isSelfMouseDownRef.current = false
      }
    }
    document.addEventListener('mousedown', onDocumentMouseDown)
    return () => {
      document.removeEventListener('mousedown', onDocumentMouseDown)
    }
  }, [isFocusedRef])

  useEffect(() => {
    const handle = requestAnimationFrame(() => {
      delayedIsFocused.current = isFocused
    })
    return () => {
      cancelAnimationFrame(handle)
    }
  }, [isFocused])

  return (
    <FocusRing placement="outset">
      <div
        ref={(el) => {
          mergeRefs(ref, rootRef)(el)
        }}
        onMouseDown={() => {
          isSelfMouseDownRef.current = true
          // `isFocused` cannot be used as `isFocusWithin` is set to `false` immediately before
          // this event handler is called.
          setIsMouseFocused(!delayedIsFocused.current)
        }}
        tabIndex={-1}
        className={styles.base({ className })}
        {...mergeProps<React.JSX.IntrinsicElements['div']>()(focusWithinProps, {
          onBlur: (event) => {
            if (!event.currentTarget.contains(event.relatedTarget)) {
              setIsMouseFocused(false)
            }
          },
        })}
      >
        <div className={styles.container()}>
          <div className={styles.options()}>
            {/* Spacing. */}
            <div className={styles.input()}>&nbsp;</div>
            <div className={styles.optionsContainer()}>
              <ListBox
                aria-label={props['aria-label'] ?? 'Dropdown'}
                selectionMode={multiple ? 'multiple' : 'single'}
                selectionBehavior={multiple ? 'toggle' : 'replace'}
                items={listBoxItems}
                dependencies={[selectedIndices]}
                className={styles.optionsList()}
                onSelectionChange={(keys) => {
                  if (multiple) {
                    const indices = Array.from(keys, (i) => Number(i))
                    props.onChange(
                      indices.flatMap((i) => {
                        const item = items[i]
                        return item === undefined ? [] : [item]
                      }),
                      indices,
                    )
                  } else {
                    const [key] = keys
                    if (key != null) {
                      const i = Number(key)
                      const item = items[i]
                      if (item !== undefined) {
                        props.onChange(item, i)
                        setIsMouseFocused(false)
                        rootRef.current?.blur()
                      }
                    }
                  }
                }}
              >
                {({ item, i }) => (
                  <ListBoxItem
                    key={i}
                    id={i}
                    textValue={typeof item === 'string' ? item : `${i}`}
                    className={styles.optionsItem()}
                  >
                    <Icon
                      icon="check"
                      className={styles.icon({
                        className: selectedIndices.includes(i) ? '' : 'invisible',
                      })}
                    />
                    <Child item={item} />
                  </ListBoxItem>
                )}
              </ListBox>
            </div>
          </div>
        </div>
        <div className={styles.input()}>
          <Icon icon="chevron_right" className={styles.dropdownArrow()} />
          <div className={styles.inputDisplay()}>
            {isMouseFocused && !multiple ?
              '\u00a0'
            : visuallySelectedItem != null ?
              <Child item={visuallySelectedItem} />
            : multiple && <props.renderMultiple items={selectedItems}>{Child}</props.renderMultiple>
            }
          </div>
        </div>
        {/* Hidden, but required to exist for the width of the parent element to be correct.
         * Classes that do not affect width have been removed. */}
        <div className={styles.hiddenOptions()}>
          {items.map((item, i) => (
            <div key={i} className={styles.hiddenOption()}>
              <Icon icon="check" />
              <Child item={item} />
            </div>
          ))}
        </div>
      </div>
    </FocusRing>
  )
})

/** Props for a {@link FormDropdown}. */
export interface FormDropdownProps<
  Schema extends TSchema,
  TFieldName extends FieldPath<Schema, Constraint>,
  Constraint,
>
  extends
    FieldStateProps<
      Omit<DropdownProps<Constraint>, 'aria-label' | 'multiple' | 'onChange'> & {
        value: FieldValues<Schema>[TFieldName]
      },
      Schema,
      TFieldName,
      Constraint
    >,
    FieldProps,
    FieldVariantProps {
  readonly form?: FormInstance<Schema>
  readonly name: TFieldName
}

/** A dropdown. */
export function FormDropdown<
  Schema extends TSchema,
  TFieldName extends FieldPath<Schema, Constraint>,
  Constraint,
>(props: FormDropdownProps<Schema, TFieldName, Constraint>) {
  const { name, children, rounded, size, variants, contextualHelp, ...inputProps } = props
  const { items } = inputProps

  const form = Form.useFormContext(props.form)

  const { fieldProps, formInstance } = Form.useFieldRegister<
    Omit<InputProps, 'children' | 'size'>,
    Schema,
    TFieldName,
    Constraint
  >({ ...props, form })

  return (
    <Form.Field
      {...mergeProps<FieldComponentProps<Schema>>()(inputProps, fieldProps, {
        form: formInstance,
      })}
      name={props.name}
      isRequired={props.isRequired}
      contextualHelp={contextualHelp}
    >
      <Form.Controller
        control={form.control}
        name={name}
        render={({ field, fieldState }) => {
          const { value, onChange } = field
          return (
            <>
              <Dropdown
                {...inputProps}
                selectedIndex={items.findIndex(
                  (otherItem) => JSON.stringify(value) === JSON.stringify(otherItem),
                )}
                onChange={onChange}
                rounded={rounded}
                size={size}
                variants={variants}
              >
                {children}
              </Dropdown>
              <FieldError>{fieldState.error?.message}</FieldError>
            </>
          )
        }}
      />
    </Form.Field>
  )
}
