// app/gui/src/cloud/billing/paywall/PaywallScreen.vue
<script setup lang="ts">
/**
 * @file A screen in place of a feature the user's plan lacks: the plan it needs, what it brings,
 * and the upgrade button.
 */
import Heading from '$/components/Text/Heading.vue'
import Text from '$/components/Text/Text.vue'
import { getFeatureConfiguration, type PaywallFeatureName } from '$/composables/paywall'
import { useText } from '$/providers/text'
import { twMerge } from '$/utils/style/tailwindMerge'
import { computed } from 'vue'
import PaywallBulletPoints from './PaywallBulletPoints.vue'
import PaywallLock from './PaywallLock.vue'
import PaywallUpgradeButton from './PaywallUpgradeButton.vue'

const { feature, class: className } = defineProps<{
  feature: PaywallFeatureName
  class?: string | undefined
}>()

const { getText } = useText()
const configuration = computed(() => getFeatureConfiguration(feature))
</script>

<template>
  <div :class="twMerge('flex flex-col items-start', className)">
    <PaywallLock :feature="feature" />
    <Heading :level="2">{{ getText('paywallScreenTitle') }}</Heading>
    <Text balance variant="subtitle" class="mt-1 max-w-[720px]">
      {{ getText(configuration.descriptionTextId) }}
    </Text>
    <PaywallBulletPoints :bulletPointsTextId="configuration.bulletPointsTextId" class="my-3" />
    <PaywallUpgradeButton :feature="feature" class="mt-0.5 min-w-36" />
  </div>
</template>

// app/gui/src/dashboard/components/Paywall/PaywallScreen.tsx
/** @file A screen that shows a paywall. */
import { Text } from '#/components/Text'
import { getFeatureConfiguration, type PaywallFeatureName } from '$/composables/paywall'
import { useText } from '$/providers/react'
import { twMerge } from '$/utils/style/tailwindMerge'
import { PaywallBulletPoints, PaywallLock } from './components'
import { UpgradeButton } from './UpgradeButton'

/** Props for a {@link PaywallScreen}. */
export interface PaywallScreenProps {
  readonly feature: PaywallFeatureName
  readonly className?: string
}

/** A screen that shows a paywall. */
export function PaywallScreen(props: PaywallScreenProps) {
  const { feature, className } = props
  const { getText } = useText()

  const { bulletPointsTextId, descriptionTextId } = getFeatureConfiguration(feature)

  return (
    <div className={twMerge('flex flex-col items-start', className)}>
      <PaywallLock feature={feature} />

      <Text.Heading level="2">{getText('paywallScreenTitle')}</Text.Heading>

      <Text balance variant="subtitle" className="mt-1 max-w-[720px]">
        {getText(descriptionTextId)}
      </Text>

      <PaywallBulletPoints bulletPointsTextId={bulletPointsTextId} className="my-3" />

      <UpgradeButton feature={feature} className="mt-0.5 min-w-36" />
    </div>
  )
}
