// app/gui/src/dashboard/pages/dashboard/UserBar/UserBar.vue
<script setup lang="ts">
/**
 * @file The user bar, at the right of the app container's top bar: the offline notice, the trial
 * indicator, "Invite" and "Upgrade", the notification tray and the user menu. The Vue counterpart
 * of the React `UserBar` (#83), mounted by `AppContainer.vue`.
 *
 * The cloud-only parts come from `src/cloud/`, imported directly (decision 6b's registries do not
 * exist yet). "Invite" stays a React leaf until the organization port (#87) moves its dialog.
 */
import TrialProgress from '$/cloud/billing/TrialProgress.vue'
import UpgradeButton from '$/cloud/billing/UpgradeButton.vue'
import Icon from '$/components/Icon/Icon.vue'
import Text from '$/components/Text/Text.vue'
import { useIsFeatureUnderPaywall } from '$/composables/paywall'
import { useAuth } from '$/providers/auth'
import { useIsOnline } from '$/providers/online'
import { useText } from '$/providers/text'
import { reactComponent } from '$/utils/react'
import { InviteUsersButton as InviteUsersButtonReact } from '#/modals/InviteUsersModal/InviteUsersButton'
import { Plan } from 'enso-common/src/services/Backend'
import { computed } from 'vue'
import NotificationTray from './NotificationTray/NotificationTray.vue'
import UserMenu from './UserMenu.vue'

const InviteUsersButton = reactComponent(InviteUsersButtonReact)

const { goToSettingsPage } = defineProps<{ goToSettingsPage: () => void }>()
const emit = defineEmits<{ signOut: [] }>()

const auth = useAuth()
const { getText } = useText()
const isOnline = useIsOnline()
const isFeatureUnderPaywall = useIsFeatureUnderPaywall()

const user = computed(() => auth.session?.user)
const shouldShowInviteButton = computed(() => !isFeatureUnderPaywall('inviteUser'))
const shouldShowUpgradeButton = computed(
  () => user.value?.isOrganizationAdmin === true && user.value.plan === Plan.free,
)
</script>

<template>
  <div v-if="user" class="flex-shrink-0 pt-0.5">
    <div class="flex h-full shrink-0 cursor-default items-center gap-user-bar pl-icons-x">
      <div v-if="!isOnline" class="mr-2 flex items-center gap-2">
        <Icon icon="cloud_offline" />
        <Text :tooltip="getText('offlineToastMessage')" tooltipDisplay="always">
          {{ getText('youAreOffline') }}
        </Text>
      </div>
      <TrialProgress :user="user" />
      <InviteUsersButton v-if="shouldShowInviteButton" />
      <UpgradeButton v-if="shouldShowUpgradeButton" />
      <NotificationTray />
      <UserMenu :user="user" :goToSettingsPage="goToSettingsPage" @signOut="emit('signOut')" />
    </div>
  </div>
</template>

// app/gui/src/dashboard/pages/dashboard/UserBar/UserBar.tsx
/** @file A toolbar containing chat and the user menu. */
import { Button } from '#/components/Button'
import { Dialog, Popover } from '#/components/Dialog'
import { Icon } from '#/components/Icon'
import { ProfilePicture } from '#/components/ProfilePicture'
import { ProgressBar } from '#/components/ProgressBar'
import { Text } from '#/components/Text'
import { VisualTooltip } from '#/components/VisualTooltip'
import { backendQueryOptions } from '#/hooks/backendHooks'
import { useOffline } from '#/hooks/offlineHooks'
import InviteUsersModal from '#/modals/InviteUsersModal'
import { SUBSCRIBE_PATH } from '$/appUtils'
import {
  useBackends,
  useFullUserSession,
  useIsFeatureUnderPaywall,
  useText,
} from '$/providers/react'
import { rfc3339DurationProgress } from '$/utils/time'
import { useQuery } from '@tanstack/react-query'
import { Plan } from 'enso-common/src/services/Backend'
import { toReadableIsoString } from 'enso-common/src/utilities/data/dateTime'
import { NotificationTray } from './NotificationTray'
import { UserMenu } from './UserMenu'

/** Props for a {@link UserBar}. */
export interface UserBarProps {
  readonly goToSettingsPage: () => void
  readonly onSignOut: () => void
}

/** A toolbar containing chat and the user menu. */
export function UserBar(props: UserBarProps) {
  const { goToSettingsPage, onSignOut } = props

  const { user } = useFullUserSession()
  const { getText } = useText()
  const isFeatureUnderPaywall = useIsFeatureUnderPaywall()
  const { isOffline } = useOffline()
  const { remoteBackend } = useBackends()
  const { data: organization } = useQuery(
    backendQueryOptions(remoteBackend, 'getOrganization', [], {
      enabled: user.isOrganizationAdmin,
    }),
  )
  const subscription = user.isOrganizationAdmin ? organization?.subscription : null
  const trialProgress =
    (
      subscription?.trialEnd != null &&
      new Date(subscription.trialEnd) > new Date() &&
      subscription.trialStart != null
    ) ?
      rfc3339DurationProgress(subscription.trialStart, subscription.trialEnd)
    : null
  const trialText =
    trialProgress == null ? null
    : trialProgress.daysLeft > 0 ? getText('xDaysLeftInTrial', trialProgress.daysLeft)
    : trialProgress.hoursLeft > 0 ? getText('xHoursLeftInTrial', trialProgress.hoursLeft)
    : getText('lessThanOneHourLeftInTrial')
  const isCurrentlyTrialing = trialProgress != null && subscription?.trialEnd != null

  const shouldShowInviteButton = !isFeatureUnderPaywall('inviteUser')
  const shouldShowUpgradeButton = user.isOrganizationAdmin && user.plan === Plan.free
  const upgradeButtonVariant = user.plan === Plan.free ? 'primary' : 'outline'

  return (
    <div className="flex-shrink-0 pt-0.5">
      <div className="flex h-full shrink-0 cursor-default items-center gap-user-bar pl-icons-x">
        {isOffline && (
          <div className="mr-2 flex items-center gap-2">
            <Icon icon="cloud_offline" />
            <Text tooltip={getText('offlineToastMessage')} tooltipDisplay="always">
              {getText('youAreOffline')}
            </Text>
          </div>
        )}
        {isCurrentlyTrialing && (
          <VisualTooltip
            className="relative px-2"
            tooltip={getText(
              'yourSubscriptionExpiresAtX',
              toReadableIsoString(new Date(subscription.trialEnd)),
            )}
          >
            <Text className="opacity-0">{trialText}</Text>
            <ProgressBar
              progress={trialProgress.fraction}
              variant="clipped"
              className="absolute inset-0"
              progressBarClassName="bg-accent/50"
              aria-label={getText('trialProgressLabel')}
            />
            <Text className="absolute inset-0 mx-2 cursor-help text-center">{trialText}</Text>
          </VisualTooltip>
        )}
        {shouldShowInviteButton && (
          <Dialog.Trigger>
            <Button size="medium" variant="outline">
              {getText('invite')}
            </Button>

            <InviteUsersModal />
          </Dialog.Trigger>
        )}
        {shouldShowUpgradeButton && (
          <Button variant={upgradeButtonVariant} size="medium" href={SUBSCRIBE_PATH}>
            {getText('upgrade')}
          </Button>
        )}
        <NotificationTray />
        <Popover.Trigger>
          <Button
            size="custom"
            variant="icon"
            icon={<ProfilePicture picture={user.profilePicture} name={user.name} />}
            className="ml-2"
            aria-label={getText('userMenuLabel')}
          />
          <UserMenu goToSettingsPage={goToSettingsPage} onSignOut={onSignOut} />
        </Popover.Trigger>
      </div>
    </div>
  )
}
