// app/gui/src/components/Alert/Alert.vue
<script setup lang="ts">
/**
 * @file An alert box: the Vue counterpart of the React `#/components/Alert`. An `error` alert is an
 * `alert` live region and can take focus programmatically (`tabindex="-1"`), as in React.
 */
import { ALERT_STYLES } from '$/components/Alert/variants'
import Icon from '$/components/Icon/Icon.vue'
import type { VariantProps } from '$/utils/style/tailwindVariants'
import type { Icon as IconName } from '@/util/iconMetadata/iconName'
import { computed } from 'vue'

type AlertVariants = VariantProps<typeof ALERT_STYLES>

const {
  variant = 'error',
  size,
  rounded,
  // `undefined`, not the `false` Vue casts an absent boolean prop to, so the variant default applies.
  fullWidth = undefined,
  icon,
  class: className,
} = defineProps<{
  variant?: AlertVariants['variant']
  size?: AlertVariants['size']
  rounded?: AlertVariants['rounded']
  fullWidth?: boolean | undefined
  icon?: IconName | undefined
  class?: string | undefined
}>()

const styles = computed(() => ALERT_STYLES({ variant, size, rounded, fullWidth }))
</script>

<template>
  <div
    :class="styles.base({ className })"
    :tabindex="variant === 'error' ? -1 : undefined"
    :role="variant === 'error' ? 'alert' : undefined"
  >
    <Icon v-if="icon != null" :icon="icon" size="medium" :class="styles.iconContainer()" />
    <div :class="styles.children()"><slot /></div>
  </div>
</template>

// app/gui/src/dashboard/components/Alert/Alert.tsx
/** @file Alert component. */
import { forwardRef, type ForwardedRef, type HTMLAttributes, type PropsWithChildren } from 'react'

import { ALERT_STYLES } from '$/components/Alert/variants'
import type { VariantProps } from '$/utils/style/tailwindVariants'
import { Icon } from '../Icon'
import type { IconProp } from '../types'

/** Props for an {@link Alert}. */
export interface AlertProps<IconType extends string = string>
  extends PropsWithChildren, VariantProps<typeof ALERT_STYLES>, HTMLAttributes<HTMLDivElement> {
  /** The icon to display in the Alert */
  readonly icon?: IconProp<IconType> | null | undefined
}

/** Alert component. */
export const Alert = forwardRef(function AlertImpl<IconType extends string = string>(
  props: AlertProps<IconType>,
  ref: ForwardedRef<HTMLDivElement>,
) {
  const {
    children,
    className,
    variant,
    size,
    rounded,
    fullWidth,
    icon,
    variants = ALERT_STYLES,
    tabIndex: rawTabIndex,
    role: rawRole,
    ...containerProps
  } = props

  const tabIndex = variant === 'error' ? -1 : rawTabIndex
  const role = variant === 'error' ? 'alert' : rawRole

  const classes = variants({
    variant,
    size,
    rounded,
    fullWidth,
  })

  return (
    <div
      className={classes.base({ className })}
      ref={ref}
      tabIndex={tabIndex}
      role={role}
      {...containerProps}
    >
      {icon != null && <Icon icon={icon} size="medium" className={classes.iconContainer()} />}

      <div className={classes.children()}>{children}</div>
    </div>
  )
})

export { ALERT_STYLES } from '$/components/Alert/variants'
