// app/gui/src/dashboard/modules/payments/components/PlanSelector/PlanSelector.tsx
/** @file Plan selector component. */
import { DIALOG_BACKGROUND } from '$/components/Dialog/variants'
import { mapPlanOnPaywall } from '$/composables/paywall/FeaturesConfiguration'
import { useBackends } from '$/providers/backends'
import { backendQueryOptions } from '$/utils/backendQuery'
import type { VariantProps } from '$/utils/style/tailwindVariants'
import { tv } from '$/utils/style/tailwindVariants'
import { useSuspenseQuery } from '@tanstack/react-query'
import * as backend from 'enso-common/src/services/Backend'
import { Card } from './components'

/** Props for {@link PlanSelector} */
export interface PlanSelectorProps extends VariantProps<typeof PLAN_SELECTOR_STYLES> {
  readonly userPlan: backend.Plan
  readonly showFreePlan: boolean
  readonly isOrganizationAdmin: boolean
  readonly plan?: backend.Plan | null | undefined
}

const PLAN_SELECTOR_STYLES = tv({
  base: DIALOG_BACKGROUND({
    className: 'w-full snap-x overflow-auto rounded-4xl scroll-hidden',
  }),
  variants: {
    showFreePlan: { true: { grid: '2xl:auto-cols-5' } },
  },
  slots: {
    grid: 'inline-grid min-w-full gap-6 p-6 grid-flow-col auto-cols-1fr justify-center md:auto-cols-2 lg:auto-cols-3 xl:auto-cols-4',
    card: 'min-w-72 snap-center',
  },
})

/**
 * Plan selector component.
 * Shows the available plans and allows the user to subscribe to one.
 */
export function PlanSelector(props: PlanSelectorProps) {
  const {
    plan,
    userPlan,
    showFreePlan,
    isOrganizationAdmin,
    variants = PLAN_SELECTOR_STYLES,
  } = props

  const { remoteBackend } = useBackends()

  const { data: config } = useSuspenseQuery(
    backendQueryOptions(remoteBackend, 'getPaymentsConfig', []),
  )
  const classes = variants({ showFreePlan })

  return (
    <div className={classes.base()}>
      <div className={classes.grid()}>
        {config.cards.map(({ plan: newPlan, period, title, subtitle, pricing, features }) => {
          return (
            <Card
              key={`${newPlan}/${period}`}
              plan={newPlan}
              period={period}
              texts={{ title, subtitle, pricing, features }}
              modalOpen={newPlan === plan}
              userHasSubscription={userPlan !== backend.Plan.free}
              isOrganizationAdmin={isOrganizationAdmin}
              isCurrent={newPlan === userPlan}
              paywallLevel={mapPlanOnPaywall(newPlan)}
              userPaywallLevel={mapPlanOnPaywall(userPlan)}
              className={classes.card()}
            />
          )
        })}
      </div>
    </div>
  )
}

// app/gui/src/cloud/billing/subscribe/PlanSelector.vue
<script setup lang="ts">
/**
 * @file The plans on offer, as a row of cards: the Vue port of the React `PlanSelector`. The cards
 * come from the backend's payments configuration (`getPaymentsConfig`); the setup waits for it, as
 * React's suspense query did, so an enclosing `SuspenseLoader` shows the loader meanwhile.
 */
import { mapPlanOnPaywall } from '$/composables/paywall/FeaturesConfiguration'
import { useBackends } from '$/providers/backends'
import { useQuery } from '@tanstack/vue-query'
import { Plan } from 'enso-common/src/services/Backend'
import { computed } from 'vue'
import { paymentsConfigQueryOptions } from '../queries'
import PlanCard from './PlanCard.vue'
import { PLAN_SELECTOR_STYLES } from './variants'

const {
  plan = null,
  userPlan,
  showFreePlan,
  isOrganizationAdmin,
} = defineProps<{
  userPlan: Plan
  showFreePlan: boolean
  isOrganizationAdmin: boolean
  /** The plan whose dialog opens at once. */
  plan?: Plan | null | undefined
}>()

const { remoteBackend } = useBackends()

const configQuery = useQuery({ ...paymentsConfigQueryOptions(remoteBackend), throwOnError: true })
await configQuery.suspense()
const cards = computed(() => configQuery.data.value?.cards ?? [])

const classes = computed(() => PLAN_SELECTOR_STYLES({ showFreePlan }))
</script>

<template>
  <div :class="classes.base()">
    <div :class="classes.grid()">
      <PlanCard
        v-for="card in cards"
        :key="`${card.plan}/${card.period}`"
        :plan="card.plan"
        :period="card.period"
        :texts="card"
        :modalOpen="card.plan === plan"
        :userHasSubscription="userPlan !== Plan.free"
        :isOrganizationAdmin="isOrganizationAdmin"
        :isCurrent="card.plan === userPlan"
        :paywallLevel="mapPlanOnPaywall(card.plan).valueOf()"
        :userPaywallLevel="mapPlanOnPaywall(userPlan).valueOf()"
        :class="classes.card()"
      />
    </div>
  </div>
</template>
