// app/gui/src/cloud/billing/paywall/PaywallButton.vue
<script setup lang="ts">
/**
 * @file A button showing that a feature is behind a paywall, with a lock icon (unless `showIcon` is
 * `false`) and the plan in its tooltip: the Vue port of the React `PaywallButton`. Its label is the
 * default slot, or "Upgrade to <plan>". Other attributes go on the `Button.vue`.
 */
import Button from '$/components/Button/Button.vue'
import { getFeatureConfiguration, type PaywallFeatureName } from '$/composables/paywall'
import { useText } from '$/providers/text'
import { computed } from 'vue'

type ButtonProps = InstanceType<typeof Button>['$props']

const {
  feature,
  iconOnly = false,
  showIcon = true,
  variant = 'primary',
  size = 'medium',
} = defineProps<{
  feature: PaywallFeatureName
  iconOnly?: boolean | undefined
  showIcon?: boolean | undefined
  variant?: ButtonProps['variant']
  size?: ButtonProps['size']
}>()

const { getText } = useText()
const levelLabel = computed(() => getText(getFeatureConfiguration(feature).level.label))
</script>

<template>
  <Button
    :variant="variant"
    :size="size"
    :icon="showIcon ? 'lock' : undefined"
    iconPosition="end"
    :tooltip="getText('paywallScreenDescription', levelLabel)"
  >
    <template v-if="!iconOnly" #default>
      <slot>{{ getText('upgradeTo', levelLabel) }}</slot>
    </template>
  </Button>
</template>

// app/gui/src/dashboard/components/Paywall/components/PaywallButton.tsx
/** @file A styled button that shows that a feature is behind a paywall. */
import { Button, type ButtonProps } from '#/components/Button'
import { getFeatureConfiguration, type PaywallFeatureName } from '$/composables/paywall'
import { useText } from '$/providers/react'
import * as React from 'react'

/** Props for {@link PaywallButton}. */
export type PaywallButtonProps<IconType extends string> = ButtonProps<IconType> & {
  readonly feature: PaywallFeatureName
  readonly iconOnly?: boolean
  readonly showIcon?: boolean
}

/** A styled button that shows that a feature is behind a paywall */
export function PaywallButton<IconType extends string>(
  props: PaywallButtonProps<IconType>,
): React.JSX.Element {
  const { feature, iconOnly = false, showIcon = true, children, ...buttonProps } = props

  const { getText } = useText()

  const { level } = getFeatureConfiguration(feature)
  const levelLabel = getText(level.label)

  const showChildren = !iconOnly
  const childrenContent = children ?? getText('upgradeTo', levelLabel)

  return (
    <Button
      variant="primary"
      size="medium"
      icon={showIcon ? 'lock' : null}
      iconPosition="end"
      tooltip={getText('paywallScreenDescription', levelLabel)}
      /* This is safe because we are passing all props to the button */
      /* Load-bearing assertion; see the note in `FormProvider.tsx`. */
      /* eslint-disable-next-line @typescript-eslint/no-explicit-any,no-restricted-syntax,@typescript-eslint/no-unnecessary-type-assertion */
      {...(buttonProps as any)}
    >
      {showChildren && childrenContent}
    </Button>
  )
}
