// app/gui/src/dashboard/components/Button/CloseButton.tsx
/** @file A button for closing a modal. */
import { useText } from '$/providers/react'
import { twMerge } from '$/utils/style/tailwindMerge'
import { isOnMacOS } from 'enso-common/src/utilities/detect'
import { memo } from 'react'
import { Button } from './Button'
import type { ButtonProps } from './types'

/** Props for a {@link CloseButton}. */
export type CloseButtonProps<IconType extends string> = Omit<
  ButtonProps<IconType>,
  'children' | 'rounding' | 'size' | 'variant'
>

/** A styled button with a close icon that appears on hover. */
export const CloseButton = memo(function CloseButtonImpl<IconType extends string>(
  props: CloseButtonProps<IconType>,
) {
  const { getText } = useText()

  const {
    className,
    icon = 'close',
    tooltip = false,
    'aria-label': ariaLabel = getText('closeModalShortcut'),
    testId,
    ...buttonProps
  } = props

  return (
    <Button
      variant="icon"
      className={(values) =>
        twMerge(
          'hover:bg-red-500/80 focus-visible:bg-red-500/80 focus-visible:outline-offset-1',
          isOnMacOS() ? 'bg-primary/30' : (
            'text-primary/90 hover:text-primary focus-visible:text-primary'
          ),
          // @ts-expect-error TypeScript fails to infer the type of the `className` prop
          // But it's safe because we are passing all values transparently
          // and they are typed outside.
          typeof className === 'function' ? className(values) : className,
        )
      }
      tooltip={tooltip}
      showIconOnHover={isOnMacOS()}
      size="xsmall"
      rounded="full"
      extraClickZone="medium"
      icon={icon}
      aria-label={ariaLabel}
      testId={testId}
      /* This is safe because we are passing all props to the button */
      /* eslint-disable-next-line @typescript-eslint/no-explicit-any,no-restricted-syntax */
      {...(buttonProps as any)}
    />
  )
})

// app/gui/src/components/Button/CloseButton.vue
<script setup lang="ts">
/**
 * @file A small round button with a close icon, for closing a dialog or a panel. On macOS the icon
 * only shows on hover, as the window controls do.
 *
 * (Not to be confused with `src/components/CloseButton.vue`, the window-control close button of the
 * app's own title bar.)
 */
import { useText } from '$/providers/text'
import { twMerge } from '$/utils/style/tailwindMerge'
import type { Icon as IconName } from '@/util/iconMetadata/iconName'
import { isOnMacOS } from 'enso-common/src/utilities/detect'
import { computed, useAttrs } from 'vue'
import Button from './Button.vue'

const {
  icon = 'close',
  tooltip = false,
  class: className,
} = defineProps<{
  icon?: IconName | undefined
  tooltip?: string | false | undefined
  class?: string | undefined
}>()

const { getText } = useText()
const attrs = useAttrs()
const onMacOS = isOnMacOS()

const classes = computed(() =>
  twMerge(
    'hover:bg-red-500/80 focus-visible:bg-red-500/80 focus-visible:outline-offset-1',
    onMacOS ? 'bg-primary/30' : 'text-primary/90 hover:text-primary focus-visible:text-primary',
    className,
  ),
)
</script>

<template>
  <Button
    variant="icon"
    :class="classes"
    :tooltip="tooltip"
    :showIconOnHover="onMacOS"
    size="xsmall"
    rounded="full"
    extraClickZone="medium"
    :icon="icon"
    :aria-label="attrs['aria-label'] ?? getText('closeModalShortcut')"
  />
</template>
