// app/gui/src/dashboard/components/Button/CopyButton.tsx
/** @file A button that copies text to the clipboard. */
import type { SvgUseIcon } from '#/components/types'
import { useCopy } from '#/hooks/copyHooks'
import { useText } from '$/providers/react'
import { Button } from './Button'
import type { ButtonProps } from './types'

/** Props for a {@link CopyButton}. */
export interface CopyButtonProps<IconType extends string> extends Omit<
  ButtonProps<IconType>,
  'icon' | 'loading' | 'onPress'
> {
  /** The text to copy to the clipboard. */
  readonly copyText: string
  /**
   * Custom icon
   * If `false` is provided, no icon will be shown.
   */
  readonly copyIcon?: SvgUseIcon | false | (string & {})
  readonly errorIcon?: SvgUseIcon | (string & {})
  readonly successIcon?: SvgUseIcon | (string & {})
  readonly onCopy?: () => void
  /**
   * Show a toast message when the copy is successful.
   * If a string is provided, it will be used as the toast message.
   * If `true` is provided, a default toast message will be shown with the text "Copied to clipboard".
   * If `false` is provided, no toast message will be shown.
   */
  readonly successToastMessage?: boolean | string
}

/** A button that copies text to the clipboard. */
export function CopyButton<IconType extends string>(props: CopyButtonProps<IconType>) {
  const {
    variant = 'icon',
    copyIcon = 'duplicate',
    successIcon = 'check',
    errorIcon = 'close',
    copyText,
    onCopy,
    ...buttonProps
  } = props
  const { getText } = useText()
  const copyQuery = useCopy({ onCopy })
  const successfullyCopied = copyQuery.isSuccess
  const isError = copyQuery.isError
  const showIcon = copyIcon !== false
  const icon =
    showIcon ?
      isError ? errorIcon
      : successfullyCopied ? successIcon
      : copyIcon
    : null

  return (
    <Button
      /* This is safe because we are passing all props to the button */
      /* eslint-disable-next-line @typescript-eslint/no-explicit-any,no-restricted-syntax */
      {...(buttonProps as any)}
      variant={variant}
      aria-label={props['aria-label'] ?? getText('copyShortcut')}
      onPress={() => copyQuery.mutateAsync(copyText)}
      icon={icon}
    />
  )
}

// app/gui/src/components/Button/CopyButton.vue
<script setup lang="ts">
/**
 * @file A button that copies text to the clipboard, and briefly shows whether that worked: the
 * Vue counterpart of the React `Button/CopyButton`.
 *
 * Like the React one, it shows a "Copied to clipboard" toast at the bottom right on success (unless
 * `successToastMessage` is `false`), which closes with the success icon; a failure shows an error
 * toast and is logged.
 */
import { useText } from '$/providers/text'
import type { Icon as IconName } from '@/util/iconMetadata/iconName'
import { useAttrs } from 'vue'
import Button from './Button.vue'
import { useCopy } from './copy'

const {
  copyText,
  copyIcon = 'duplicate',
  successIcon = 'check',
  errorIcon = 'close',
  variant = 'icon',
  successToastMessage = true,
} = defineProps<{
  copyText: string
  /** `null` shows no icon (`false` in React). */
  copyIcon?: IconName | null | undefined
  successIcon?: IconName | undefined
  errorIcon?: IconName | undefined
  variant?: InstanceType<typeof Button>['$props']['variant']
  /**
   * The toast shown once the text is copied: `true` for "Copied to clipboard" (the default), a
   * string for another message, `false` for none.
   */
  successToastMessage?: boolean | string | undefined
}>()

const emit = defineEmits<{ copy: [] }>()

const { getText } = useText()
const attrs = useAttrs()
const { state, copy: copyToClipboard } = useCopy({
  successToastMessage: () => successToastMessage,
  onCopy: () => emit('copy'),
})

function copy() {
  return copyToClipboard(copyText)
}
</script>

<template>
  <Button
    :variant="variant"
    :icon="
      copyIcon == null ? undefined
      : state === 'success' ? successIcon
      : state === 'error' ? errorIcon
      : copyIcon
    "
    :aria-label="attrs['aria-label'] ?? getText('copyShortcut')"
    :data-copy-state="state"
    @press="copy"
  >
    <template v-if="$slots.default" #default><slot /></template>
  </Button>
</template>
