// app/gui/src/dashboard/components/Dialog/Dialog.tsx
/**
 * @file A dialog is an overlay shown above other content in an application.
 * Can be used to display alerts, confirmations, or other content.
 */
import * as aria from '#/components/aria'
import { CloseButton, ResetButtonGroupContext } from '#/components/Button'
import { ErrorBoundary } from '#/components/ErrorBoundary'
import { usePortalContext } from '#/components/Portal'
import { Suspense } from '#/components/Suspense'
import { Text } from '#/components/Text'
import { useEventCallback } from '#/hooks/eventCallbackHooks'
import { mergeRefs } from '#/utilities/mergeRefs'
import type { VariantProps } from '#/utilities/tailwindVariants'
import { unsafeWriteValue } from '#/utilities/write'
import * as React from 'react'
import { Close } from './Close'
import { DialogProvider } from './DialogProvider'
import { DialogStackRegistrar, type DialogStackItem } from './DialogStackProvider'
import { DialogTrigger } from './DialogTrigger'
import type * as types from './types'
import { useInteractOutside } from './utilities'
import { DIALOG_MODAL_STYLES, DIALOG_OVERLAY_STYLES, DIALOG_STYLES } from './variants'

/** Props for the {@link Dialog} component. */
export interface DialogProps
  extends types.DialogProps, Omit<VariantProps<typeof DIALOG_STYLES>, 'scrolledToTop'> {}

/**
 * A dialog is an overlay shown above other content in an application.
 * Can be used to display alerts, confirmations, or other content.
 */
export const Dialog = Object.assign(
  React.forwardRef(function Dialog(props: DialogProps, ref: React.ForwardedRef<HTMLDivElement>) {
    const {
      type = 'modal',
      isDismissable = true,
      isKeyboardDismissDisabled = false,
      onOpenChange = () => {},
      modalProps = {},
    } = props

    const root = usePortalContext()

    return (
      <aria.ModalOverlay
        className={({ isEntering, isExiting }) =>
          DIALOG_OVERLAY_STYLES({ isEntering, isExiting, blockInteractions: !isDismissable })
        }
        ref={(element) =>
          mergeRefs(ref, (el) => {
            if (el) {
              el.addEventListener('keydown', (event) => {
                if (event.key !== 'Escape') {
                  event.stopPropagation()
                }
              })
            }
          })(element)
        }
        isDismissable={isDismissable}
        isKeyboardDismissDisabled={isKeyboardDismissDisabled}
        UNSTABLE_portalContainer={root}
        onOpenChange={onOpenChange}
        shouldCloseOnInteractOutside={() => false}
        {...modalProps}
      >
        {(values) => (
          <aria.Modal
            className={({ isEntering, isExiting }) =>
              DIALOG_MODAL_STYLES({ type, isEntering, isExiting })
            }
            isDismissable={isDismissable}
            isKeyboardDismissDisabled={isKeyboardDismissDisabled}
            UNSTABLE_portalContainer={root}
            onOpenChange={onOpenChange}
            shouldCloseOnInteractOutside={() => false}
            data-testid="modal-dialog"
            {...modalProps}
          >
            <DialogContent {...props} modalState={values.state} />
          </aria.Modal>
        )}
      </aria.ModalOverlay>
    )
  }),
  {
    // eslint-disable-next-line @typescript-eslint/naming-convention
    Close: Close,
    // eslint-disable-next-line @typescript-eslint/naming-convention
    Trigger: DialogTrigger,
  },
)

const TYPE_TO_DIALOG_TYPE: Record<NonNullable<DialogProps['type']>, DialogStackItem['type']> = {
  modal: 'dialog',
  fullscreen: 'dialog-fullscreen',
}

/**
 * Props for the {@link DialogContent} component.
 */
interface DialogContentProps extends DialogProps, VariantProps<typeof DIALOG_STYLES> {
  readonly modalState: aria.OverlayTriggerState
}

/**
 * The content of a dialog.
 * @internal
 */
function DialogContent(props: DialogContentProps) {
  const {
    variants = DIALOG_STYLES,
    modalState,
    className,
    type = 'modal',
    rounded,
    hideCloseButton = false,
    closeButton = 'normal',
    size,
    padding: paddingRaw,
    fitContent,
    layout,
    testId,
    title,
    children,
    isDismissable = true,
    onDismiss,
    ...ariaDialogProps
  } = props
  const dialogRef = React.useRef<HTMLDivElement>(null)
  const scrollerRef = React.useRef<HTMLDivElement | null>(null)
  const dialogId = aria.useId()
  const titleId = `${dialogId}-title`
  const padding = paddingRaw ?? (type === 'modal' ? 'medium' : 'xlarge')

  // Mutating the method of the modalState object to ensure that the close `close`
  // function will call the `onDismiss` function and then close the modal.
  unsafeWriteValue(
    modalState,
    'close',
    useEventCallback(() => {
      onDismiss?.()
      modalState.setOpen(false)
    }),
  )

  const close = useEventCallback(() => {
    modalState.close()
  })

  useInteractOutside({
    ref: dialogRef,
    id: dialogId,
    onInteractOutside: () => {
      if (isDismissable) {
        close()
      }
    },
  })

  const styles = variants({
    className,
    type,
    rounded,
    hideCloseButton,
    closeButton,
    size,
    padding,
    fitContent,
    layout,
  })

  return (
    <ResetButtonGroupContext>
      <aria.Dialog
        id={dialogId}
        ref={(ref: HTMLDivElement | null) => {
          mergeRefs(dialogRef, (element) => {
            if (!element) return
            // This is a workaround for the `data-testid` attribute not being
            // supported by the 'react-aria-components' library.
            // We need to set the `data-testid` attribute on the dialog element
            // so that we can use it in our tests.
            // This is a temporary solution until we refactor the Dialog component
            // to use `useDialog` hook from the 'react-aria-components' library.
            // this will allow us to set the `data-testid` attribute on the dialog
            element.dataset.testid = testId
          })(ref)
        }}
        className={styles.base()}
        aria-labelledby={titleId}
        {...ariaDialogProps}
      >
        <div className="w-full">
          <DialogHeader
            closeButton={closeButton}
            title={title}
            titleId={titleId}
            scrollerRef={scrollerRef}
            fitContent={fitContent}
            hideCloseButton={hideCloseButton}
            padding={padding}
            rounded={rounded}
            size={size}
            type={type}
            close={close}
            variants={variants}
          />
        </div>

        <div className={styles.scroller()} ref={scrollerRef}>
          <DialogBody
            close={close}
            dialogId={dialogId}
            scrollerRef={scrollerRef}
            measurerWrapperClassName={styles.measurerWrapper()}
            contentClassName={styles.content()}
            type={type}
          >
            {children}
          </DialogBody>
        </div>
      </aria.Dialog>

      <DialogStackRegistrar id={dialogId} type={TYPE_TO_DIALOG_TYPE[type]} />
    </ResetButtonGroupContext>
  )
}

/** Props for a {@link DialogBody}. */
interface DialogBodyProps {
  readonly dialogId: string
  readonly scrollerRef: React.RefObject<HTMLDivElement>
  readonly close: () => void
  readonly measurerWrapperClassName: string
  readonly contentClassName: string
  readonly children: DialogProps['children']
  readonly type: DialogProps['type']
}

/** The internals of a dialog. Exists only as a performance optimization. */
const DialogBody = React.memo(function DialogBody(props: DialogBodyProps) {
  const { close, dialogId, children, measurerWrapperClassName, contentClassName, type } = props

  return (
    <div className={measurerWrapperClassName}>
      <div className={contentClassName}>
        <ErrorBoundary>
          <Suspense loaderProps={{ minHeight: type === 'fullscreen' ? 'full' : 'h32' }}>
            <DialogProvider close={close} dialogId={dialogId}>
              {typeof children === 'function' ? children({ close }) : children}
            </DialogProvider>
          </Suspense>
        </ErrorBoundary>
      </div>
    </div>
  )
})

/**
 * Props for the {@link DialogHeader} component.
 */
interface DialogHeaderProps extends Omit<VariantProps<typeof DIALOG_STYLES>, 'scrolledToTop'> {
  readonly closeButton: DialogProps['closeButton']
  readonly title: DialogProps['title']
  readonly titleId: string
  readonly scrollerRef: React.RefObject<HTMLDivElement>
  readonly close: () => void
}

/**
 * The header of a dialog.
 * @internal
 */
const DialogHeader = React.memo(function DialogHeader(props: DialogHeaderProps) {
  const {
    closeButton,
    title,
    titleId,
    scrollerRef,
    fitContent,
    hideCloseButton,
    padding,
    rounded,
    size,
    type,
    variants = DIALOG_STYLES,
    close,
    layout,
  } = props

  const styles = variants({
    type,
    closeButton,
    fitContent,
    hideCloseButton,
    padding,
    rounded,
    size,
    layout,
  })

  const [isScrolledToTop, privateSetIsScrolledToTop] = React.useState(true)

  const setIsScrolledToTop = React.useCallback(
    (value: boolean) => {
      React.startTransition(() => {
        privateSetIsScrolledToTop(value)
      })
    },
    [privateSetIsScrolledToTop],
  )

  /** Handles the scroll event on the dialog content. */
  const handleScrollEvent = useEventCallback(() => {
    if (scrollerRef.current) {
      setIsScrolledToTop(scrollerRef.current.scrollTop === 0)
    } else {
      setIsScrolledToTop(true)
    }
  })

  React.useEffect(() => {
    const scroller = scrollerRef.current
    if (scroller) {
      handleScrollEvent()

      scroller.addEventListener('scroll', handleScrollEvent, { passive: true })

      return () => {
        scroller.removeEventListener('scroll', handleScrollEvent)
      }
    }
  }, [handleScrollEvent, scrollerRef])

  return (
    <aria.Header className={styles.header({ scrolledToTop: isScrolledToTop })}>
      {closeButton !== 'none' && <CloseButton className={styles.closeButton()} onPress={close} />}

      {title != null && (
        <Text.Heading id={titleId} level={2} className={styles.heading()} weight="semibold">
          {title}
        </Text.Heading>
      )}
    </aria.Header>
  )
})

// app/gui/src/components/Dialog/Dialog.vue
<script setup lang="ts">
/**
 * @file A modal dialog on Reka UI's `Dialog`: the Vue counterpart of the React
 * `#/components/Dialog`, styled by the same `DIALOG_STYLES`, `DIALOG_OVERLAY_STYLES` and
 * `DIALOG_MODAL_STYLES`.
 *
 * Reka provides what react-aria did: `role="dialog"` labelled by the title, focus moved in on open
 * and trapped, focus returned to the trigger on close, Escape and outside-click dismissal, scroll
 * lock, and `aria-hidden` on everything else. Nested dialogs and popovers stack: Escape and outside
 * clicks reach the topmost one first, so React's `DialogStackProvider` has no Vue counterpart.
 *
 * - The trigger is the `trigger` slot, and replaces React's `Dialog.Trigger` wrapper. Without one,
 *   the dialog is controlled through `v-model:open`.
 * - The content is the default slot, which receives `{ close }`. `DialogClose.vue`, anywhere inside,
 *   closes it too.
 * - `@dismiss` fires when the user closes it (Escape, outside click, the close button, or
 *   `close`), like React's `onDismiss`. Setting `open` to `false` from outside does not fire it.
 * - Like React, keys other than Escape do not propagate out of the dialog, so global shortcuts do
 *   not fire while it is open.
 *
 * The global modal stack (`setModal` and its Vue replacement) is #80's; this is the primitive it
 * will render.
 */
import ResetButtonGroup from '$/components/Button/ResetButtonGroup.vue'
import CloseButton from '$/components/Button/CloseButton.vue'
import {
  DIALOG_MODAL_STYLES,
  DIALOG_MOTION,
  DIALOG_OVERLAY_STYLES,
  DIALOG_STYLES,
  IGNORE_INTERACT_OUTSIDE_SELECTOR,
} from '$/components/Dialog/variants'
import ErrorBoundary from '$/components/ErrorBoundary/ErrorBoundary.vue'
import SuspenseLoader from '$/components/ErrorBoundary/SuspenseLoader.vue'
import { portalTarget } from '$/components/portal'
import Heading from '$/components/Text/Heading.vue'
import type { VariantProps } from '$/utils/style/tailwindVariants'
import {
  DialogContent,
  DialogOverlay,
  DialogPortal,
  DialogRoot,
  DialogTitle,
  DialogTrigger,
} from 'reka-ui'
import { computed, ref } from 'vue'
import { provideDialogContext } from './dialogContext'

type DialogVariants = VariantProps<typeof DIALOG_STYLES>

const {
  title,
  type = 'modal',
  isDismissable = true,
  isKeyboardDismissDisabled = false,
  closeButton = 'normal',
  hideCloseButton = undefined,
  size,
  padding,
  rounded,
  fitContent = undefined,
  layout = undefined,
  role = 'dialog',
  testId,
  class: className,
} = defineProps<{
  title?: string | undefined
  type?: 'fullscreen' | 'modal' | undefined
  /** Whether an outside click closes it. Also blurs what is behind it when `false`. */
  isDismissable?: boolean | undefined
  isKeyboardDismissDisabled?: boolean | undefined
  closeButton?: DialogVariants['closeButton']
  hideCloseButton?: boolean | undefined
  /** Only applies to the `modal` type. */
  size?: DialogVariants['size']
  padding?: DialogVariants['padding']
  rounded?: DialogVariants['rounded']
  fitContent?: boolean | undefined
  layout?: boolean | undefined
  role?: 'alertdialog' | 'dialog' | undefined
  testId?: string | undefined
  class?: string | undefined
}>()

const open = defineModel<boolean>('open', { default: false })

const emit = defineEmits<{
  /** The user closed the dialog. */
  dismiss: []
}>()

function close() {
  emit('dismiss')
  open.value = false
}

function onOpenChange(value: boolean) {
  if (!value) emit('dismiss')
}

provideDialogContext({ close })

const styles = computed(() =>
  DIALOG_STYLES({
    type,
    rounded,
    hideCloseButton,
    closeButton,
    size,
    padding: padding ?? (type === 'modal' ? 'medium' : 'xlarge'),
    fitContent,
    layout,
  }),
)

const scroller = ref<HTMLElement>()
const isScrolledToTop = ref(true)
function onScroll() {
  isScrolledToTop.value = (scroller.value?.scrollTop ?? 0) === 0
}

function onPointerDownOutside(event: CustomEvent<{ originalEvent: PointerEvent }>) {
  const target = event.detail.originalEvent.target
  if (
    !isDismissable ||
    (target instanceof Element && target.closest(IGNORE_INTERACT_OUTSIDE_SELECTOR) != null)
  ) {
    event.preventDefault()
  }
}

function onEscapeKeyDown(event: KeyboardEvent) {
  if (isKeyboardDismissDisabled) event.preventDefault()
}

function stopNonEscapeKeys(event: KeyboardEvent) {
  if (event.key !== 'Escape') event.stopPropagation()
}
</script>

<template>
  <DialogRoot v-model:open="open" @update:open="onOpenChange">
    <DialogTrigger v-if="$slots.trigger" asChild>
      <slot name="trigger" />
    </DialogTrigger>
    <DialogPortal :to="portalTarget()">
      <!-- React's `ModalOverlay` > `Modal` > `Dialog` nesting. The content sits inside the overlay
      (Reka's "scrollable overlay" layout), so a click on either outer layer is outside it. -->
      <DialogOverlay
        :class="
          DIALOG_OVERLAY_STYLES({
            isEntering: open,
            isExiting: !open,
            blockInteractions: !isDismissable,
          })
        "
        @keydown="stopNonEscapeKeys"
      >
        <div :class="DIALOG_MODAL_STYLES({ type })" data-testid="modal-dialog">
          <DialogContent
            :class="`${styles.base({ className })} ${DIALOG_MOTION({ type })}`"
            :role="role"
            :data-testid="testId"
            :aria-describedby="undefined"
            @pointerDownOutside="onPointerDownOutside"
            @escapeKeyDown="onEscapeKeyDown"
          >
            <div class="w-full">
              <header :class="styles.header({ scrolledToTop: isScrolledToTop })">
                <CloseButton
                  v-if="closeButton !== 'none'"
                  :class="styles.closeButton()"
                  @press="close"
                />
                <DialogTitle v-if="title != null" asChild>
                  <Heading :level="2" :class="styles.heading()" weight="semibold">
                    {{ title }}
                  </Heading>
                </DialogTitle>
              </header>
            </div>

            <div ref="scroller" :class="styles.scroller()" @scroll.passive="onScroll">
              <div :class="styles.measurerWrapper()">
                <div :class="styles.content()">
                  <ErrorBoundary>
                    <SuspenseLoader
                      :loaderProps="{ minHeight: type === 'fullscreen' ? 'full' : 'h32' }"
                    >
                      <ResetButtonGroup>
                        <slot :close="close" />
                      </ResetButtonGroup>
                    </SuspenseLoader>
                  </ErrorBoundary>
                </div>
              </div>
            </div>
          </DialogContent>
        </div>
      </DialogOverlay>
    </DialogPortal>
  </DialogRoot>
</template>
