// app/gui/src/components/Inputs/Password.vue
<script setup lang="ts">
/**
 * @file A password input with a show/hide button.
 * Every prop and attribute falls through to `Input.vue`; the button appears once there is a value.
 */
import Button from '$/components/Button/Button.vue'
import { useFormContext } from '$/components/Form/formContext'
import type { AnyFormInstance } from '$/components/Form/types'
import { computed, ref } from 'vue'
import Input from './Input.vue'

const { name, form } = defineProps<{
  name: string
  form?: AnyFormInstance | undefined
}>()

const formInstance = useFormContext(form)
const showPassword = ref(false)
const hasValue = computed(() => {
  const value = formInstance.watch(name as never)
  return typeof value === 'string' && value.length > 0
})
</script>

<template>
  <Input :name="name" :form="formInstance" :type="showPassword ? 'text' : 'password'">
    <template #addonEnd>
      <slot name="addonEnd" />
      <Button
        v-if="hasValue"
        size="medium"
        variant="icon"
        extraClickZone
        :icon="showPassword ? 'eye' : 'eye_crossed'"
        @press="showPassword = !showPassword"
      />
    </template>
  </Input>
</template>

// app/gui/src/dashboard/components/Inputs/Password/Password.tsx
/** @file A component wrapping {@link Input} with the ability to show and hide password. */
import { Button } from '#/components/Button'
import { Form, type FieldPath, type TSchema } from '#/components/Form'
import { Input, type InputProps } from '#/components/Inputs/Input'
import { useState } from 'react'

/** Props for a {@link Password}. */
export interface PasswordProps<
  Schema extends TSchema,
  TFieldName extends FieldPath<Schema, string>,
> extends Omit<InputProps<Schema, TFieldName, string>, 'type'> {}

/** A component wrapping {@link Input} with the ability to show and hide password. */
export function Password<Schema extends TSchema, TFieldName extends FieldPath<Schema, string>>(
  props: PasswordProps<Schema, TFieldName>,
) {
  const [showPassword, setShowPassword] = useState(false)

  const form = Form.useFormContext(props.form)

  return (
    <Input<Schema, TFieldName, string>
      {...props}
      type={showPassword ? 'text' : 'password'}
      addonEnd={
        <>
          {props.addonEnd}

          <Form.FieldValue<Schema, TFieldName, string> form={form} name={props.name}>
            {(value) =>
              value != null && value.length > 0 ?
                <Button
                  size="medium"
                  variant="icon"
                  extraClickZone
                  icon={showPassword ? 'eye' : 'eye_crossed'}
                  onPress={() => {
                    setShowPassword(!showPassword)
                  }}
                />
              : null
            }
          </Form.FieldValue>
        </>
      }
    />
  )
}
