// app/gui/src/components/ContextualHelp/ContextualHelp.vue
<script setup lang="ts">
/**
 * @file A help (or info) icon button that opens a popover with more detail: the Vue counterpart of
 * the React `#/components/ContextualHelp`. The content is the default slot.
 */
import Button from '$/components/Button/Button.vue'
import Popover from '$/components/Dialog/Popover.vue'
import type { Placement } from '$/components/placement'

const {
  placement = 'top',
  variant = 'help',
  testId,
} = defineProps<{
  placement?: Placement | undefined
  variant?: 'help' | 'info' | undefined
  testId?: string | undefined
}>()
</script>

<template>
  <Popover :placement="placement">
    <template #trigger>
      <Button :testId="testId" :icon="variant === 'help' ? 'help' : 'info'" variant="icon" />
    </template>
    <slot />
  </Popover>
</template>

// app/gui/src/dashboard/components/ContextualHelp/ContextualHelp.tsx
/** @file A contextual help component that displays a help message when the user hovers over an element. */
import type { AriaLabelingProps } from '@react-types/shared'
import type { PropsWithChildren } from 'react'
import type { OverlayTriggerProps } from 'react-stately'
import { Button } from '../Button'
import { Popover } from '../Dialog'
import type { Placement, SvgUseIcon, TestIdProps } from '../types'

/**
 * Props for the {@link ContextualHelp} component.
 */
export interface ContextualHelpProps
  extends TestIdProps, OverlayTriggerProps, AriaLabelingProps, PropsWithChildren {
  readonly placement: Placement
  readonly variant?: 'help' | 'info'
}

/**
 * A contextual help component that displays a help message when the user hovers over an element.
 */
export function ContextualHelp(props: ContextualHelpProps) {
  const { placement, testId, defaultOpen, isOpen, onOpenChange, variant = 'help', children } = props

  const icon: SvgUseIcon = variant === 'help' ? 'help' : 'info'

  return (
    <Popover.Trigger defaultOpen={defaultOpen} isOpen={isOpen} onOpenChange={onOpenChange}>
      <Button testId={testId} icon={icon} variant="icon" />

      <Popover placement={placement}>{children}</Popover>
    </Popover.Trigger>
  )
}
