// app/gui/src/dashboard/components/Switch/Switch.tsx
/** @file A switch allows a user to turn a setting on or off. */
import { forwardRef, useRef, type CSSProperties, type ForwardedRef } from 'react'

import {
  Switch as AriaSwitch,
  mergeProps,
  type SwitchProps as AriaSwitchProps,
} from '#/components/aria'
import { mergeRefs } from '#/utilities/mergeRefs'
import { SWITCH_STYLES } from '$/components/Switch/variants'
import type { VariantProps } from '$/utils/style/tailwindVariants'
import { Form, type FieldPath, type FieldProps, type FieldStateProps, type TSchema } from '../Form'

/** Props for a {@link Switch}. */
export interface SwitchProps<Schema extends TSchema, TFieldName extends FieldPath<Schema, boolean>>
  extends
    FieldStateProps<
      Omit<AriaSwitchProps, 'children' | 'size' | 'value'> & { value: boolean },
      Schema,
      TFieldName,
      boolean
    >,
    FieldProps,
    Omit<VariantProps<typeof SWITCH_STYLES>, 'disabled' | 'invalid'> {
  readonly className?: string
  readonly style?: CSSProperties
  readonly labelPosition?: 'after' | 'before' | undefined
  readonly halfway?: boolean | undefined
}

// This is a function, even though it does not contain function syntax.
// eslint-disable-next-line no-restricted-syntax
const useBooleanField = Form.makeUseField<boolean>()

/** A switch allows a user to turn a setting on or off. */
export const Switch = forwardRef(function SwitchImpl<
  Schema extends TSchema,
  TFieldName extends FieldPath<Schema, boolean>,
>(props: SwitchProps<Schema, TFieldName>, ref: ForwardedRef<HTMLDivElement>) {
  const {
    label,
    isDisabled = false,
    isRequired = false,
    halfway = false,
    defaultValue,
    className,
    name,
    form,
    description,
    error,
    size,
    labelPosition = 'after',
    contextualHelp,
    ...ariaSwitchProps
  } = props

  const switchRef = useRef<HTMLInputElement>(null)

  const { fieldState, formInstance, field } = useBooleanField({
    name,
    isDisabled,
    form,
    defaultValue,
  })

  const { ref: fieldRef, ...fieldProps } = formInstance.register(name, {
    disabled: isDisabled,
    required: isRequired,
    ...(props.onBlur && { onBlur: props.onBlur }),
    ...(props.onChange && {
      onChange: (event: { target: { value: boolean } }) => props.onChange?.(event.target.value),
    }),
  })

  const styles = SWITCH_STYLES({ size, disabled: fieldProps.disabled, halfway })

  return (
    <Form.Field
      ref={ref}
      form={formInstance}
      name={name}
      className={styles.base({ className })}
      fullWidth
      description={description}
      error={error}
      aria-label={props['aria-label']}
      aria-labelledby={props['aria-labelledby']}
      aria-describedby={props['aria-describedby']}
      isRequired={fieldProps.required}
      isInvalid={fieldState.invalid}
      aria-details={props['aria-details']}
      style={props.style}
      contextualHelp={contextualHelp}
    >
      <AriaSwitch
        ref={(el) => {
          mergeRefs(switchRef, fieldRef)(el)
        }}
        {...mergeProps<AriaSwitchProps>()(ariaSwitchProps, fieldProps, {
          defaultSelected: field.value,
          className: styles.switch(),
          onChange: field.onChange,
          onBlur: field.onBlur,
        })}
      >
        {labelPosition === 'before' && <div className={styles.label()}>{label}</div>}

        <div className={styles.background()} role="presentation">
          <span className={styles.thumb()} />
        </div>

        {labelPosition === 'after' && <div className={styles.label()}>{label}</div>}
      </AriaSwitch>
    </Form.Field>
  )
})

// app/gui/src/components/Switch/Switch.vue
<script setup lang="ts">
/**
 * @file A switch bound to a boolean form field, styled by `SWITCH_STYLES`. A native checkbox with
 * `role="switch"`, visually hidden inside a `<label>`, so Space toggles it. The label is `label` or
 * the `label` slot, before or after the track (`labelPosition`).
 */
import Field from '$/components/Form/Field.vue'
import type { AnyFormInstance } from '$/components/Form/types'
import { useField } from '$/components/Form/useField'
import { SWITCH_STYLES, SWITCH_VUE_STATES } from '$/components/Switch/variants'
import type { VariantProps } from '$/utils/style/tailwindVariants'
import { computed, ref } from 'vue'

type SwitchVariants = VariantProps<typeof SWITCH_STYLES>

defineOptions({ inheritAttrs: false })

const props = withDefaults(
  defineProps<{
    name: string
    form?: AnyFormInstance | undefined
    defaultValue?: boolean | undefined
    label?: string | undefined
    description?: string | undefined
    contextualHelp?: string | undefined
    /** Overrides the field's error. */
    error?: string | null | undefined
    isDisabled?: boolean | undefined
    isRequired?: boolean | undefined
    /** Shows the thumb half-way, for a mixed state. */
    halfway?: boolean | undefined
    labelPosition?: 'after' | 'before' | undefined
    size?: SwitchVariants['size']
    testId?: string | undefined
    class?: string | undefined
  }>(),
  { defaultValue: undefined, error: undefined, labelPosition: 'after' },
)

const input = ref<HTMLInputElement>()

const field = useField<boolean | undefined>({
  name: () => props.name,
  form: () => props.form,
  defaultValue: props.defaultValue,
  isDisabled: () => props.isDisabled,
  isRequired: () => props.isRequired,
  focus: () => input.value?.focus(),
})

const isSelected = computed(() => field.value.value === true)
const styles = computed(() =>
  SWITCH_STYLES({ size: props.size, disabled: field.isDisabled.value, halfway: props.halfway }),
)
</script>

<template>
  <Field
    :name="name"
    :form="field.form"
    :class="styles.base({ className: props.class })"
    :fullWidth="true"
    :description="description"
    :contextualHelp="contextualHelp"
    :error="error"
    :isRequired="field.isRequired.value"
    :isInvalid="field.isInvalid.value"
    :ids="field.ids"
    :testId="testId"
  >
    <label :class="styles.switch()" :data-selected="isSelected || undefined">
      <input
        ref="input"
        v-bind="$attrs"
        type="checkbox"
        role="switch"
        class="sr-only"
        :name="name"
        :checked="isSelected"
        :disabled="field.isDisabled.value"
        :required="field.isRequired.value"
        :aria-invalid="field.isInvalid.value || undefined"
        :aria-describedby="field.error.value != null ? field.ids.errorId : undefined"
        @change="field.onChange(($event.target as HTMLInputElement).checked)"
        @blur="field.onBlur"
      />
      <div v-if="labelPosition === 'before'" :class="styles.label()">
        <slot name="label">{{ label }}</slot>
      </div>

      <div :class="`${styles.background()} ${SWITCH_VUE_STATES.background}`" role="presentation">
        <span :class="`${styles.thumb()} ${SWITCH_VUE_STATES.thumb}`" />
      </div>

      <div v-if="labelPosition === 'after'" :class="styles.label()">
        <slot name="label">{{ label }}</slot>
      </div>
    </label>
  </Field>
</template>
