// app/gui/src/components/Inputs/MultiSelector.vue
<script setup lang="ts" generic="T">
/**
 * @file A horizontal selector of several items, bound to a form field holding the selected items:
 * the Vue counterpart of the React `MultiSelector`, styled by the same `MULTI_SELECTOR_STYLES` and
 * `MULTI_SELECTOR_OPTION_STYLES`. A Reka `Listbox` (`role="listbox"`, `aria-multiselectable`):
 * arrow keys move between options, Space and Enter toggle one. `toLabel` names each item (React's
 * `children`, default `String`).
 */
import Field from '$/components/Form/Field.vue'
import type { AnyFormInstance } from '$/components/Form/types'
import { useField } from '$/components/Form/useField'
import { valuesEqual } from '$/components/Form/values'
import {
  MULTI_SELECTOR_OPTION_STYLES,
  MULTI_SELECTOR_OPTION_VUE_STATES,
  MULTI_SELECTOR_STYLES,
} from '$/components/Inputs/variants'
import type { VariantProps } from '$/utils/style/tailwindVariants'
import { ListboxContent, ListboxItem, ListboxRoot } from 'reka-ui'
import { computed, useAttrs } from 'vue'

type MultiSelectorVariants = VariantProps<typeof MULTI_SELECTOR_STYLES>

const OPTION_VARIANTS = {
  outline: 'default',
  'separate-outline': 'outline',
} as const

const props = withDefaults(
  defineProps<{
    name: string
    form?: AnyFormInstance | undefined
    items: readonly T[]
    /** The text of each item. React's `children`. */
    toLabel?: ((item: T) => string) | undefined
    columns?: number | undefined
    defaultValue?: readonly T[] | undefined
    label?: string | undefined
    contextualHelp?: string | undefined
    isDisabled?: boolean | undefined
    isRequired?: boolean | undefined
    readOnly?: boolean | undefined
    size?: MultiSelectorVariants['size']
    rounded?: MultiSelectorVariants['rounded']
    variant?: MultiSelectorVariants['variant']
    testId?: string | undefined
    class?: string | undefined
  }>(),
  { toLabel: String, readOnly: undefined },
)

const attrs = useAttrs()

const labelOf = (item: T) => (props.toLabel ?? String)(item)

const field = useField<readonly T[] | undefined>({
  name: () => props.name,
  form: () => props.form,
  defaultValue: props.defaultValue,
  isDisabled: () => props.isDisabled,
  isRequired: () => props.isRequired,
})

const disabled = computed(() => field.isDisabled.value || field.isSubmitting.value)
const classes = computed(() =>
  MULTI_SELECTOR_STYLES({
    size: props.size,
    rounded: props.rounded,
    readOnly: props.readOnly,
    disabled: disabled.value,
    variant: props.variant,
  }),
)
const optionVariant = computed(() => OPTION_VARIANTS[props.variant ?? 'outline'])

/** Reka works in indices, so that items need not be strings. */
const selectedIndices = computed({
  get: () =>
    (field.value.value ?? [])
      .map((value) => props.items.findIndex((item) => valuesEqual(item, value)))
      .filter((i) => i >= 0),
  set: (indices: number[]) => {
    if (props.readOnly === true) return
    field.onChange(props.items.filter((_, i) => indices.includes(i)))
  },
})
const ariaLabel = computed(() => (attrs['aria-label'] as string | undefined) ?? props.label ?? '')
</script>

<template>
  <Field
    :name="name"
    :form="field.form"
    :label="label"
    :contextualHelp="contextualHelp"
    :isRequired="field.isRequired.value"
    :isInvalid="field.isInvalid.value"
    :fullWidth="true"
    :ids="field.ids"
    :testId="testId"
    :class="props.class"
  >
    <div :class="classes.base()">
      <ListboxRoot
        v-model="selectedIndices"
        multiple
        selectionBehavior="toggle"
        orientation="horizontal"
        :disabled="disabled"
      >
        <ListboxContent
          :class="classes.listBox()"
          :style="{ gridTemplateColumns: `repeat(${columns ?? items.length}, 1fr)` }"
          :aria-label="ariaLabel"
          :aria-invalid="field.isInvalid.value || undefined"
          :aria-describedby="field.error.value != null ? field.ids.errorId : undefined"
          @focusout="field.onBlur"
        >
          <ListboxItem
            v-for="(item, i) in items"
            :key="i"
            :value="i"
            :class="`${MULTI_SELECTOR_OPTION_STYLES({ variant: optionVariant })} ${MULTI_SELECTOR_OPTION_VUE_STATES}`"
          >
            {{ labelOf(item) }}
          </ListboxItem>
        </ListboxContent>
      </ListboxRoot>
    </div>
  </Field>
</template>

// app/gui/src/dashboard/components/Inputs/MultiSelector/MultiSelector.tsx
/** @file A horizontal selector supporting multiple input. */
import {
  FieldError,
  ListBox,
  mergeProps,
  type ListBoxItemProps,
  type ListBoxProps,
} from '#/components/aria'
import {
  Form,
  type FieldPath,
  type FieldProps,
  type FieldStateProps,
  type FieldValues,
  type TSchema,
} from '#/components/Form'
import { mergeRefs } from '#/utilities/mergeRefs'
import { MULTI_SELECTOR_STYLES } from '$/components/Inputs/variants'
import type { VariantProps } from '$/utils/style/tailwindVariants'
import { omit, unsafeRemoveUndefined } from 'enso-common/src/utilities/data/object'
import { forwardRef, useRef, type CSSProperties, type ForwardedRef, type Ref } from 'react'
import { MultiSelectorOption, type MultiSelectorOptionProps } from './MultiSelectorOption'

const OPTION_VARIANTS: Record<
  MultiSelectorProps<never, never, never>['variant'] & {},
  MultiSelectorOptionProps['variant'] & {}
> = {
  outline: 'default',
  // eslint-disable-next-line @typescript-eslint/naming-convention
  'separate-outline': 'outline',
}

/** * Props for the MultiSelector component. */
export interface MultiSelectorProps<
  Schema extends TSchema,
  TFieldName extends FieldPath<Schema, readonly T[]>,
  T,
>
  extends
    FieldStateProps<
      Omit<ListBoxItemProps, 'children' | 'value'> & { value: FieldValues<Schema>[TFieldName] },
      Schema,
      TFieldName,
      readonly T[]
    >,
    FieldProps,
    Omit<VariantProps<typeof MULTI_SELECTOR_STYLES>, 'disabled' | 'invalid'> {
  readonly items: readonly T[]
  readonly children?: (item: T) => string
  readonly columns?: number
  readonly className?: string
  readonly style?: CSSProperties
  readonly inputRef?: Ref<HTMLDivElement>
  readonly placeholder?: string
}

// This is a function, even though it does not contain function syntax.
// eslint-disable-next-line no-restricted-syntax, @typescript-eslint/no-explicit-any
const useReadonlyArrayField = Form.makeUseField<readonly any[]>()

/** A horizontal multi-selector. */
export const MultiSelector = forwardRef(function MultiSelectorImpl<
  Schema extends TSchema,
  TFieldName extends FieldPath<Schema, readonly T[]>,
  T,
>(props: MultiSelectorProps<Schema, TFieldName, T>, ref: ForwardedRef<HTMLDivElement>) {
  const {
    name,
    items,
    children = String,
    isDisabled = false,
    columns,
    form,
    defaultValue,
    inputRef,
    label,
    size,
    rounded,
    isRequired = false,
    variant,
    contextualHelp,
    ...inputProps
  } = props

  const privateInputRef = useRef<HTMLDivElement>(null)

  // eslint-disable-next-line no-restricted-syntax
  const { fieldState, formInstance } = useReadonlyArrayField({
    name,
    isDisabled,
    form,
    defaultValue,
  }) as unknown as ReturnType<ReturnType<typeof Form.makeUseField<readonly T[]>>>

  const classes = MULTI_SELECTOR_STYLES({
    size,
    rounded,
    readOnly: inputProps.readOnly,
    disabled: isDisabled || formInstance.formState.isSubmitting,
    variant,
  })

  const optionVariant = OPTION_VARIANTS[variant ?? 'outline']

  return (
    <Form.Field
      form={formInstance}
      name={name}
      fullWidth
      label={label}
      aria-label={props['aria-label']}
      aria-labelledby={props['aria-labelledby']}
      aria-describedby={props['aria-describedby']}
      isRequired={isRequired}
      isInvalid={fieldState.invalid}
      aria-details={props['aria-details']}
      ref={ref}
      style={props.style}
      className={props.className}
      contextualHelp={contextualHelp}
    >
      <div
        className={classes.base()}
        onClick={() => privateInputRef.current?.focus({ preventScroll: true })}
      >
        <Form.Controller
          control={formInstance.control}
          name={name}
          render={(renderProps) => {
            const { ref: fieldRef, value, onChange, ...field } = renderProps.field
            return (
              <ListBox
                ref={mergeRefs(inputRef, privateInputRef, fieldRef)}
                orientation="horizontal"
                selectionMode="multiple"
                {...(inputProps.id != null && { id: String(inputProps.id) })}
                {...mergeProps<ListBoxProps<FieldValues<Schema>[TFieldName]>>()(
                  {
                    className: classes.listBox(),
                    style: { gridTemplateColumns: `repeat(${columns ?? items.length}, 1fr)` },
                  },
                  unsafeRemoveUndefined(omit(inputProps, 'id')),
                  field,
                )}
                // eslint-disable-next-line no-restricted-syntax
                aria-label={props['aria-label'] ?? (typeof label === 'string' ? label : '')}
                // This is SAFE, as there is a constraint on `items` that prevents using keys
                // that do not correspond to array values.
                // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-call
                defaultSelectedKeys={value?.map((item: FieldValues<Schema>[TFieldName]) =>
                  items.indexOf(item),
                )}
                onSelectionChange={(selection) => {
                  onChange([...selection].map((key) => items[Number(key)]))
                }}
              >
                {items.map((item, i) => (
                  <MultiSelectorOption
                    key={i}
                    id={i}
                    value={{ item }}
                    label={children(item)}
                    variant={optionVariant}
                  />
                ))}
              </ListBox>
            )
          }}
        />
      </div>
      <FieldError />
    </Form.Field>
  )
})
