// app/gui/src/dashboard/layouts/InfoMenu.tsx
/** @file A menu containing info about the app. */
import { Popover } from '#/components/Dialog'
import { Icon } from '#/components/Icon'
import MenuEntry from '#/components/MenuEntry'
import { Text } from '#/components/Text'
import { LOGIN_PATH } from '$/appUtils'
import { openAboutModal } from '$/components/AboutModal/aboutModal'
import { useAuth, useRouter, useSession, useText } from '$/providers/react'
import { PRODUCT_NAME } from 'enso-common/src/constants'

/** A menu containing info about the app. */
export function InfoMenu() {
  const { router } = useRouter()
  const { signOut } = useSession()
  const { session } = useAuth()
  const { getText } = useText()

  return (
    <>
      <Popover data-testid="info-menu" size="xxsmall">
        <div className="mb-2 flex items-center gap-icons overflow-hidden px-menu-entry transition-all duration-user-menu">
          <Icon icon="enso_logo" className="pointer-events-none h-7 w-7 text-primary" />
          <Text>{PRODUCT_NAME}</Text>
        </div>
        <div aria-label={getText('infoMenuLabel')} className="flex flex-col overflow-hidden">
          <MenuEntry
            action="aboutThisApp"
            doAction={() => {
              openAboutModal()
            }}
          />
          {session && (
            <MenuEntry
              action="signOut"
              doAction={() => signOut().then(() => router.push(LOGIN_PATH))}
            />
          )}
        </div>
      </Popover>
    </>
  )
}

// app/gui/src/components/InfoBar/InfoMenu.vue
<script setup lang="ts">
/**
 * @file A menu with information about the app, opened from the {@link InfoBar}: a popover of
 * buttons.
 */
import { openAboutModal } from '$/components/AboutModal/aboutModal'
import Icon from '$/components/Icon/Icon.vue'
import MenuEntry from '$/components/MenuEntry/MenuEntry.vue'
import Text from '$/components/Text/Text.vue'
import { LOGIN_PATH } from '$/appUtils'
import { useAuth } from '$/providers/auth'
import { useSession } from '$/providers/session'
import { useText } from '$/providers/text'
import { PRODUCT_NAME } from 'enso-common/src/constants'
import { useRouter } from 'vue-router'

const router = useRouter()
const { signOut } = useSession()
const auth = useAuth()
const { getText } = useText()

function onSignOut() {
  void signOut().then(() => router.push(LOGIN_PATH))
}
</script>

<template>
  <div
    class="mb-2 flex items-center gap-icons overflow-hidden px-menu-entry transition-all duration-user-menu"
  >
    <Icon icon="enso_logo" class="pointer-events-none h-7 w-7 text-primary" />
    <Text>{{ PRODUCT_NAME }}</Text>
  </div>
  <div :aria-label="getText('infoMenuLabel')" class="flex flex-col overflow-hidden">
    <MenuEntry action="aboutThisApp" @press="openAboutModal" />
    <MenuEntry v-if="auth.session" action="signOut" @press="onSignOut" />
  </div>
</template>
