// app/gui/src/dashboard/components/Radio/RadioGroup.tsx
/** @file A radio group. */
import * as aria from '#/components/aria'
import * as mergeRefs from '#/utilities/mergeRefs'
import { RADIO_GROUP_STYLES } from '$/components/Radio/variants'
import type * as twv from '$/utils/style/tailwindVariants'
import { omit } from 'enso-common/src/utilities/data/object'
import * as React from 'react'
import type { FieldVariantProps } from '../Form'
import { Form, type FieldPath, type FieldProps, type FieldStateProps, type TSchema } from '../Form'
import { RadioGroupProvider } from './RadioGroupContext'

/** Props for {@link RadioGroup}. */
export interface RadioGroupProps<
  Schema extends TSchema,
  TFieldName extends FieldPath<Schema, string>,
>
  extends
    FieldStateProps<
      Omit<aria.AriaRadioGroupProps, 'description' | 'label'>,
      Schema,
      TFieldName,
      string
    >,
    twv.VariantProps<typeof RADIO_GROUP_STYLES>,
    FieldProps,
    FieldVariantProps {
  readonly children?: React.ReactNode
  readonly className?: string
  readonly style?: React.CSSProperties
}

// This is a function, even though it does not contain function syntax.
// eslint-disable-next-line no-restricted-syntax
const useStringField = Form.makeUseField<string>()

/** A radio group. */
export const RadioGroup = React.forwardRef(function RadioGroupImpl<
  Schema extends TSchema,
  TFieldName extends FieldPath<Schema, string>,
>(props: RadioGroupProps<Schema, TFieldName>, ref: React.ForwardedRef<HTMLDivElement>) {
  const {
    children,
    isRequired = false,
    isReadOnly = false,
    isDisabled = false,
    isInvalid = false,
    name,
    className,
    form,
    defaultValue,
    label,
    description,
    fullWidth,
    variants = RADIO_GROUP_STYLES,
    fieldVariants,
    contextualHelp,
    ...radioGroupProps
  } = props

  const { field, fieldState, formInstance } = useStringField({
    name,
    isDisabled,
    form,
    defaultValue,
  })

  const invalid = isInvalid || fieldState.invalid

  const base = variants({ fullWidth, className })

  return (
    <aria.RadioGroup
      ref={(el) => {
        mergeRefs.mergeRefs(ref, field.ref)(el)
      }}
      {...aria.mergeProps<aria.RadioGroupProps>()(omit(radioGroupProps, 'validate'), {
        name: field.name,
        value: field.value,
        isDisabled: field.disabled ?? isDisabled,
        onChange: field.onChange,
        onBlur: field.onBlur,
        className: base,
        isRequired,
        isReadOnly,
        isInvalid: invalid,
      })}
    >
      <RadioGroupProvider>
        <Form.Field
          name={name}
          form={formInstance}
          label={label}
          description={description}
          fullWidth={fullWidth}
          isInvalid={invalid}
          variants={fieldVariants}
          isRequired={isRequired}
          contextualHelp={contextualHelp}
        >
          {children}
        </Form.Field>
      </RadioGroupProvider>
    </aria.RadioGroup>
  )
})

// app/gui/src/components/Radio/RadioGroup.vue
<script setup lang="ts">
/**
 * @file A radio group bound to a string form field, styled by `RADIO_GROUP_STYLES`. The radios are
 * the default slot. It is a `role="radiogroup"` labelled by its field's label; the radios are
 * native, so arrow keys move the selection as the browser does.
 */
import Field from '$/components/Form/Field.vue'
import type { AnyFormInstance } from '$/components/Form/types'
import { useField } from '$/components/Form/useField'
import type { FIELD_STYLES } from '$/components/Form/variants'
import { RADIO_GROUP_STYLES } from '$/components/Radio/variants'
import type { ExtractFunction } from '$/utils/style/tailwindVariants'
import { computed, ref } from 'vue'
import { provideRadioGroup } from './radioGroup'

const props = withDefaults(
  defineProps<{
    name: string
    form?: AnyFormInstance | undefined
    defaultValue?: string | undefined
    label?: string | undefined
    description?: string | undefined
    contextualHelp?: string | undefined
    isDisabled?: boolean | undefined
    isRequired?: boolean | undefined
    isInvalid?: boolean | undefined
    isReadOnly?: boolean | undefined
    // `undefined`, not the `false` Vue casts an absent boolean prop to, so the variant applies.
    fullWidth?: boolean | undefined
    fieldVariants?: ExtractFunction<typeof FIELD_STYLES> | undefined
    testId?: string | undefined
    class?: string | undefined
  }>(),
  { fullWidth: undefined },
)

const field = useField<string | undefined>({
  name: () => props.name,
  form: () => props.form,
  defaultValue: props.defaultValue,
  isDisabled: () => props.isDisabled,
  isRequired: () => props.isRequired,
})

const invalid = computed(() => props.isInvalid || field.isInvalid.value)

provideRadioGroup({
  name: props.name,
  value: field.value,
  isDisabled: field.isDisabled,
  isInvalid: invalid,
  isReadOnly: computed(() => props.isReadOnly),
  isRequired: computed(() => props.isRequired),
  pressed: ref(null),
  select: (value) => field.onChange(value),
  onBlur: field.onBlur,
})
</script>

<template>
  <div
    role="radiogroup"
    :class="RADIO_GROUP_STYLES({ fullWidth, className: props.class })"
    :aria-labelledby="label != null ? field.ids.labelId : undefined"
    :aria-describedby="field.error.value != null ? field.ids.errorId : undefined"
    :aria-invalid="invalid || undefined"
    :aria-required="isRequired || undefined"
    :aria-disabled="field.isDisabled.value || undefined"
    :data-testid="testId"
  >
    <Field
      :name="name"
      :form="field.form"
      :label="label"
      :description="description"
      :contextualHelp="contextualHelp"
      :fullWidth="fullWidth"
      :isInvalid="invalid"
      :isRequired="isRequired"
      :variants="fieldVariants"
      :ids="field.ids"
    >
      <slot />
    </Field>
  </div>
</template>
