// app/gui/src/dashboard/pages/dashboard/UserBar/NotificationTray/NotificationTray.vue
<script setup lang="ts">
/**
 * @file The notifications button in the user bar, with a badge while there are notifications newer
 * than the last time it was opened, and the tray it opens: the Vue counterpart of the React
 * `NotificationTray` (#83).
 *
 * The list is a plain `role="list"`, where React's was a react-aria `GridList` (`role="grid"`) that
 * nothing selects or navigates; see "Rulings from #83".
 */
import StatusBadge from '$/components/Badge/StatusBadge.vue'
import Button from '$/components/Button/Button.vue'
import Popover from '$/components/Dialog/Popover.vue'
import Icon from '$/components/Icon/Icon.vue'
import Result from '$/components/Result/Result.vue'
import Heading from '$/components/Text/Heading.vue'
import { useText } from '$/providers/text'
import { computed, ref, watch } from 'vue'
import NotificationItem from './NotificationItem.vue'
import { useNotifications } from './notifications'

const DIALOG_OFFSET = 16
const DIALOG_CROSS_OFFSET = 16

const { getText } = useText()
const { notifications, removeNotification } = useNotifications(NotificationItem)

const isOpen = ref(false)
const lastOpenTimestamp = ref(0)
watch(isOpen, (open) => {
  if (open) lastOpenTimestamp.value = Number(new Date())
})
const hasUnreadNotifications = computed(() =>
  notifications.value.some(
    (notification) =>
      notification.timestamp != null && notification.timestamp > lastOpenTimestamp.value,
  ),
)
</script>

<template>
  <Popover
    v-model:open="isOpen"
    placement="bottom-end"
    :offset="DIALOG_OFFSET"
    :crossOffset="DIALOG_CROSS_OFFSET"
    :aria-label="getText('notifications')"
  >
    <template #trigger>
      <Button variant="icon" :aria-label="getText('notifications')">
        <template #icon>
          <StatusBadge color="danger" :hidden="!hasUnreadNotifications">
            <Icon icon="inbox" class="size-4" />
          </StatusBadge>
        </template>
      </Button>
    </template>
    <div class="flex max-h-[90vh] flex-col overflow-y-auto">
      <Heading :level="3" variant="subtitle">{{ getText('notifications') }}</Heading>
      <div role="list" :aria-label="getText('notifications')">
        <Result
          v-if="notifications.length === 0"
          centered
          class="min-h-10"
          :title="getText('youAreAllCaughtUp')"
        />
        <div v-for="info in notifications" :key="info.id" role="listitem">
          <NotificationItem
            :message="info.message"
            :icon="info.icon"
            :color="info.color"
            :progress="info.progress"
            :timestamp="info.timestamp"
            :remove="() => removeNotification(info.id)"
          />
        </div>
      </div>
    </div>
  </Popover>
</template>

// app/gui/src/dashboard/pages/dashboard/UserBar/NotificationTray/NotificationTray.tsx
/** @file A tray for displaying notifications. */
import { Button } from '#/components/Button'
import { Popover } from '#/components/Dialog'
import { Icon } from '#/components/Icon'
import { Result } from '#/components/Result'
import { StatusBadge } from '#/components/StatusBadge'
import { Text } from '#/components/Text'
import { DialogTrigger, GridList, GridListItem } from '#/components/aria'
import { useText } from '$/providers/react'
import { useState } from 'react'
import { NotificationItem } from './NotificationItem'
import { useComputedNotifications, useNotificationState } from './computedNotificationHooks'
import type { NotificationInfo } from './types'

const DIALOG_OFFSET = 16
const DIALOG_CROSS_OFFSET = 16

/** A button to show a list of notifications. */
export function NotificationTray() {
  const { getText } = useText()
  const notificationState = useNotificationState()
  const { computedNotifications, removeComputedNotification } = notificationState
  useComputedNotifications(notificationState)

  const [lastOpenTimestamp, setLastOpenTimestamp] = useState(0)
  const hasUnreadNotifications = computedNotifications.some(
    (notification) => notification.timestamp != null && notification.timestamp > lastOpenTimestamp,
  )

  return (
    <DialogTrigger
      onOpenChange={(isOpen) => {
        if (isOpen) {
          setLastOpenTimestamp(Number(new Date()))
        }
      }}
    >
      <Button
        variant="icon"
        aria-label={getText('notifications')}
        icon={
          <StatusBadge color="danger" hidden={!hasUnreadNotifications}>
            <Icon icon="inbox" className="size-4" />
          </StatusBadge>
        }
      />
      <NotificationTrayDialog
        computedNotifications={computedNotifications}
        removeComputedNotification={removeComputedNotification}
      />
    </DialogTrigger>
  )
}

/** Props for a {@link NotificationTrayDialog}. */
interface NotificationTrayDialogProps {
  readonly computedNotifications: readonly NotificationInfo[]
  readonly removeComputedNotification: (id: string) => void
}

/** Dialog to display notifications for a {@link NotificationTray}. */
function NotificationTrayDialog(props: NotificationTrayDialogProps) {
  const { computedNotifications, removeComputedNotification } = props
  const { getText } = useText()

  return (
    <Popover placement="bottom right" offset={DIALOG_OFFSET} crossOffset={DIALOG_CROSS_OFFSET}>
      <div className="flex max-h-[90vh] flex-col overflow-y-auto">
        <Text.Heading level={3} variant="subtitle">
          {getText('notifications')}
        </Text.Heading>
        <NotificationTrayDialogInner
          computedNotifications={computedNotifications}
          removeComputedNotification={removeComputedNotification}
        />
      </div>
    </Popover>
  )
}

/** Dialog to display notifications for a {@link NotificationTray}. */
function NotificationTrayDialogInner(props: NotificationTrayDialogProps) {
  const { computedNotifications, removeComputedNotification } = props
  const { getText } = useText()

  return (
    <GridList
      aria-label={getText('notifications')}
      selectionMode="none"
      items={computedNotifications}
      renderEmptyState={() => (
        <Result centered className="min-h-10" title={getText('youAreAllCaughtUp')} />
      )}
    >
      {(info) => (
        <GridListItem>
          <NotificationItem
            {...info}
            remove={() => {
              removeComputedNotification(info.id)
            }}
          />
        </GridListItem>
      )}
    </GridList>
  )
}
