// app/gui/src/components/Form/FormError.vue
<script setup lang="ts">
/**
 * @file The form-level errors: the Vue counterpart of the React `Form.FormError`. It shows the
 * offline notice (for a form that cannot submit offline) and a failed submission's message, each in
 * an `Alert`, with the same test ids as React (`form-submit-offline`, `form-submit-error`).
 */
import Alert from '$/components/Alert/Alert.vue'
import type { ALERT_STYLES } from '$/components/Alert/variants'
import Text from '$/components/Text/Text.vue'
import { useText } from '$/providers/text'
import type { VariantProps } from '$/utils/style/tailwindVariants'
import { computed } from 'vue'
import { FORM_OFFLINE_ERROR, FORM_SUBMIT_ERROR, formLevelErrors } from './errorMap'
import { useFormContext } from './formContext'
import type { AnyFormInstance } from './types'

type AlertVariants = VariantProps<typeof ALERT_STYLES>

const {
  form,
  size = 'large',
  variant = 'error',
  rounded = 'xxlarge',
  // `undefined`, not the `false` Vue casts an absent boolean prop to, so the variant default applies.
  fullWidth = undefined,
  class: className,
} = defineProps<{
  form?: AnyFormInstance | undefined
  size?: AlertVariants['size']
  variant?: AlertVariants['variant']
  rounded?: AlertVariants['rounded']
  fullWidth?: boolean | undefined
  class?: string | undefined
}>()

const formInstance = useFormContext(form)
const { getText } = useText()

const errors = computed(() =>
  formLevelErrors(
    getText,
    formInstance.formState.errors[FORM_OFFLINE_ERROR],
    formInstance.formState.errors[FORM_SUBMIT_ERROR],
  ),
)
</script>

<template>
  <div v-if="errors.length > 0" class="flex w-full flex-col gap-4">
    <Alert
      v-for="error in errors"
      :key="error.message"
      :size="size"
      :variant="error.type === 'offline' ? 'outline' : variant"
      :rounded="rounded"
      :fullWidth="fullWidth"
      :icon="error.type === 'offline' ? 'cloud_offline' : undefined"
      :class="className"
    >
      <Text
        disableLineHeightCompensation
        variant="body"
        truncate="3"
        color="primary"
        :testId="`form-submit-${error.type}`"
      >
        {{ error.message }}
      </Text>
    </Alert>
  </div>
</template>

// app/gui/src/dashboard/components/Form/components/FormError.tsx
/** @file Form error component. */
import { Alert, type AlertProps } from '#/components/Alert'
import { Text } from '#/components/Text'
import { useFormError, type UseFormErrorProps } from './useFormError'

/** Props for the FormError component. */
export interface FormErrorProps extends Omit<AlertProps, 'children'>, UseFormErrorProps {}

/** Form error component. */
export function FormError(props: FormErrorProps) {
  const { size = 'large', variant = 'error', rounded = 'xxlarge', ...alertProps } = props

  const errors = useFormError(props)

  if (errors.length === 0) {
    return null
  }

  return (
    <div className="flex w-full flex-col gap-4">
      {errors.map((error) => {
        const testId = `form-submit-${error.type}`
        const finalVariant = error.type === 'offline' ? 'outline' : variant
        const icon = error.type === 'offline' ? 'cloud_offline' : null

        return (
          <Alert
            key={error.message}
            size={size}
            variant={finalVariant}
            rounded={rounded}
            icon={icon}
            {...alertProps}
          >
            <Text
              disableLineHeightCompensation
              variant="body"
              truncate="3"
              color="primary"
              testId={testId}
            >
              {error.message}
            </Text>
          </Alert>
        )
      })}
    </div>
  )
}
