// app/gui/src/dashboard/components/Stepper/Stepper.tsx
/** @file UI for a multi-step process. */
import { ErrorBoundary } from '#/components/ErrorBoundary'
import { Suspense } from '#/components/Suspense'
import { useEventCallback } from '#/hooks/eventCallbackHooks'
import { STEPPER_STYLES } from '$/components/Stepper/variants'
import type { CSSProperties, ReactNode } from 'react'
import { Step } from './Step'
import { StepContent } from './StepContent'
import { StepperProvider } from './StepperProvider'
import type { BaseRenderProps, RenderChildrenProps, RenderStepProps } from './types'
import { useStepperState, type StepperState } from './useStepperState'

/** Props for {@link Stepper} component. */
export interface StepperProps {
  readonly state: StepperState
  readonly children: ReactNode | ((props: RenderChildrenProps) => ReactNode)
  readonly className?:
    string | ((props: BaseRenderProps) => string | null | undefined) | null | undefined
  readonly renderStep?: ((props: RenderStepProps) => ReactNode) | null
  readonly style?:
    CSSProperties | ((props: BaseRenderProps) => CSSProperties | undefined) | undefined
}

/** A stepper component is used to indicate progress through a multi-step process. */
export function Stepper(props: StepperProps) {
  const { renderStep, children, state } = props

  const { onStepChange, currentStep, totalSteps, nextStep, previousStep } = state

  const goToStep = useEventCallback((step: number) => {
    if (step < 0 || step >= totalSteps) return
    onStepChange(step)
  })

  const baseRenderProps = {
    goToStep,
    nextStep,
    previousStep,
    currentStep,
    totalSteps,
  } satisfies BaseRenderProps

  const styles = STEPPER_STYLES({})

  const style = typeof props.style === 'function' ? props.style(baseRenderProps) : props.style

  /** Render children of the stepper component. */
  const renderChildren = () => {
    const renderProps = {
      currentStep,
      totalSteps,
      isFirst: currentStep === 0,
      isLast: currentStep === totalSteps - 1,
      goToStep,
      nextStep,
      previousStep,
    } satisfies RenderChildrenProps

    return typeof children === 'function' ? children(renderProps) : children
  }

  return (
    <div
      className={styles.base({
        className:
          typeof props.className === 'function' ?
            props.className(baseRenderProps)
          : props.className,
      })}
      style={style}
    >
      <StepperProvider value={{ totalSteps, currentStep, goToStep, nextStep, previousStep }}>
        {renderStep == null ? null : (
          <div className={styles.steps()}>
            {Array.from({ length: totalSteps }).map((_, index) => {
              const renderStepProps = {
                index,
                currentStep,
                totalSteps,
                isFirst: index === 0,
                isLast: index === totalSteps - 1,
                nextStep,
                previousStep,
                goToStep,
                isCompleted: index < currentStep,
                isCurrent: index === currentStep,
                isDisabled: index > currentStep,
              } satisfies RenderStepProps

              const nextRenderStep = renderStep(renderStepProps)

              if (nextRenderStep == null) {
                return null
              }

              return (
                <div key={index} className={styles.step({})}>
                  {nextRenderStep}
                </div>
              )
            })}
          </div>
        )}

        <div className={styles.content()}>
          <div key={currentStep}>
            <ErrorBoundary>
              <Suspense loaderProps={{ minHeight: 'h32' }}>{renderChildren()}</Suspense>
            </ErrorBoundary>
          </div>
        </div>
      </StepperProvider>
    </div>
  )
}

Stepper.Step = Step
Stepper.StepContent = StepContent
Stepper.useStepperState = useStepperState

// app/gui/src/components/Stepper/Stepper.vue
<script setup lang="ts">
/**
 * @file A multi-step process: the Vue counterpart of the React `Stepper`, styled by the same
 * `STEPPER_STYLES`. Its state comes from `useStepperState`.
 *
 * - The `step` slot renders each step's marker (React's `renderStep`), usually a `Step.vue`, with
 *   `{ index, isCurrent, isCompleted, isFirst, isLast, isDisabled, … }`. Without it no markers show.
 * - The default slot is the current step's content, with `{ currentStep, isFirst, isLast,
 *   nextStep, previousStep, goToStep, … }`, inside an error boundary and a suspense loader, as in
 *   React. It is re-created on every step change. `StepContent.vue`s inside it show only the
 *   current step's content.
 */
import ErrorBoundary from '$/components/ErrorBoundary/ErrorBoundary.vue'
import SuspenseLoader from '$/components/ErrorBoundary/SuspenseLoader.vue'
import { STEPPER_STYLES } from '$/components/Stepper/variants'
import { computed } from 'vue'
import { provideStepper } from './stepperContext'
import type { StepperState } from './useStepperState'

const { state, class: className } = defineProps<{
  state: StepperState
  class?: string | undefined
}>()

/** What every slot receives. */
interface BaseSlotProps {
  readonly currentStep: number
  readonly totalSteps: number
  readonly isFirst: boolean
  readonly isLast: boolean
  readonly goToStep: (step: number) => void
  readonly nextStep: () => void
  readonly previousStep: () => void
}

defineSlots<{
  default?: (props: BaseSlotProps) => unknown
  step?: (
    props: BaseSlotProps & {
      readonly index: number
      readonly isCurrent: boolean
      readonly isCompleted: boolean
      readonly isDisabled: boolean
    },
  ) => unknown
}>()

provideStepper(state)

const styles = STEPPER_STYLES()

const base = computed<BaseSlotProps>(() => ({
  currentStep: state.currentStep.value,
  totalSteps: state.totalSteps,
  isFirst: state.currentStep.value === 0,
  isLast: state.currentStep.value === state.totalSteps - 1,
  goToStep: state.goToStep,
  nextStep: state.nextStep,
  previousStep: state.previousStep,
}))

function stepProps(index: number) {
  const current = state.currentStep.value
  return {
    ...base.value,
    index,
    isFirst: index === 0,
    isLast: index === state.totalSteps - 1,
    isCurrent: index === current,
    isCompleted: index < current,
    isDisabled: index > current,
  }
}
</script>

<template>
  <div :class="styles.base({ className })">
    <div v-if="$slots.step" :class="styles.steps()">
      <div v-for="index in state.totalSteps" :key="index" :class="styles.step()">
        <slot name="step" v-bind="stepProps(index - 1)" />
      </div>
    </div>

    <div :class="styles.content()">
      <div :key="state.currentStep.value">
        <ErrorBoundary>
          <SuspenseLoader :loaderProps="{ minHeight: 'h32' }">
            <slot v-bind="base" />
          </SuspenseLoader>
        </ErrorBoundary>
      </div>
    </div>
  </div>
</template>
