// app/gui/src/dashboard/components/Checkbox/CheckboxGroup.tsx
/** @file A selector for one or more items from a list of choices. */
import type { CheckboxGroupProps as AriaCheckboxGroupProps } from '#/components/aria'
import { CheckboxGroup as AriaCheckboxGroup, mergeProps } from '#/components/aria'
import { mergeRefs } from '#/utilities/mergeRefs'
import { CHECKBOX_GROUP_STYLES } from '$/components/Checkbox/variants'
import type { VariantProps } from '$/utils/style/tailwindVariants'
import { omit } from 'enso-common/src/utilities/data/object'
import {
  forwardRef,
  type CSSProperties,
  type ForwardedRef,
  type ReactElement,
  type ReactNode,
} from 'react'
import type { FieldVariantProps } from '../Form'
import {
  Form,
  type FieldPath,
  type FieldPropsExcept,
  type FieldStateProps,
  type TSchema,
} from '../Form'
import type { TestIdProps } from '../types'
import { CheckboxGroupProvider } from './CheckboxContext'

/** Props for the {@link CheckboxGroup} component. */
export interface CheckboxGroupProps<
  Schema extends TSchema,
  TFieldName extends FieldPath<Schema, readonly string[]>,
>
  extends
    FieldStateProps<AriaCheckboxGroupProps, Schema, TFieldName, readonly string[]>,
    FieldPropsExcept<AriaCheckboxGroupProps>,
    FieldVariantProps,
    Omit<VariantProps<typeof CHECKBOX_GROUP_STYLES>, 'disabled' | 'invalid'>,
    TestIdProps {
  readonly className?: string
  readonly style?: CSSProperties
  readonly checkboxRef?: ForwardedRef<HTMLInputElement>
  readonly children: ReactNode | ((props: AriaCheckboxGroupProps) => ReactNode)
}

/** A selector for one or more items from a list of choices. */
export const CheckboxGroup = forwardRef(
  <Schema extends TSchema, TFieldName extends FieldPath<Schema, readonly string[]>>(
    props: CheckboxGroupProps<Schema, TFieldName>,
    ref: ForwardedRef<HTMLDivElement>,
  ): ReactElement => {
    const {
      children,
      className,
      variants = CHECKBOX_GROUP_STYLES,
      form,
      defaultValue: defaultValueOverride,
      isDisabled = false,
      isRequired = false,
      isInvalid,
      isReadOnly = false,
      label,
      name,
      description,
      fullWidth = false,
      fieldVariants,
      contextualHelp,
      ...checkboxGroupProps
    } = props

    const formInstance = Form.useFormContext(form)

    const styles = variants({ fullWidth, className })
    const testId = props['data-testid'] ?? props.testId

    return (
      <Form.Controller
        name={name}
        control={formInstance.control}
        {...(defaultValueOverride != null && { defaultValue: defaultValueOverride })}
        render={({ field, fieldState }) => {
          const defaultValue = defaultValueOverride ?? formInstance.control._defaultValues[name]
          const invalid = isInvalid ?? fieldState.invalid
          return (
            <>
              <CheckboxGroupProvider
                name={name}
                field={field}
                defaultValue={defaultValue}
                onChange={(value) => {
                  field.onChange({ target: { value } })
                  void formInstance.trigger(name)
                }}
              >
                <AriaCheckboxGroup
                  {...mergeProps<AriaCheckboxGroupProps>()(omit(checkboxGroupProps, 'validate'), {
                    className: styles,
                    isInvalid: invalid,
                    isDisabled,
                    isReadOnly,
                    name,
                    defaultValue: defaultValue ?? [],
                  })}
                  ref={mergeRefs(ref, field.ref)}
                  data-testid={testId}
                >
                  {(renderProps) => (
                    <Form.Field
                      name={name}
                      form={formInstance}
                      label={label}
                      description={description}
                      isRequired={isRequired}
                      fullWidth={fullWidth}
                      isInvalid={invalid}
                      variants={fieldVariants}
                      {...checkboxGroupProps}
                      contextualHelp={contextualHelp}
                      className="w-full"
                    >
                      {typeof children === 'function' ? children(renderProps) : children}
                    </Form.Field>
                  )}
                </AriaCheckboxGroup>
              </CheckboxGroupProvider>
            </>
          )
        }}
      />
    )
  },
)

// app/gui/src/components/Checkbox/CheckboxGroup.vue
<script setup lang="ts">
/**
 * @file A group of checkboxes bound to one form field holding the selected values: the Vue
 * counterpart of the React `Checkbox.Group`, styled by the same `CHECKBOX_GROUP_STYLES`. The
 * checkboxes are the default slot, each with its `value`. It is a `role="group"` labelled by its
 * field's label.
 */
import { CHECKBOX_GROUP_STYLES } from '$/components/Checkbox/variants'
import Field from '$/components/Form/Field.vue'
import type { AnyFormInstance } from '$/components/Form/types'
import { useField } from '$/components/Form/useField'
import type { FIELD_STYLES } from '$/components/Form/variants'
import type { ExtractFunction } from '$/utils/style/tailwindVariants'
import { computed } from 'vue'
import { provideCheckboxGroup } from './checkboxGroup'

const props = withDefaults(
  defineProps<{
    name: string
    form?: AnyFormInstance | undefined
    defaultValue?: readonly string[] | undefined
    label?: string | undefined
    description?: string | undefined
    contextualHelp?: string | undefined
    isDisabled?: boolean | undefined
    isRequired?: boolean | undefined
    isInvalid?: boolean | undefined
    isReadOnly?: boolean | undefined
    fullWidth?: boolean | undefined
    fieldVariants?: ExtractFunction<typeof FIELD_STYLES> | undefined
    testId?: string | undefined
    class?: string | undefined
  }>(),
  {
    // `undefined`, not the `false` Vue casts an absent boolean prop to: "not set".
    isInvalid: undefined,
  },
)

const field = useField<readonly string[] | undefined>({
  name: () => props.name,
  form: () => props.form,
  defaultValue: props.defaultValue,
  isDisabled: () => props.isDisabled,
  isRequired: () => props.isRequired,
  isInvalid: () => props.isInvalid,
})

const selected = computed(() => field.value.value ?? [])

provideCheckboxGroup({
  name: props.name,
  selected,
  isDisabled: computed(() => props.isDisabled),
  isInvalid: field.isInvalid,
  isReadOnly: computed(() => props.isReadOnly),
  isRequired: computed(() => props.isRequired),
  toggle: (value, isSelected) => {
    const current = selected.value
    const next =
      isSelected ?
        current.includes(value) ?
          current
        : [...current, value]
      : current.filter((v) => v !== value)
    field.onChange(next)
    // React validates the group on every change.
    void field.form.trigger(field.name.value)
  },
  onBlur: field.onBlur,
})
</script>

<template>
  <div
    role="group"
    :class="CHECKBOX_GROUP_STYLES({ fullWidth, className: props.class })"
    :aria-labelledby="label != null ? field.ids.labelId : undefined"
    :aria-describedby="field.error.value != null ? field.ids.errorId : undefined"
    :data-testid="testId"
    :data-invalid="field.isInvalid.value || undefined"
    :data-disabled="isDisabled || undefined"
  >
    <Field
      :name="name"
      :form="field.form"
      :label="label"
      :description="description"
      :contextualHelp="contextualHelp"
      :isRequired="isRequired"
      :fullWidth="fullWidth"
      :isInvalid="field.isInvalid.value"
      :variants="fieldVariants"
      :ids="field.ids"
      class="w-full"
    >
      <slot />
    </Field>
  </div>
</template>
