// app/gui/src/dashboard/pages/dashboard/components/PermissionDisplay.tsx
/** @file Colored border around icons and text indicating permissions. */
import type * as aria from '#/components/aria'
import { Button } from '#/components/Button'
import { Text } from '#/components/Text'
import { PERMISSION_CLASS_NAME } from '$/cloud/permissionsClasses'
import * as tailwindMerge from '$/utils/style/tailwindMerge'
import * as permissionsModule from 'enso-common/src/utilities/permissions'
import * as React from 'react'

/** Props for a {@link PermissionDisplay}. */
export interface PermissionDisplayProps extends Readonly<React.PropsWithChildren> {
  readonly action: permissionsModule.PermissionAction
  readonly className?: string
  readonly onPress?: ((event: aria.PressEvent) => void) | null
}

/** Colored border around icons and text indicating permissions. */
export default function PermissionDisplay(props: PermissionDisplayProps) {
  const { action, className, onPress, children: childrenRaw } = props
  const permission = permissionsModule.FROM_PERMISSION_ACTION[action]

  const children =
    typeof childrenRaw !== 'string' ? childrenRaw : (
      <Text truncate="1" className="max-w-24 text-inherit">
        {childrenRaw}
      </Text>
    )

  switch (permission.type) {
    case permissionsModule.Permission.owner:
    case permissionsModule.Permission.admin:
    case permissionsModule.Permission.edit: {
      return (
        <Button
          size="custom"
          variant="custom"
          isDisabled={!onPress}
          className={tailwindMerge.twMerge(
            'inline-block h-6 whitespace-nowrap rounded-full px-[7px]',
            PERMISSION_CLASS_NAME[permission.type],
            className,
          )}
          onPress={onPress}
        >
          {children}
        </Button>
      )
    }
    case permissionsModule.Permission.read:
    case permissionsModule.Permission.view: {
      return (
        <Button
          size="custom"
          variant="custom"
          className={tailwindMerge.twMerge(
            'relative inline-block whitespace-nowrap rounded-full',
            className,
          )}
          isDisabled={!onPress}
          onPress={onPress}
        >
          {permission.docs && (
            <div className="absolute size-full rounded-full border-2 border-permission-docs clip-path-top" />
          )}
          {permission.execute && (
            <div className="absolute size-full rounded-full border-2 border-permission-exec clip-path-bottom" />
          )}
          <div
            className={tailwindMerge.twMerge(
              'm-1 flex h-6 items-center rounded-full px-[7px]',
              PERMISSION_CLASS_NAME[permission.type],
              (permission.docs || permission.execute) && 'm-1',
            )}
          >
            {children}
          </div>
        </Button>
      )
    }
  }
}

// app/gui/src/cloud/properties/PermissionDisplay.vue
<script setup lang="ts">
/**
 * @file A user's name in a coloured pill showing their permission on an asset: the Vue port of the
 * React `PermissionDisplay`, as the Properties tab uses it (never pressable, so always a disabled
 * button, as React rendered it without `onPress`).
 */
import Button from '$/components/Button/Button.vue'
import Text from '$/components/Text/Text.vue'
import { PERMISSION_CLASS_NAME } from '$/cloud/permissionsClasses'
import { twMerge } from '$/utils/style/tailwindMerge'
import {
  FROM_PERMISSION_ACTION,
  Permission,
  type PermissionAction,
} from 'enso-common/src/utilities/permissions'
import { computed } from 'vue'

const { action } = defineProps<{ action: PermissionAction }>()

const permission = computed(() => FROM_PERMISSION_ACTION[action])
const docs = computed(() => 'docs' in permission.value && permission.value.docs)
const execute = computed(() => 'execute' in permission.value && permission.value.execute)
const isPill = computed(
  () =>
    permission.value.type === Permission.owner ||
    permission.value.type === Permission.admin ||
    permission.value.type === Permission.edit,
)
</script>

<template>
  <Button
    v-if="isPill"
    size="custom"
    variant="custom"
    isDisabled
    :class="
      twMerge(
        'inline-block h-6 whitespace-nowrap rounded-full px-[7px]',
        PERMISSION_CLASS_NAME[permission.type],
      )
    "
  >
    <Text truncate="1" class="max-w-24 text-inherit"><slot /></Text>
  </Button>
  <Button
    v-else
    size="custom"
    variant="custom"
    isDisabled
    class="relative inline-block whitespace-nowrap rounded-full"
  >
    <div
      v-if="docs"
      class="absolute size-full rounded-full border-2 border-permission-docs clip-path-top"
    />
    <div
      v-if="execute"
      class="absolute size-full rounded-full border-2 border-permission-exec clip-path-bottom"
    />
    <div
      :class="
        twMerge(
          'm-1 flex h-6 items-center rounded-full px-[7px]',
          PERMISSION_CLASS_NAME[permission.type],
          (docs || execute) && 'm-1',
        )
      "
    >
      <Text truncate="1" class="max-w-24 text-inherit"><slot /></Text>
    </div>
  </Button>
</template>
