// app/gui/src/cloud/auth/ForgotPassword.vue
<script setup lang="ts">
/**
 * @file The first half of the password reset. It asks Cognito to email a reset link, then returns
 * to the sign-in page. When the account's email is not confirmed yet, it offers to send the
 * confirmation email again.
 */
import Button from '$/components/Button/Button.vue'
import FormError from '$/components/Form/FormError.vue'
import Submit from '$/components/Form/Submit.vue'
import { useForm } from '$/components/Form/useForm'
import Input from '$/components/Inputs/Input.vue'
import Link from '$/components/Link/Link.vue'
import { LOGIN_PATH } from '$/appUtils'
import { useBackends } from '$/providers/backends'
import { useSession } from '$/providers/session'
import { useText } from '$/providers/text'
import { useToasts } from '$/providers/toasts'
import { computed, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { z } from 'zod'
import AuthenticationPage from './AuthenticationPage.vue'
import { queryParam } from './queryParam'

const session = useSession()
const router = useRouter()
const toasts = useToasts()
const { getText } = useText()
const backends = useBackends()
const supportsOffline = computed(() => backends.localBackend != null)

const route = useRoute()
const initialEmail = queryParam(route, 'email')
const resendConfirmationButtonVisible = ref(false)

const form = useForm({
  schema: z.object({ email: z.string().email() }),
  defaultValues: { email: initialEmail ?? '' },
  onSubmit: async ({ email }) => {
    try {
      resendConfirmationButtonVisible.value = false
      await session.forgotPassword(email)
      void router.push(LOGIN_PATH)
      // A global toast, not `useToast`'s: it must outlive this page.
      toasts.show(getText('forgotPasswordSuccess'), { type: 'success' })
    } catch (error) {
      if (error instanceof Error && /verify your email first/.test(error.message)) {
        resendConfirmationButtonVisible.value = true
      }
      throw error
    }
  },
})

const email = computed(() => String(form.watch('email') ?? ''))
const loginLink = computed(
  () => `${LOGIN_PATH}?${new URLSearchParams({ email: email.value }).toString()}`,
)
</script>

<template>
  <AuthenticationPage
    :title="getText('forgotYourPassword')"
    :form="form"
    :supportsOffline="supportsOffline"
  >
    <Input
      autoFocus
      required
      testId="email-input"
      name="email"
      :label="getText('emailLabel')"
      type="email"
      autocomplete="email"
      icon="at"
      :placeholder="getText('emailPlaceholder')"
    />

    <Submit size="large" icon="arrow_right" iconPosition="end" fullWidth>
      {{ getText('sendLink') }}
    </Submit>

    <FormError />

    <Button
      v-if="resendConfirmationButtonVisible"
      variant="submit"
      size="large"
      fullWidth
      @press="() => session.resendSignUp(email)"
    >
      {{ getText('resendConfirmRegistrationEmail') }}
    </Button>

    <template #footer>
      <Link :to="loginLink" icon="navigate_back" :text="getText('goBackToLogin')" />
    </template>
  </AuthenticationPage>
</template>

// app/gui/src/dashboard/pages/authentication/ForgotPassword.tsx
/**
 * @file Container responsible for rendering and interactions in first half of forgot password
 * flow.
 */
import { Button } from '#/components/Button'
import { Form } from '#/components/Form'
import { Input } from '#/components/Inputs/Input'
import Link from '#/components/Link'
import AuthenticationPage from '#/pages/authentication/AuthenticationPage'
import { LOGIN_PATH } from '$/appUtils'
import { useBackends, useRouter, useSession, useText } from '$/providers/react'
import { useQueryParam } from '$/providers/react/queryParams'
import { useState } from 'react'
import { toast } from 'react-toastify'

/** A form for users to request for their password to be reset. */
export default function ForgotPassword() {
  const [resendConfirmationButtonVisible, setResendConfirmationButtonVisible] = useState(false)
  const { forgotPassword, resendSignUp } = useSession()
  const { getText } = useText()

  const { router } = useRouter()

  const { localBackend } = useBackends()
  const supportsOffline = localBackend != null

  const [initialEmail] = useQueryParam('email')
  const [emailInput, setEmailInput] = useState(initialEmail ?? '')

  return (
    <AuthenticationPage
      title={getText('forgotYourPassword')}
      schema={(z) => z.object({ email: z.string().email() })}
      footer={
        <Link
          to={`${LOGIN_PATH}?${new URLSearchParams({ email: emailInput }).toString()}`}
          icon="navigate_back"
          text={getText('goBackToLogin')}
        />
      }
      supportsOffline={supportsOffline}
      onSubmit={async ({ email }) => {
        try {
          setResendConfirmationButtonVisible(false)
          await forgotPassword(email)
          void router.push(LOGIN_PATH)
          toast.success(getText('forgotPasswordSuccess'))
        } catch (error) {
          // eslint-disable-next-line no-restricted-syntax
          const safeError = error as Error
          const isUserNotConfirmed = /verify your email first/.test(safeError.message)

          if (isUserNotConfirmed) {
            setResendConfirmationButtonVisible(true)
          }
          throw error
        }
      }}
    >
      <Input
        autoFocus
        required
        data-testid="email-input"
        name="email"
        label={getText('emailLabel')}
        type="email"
        autoComplete="email"
        icon="at"
        placeholder={getText('emailPlaceholder')}
        defaultValue={initialEmail ?? undefined}
        onChange={(event) => {
          setEmailInput(event.currentTarget.value)
        }}
      />

      <Form.Submit size="large" icon="arrow_right" iconPosition="end" fullWidth>
        {getText('sendLink')}
      </Form.Submit>

      <Form.FormError />

      {resendConfirmationButtonVisible && (
        <Button
          variant="submit"
          size="large"
          fullWidth
          onPress={async () => {
            await resendSignUp(emailInput)
          }}
        >
          {getText('resendConfirmRegistrationEmail')}
        </Button>
      )}
    </AuthenticationPage>
  )
}
