// app/gui/src/cloud/auth/ResetPassword.vue
<script setup lang="ts">
/**
 * @file The second half of the password reset, reached from the emailed link with the `email` and
 * `verification_code` parameters. It sets the new password, then sends the user to `redirect_url`
 * (by default the desktop app's sign-in deep link) after three seconds, or at once with the "open
 * in desktop" button. Without either parameter it returns to the sign-in page with an error.
 */
import ButtonGroup from '$/components/Button/ButtonGroup.vue'
import Button from '$/components/Button/Button.vue'
import FormError from '$/components/Form/FormError.vue'
import Submit from '$/components/Form/Submit.vue'
import { useForm } from '$/components/Form/useForm'
import Input from '$/components/Inputs/Input.vue'
import Password from '$/components/Inputs/Password.vue'
import Link from '$/components/Link/Link.vue'
import Result from '$/components/Result/Result.vue'
import StepContent from '$/components/Stepper/StepContent.vue'
import Stepper from '$/components/Stepper/Stepper.vue'
import { useStepperState } from '$/components/Stepper/useStepperState'
import { LOGIN_PATH } from '$/appUtils'
import { PASSWORD_REGEX } from '$/cloud/validation'
import { useBackends } from '$/providers/backends'
import { useSession } from '$/providers/session'
import { useText } from '$/providers/text'
import { useToasts } from '$/providers/toasts'
import { computed, onMounted, onScopeDispose } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { z } from 'zod'
import AuthenticationPage from './AuthenticationPage.vue'
import { queryParam } from './queryParam'
import { passwordWithPatternSchema } from './schemas'

const REDIRECT_TIMEOUT_MS = 3_000

const session = useSession()
const router = useRouter()
const toasts = useToasts()
const { getText } = useText()
const backends = useBackends()
const supportsOffline = computed(() => backends.localBackend != null)

const route = useRoute()
const defaultEmail = queryParam(route, 'email')
const defaultVerificationCode = queryParam(route, 'verification_code')
const redirectUrl = queryParam(route, 'redirect_url') ?? 'enso://auth/login'

/** An error toast, logged too. */
function toastAndLog(textId: 'missingEmailError' | 'missingVerificationCodeError') {
  const message = `${getText(textId)}.`
  toasts.show(message, { type: 'error' })
  console.error(message)
}

onMounted(() => {
  if (defaultEmail == null) {
    toastAndLog('missingEmailError')
    void router.push(LOGIN_PATH)
  }
  if (defaultVerificationCode == null) {
    toastAndLog('missingVerificationCodeError')
    void router.push(LOGIN_PATH)
  }
})

const { stepperState } = useStepperState({ steps: 2, defaultStep: 0 })

let redirectTimer: ReturnType<typeof setTimeout> | undefined
onScopeDispose(() => clearTimeout(redirectTimer))

const form = useForm({
  schema: z
    .object({
      email: z.string().email(getText('invalidEmailValidationError')),
      verificationCode: z.string(),
      newPassword: passwordWithPatternSchema(getText),
      confirmNewPassword: z.string().trim(),
    })
    .superRefine((object, context) => {
      if (
        PASSWORD_REGEX.test(object.newPassword) &&
        object.newPassword !== object.confirmNewPassword
      ) {
        context.addIssue({
          path: ['confirmNewPassword'],
          code: 'custom',
          message: getText('passwordMismatchError'),
        })
      }
    }),
  defaultValues: {
    email: defaultEmail ?? '',
    verificationCode: defaultVerificationCode ?? '',
    newPassword: '',
    confirmNewPassword: '',
  },
  onSubmit: async ({ email, verificationCode, newPassword }) => {
    await session.resetPassword(email, verificationCode, newPassword)
    toasts.show(getText('resetPasswordSuccess'), { type: 'success' })
    stepperState.nextStep()
    redirectTimer = setTimeout(() => {
      window.location.href = redirectUrl
    }, REDIRECT_TIMEOUT_MS)
  },
})

const loginLink = `${LOGIN_PATH}?${new URLSearchParams({ email: defaultEmail ?? '' }).toString()}`
</script>

<template>
  <AuthenticationPage
    :title="getText('resetYourPassword')"
    :form="form"
    :supportsOffline="supportsOffline"
  >
    <Stepper :state="stepperState">
      <StepContent :index="0">
        <Input
          required
          readOnly
          hidden
          testId="email-input"
          name="email"
          type="email"
          autocomplete="email"
          :placeholder="getText('emailPlaceholder')"
        />

        <Input
          required
          readOnly
          hidden
          testId="verification-code-input"
          name="verificationCode"
          type="text"
          autocomplete="one-time-code"
          :placeholder="getText('confirmationCodePlaceholder')"
        />

        <Password
          autoFocus
          required
          testId="new-password-input"
          name="newPassword"
          :label="getText('newPasswordLabel')"
          autocomplete="new-password"
          icon="lock"
          :placeholder="getText('newPasswordPlaceholder')"
          :description="getText('passwordValidationMessage')"
        />

        <Password
          required
          testId="confirm-new-password-input"
          name="confirmNewPassword"
          :label="getText('confirmNewPasswordLabel')"
          autocomplete="new-password"
          icon="lock"
          :placeholder="getText('confirmNewPasswordPlaceholder')"
        />

        <Submit size="large" icon="arrow_right" fullWidth>
          {{ getText('reset') }}
        </Submit>

        <FormError />
      </StepContent>

      <StepContent :index="1">
        <Result
          :title="getText('resetPasswordSuccess')"
          status="success"
          :subtitle="getText('resetPasswordSuccessSubtitle')"
        >
          <ButtonGroup align="center">
            <Button :href="redirectUrl" size="large" variant="submit" icon="arrow_right" fullWidth>
              {{ getText('openInDesktop') }}
            </Button>
          </ButtonGroup>
        </Result>
      </StepContent>
    </Stepper>

    <template #footer>
      <Link :to="loginLink" icon="navigate_back" :text="getText('goBackToLogin')" />
    </template>
  </AuthenticationPage>
</template>

// app/gui/src/dashboard/pages/authentication/ResetPassword.tsx
/**
 * @file Container responsible for rendering and interactions in second half of forgot password
 * flow.
 */
import { Button } from '#/components/Button'
import { Form } from '#/components/Form'
import { Input } from '#/components/Inputs/Input'
import { Password } from '#/components/Inputs/Password'
import Link from '#/components/Link'
import { Result } from '#/components/Result'
import { Stepper } from '#/components/Stepper'
import { useMount } from '#/hooks/mountHooks'
import { useTimeoutAPI } from '#/hooks/timeoutHooks'
import { useToastAndLog } from '#/hooks/toastAndLogHooks'
import AuthenticationPage from '#/pages/authentication/AuthenticationPage'
import { passwordWithPatternSchema } from '#/pages/authentication/schemas'
import { LOGIN_PATH } from '$/appUtils'
import { PASSWORD_REGEX } from '$/cloud/validation'
import { useBackends, useRouter, useSession, useText } from '$/providers/react'
import { useQueryParam } from '$/providers/react/queryParams'
import type { GetText } from '$/providers/text'
import { noop } from '$/utils/functions'
import { unsafeWriteValue } from '$/utils/write'
import { toast } from 'react-toastify'
import * as z from 'zod'

/** Create the schema for this form. */
function createResetPasswordFormSchema(getText: GetText) {
  return z
    .object({
      email: z.string().email(getText('invalidEmailValidationError')),
      verificationCode: z.string(),
      newPassword: passwordWithPatternSchema(getText),
      confirmNewPassword: z.string().trim(),
    })
    .superRefine((object, context) => {
      if (
        PASSWORD_REGEX.test(object.newPassword) &&
        object.newPassword !== object.confirmNewPassword
      ) {
        context.addIssue({
          path: ['confirmNewPassword'],
          code: 'custom',
          message: getText('passwordMismatchError'),
        })
      }
    })
}

const REDIRECT_TIMEOUT = 3000

/** A form for users to reset their password. */
export default function ResetPassword() {
  const { resetPassword } = useSession()
  const { getText } = useText()
  const { router } = useRouter()

  const toastAndLog = useToastAndLog()
  const { localBackend } = useBackends()
  const supportsOffline = localBackend != null

  const [defaultEmail] = useQueryParam('email')
  const [defaultVerificationCode] = useQueryParam('verification_code')
  const [maybeRedirectUrl] = useQueryParam('redirect_url')
  const redirectUrl = maybeRedirectUrl ?? 'enso://auth/login'

  const { startTimer } = useTimeoutAPI({ ms: REDIRECT_TIMEOUT })

  useMount(() => {
    if (defaultEmail == null) {
      toastAndLog('missingEmailError')
      void router.push(LOGIN_PATH)
    }

    if (defaultVerificationCode == null) {
      toastAndLog('missingVerificationCodeError')
      void router.push(LOGIN_PATH)
    }
  })

  const { stepperState } = Stepper.useStepperState({ steps: 2, defaultStep: 0 })

  return (
    <AuthenticationPage
      supportsOffline={supportsOffline}
      title={getText('resetYourPassword')}
      schema={createResetPasswordFormSchema(getText)}
      footer={
        <Link
          to={`${LOGIN_PATH}?${new URLSearchParams({ email: defaultEmail ?? '' }).toString()}`}
          icon="navigate_back"
          text={getText('goBackToLogin')}
        />
      }
      onSubmit={({ email, verificationCode, newPassword }) =>
        resetPassword(email, verificationCode, newPassword).then(() => {
          toast.success(getText('resetPasswordSuccess'))

          stepperState.nextStep()

          void startTimer()
            .then(() => {
              unsafeWriteValue(window.location, 'href', redirectUrl)
            })
            .catch(noop)
        })
      }
    >
      <Stepper state={stepperState}>
        <Stepper.StepContent index={0}>
          <Input
            required
            readOnly
            hidden
            data-testid="email-input"
            name="email"
            type="email"
            autoComplete="email"
            placeholder={getText('emailPlaceholder')}
            value={defaultEmail ?? ''}
          />

          <Input
            required
            readOnly
            hidden
            data-testid="verification-code-input"
            name="verificationCode"
            type="text"
            autoComplete="one-time-code"
            placeholder={getText('confirmationCodePlaceholder')}
            value={defaultVerificationCode ?? ''}
          />

          <Password
            autoFocus
            required
            data-testid="new-password-input"
            name="newPassword"
            label={getText('newPasswordLabel')}
            autoComplete="new-password"
            icon="lock"
            placeholder={getText('newPasswordPlaceholder')}
            description={getText('passwordValidationMessage')}
          />

          <Password
            required
            data-testid="confirm-new-password-input"
            name="confirmNewPassword"
            label={getText('confirmNewPasswordLabel')}
            autoComplete="new-password"
            icon="lock"
            placeholder={getText('confirmNewPasswordPlaceholder')}
          />

          <Form.Submit size="large" icon="arrow_right" fullWidth>
            {getText('reset')}
          </Form.Submit>

          <Form.FormError />
        </Stepper.StepContent>

        <Stepper.StepContent index={1}>
          <Result
            title={getText('resetPasswordSuccess')}
            status="success"
            subtitle={getText('resetPasswordSuccessSubtitle')}
          >
            <Button.Group align="center">
              <Button href={redirectUrl} size="large" variant="submit" icon="arrow_right" fullWidth>
                {getText('openInDesktop')}
              </Button>
            </Button.Group>
          </Result>
        </Stepper.StepContent>
      </Stepper>
    </AuthenticationPage>
  )
}
